<script type="text/javascript">
  var disqus_identifier = "Compile_Like_Its_1993";
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Wolfenstein 3D compilation on DosBox"/>
		<meta name="Description" content="Wolfenstein 3D compilation on DosBox"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
	
 	
		
		<title>Compile like it's 1992</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       August 10th, 2014</div>
   <h1>Let's Compile like it's 1992</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="cli1992-1.png" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         
        <!-- Add fancyBox -->
  <link rel="stylesheet" href="../fancybox/source/jquery.fancybox.css?v=2.1.5" type="text/css" media="screen" />
  <script type="text/javascript" src="../fancybox/source/jquery.fancybox.pack.js?v=2.1.5"></script>

    <style>

 .comment{color: rgb(66,135,65);}
 .keyword{color: rgb(182,16,162);}
 .literal{color: rgb(218,37,36);}

 .include{color: rgb(117,85,119);}

 .numbers{color: rgb(96,0,205);}

 .blackPre{
     background-color :black;
     color: white;
 }

 .screenshot{
    box-shadow: rgb(119, 119, 119) 3px 3px 3px;
    display: block;
    margin-left: auto;
    margin-right: auto;
    margin-top: 10px;
    margin-bottom: 15px;
 }

h4 {
 
  border-bottom: 0px;
  font-size: 15px;
}

  pre{
    font: 12px courrier,monospace;
  }
 </style>
 <p>
I have been tinkering with the vanilla source code of Wolfenstein 3D from 1992. Even though it
is more than 20 years old and has rotten for modern systems, you can still compile it if you recreate the environment.
All you need is :<br/>
 <ul>
     <li>Wolfenstein 3D source code.</li>
     <li>DosBox.</li>
     <li>The Compiler Borland C++ 3.1.</li>
     <li>Wolfenstein 3D shareware (for the assets).</li>
 </ul>
 </p>
  
 <br/>
<div style="clear:both;"></div>
<br/>
<h3>Setup filesystem</h3>
<p>
  Open a command line and create two folders, one for each DOS drive needed:
<p>
<pre>
  
   cd ~
   mkdir system
   cd system
   mkdir c
   mkdir a
   cd ~


 </pre>
</p>
<br/>
<h3>Download</h3>
 <p>
  <ul>
  <li>Download Borland 3.1 to <code>system/a</code>.<br/>
  <li>Download Wolfenstein 3D source code to <code>system/c</code><br/>
  <li>Download VGA files to <code>system/c</code> (the purpose of those is explained at the bottom of this page.<br/>
  </ul>
  <p>
 <pre>


    cd system/a
    curl -O http://fabiensanglard.net/Compile_Like_Its_1992/tools/BCPP31.zip
    

    cd ../c
    curl -O http://fabiensanglard.net/Compile_Like_Its_1992/tools/wolfsrc.zip
    curl -O http://fabiensanglard.net/Compile_Like_Its_1992/tools/vgafiles.zip


  </pre>

<p>
<br/>
  Now we have all the files in the filesytem. Just to check, type: <br/>
  <br/>
  <pre>

   cd ..
   find ~/system


  </pre>
  <br/>
  <p>
    You should have the following :<br/>
    <br/>
  <pre>


    /Users/fabiensanglard/system
    /Users/fabiensanglard/system/a
    /Users/fabiensanglard/system/a/BCPP31.zip
    /Users/fabiensanglard/system/c
    /Users/fabiensanglard/system/c/vgafiles.zip
    /Users/fabiensanglard/system/c/wolfsrc.zip


  </pre>
</p>
<br/>
<h3>Decompress everything</h3>
 <p>
<pre>

    cd ~/system/a
    unzip BCPP31.zip

    cd ~/system/c
    unzip vgafiles.zip
    unzip wolfsrc.zip


</pre>

</p>
<Br/>
<h3>DosBox</h3>
 <p>
  Download and start <a href="http://www.dosbox.com/">DosBox</a>:
  <img class="screenshot" src="images/dosbox_splash.png"/>
  <br/>
</p>

<br/>
<h3>Mount</h3>
  <p>
    Mount the filesystem, one folder for each drive :
  <pre class="blackPre">


   Z:/> mount c ~/system/c 
   Z:/> mount a ~/system/a

  </pre>

</p>

<br/>
<h3>Install the compiler</h3>
  <p>
  Now is time to install Borland C++ 3.1 :
  <pre class="blackPre">

    Z:\> a:
    A:\> cd BCPP31
    A:\> install

 </pre>
 <p>
 <img class="screenshot" src="images/borland_install.png"/>
 <br/>
  Press enter when you select the source drive ( it should already be A drive )<br/>
  <img class="screenshot" src="images/borland_choose_drive.png"/>
  <p>
  Leave all the default settings and select "Start Installation":<br/>
 <img class="screenshot" src="images/borland_choose_dir.png"/>
  The warnings will tell you that Microsoft windows folder could not be found  but it is not needed anyway, 
  just press Enter.<br/>
  <img class="screenshot" src="images/borland_warning_one.png"/><br/>
  <img class="screenshot" src="images/borland_inst_process.png"/><br/>
  <img class="screenshot" src="images/borland_warning_two.png"/><br/>
  <br/>

</p>

<br/>
<h3>Install Wolfenstein 3D source code</h3>
  <p>
  We have a system running and a compiler on it: Time to decompress (again) the source code.<Br/>
  <br/>


  <pre class="blackPre">

  A:\> c:
  C:\> cd\
  C:\> install

</pre>
<p>
 <br/>
  
<img class="screenshot" src="images/wolf_src_drive_selection.png"/><br/>
  Type 'C'<br/>
  
<img class="screenshot" src="images/wolf_src_directory_selection.png"/><br/>
 Keep the default path: <code>\WOLFSRC</code><br/>

 <img class="screenshot" src="images/wolf_src_not_folder.png"/><br/>
 Y to create the directory.<br/>
<br/>
Installing !
 <img class="screenshot" src="images/wolf_src_install.png"/><br/>
  
<br/>
<h3>Compiling</h3>
  <p>
  Start Borland C++ 3.1:
  <pre  class="blackPre">

     
     C:\> cd\
     C:\> cd borlandc
     C:\> cd bin
     C:\> bc.exe

  </pre>
  <p>
    <img class="screenshot" src="images/compile_0.png"/><br/>
    After pressing OK, use the mouse or the shortcuts to Project -> Open Project  <code>..\..\WOLFSRC\WOLF3D.PRJ</code>:
    <img class="screenshot" src="images/compile_1.png"/><br/>
<p>
    Select Options -> Directories and change the value as follow :
    <pre>

    Include Directories: C:\BORLANDC\INCLUDE

    Library Directories: C:\BORLANDC\LIB

    Ouptput Directories: OBJ

    Source Directories:  C:\WOLFSRC

    </pre>
    
    <img class="screenshot" src="images/compile_2.png"/><br/>



Let's try to compile: Compile -> Build All
    
    <img class="screenshot" src="images/compile_3.png"/><br/>

    We get an error: "Cannot find executable TASM"
    <img class="screenshot" src="images/compile_4.png"/><br/>

    Exit Borland C++, we need to set the PATH:

      <pre  class="blackPre">

     
     C:\> CD ..
     C:\> PATH=C:\BORLANDC\BIN
     C:\> BC.EXE

  </pre>
  <p>
    Try to compile again (Compile -> Build All):
    <img class="screenshot" src="images/compile41.png"/><br/>

    Compiling did work but the linking failed: "Unable to find OBJ file" because the path of SIGNON.OBJ and GAMEPAL.OBJ in wrong in the project: 
    They are marked in <code>C:\SOURCE\WOLF\</code> : 
    <img class="screenshot" src="images/compile_5.png"/><br/>
<br/>
    Delete them from the project (Select and the Projext -> Delete item). Add them again via PROJECT -> Add Item...  . Add <code>WOLFSRC\OBJ\SIGNON.OBJ</code> and <code>WOLFSRC\OBJ\GAMEPAL.OBJ</code>
    <img class="screenshot" src="images/compile_6.png"/><br/>
    Try to compile again via (Compile -> Build All)
    <img class="screenshot" src="images/compile_7.png"/><br/>

    IT WORKED ! But will it run ?
    <img class="screenshot" src="images/compile_8.png"/><br/>
    </p>

<br/>
<h3>Getting the assets</h3>
<p>
Download the shareware version or even better: Purchase as full version on Wolfenstein 3D.<br/>
<pre>

    cd ~/system/c
    curl -O http://fabiensanglard.net/Compile_Like_Its_1992/tools/1wolf14.zip
    unzip 1wolf14.zip

</pre>
<p>
  Go back to DosBox and install the game to <code>C:\WOLF3D</code>.
  <pre class="blackPre">

  C:\> c:
  C:\> cd \
  C:\> cd 1wolf14
  C:\1WOLF14> install

  </pre>
  <p>
    After installation of the game, copy the .EXE we just compiled to the game folder, 
  <pre class="blackPre">


    C:\> c:
    C:\> cd wolf3d
    C:\WOLF3D> copy WOLF3D.EXE WOLF3D.OLD
    C:\WOLF3D> copy ../WOLRSRC/WOLF.EXE .

  </pre>

<br/>
<h3>Running the game</h3>
<p>
Try to run it:
<pre class="blackPre">


    C:\> cd wolf3d
    C:\WOLF3D> copy WOLF3D.EXE WOLF3D.OLD
    C:\WOLF3D> copy ../WOLRSRC/OBJ/WOLF3D.EXE .
    C:\WOLF3D> WOLF3D.EXE


  </pre>
  <p>
  <br/>

  Hm, that looks weird.....
  <br/>
<img class="screenshot" src="images/run_wolf.png"/><br/>
Uh...
<img class="screenshot" src="images/run_wolf2.png"/><br/>
What ?
<img class="screenshot" src="images/run_wolf3.png"/><br/>
I did not remember it like that....
<img class="screenshot" src="images/run_wolf4.png"/><br/>
Ok something must be very wrong here !!<br/>
</p>

<br/>
<h3>What happened ?</h3>
<p>
It has to do with the production access pipeline and how they are used by the engine. 
When Adrian Carmack and Kevin Cloud were done crafting all the graphic files, they used a tool (IGRABed) to pack them together.
The output was made of 3+2 files.
<ul>
   <li>VGAHEAD.WL1</li>
   <li>VGAGRAPH.WL1</li>
   <li>VGADICT.WL1</li>
 </ul>
 <p>
  The VGAHEAD file is an index containing pointers to the VGAGRAPH where the data is stored huffman compressed. VGADICT
  contains the huffman dictionaries to decompress the data.<br/>
<br/>
The two other files produced:
  <ul>
    <li>GRE.H</li>
    <li>GRE.EQU</li>
  </ul>
  <p>
    Are compiled into engine as seen in the following drawing :<br/>
    <br/>

    <!--<img src="images/drawing_plain.svg" width="700px" height="469px" style="display:block;margin-left:auto;margin-right:auto;"/><br/>
  -->
  <img src="images/drawing_plain.png" width="700px" height="469px" style="display:block;margin-left:auto;margin-right:auto;"/><br/>


    What are the <code>.H</code> and <code>.EQU</code> files needed for? In short, to allow access by name. When IGRABed assembled all files
    it would also create an enum with matching indices:<br/>
    <br/>
    <b>GRE.H</b>
    <pre>

            enum{ 
            H_WOLFLOGOPIC
            GETPSYCHEDPIC
            L_GUYPIC
            .
            .
            } graphicnums

    </pre>
    <p>
    <b>GRE.EQU</b>
 <pre>

            
            H_WOLFLOGOPIC  = 0
            GETPSYCHEDPIC  = 1
            L_GUYPIC       = 2

    </pre>
    <p>
      This way when the engine requested a particular asset, it could use a logical name (L_GUYPIC) instead of a "magic number" (2).<br/>
      <br/>
      That means the engine shipped with the indices of the images in the VGA files HARD-CODED. Since the assets and
      codebase evolved after shipping wolf3D shareware (with Spears of Destiny), the newly compiled game indices do not
      match the location in the original assets files.

</p>
<br/>
<h3>Running the game (again)</h3>
<p>

  Fortunately there is a simple solution to this problem: Somebody regenerated the VGA assets so they match the indices in the .H and .EQU
  released with the source code. Just copy those files (if you use the shareware assets you will have to change the file extension from .WL6 to .WL1).<br/>
  <br/>
<pre class="blackPre">

  C:\> copy C:\vgafiles\VGADICT.WL6 C:\WOLF3D\VGADICT.WL1
  C:\> copy C:\vgafiles\VGAGRAPH.WL6 C:\WOLF3D\VGAGRAPH.WL1
  C:\> copy C:\vgafiles\VGAHEAD.WL6 C:\WOLF3D\VGAHEAD.WL1

</pre>
<p>
    Let's try again:<br/>
<pre class="blackPre">


  C:\WOLF3D> WOLF3D.EXE
  

</pre>
<p>
  <br/>
It works !!

<img class="screenshot" src="images/compressed.png"/><br/>
<br/>
Yet we are are not done !

<br/>
<h3>VGA framebuffer and screen aspect ratio</h3>
<p>
  It may not be obvious to people that never saw the original game but the DosBox image above is not what people saw in 1992.
  The VGA framebuffer was 320x200 but the CRT monitors had an aspect ratio of 4:3. Which mean the framebuffer was stretched vertically
  when sent to the monitor. DosBox has an option to compensate for that :
 <br/>
<pre>

     vi ~/Library/Preferences/DOSBox\ 0.74\ Preferences
  
    [render]
    # frameskip: How many frames DOSBox skips before drawing one.
    # aspect: Do aspect correction, if your output method doesn't support scaling this can slow things down!.
    # scaler: Scaler used to enlarge/enhance low resolution modes.
      # If 'forced' is appended, then the scaler will be used even if the result might not be desired.
      # Possible values: none, normal2x, normal3x, advmame2x, advmame3x, advinterp2x, advinterp3x, ...

    frameskip=0
    aspect=<b>false</b>
    scaler=normal2x


</pre>
<p>
  Change that aspect to <b/>true</b>:
<br/>
Try again :<Br/>

<pre class="blackPre">


  C:\WOLF3D> WOLF3D.EXE
  

</pre>
<p>
  <br/>
  Finally, IT WORKS !<br/>
  <br/>
<img class="screenshot" src="images/Yea.png"/><br/>
<img class="screenshot" src="images/working_not_compressed.png"/><br/>
<img class="screenshot" src="images/see_ya.png"/><br/>
</pre>
</p>



<br/>
<h3>Recommended Readings</h3>
<p>
  <a href="../Game_Engine_Black_Book/index.php">
  <img class="screenshot" style="margin-left:20px;" src="gebb_book.png"/>
</a>
</p>


<!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

