<script type="text/javascript">
  var disqus_identifier = "SC_Reverse_Engineering";
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Reverse Engineering Strike Commander"/>
		<meta name="Description" content="Reverse Engineering Strike Commander"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>Reverse Engineering Strike Commander</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       Jan 22th, 2014</div>
   <h1>Reverse Engineering Strike Commander</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="icon_plane.png" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         
    
    <style>

 .comment{color: rgb(66,135,65);}
 .keyword{color: rgb(182,16,162);}
 .literal{color: rgb(218,37,36);}

 .include{color: rgb(117,85,119);}

 .numbers{color: rgb(96,0,205);}

h4 {
 
  border-bottom: 0px;
  font-size: 15px;
}

  pre{
    font: 12px courrier,monospace;
  }
 </style>
<p>
Back in the early 90s, one company was on the bleeding edge of PC gaming: 
<a href="http://en.wikipedia.org/wiki/Origin_Systems">Origin Systems</a>.
Their motto was "We Create Worlds" and boy did they deliver: With the <a href="http://en.wikipedia.org/wiki/Ultima_(series)">Ultima</a> series, Crusader series and
<a href="http://en.wikipedia.org/wiki/Wing_Commander_(franchise)">Wing Commander</a> series, they consistently took gamer's breath away.<br/>
<br/>
One of them took four years and more than a million man hours to complete: <a href="http://en.wikipedia.org/wiki/Strike_Commander">
Strike Commander</a>. The famous flight simulator
had its own 3D engine called <a href="http://www.wcnews.com/wcpedia/RealSpace">RealSpace</a> which pioneered many of what we take 
for granted today: Texture Mapping, Gouraud Shading, Level of Details and Dithered colors.<br/>
<br/>

My old dream was to play the game with a Virtual Reality device. With 
the <A href="http://www.oculusvr.com/">Oculus Rift</a> that fantasy came one step closer to reality.
But when it turned out the source code had been lost and would never be released, I decided to reverse engineer it.<br/>
<br/>
As of the publication of this article, the project is not yet completed  but I want to share the techniques that have so far allowed this :<br/>
<br/>
  <img class="shadowed"  src="sc_before.png" style="margin-left: auto; margin-right: auto; display: inline;" /><br/>
  <br/>
to become that :<br/>
<br/>
  <img class="shadowed"  src="sc_after.png" style="margin-left: auto; margin-right: auto; display: inline;" /><br/>
<br/>
... and maybe inspire some people to join the adventure.<br/>
<br/>
<br/><u><b>TABLE OF CONTENT :</b></u><br/>
<br/>
<a href="index.php">Part 1:  Introduction</a><Br/>
<a href="strike_commander_architecture.php">Part 2: Game Architecture</a><Br/>
<a href="strike_commander_assets.php">Part 3: Reverse Engineer Assets</a><Br/>
<a href="strike_commander_game.php">Part 4: Play the game again</a><Br/>
<a href="strike_commander_oculus_rift.php">Part 5: Oculus Rift</a><Br/>

</p>

<h2>Before Strike Commander
</h2>
<p>
  Early 90s flight simulators were good but like <a href="http://en.wikipedia.org/wiki/Falcon_(video_game_series)#Falcon_3.0">Falcon 3.0</a> 
  or <a href="http://en.wikipedia.org/wiki/History_of_Microsoft_Flight_Simulator#Flight_Simulator_4.0">Flight simulator 4.0</a> they focused mostly on accurate flying models than beautiful rendition :<br/>
  <br/>
  <img class="shadowed"  src="falcon3_small.jpg" style="margin-left: auto; margin-right: auto; display: inline;" />
  <img class="shadowed"  src="flight_simulator_4_small.gif" style="margin-left: auto; margin-right: auto; display: inline;" /><br/>
  <br/>
 There were many fight simulator on the market and few people noticed the 1990 Origin Systems announcement for a new game. But things
 changed after Chicago CES 1991 where a demo could be seen in action : 
  Nobody could believe the game could feature things only seen in military flight simulator so far: Texture Mapping, Gouraud Shading, Haze and more. 
  Screenshots demonstrated a technology far ahead any competitors :<br/>
  <br/>
  <img class="shadowed"  src="sick_game_small.png" style="margin-left: auto; margin-right: auto; display: inline;" />
  <img class="shadowed"  src="sick_game_cockpit_small.png" style="margin-left: auto; margin-right: auto; display: inline;" /><br/>
  <img class="shadowed"  src="sc_story_small.png" style="margin-left: auto; margin-right: auto; display: inline;" />
  <img class="shadowed"  src="sc_story2_small.png" style="margin-left: auto; margin-right: auto; display: inline;" /><br/>
  <br/>
  After 1991 the game became highly anticipated. Not only the engine was gorgeous and the story captivating, RealSpace also supported exceptional hardware out of the box: The very expensive 
  and fragile accessories that every flight simulator 
  enthusiast wanted were the THRUSTMASTER WEAPON CONTROL SYSTEM and the THRUSTMASTER FLIGHT CONTROL SYSTEM:<br/>
  <br/>
  <img src="tm_TQS-web.jpg" class="shadowed"  style="margin-right: 100px ; display: inline;"/>
  <img src="tm_FCS-web.jpg" class="shadowed"  style="margin-left: auto; margin-right: auto; display: inline;"/>
  <br/>
  <br/>
  And you could even connect the THRUSTMASTER RUDDER:<br/>
  <br/>
  <img src="tm_rcs-web.jpg" class="shadowed"  style="margin-left: auto; margin-right: auto; display: block;"/><br/>
  <br/>
  Still, there was more: The game also supported a Virtual Cockpit. The
  4-way 'hat switch' on the ThrustMaster allowing to move the pilot's head and follow ground objects/enemy jets without the need for a Virtual Reality HeadSet :<br/>
  <br/>
  <img src="sick_game_v_cockpit_small.png" class="shadowed"  style="margin-left: auto; margin-right: auto; display: inline;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
  <img src="sick_game_v_cockpit2_small.png"  class="shadowed"  style="margin-left: auto; margin-right: auto; display: inline;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/><br/><br/>
  
</p>

<h2>1993: First Contact</h2>
<p>
  The game and its 3D engine were mind blowing but required an impossibly powerful machine :
  <ul>
    <li>IBM PC 486-DX2 66Mhz</li>
    <li>4MB RAM</li>
    <li>38MB mandatory installation</li>
    <li>Game comes on 11 x 1.44MB floppy disks.</li>
  </ul>
<p>
  Adjusted to today technological inflation the recommended configuration would be : 
  <ul>
      <li>8 Cores CPU with 16 GB of RAM.</li>
      <li>Dual Nvidia Titan GPUs.</li>
      <li>Mandatory install of 1000 GB.</li>
      <li>Game comes on five BluRays.</li>
  </ul>
  <p>
  And purchasing the game was not enough, you also had to survive the installation ! Upon opening the box you would be faced with 8 floppy disks (
  +3 for the Speech Pack):<br/>
  <br/>
  
  <img class="shadowed"  style="margin-left: auto; margin-right: auto; display: inline;" src="Strike-Poster_small.png"/>
  <img class="shadowed"  style="margin-left: auto; margin-right: auto; display: inline;" src="sc_disks_small.jpg"/>
  </p>
  <p>
   <u><b>Trivia :</b></u> Notice the poster announcing a Christmas 1991 release. The game would not be completed until 1993 after a long process that Chris Robert labeled "The Apocalypse Now of computer games".<br/>
  <br/>
   Decompressing the game from floppies to hard-drive and swapping the 13 flopping disk took a good 30 minutes. And when you thought you were done,
   the game proceeded to generate all the maps. The size of the game would blow up from 24MB to 38MB: Four times the size of any game back them.<br/>
    <br/>
  <img src="sc_mapgenerator.png" class="shadowed"  style="margin-left: auto; margin-right: auto; display: block;"/><br/>
  <br/>
  <u><b>Trivia :</b></u> A map was generated from a single "seed" (an integer number) that was injected in a pseudo-random numbers generation algorithm.
  This was a clever technique that avoided shipping data by generating the map after installation. If you are curious about this technique, go read <a href="http://www.amazon.com/The-Backroom-Boys-Secret-British/dp/0571214975">The Backroom Boys</a> and the chapter about Frontier Elite game.<br/>
  <br/>
   The maps generation step took ONE hour on a 386 PC. But Origin Systems had the good idea to ship with <a href="docs/sudden_death.JPG">the box</a> a superb 100 pages magazine set in the dystopian 2012 world of the game. <a href="docs/StrikeCommanderManual.pdf">Sudden Death</a>  made the entire process less painful ( notice the fake advertisement on page 38 promising the release of Strike Commander for Christmas 2013).
        
   <br/>
 </p>

 <h2>Strike Commander !</h2>
<p>
  Finally after all those steps, players were able to enjoy the game....in April 1993 ! Despite being 2 years late, the game was everything Origin promised and it sold very well. Many spent nights after nights dogfighting even if for most what was supposed to look like this :<Br/>
  <br/>
   <img src="sc_ingame.png" class="shadowed"  style="margin-left: auto; margin-right: auto; display: block;" /><br/>
   <br/>
   ...ended up looking like that on minimum settings :<br/>
   <br/>
   <img src="sc_ingame_low.png" class="shadowed" style="margin-left: auto; margin-right: auto; display: block;" /><br/>
<br/>
   Overall the game was enough to captivate pilots and generate fond memories.
</p>




<h2>The Lost Source Code</h2>
<p>
  With the Oculus Rift release, my interest in Strike Commander peaked again: The hardware was ready. Since
  it was a 20 years old game, I expected the source code to have been released but I quickly found out the sad story of Origin Systems 
  decline.<br/>
  <br/>
  Origin Systems was acquired by Electronic Arts in September 1992 and all projects were canceled circa 1999 following poor sales of
  Ultima 9. The company was to refocus on an other field they pioneered: <a href="http://en.wikipedia.org/wiki/Ultima_Online">MMORPG Ultima Online</a>.
  Most people assume the source codes and gold versions of all finished games were stored in a Vault somewhere at EA. 
  But after getting in touch with people at <a href="http://www.wcnews.com/chatzone/threads/wing-commander-source-code.24840/">Wing Commander CIC</a>, 
  it appeared that all the source code was lost when the company closed.<br/>
  <br/>
  It is something hard to believe today but back then developers and companies were more focused on the next title
  instead of preserving "old things", there was not nostalgia factor, no huge fan base and no market like <a href="http://www.gog.com/">Good Old Games</a> today. Many stories could illustrate how "primitive" source control was but the best 
  is probably the "ZAP SC" story at 15m14s :<br/>
  <br/>
  <div style="display:block; width:100%; text-align: center;">
     <iframe width="560" height="315" src="https://www.youtube.com/embed/K8gj2YyB0Hg#start=922" frameborder="0" allowfullscreen></iframe>
  </div>
  <br/>
  On his first day one developer managed to delete the full 900MB of Strike Commander source tree. The IT team spent 72 hours recovering everything from developers machines. The interview also mention that Wing Commander 1 and 2 code was exchanged via floppy disks: They did not have a network until SC !
  <br/>
  <br/>
  <u><b>Trivia :</b></u> In a surprising turn of event, some of the source code re-emerged recently via ex-Origin developers: Wing Commander CIC 
  maintains an off-line archive which features the source codes of <a href="http://cdn.wcnews.com/newestshots/full/squadronsourcecode.png">Wing Commander I</a>
  <a href="http://cdn.wcnews.com/newestshots/full/wc3sourcecode.PNG">Wing Commander  III</a> and people working on Ultima 8 were offered (but turned down) 
  the source code of "Ultima 8: Pagan" by <a href="http://exult.sourceforge.net/forum/read.php?f=1&i=13863&t=13863">an anonymous source</a>. As for Strike Commander, I have never heard of someone having it.
</p>


<h2>Reverse Engineering: Can it be done ?</h2>
<p>
  Over the years many teams had done work on Origin Systems game and reached great results:
  <ul style="overflow: auto;">
    <li><a href="http://uw2rev.sourceforge.net/">Underworld II Revial</a> reimplemented <a href="http://en.wikipedia.org/wiki/Ultima_Underworld_II:_Labyrinth_of_Worlds">Ultima Underworld II: Labyrinth of Worlds</a>.</li>
    <li><a href="http://exult.sourceforge.net/screenshots.php">Exult</a> reimplemented <a href="http://en.wikipedia.org/wiki/Ultima_VII:_The_Black_Gate">Ultima VII: The Glack Gate</a>.</li>
    <li><a href="http://pentagram.sourceforge.net/screenshots.php">Pentagram</a> reimplemented <a href="http://en.wikipedia.org/wiki/Ultima_VIII:_Pagan">Ultima VIII: Pagan</a> (check out the code, the design based on actors being processes within a kernel is beautiful).</li>
  </ul>
  <p>
   How long and how hard would it be ? After chatting with Gregory Montoir who did most of the reverse engineer on <a href="../anotherWorld_code_review/index.php">Another World</a>
  I learned that working one hour per evening allowed to reverse 10KB of assembly to C each month. There are many executable in Strike Commander and the initial discouraging time estimate was :<br/>
 <br/>
  <pre class="long">


  INSTALL.EXE       7,793 bytes :  2 weeks
  MKTERR.EXE      203,744 bytes :  1.5 years
  SC.EXE           20,000 bytes :  1 month
  MKGAME.EXE      131,696 bytes :  1 year
  OPTTEST.EXE     870,528 bytes :  7 years
  STRIKE.EXE      746,304 bytes :  6 years
  =============================================

                                  15 years, 7 months and 2 weeks. Ouch.

</pre>
<p>
  That was upsetting: If someone had started back in 1993 then he would have finished six years ago and I would just have had to <code>git clone </code> it :( ! But after starting up <a href="https://www.hex-rays.com/index.shtml">IDA</a> and taking a quick look
  it turned out that not all of it would have to be reverse engineered: The 3D engine is fully contained within STRIKE.EXE and a small team 
  could do it in a reasonable amount of time.

  <br/>
</p>

<h2>Road Map</h2>
<p>
  The road-map I initially drew in order to reverse engineer Strike Commander was as follow :
  <ol style="overflow: auto;">
   <li>Gather as much documentation as possible.</li>
   <li>Understand the Global Architecture of Strike Commander.</li>
   <li>Reverse-Engineer the Game Assets.</li>
   <li>Document step 3 and extrapolate (Visual Surface Determination method, Level Of Detail, ...)</li>
   <li>Re-implement the 3D engine and build <code>NEO_STRIKE.EXE</code></li>
   <li>Add support for VR device Oculus Rift.</li>
  </ol>
  <p>
    And then I got busy.
</p>


<h2>Next</h2>
<p>
  <a href="strike_commander_architecture.php">Architecture and Documentation</a>

  
</p>

    
  <!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

