<script type="text/javascript">
  var disqus_identifier = "SC_Reverse_Engineering";
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Reverse Engineering Strike Commander"/>
		<meta name="Description" content="Reverse Engineering Strike Commander"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>Reverse Engineering Strike Commander</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       Jan 22th, 2014</div>
   <h1>Strike Commander: Architecture and Documentation</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="icon_plane.png" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         
    
    <style>

 .comment{color: rgb(66,135,65);}
 .keyword{color: rgb(182,16,162);}
 .literal{color: rgb(218,37,36);}

 .include{color: rgb(117,85,119);}

 .numbers{color: rgb(96,0,205);}

h4 {
 
  border-bottom: 0px;
  font-size: 15px;
}

  pre{
    font: 12px courrier,monospace;
  }
 </style>

This page describes the architecture of Strike Commander and provides a list of all relevant documentation.<br/>
<br/>
<br/><u><b>TABLE OF CONTENT :</b></u><br/>
<br/>
<a href="index.php">Part 1:  Introduction</a><Br/>
<a href="strike_commander_architecture.php">Part 2: Game Architecture</a><Br/>
<a href="strike_commander_assets.php">Part 3: Reverse Engineer Assets</a><Br/>
<a href="strike_commander_game.php">Part 4: Play the game again</a><Br/>
<a href="strike_commander_oculus_rift.php">Part 5: Oculus Rift</a><Br/>
<div style="clear:both;"/>
</p>

<h2>Architecture</h2>
<p>
  Strike Commander is not made of one monolithic executable. Instead six executable collaborate together to 
  generate the game experience. The core idea is similar to what found in <a href="../second_reality/index.html">Second Reality code Review</a>. 
  Several EXE can have multiple explanations:
  <ul>
    <li>Improved team collaboration (each member could work on a part without impacting the others).</li>
    <li>Programs were limited to 640KB RAM because of DOS real-mode. A big monolithic executable would have caused a lot of disk swapping or not been loadable at all.</li>
  </ul>
  <p>
  Upon inspection with IDA, it turned out that each executables featured DOS 21h system call
  to load and start others <code>.EXE</code>. For example, the story mode which takes care of 
  dialogs and cinematic is <code>OPTTEST.EXE</code>. It removes itself from RAM and load/starts <code>STRIKE.EXE</code> when the 3D action is needed.
  <br/>
  <br/>
  DosBOX was very handy to explore and discover what components were responsible for which part of Strike Commander:
  The currently running executable name appears in the Window Title:<br/>
  <br/>
  <style>
    table.archi tr td, th {
    border: 1px solid black;
    }
    table.archi {
    border-collapse: collapse;
    background-color: #FFF;
    }
     tr td{
      margin: 10px;
      padding: 10px;
    }
  </style>
  <table class="archi" border=1 width="100%">
    <tr>
      <th>
        Executable
      </th>
      <th>
        Screenshot
      </th>
      <th>
        Notes
      </th>
    </tr>
    <tr>
      <td>
        INSTALL.EXE
      </td>
      <td>
        <img src="stages/Untiitled&#32;5_small.png" style="box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
      </td>
      <td>
        A laucher that starts MKGAME.EXE
      </td>
    </tr>

     <tr>
      <td>
        MKGAME.EXE
      </td>
      <td>
        <img src="stages/Untitled&#32;8_small.png" style="box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/><br/>
        <img src="stages/Untitled&#32;6_small.png" style="box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/><br/>
      </td>
      <td>
        
        The real installer: 
        <ul style="overflow: auto;">
            <li>Make boot disk.</li>
            <li>Detect sound card.</li>
            <li>Perform copy protection (question with answer in Sudden Death magazine).</li>
            <li>Decompress the 8 floppy disks.</li>
        </ul>
      </td>
    </tr>
     <tr>
      <td>
        MKTERR.EXE
      </td>
      <td>
         <img src="stages/Untitled&#32;11_small.png" style="box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/><br/>
        <img src="stages/Untitled&#32;9_small.png" style="box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/><br/>
        <img src="stages/Untitled&#32;12_small.png" style="box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
      </td>
      <td>
        The map generator in charge of producing all elements of a map and group them in a PAK:
        <ul style="overflow: auto;" style="box-shadow: rgb(119, 119, 119) 3px 3px 3px;">
       
         <li>ALASKA.PAK<li>ANDMAL1.PAK<li>ANDMAL2.PAK<li>
        ARENA.PAK<li>CANYON.PAK<li>EGYPT.PAK<li>EUROPE.PAK<li>MAPDATA.PAK<li>MAURITAN.PAK<li>QUEBEC.PAK<li>RHODEI.PAK<li>
        SANFRAN.PAK <li> TURKEY.PAK
         </ul>
      </td>
    </tr>
     <tr>
      <td>
        OPTTEST.EXE
      </td>
      <td>
        <img src="stages/Untitled&#32;13_small.png" style="box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/><br/>
        <img src="stages/Untitled&#32;14_small.png" style="box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/><br/>
        <img src="stages/Untitled&#32;16_small.png" style="box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/><br/>
      </td>
      <td>
        Responsible for all midgames dialogs, cinematic, menu, hangar weapon selection and object viewer.
      </td>
    </tr>
     <tr>
      <td>
        SC.EXE
      </td>
      <td>
        <img src="stages/Untiitled&#32;5_small.png" style="box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
      </td>
      <td>
        The way the game used to be started. It usually load and executes <code>OPTTEST.EXE</code>.
      </td>
    </tr>
    <tr>
      <td>
        STRIKE.EXE
      </td>
      <td>
        <img src="stages/Untitled&#32;15_small.png" style="box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/><br/>
      </td>
      <td>
        RealSpace 3D engine. Responsible for action phase.
      </td>
    </tr>
  </table>
  <br/>
  <br/>
  <u>Note:</u> If you delete a map PAK archive, <code>STRIKE.EXE</code> will detect the missing file and will automatically spawn <code>MKTERR.EXE</code> in order to regenerate
  the map.<br/>
  <br/>
  So most of the effort is to be focused on <code>OPTTEST.EXE</code> and <code>STRIKE.EXE</code>. Something that hasn't been
  done yet is to determine how parameters are passed between them. Dos 21h system calls allows command line parameters and a specific page of memory to contain data but the state of the game could also be stored on HD: IDA will tell.

</p>
<h2>Important files List</h2>
<p>
  Here are the important files :
  <pre class="long">


    //Executables
      16 -rw-r--r--  1 fabiensanglard  staff      7,793 17 Jan 03:02 INSTALL.EXE
     264 -rw-r--r--  1 fabiensanglard  staff    131,696 17 Jan 03:02  MKGAME.EXE
     400 -rw-r--r--  1 fabiensanglard  staff    203,744 17 Jan 03:03  MKTERR.EXE
    1704 -rw-r--r--  1 fabiensanglard  staff    870,528 17 Jan 03:02 OPTTEST.EXE
      16 -rw-r--r--  1 fabiensanglard  staff      7,793 17 Jan 03:09      SC.EXE
    1464 -rw-r--r--  1 fabiensanglard  staff    746,304 17 Jan 03:03  STRIKE.EXE

    //Assets
   19832 -rw-r--r--  1 fabiensanglard  staff 10,150,560 17 Jan 03:03 GAMEFLOW.TRE
     952 -rw-r--r--  1 fabiensanglard  staff    485,877 17 Jan 03:02     MISC.TRE
    1304 -rw-r--r--  1 fabiensanglard  staff    665,456 17 Jan 03:02 MISSIONS.TRE
   13544 -rw-r--r--  1 fabiensanglard  staff  6,932,708 17 Jan 03:02  OBJECTS.TRE
    1760 -rw-r--r--  1 fabiensanglard  staff    899,145 17 Jan 03:02    SOUND.TRE
    3288 -rw-r--r--  1 fabiensanglard  staff  1,681,738 17 Jan 03:02 TEXTURES.TRE

    //Maps
    2040 -rw-r--r--  1 fabiensanglard  staff  1,042,674 17 Jan 03:05   ALASKA.PAK
    2040 -rw-r--r--  1 fabiensanglard  staff  1,042,570 17 Jan 03:04  ANDMAL1.PAK
    2040 -rw-r--r--  1 fabiensanglard  staff  1,042,960 17 Jan 03:09  ANDMAL2.PAK
    2048 -rw-r--r--  1 fabiensanglard  staff  1,046,382 17 Jan 03:09    ARENA.PAK
    2040 -rw-r--r--  1 fabiensanglard  staff  1,043,268 17 Jan 03:06   CANYON.PAK
    2032 -rw-r--r--  1 fabiensanglard  staff  1,038,716 17 Jan 03:05    EGYPT.PAK
    2024 -rw-r--r--  1 fabiensanglard  staff  1,033,096 17 Jan 03:07   EUROPE.PAK
     656 -rw-r--r--  1 fabiensanglard  staff    333,464 17 Jan 03:02  MAPDATA.PAK
    2040 -rw-r--r--  1 fabiensanglard  staff  1,044,396 17 Jan 03:03 MAURITAN.PAK
    2032 -rw-r--r--  1 fabiensanglard  staff  1,037,798 17 Jan 03:04   QUEBEC.PAK
    2040 -rw-r--r--  1 fabiensanglard  staff  1,043,840 17 Jan 03:08   RHODEI.PAK
    2048 -rw-r--r--  1 fabiensanglard  staff  1,046,316 17 Jan 03:06  SANFRAN.PAK
    2048 -rw-r--r--  1 fabiensanglard  staff  1,045,766 17 Jan 03:08   TURKEY.PAK

    //Maps Seeds Files
      80 -rw-r--r--  1 fabiensanglard  staff     37,732 17 Jan 03:02 MSFILES.PAK

    // The 3D engine palette
      8 -rw-r--r--  1 fabiensanglard  staff       1,806 17 Jan 03:02  PALETTE.IFF
    
  </pre>

</p>

<h2>Documentation relevant to Strike Commander</h2>
<p>
 
  <ul>
  <li>PAK Archive Format (<a href="docs/wc1g.txt">wc1g.txt</a>).</li>
  <li>TRE Archive Format  (<a href="docs/wc1g.txt">wc1g.txt</a>).</li>
  <li>RLE Run Length Encoding for images and animations  (<a href="docs/wc1g.txt">wc1g.txt</a>).</li>
  <li>IFF Format (<a href="docs/IFF.txt">IFF.txt</a> and <a href="docs/A&#32;Quick&#32;Introduction&#32;to&#32;IFF.txt">A Quick Introduction to IFF.txt</a>).</li>
  <li>VOC Audio format Creative Voice (VOC) (<a href="docs/Creative&#32;Voice&#32;(VOC)&#32;file&#32;format.txt">Creative Voice (VOC) file format.txt</a>).</li>
  <li>Extended MIDI (XMIDI) Music Format. Format was opensourced by its author John Miles (<a href="docs/AIL2.ZIP">AIL2.ZIP</a> and <a href="docs/XMIDI.TXT">XMIDI.TXT</a>).</li>
  <li>Borland DOS C++ Development System (<a href="docs/Borland_C___Power_Programming_Book_and_Disk__Programming_.pdf">Borland C++ Power Programming Book and Disk Programming_.pdf</a>).</li>
  <li>The Art of Assembly Language DOS 16bits edition (<a href="http://www.plantation-productions.com/Webster/www.artofasm.com/DOS/index.html">website</a>).</li>
  <li>IDA Free version (<a href="https://www.hex-rays.com/products/ida/support/download_freeware.shtml">IDA5.0 download</a>).</li>
  <li>Origin PlayerTester Guide (contains details about the damage area in a jet) <a href="docs/Strike&#32;Commander&#32;Playtesters&#32;Guide&#32;(1998)(Origin&#32;Systems).pdf">Strike Commander Playtesters Guide (1998)(Origin Systems).pdf</a>.</li>
  <li>Jet aerodynamic properties by Wayne Sikes in Game Developer Magazine Dec 94 (<a href="docs/GDM_December_1994.pdf">GDM_December_1994.pdf</a>).</li>
  <li>Sudden Death magazine (<a href="docs/StrikeCommanderManual.pdf">StrikeCommanderManual.pdf</a>).</li>
  <li>Strike Commander Strategy Guide (<a href="docs/StrikeCommanderStrategyGuide.pdf">StrikeCommanderStrategyGuide.pdf</a>).</li>
  <li>Techno Report (<a href="docs/Origin_Software_Technogoly_Entertainment_Report.pdf">Origin_Software_Technogoly_Entertainment_Report.pdf</a>).</li>
  <li>Brian Hook: "Building a 3D Game Engine in C++": Thrust Master drivers programming (<a href="docs/AST3D.zip">AST3D.zip</a>).</li>
</ul>
</p>

<h2>Next</h2>
<p>
    <a href="strike_commander_assets.php">Reverse Engineering Assets</a>
</p>
    
  <!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

