<script type="text/javascript">
  var disqus_identifier = "SC_Reverse_Engineering";
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Reverse Engineering Strike Commander"/>
		<meta name="Description" content="Reverse Engineering Strike Commander"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>Reverse Engineering Strike Commander</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       Jan 22th, 2014</div>
   <h1>Strike Commander: Assets Reverse engineering</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="icon_plane.png" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         
    
    <style>

 .comment{color: rgb(66,135,65);}
 .keyword{color: rgb(182,16,162);}
 .literal{color: rgb(218,37,36);}

 .include{color: rgb(117,85,119);}

 .numbers{color: rgb(96,0,205);}

h4 {
 
  border-bottom: 0px;
  font-size: 15px;
}

  pre{
    font: 12px courrier,monospace;
  }
 </style>

On this page are referenced all the formats used in Strike Commander. 
Tools used so far are HexEditor, DOSBOx debug Mode and IDA.<br/>
<br/>
<br/><u><b>TABLE OF CONTENT :</b></u><br/>
<br/>
<a href="index.php">Part 1:  Introduction</a><Br/>
<a href="strike_commander_architecture.php">Part 2: Game Architecture</a><Br/>
<a href="strike_commander_assets.php">Part 3: Reverse Engineer Assets</a><Br/>
<a href="strike_commander_game.php">Part 4: Play the game again</a><Br/>
<a href="strike_commander_oculus_rift.php">Part 5: Oculus Rift</a><Br/>
<div style="clear:both;"/>
</p>

<h2>Archive system</h2>
<p>
  Both PAK and TRE are 100% understood thanks to <a href="https://github.com/fabiensanglard/libRealSpace/blob/master/doc/wc1g.txt">Mario's specs</a>.
  <ul>
    <li><a href="https://github.com/fabiensanglard/libRealSpace/blob/master/doc/strike_commander_tre_content.txt">List of files in the TRE archives</a>.</li>
  </ul>
  <p>
    Archive can easily be manipulated/decompressed via TreArchive and PakArchvive in libRealSpace.
</p>


<h2>Jets</h2>
<p>
  Jets are stored in fully contained file in IFF archives. They are 95% understood. Four key parts:
  <ol>
    <li>Aerodynamic properties.</li>
    <li>Damage system and HP</li>
    <li>Weapon system</li>
    <li>
      Appearance
      <ol>
        <li>3D Data</li>
        <li>Textures</li>
       </ol>
    </li>
  </ol>
  <p>
  See <a href="https://github.com/fabiensanglard/libRealSpace/blob/master/doc/strike_commander_jet_format.txt">JET Format specs</a>.
</p>

<h2>Maps</h2>
<p>
  Maps are 95% understood. They are store in a <code>X.PAK</code> but also reference textures in <code>TEXTURES.TRE</code>.
  See <a href="https://github.com/fabiensanglard/libRealSpace/blob/master/doc/strike_commander_map_format.txt">Map Format specs</a>.<Br/>
  See <a href="https://github.com/fabiensanglard/libRealSpace/blob/master/doc/strike_commander_map_texture_format.txt">Texture map Format specs</a>.<Br/>
</p>

<h2>Menus</h2>
<p>
  Menu are 50% understood (Rendition but not logic).<br/>
  No specs yet.
</p>

<h2>Animations</h2>
<p>
  Animation are 50% understood:
  <ul>
    <li>Individual layers can be rendered and played.</li>
    <li>Palette to use is understood.</li>
    <li>Compositor to assemble layers together is not known.</li>
  </ul>


  See <a href="https://github.com/fabiensanglard/libRealSpace/blob/master/doc/strike_commander_animation_format.txt">Animation Format specs</a>.
</p>

<h2>Palettes</h2>
<p>
  Palette are 100% understood :
  See <a href="https://github.com/fabiensanglard/libRealSpace/blob/master/doc/strike_commander_palette_format.txt">Palettes Format specs</a>.<Br/>
  
</p>

<h2>IA/Game Logic</h2>
<p>
  Not work done so far. This is probably all in the EXE.<br/>
  Given the time and documentation found in the PlayTester Guide, I expect more than a simple decision tree: Probably a hierarchical state machines.<br/>
  Read <A href="http://www.amazon.com/Artificial-Intelligence-Games-Ian-Millington/dp/0123747317">Arctificial Intelligence for Games</a> for a good coverage of all
  techniques.
</p>


<h2>Savegame</h2>
<p>
  The format of the saved game is 75%% known:
  See <a href="https://github.com/fabiensanglard/libRealSpace/blob/master/doc/cheatcodes.txt">Savegame Format Specs</a>
</p>


<h2>Next</h2>
<p>
  <a href="strike_commander_game.php">Re-implementing Strike Commander</a>
</p>

    
  <!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

