<script type="text/javascript">
  var disqus_identifier = "Computer_graphics_Principles_andPractice";
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Computer Graphics: Principles and Practice, Third Edition , The Computer Graphics Library"/>
		<meta name="Description" content="Computer Graphics: Principles and Practice, Third Edition, The Computer Graphics Library"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
	
 	
		
		<title>The Computer Graphics Library</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       March 12th, 2014</div>
   <h1>The Computer Graphics Library</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="cgpp.png" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         
        <!-- Add fancyBox -->
  <link rel="stylesheet" href="../fancybox/source/jquery.fancybox.css?v=2.1.5" type="text/css" media="screen" />
  <script type="text/javascript" src="../fancybox/source/jquery.fancybox.pack.js?v=2.1.5"></script>

    <style>

 .comment{color: rgb(66,135,65);}
 .keyword{color: rgb(182,16,162);}
 .literal{color: rgb(218,37,36);}

 .include{color: rgb(117,85,119);}

 .numbers{color: rgb(96,0,205);}

h4 {
 
  border-bottom: 0px;
  font-size: 15px;
}

  pre{
    font: 12px courrier,monospace;
  }
 </style>
 <p>
Back in the 90s, one book was ubiquitous in the world of Computer Graphics. Commonly called "The CG Bible", 
<a href="http://www.amazon.ca/Computer-Graphics-Principles-Practice-2nd/dp/0201848406/ref=sr_1_2?ie=UTF8&qid=1382128751&sr=8-2&keywords=computer+graphics+principles+and+practice">Computer Graphics: Principles and Practice</a> gathered a huge part of the knowledge of the time. 
It was commonly referenced by the best programmers of that era in <a href="../fd_proxy/doom3/pdfs/johnc-interviews.pdf">interviews</a> and <A href="quake_s&#32;hidden-surface&#32;removal.pdf">articles</a>. By 1998, the book popularity had been acknowledged with a Front Line Award.<br/>
<br/>
In order to keep up with the explosion of CG, the book has been updated twice. The third edition was 
released on July 2013 and it even features material from the <a href="../shadowmapping/index.php">shadow mapping article</a> 
I wrote back in 2009 !
<br/>
    <div style="clear:both;"></div>
</p>





<h2>The CG Bible through the ages</h2>
<p>
  The CG Bible was first published in 1982 under the name <a href="http://www.amazon.com/Fundamentals-Interactive-Computer-Graphics-Programming/dp/0201144689/ref=sr_1_1?s=books&ie=UTF8&qid=1382452501&sr=1-1&keywords=Fundamentals+of+Interactive+Computer+Graphics">Fundamentals of interactive Computer graphics</a>. It was updated a first time in 1995 as <a href="http://www.amazon.com/Computer-Graphics-Principles-Practice-2nd/dp/0201848406/ref=sr_1_2?s=books&ie=UTF8&qid=1382452568&sr=1-2&keywords=Computer+Graphics%3A+Principles+and+Practice">Computer Graphics: Principles and Practice in C</a>. And again in July 2013 as : <a href="http://www.amazon.com/Computer-Graphics-Principles-Practice-Edition/dp/0321399528/ref=dp_ob_title_bk">Computer Graphics: Principles and Practice</a>.<br/>
  <br/>
  <br/>
  <div style="display:block;width:100%;text-align:center;">
    <img src="cgpp1_small.png" style="margin-right: 25px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
    <img src="cgpp2_small.png" style="height:398px; margin-right: 25px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;border-color:#DDD;border-style:solid;border-width:1px;"/>
   <img src="cgpp3_small.png" style="margin-right: 25px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
  </div>
  <br/>
  <p>
  
  <br/>
  The three successive covers of the book, spanning over 30 years, summarize perfectly the tremendous evolution of CG: 
  <ul>
    <li>From a simple 6 faces textured cube to as multi-million shadered polygons scene.</li>
    <li>From two authors :
        <ul>
          <li>James D.Foley</li>
          <li>Andries Van Dam</li>
        </ul> 
        To seven :
         <ul>
          <li>John F. Hughes</li>
          <li>Andries Van Dam</li>
          <li>Morgan McGuire</li>
          <li>David F.Sklar</li>
          <li>James D.Foley</li>
          <li>Steven K.Feinier</li>
          <li>Kurt Akeley</li>          
        </ul>
      </li>
  </ul>
  <p>
  <u><b>Trivia :</b></u> The first edition was <a href="https://twitter.com/ID_AA_Carmack/status/404401824293060609">John Carmack's bible in the 80s</a> He even tried to make the cover image on his //GS, but couldn't get perspective correct texturing.<br/>
</p>


<h2>The CG Library</h2>
<p>
  The CG Bible is still a pretty good book today. But in order to keep up with CG
  one needs to build a library :<br/>
  <br/>
   <div style="display:block;width:100%; margin: 0px 0 0 15px; padding: 25px 0px 10px 0px;text-align:center; background-color:white; border-color:#DDD;border-style:solid;border-width:1px;">
    <img src="books/real-time-rendering.jpg"                                     style="height:400px; margin-right: 8px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
    <img src="books/Computer-Organization-and-Design-Revised-Fourth-Edition.jpg" style="height:400px; margin-right: 8px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
    <img src="cgpp3_small.png"                                                   style="height:400px; margin-right: 8px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>

    <Br/>
    <div style="display:block;width:100%;font:12px/22px 'Helvetica Neue', sans-serif;margin: 10px 0 0 0px;">
      <u>A Good Start</u>
    </div>
  </div>
  <br/>
  <p>
    A BIG library :<br/>
  <br/>
  <u><b>Shader X Serie :</b></u><br/>
  <div style="display:block;width:100%; padding: 0 0 0 15px;">
    <img src="books/ShaderX1.jpg"  style="height:150px; margin-right: 8px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
    <img src="books/ShaderX2.jpg"  style="height:150px; margin-right: 8px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
    <img src="books/ShaderX22.png" style="height:150px; margin-right: 8px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
    <img src="books/ShaderX3.jpg"  style="height:150px; margin-right: 8px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>

    <img src="books/ShaderX4.jpg"  style="height:150px; margin-right: 8px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
    <img src="books/ShaderX5.jpg"  style="height:150px; margin-right: 8px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
    <img src="books/ShaderX6.jpg"  style="height:150px; margin-right: 8px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
    <img src="books/ShaderX7.jpg"  style="height:150px; margin-right: 8px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
  </div>
  <p>
    Three first volumes are <a href="http://tog.acm.org/resources/shaderx/">available for free</a> on acm.org.
  <br/>
  <p>
  <u><b>GPU Gems Serie :</b></u><br/>
   <div style="display:block;width:100%; padding: 0 0 0 15px;">
    <img src="books/GPU&#32;Gems&#32;1.png" style="height:170px; margin-right: 8px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
    <img src="books/GPU&#32;Gems&#32;2.png" style="height:170px; margin-right: 8px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
    <img src="books/GPU&#32;Gems&#32;3.png" style="height:170px; margin-right: 8px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
  </div>
  
  <p>
  First two volumes available for free on NVidia website: <a href="https://developer.nvidia.com/content/gpu-gems">GPU Gems 1</a> and <a href="https://developer.nvidia.com/content/gpu-gems-2">GPU Gems 2</a>.<br/>
    

<br/>
  <u><b>GPU ProSerie :</b></u><br/>
   <div style="display:block;width:100%; padding: 0 0 0 15px;">
    <img src="books/GPUPro_1.png" style="height:170px; margin-right: 8px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
    <img src="books/GPUPro_2.png" style="height:170px; margin-right: 8px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
    <img src="books/GPUPro_3.png" style="height:170px; margin-right: 8px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
    <img src="books/GPUPro_4.png" style="height:170px; margin-right: 8px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
  </div>
  <br/>
<p>
<u><b>Graphic Gems Serie :</b></u><br/>
   <div style="display:block;width:100%; padding: 0 0 0 15px;">
    <img src="books/Graphics&#32;Gems&#32;I.gif" style="height:170px; margin-right: 8px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
    <img src="books/Graphics&#32;Gems&#32;II.jpg" style="height:170px; margin-right: 8px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
    <img src="books/Graphics&#32;Gems&#32;III.jpg" style="height:170px; margin-right: 8px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
    <img src="books/Graphics&#32;Gems&#32;IV.jpg" style="height:170px; margin-right: 8px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
    <img src="books/Graphics&#32;Gems&#32;V.jpg" style="height:170px; margin-right: 8px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>    
  </div>
 
  <p>
    Dated but still contains pearls such as the <a href="../rayTracing_back_of_business_card/index.php">Business card Raytracer</a>.<br/> 
     <br/>
 <u><b>The Raytracing classics :</b></u><br/> 
 <div style="display:block;width:100%; padding: 0 0 0 15px;">
     <img src="books/An&#32;introduction&#32;to&#32;raytracing.jpg" style="height:170px; margin-right: 8px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
    <img src="books/Physically-Based-Rendering-9780123750792.jpg" style="height:170px; margin-right: 8px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
    </div>
  <br/>
  <p>
 <u><b>The legendary Black Book :</b></u><br/> 
 <div style="display:block;width:100%; padding: 0 0 0 15px;">
     <img src="bb.png" style="height:170px; margin-right: 8px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
    </div>
  <br/>
  <p>
    Available <a href="http://www.drdobbs.com/parallel/graphics-programming-black-book/184404919">for free</a> on drdobbs.com.
    <br/>
    <br/>
  <u><b>The MUST READ :</b></u><br/> 
    <div style="display:block;width:100%; padding: 0 0 0 15px;">
     <img src="books/rtr3.png" style="height:170px; margin-right: 8px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
     <img src="books/RealTimeShadows.png" style="height:170px; margin-right: 8px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
     <img src="books/cover.png" style="height:170px; margin-right: 8px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
    </div>
  <br/>
  <p>
    And don't forget all the papers from siggraph :
    <ul>
      <li><a href="http://kesen.realtimerendering.com/sig2013.html">Siggraph Papers 2013</a></li>
      <li><a href="http://kesen.realtimerendering.com/sig2012.html">Siggraph Papers 2012</a></li>
      <li><a href="http://kesen.realtimerendering.com/sig2011.html">Siggraph Papers 2011</a></li>
      <li>...</li>
    </ul>
   <p>
    The field has become exponentially difficult to follow. It seems to be a general
    tendency: On the Game Programming side for example, the legendary JP. van Waveren from id Software provides a very good list of <a href="http://mrelusive.com/books/books.html">the books he recommends</a>. That is 92 books in total.<br/>
    <br/>
    

<div style="clear:both;"></div> 
</p>

<h2>Signed copy !</h2>
<p>
   <a id="mine1" href="mine/IMG_5146_full.jpg"><img style="float:left; margin-right: 25px; margin-top:10px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"  src="mine/IMG_5146_thumb.jpg"/></a>
 Spyke (John F. Hughe) was nice enough to send a complimentary copy, signed by himself and Andries Van Dam:<br/>
 <br/>
 <br/>
Below: The Seven CG Programmers !<br/>
 <a id="mine2" href="event/ShowBlogFile.jpg"><img style="float:left; margin-right: 15px; margin-top:10px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"  src="event/ShowBlogFile.jpg"/></a>
 <script type="text/javascript">
 $(document).ready(function() {
      $("#mine1").fancybox({
            helpers: {
                title : {
                    type : 'float'
                }
            }
        });
       $("#mine2").fancybox({
            helpers: {
                title : {
                    type : 'float'
                }
            }
        });
    });
  </script>
  <div style="clear:both;"></div>
</p>


  <!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

