<script type="text/javascript">
  var disqus_identifier = "Ghost_in_the_Wires_Paperback" ;
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Kevin Mitnick, Ghost in The Wire paperback, Cracking, Decyphering"/>
		<meta name="Description" content="Cracking Kevin Mitnick's Ghost in The Wire paperback."/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>Cracking Kevin Mitnick's Ghost in The Wire paperback edition</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       May 9, 2012</div>
   <h1>Cracking Kevin Mitnick's Ghost in The Wire paperback edition</h1>
   <p id="paperbox">
	   	
          <a  href="../Ghost_in_the_Wires/fullImage.jpg">
          <img src="../Ghost_in_the_Wires/icon.jpg" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         

I received yesterday a copy of <a href="http://www.amazon.ca/Ghost-Wires-Adventures-Worlds-Wanted/dp/0316037729/ref=sr_1_2?s=books&ie=UTF8&qid=1336618203&sr=1-2">Ghost In The Wire Paperback edition</a>. Kevin Mitnick seems to have updated all of the challenges found at the beginning of each chapters.
Since they are all available on <a href="http://books.google.ca/books?id=p-nRxITKc34C&pg=PT11&lpg=PT11&dq=Max+vhlm+hy+max+unl+wkboxk+ingva+B+nlxw+mh+ingva+fr+hpg+mktglyxkl&source=bl&ots=bREWkE2Q2h&sig=J3_p1C3u2tHm_HkdpVLGfCdJoGU&hl=en&sa=X&ei=ciarT9j7B4nk6QGPyoSuCQ&ved=0CCQQ6AEwAA#v=onepage&q=Max%20vhlm%20hy%20max%20unl%20wkboxk%20ingva%20B%20nlxw%20mh%20ingva%20fr%20hpg%20mktglyxkl&f=false">book.google.com preview</a> I don't think it is a big deal to publish and discuss our solutions here.<br/>
 <br/>
The codes are much more difficult than the hardcover edition and much more resistant to the <i>cribs</i>/bruteforce method <a href="../Ghost_in_the_Wires/index.php">I used last time</a>: The utility <code>CrackKevin.exe</code>  was able to crack 50% of the codes from the hardcover edition but only 5% of the paperback editon. Moreverover it seems a stack of obfuscation layers are used: <b>Chapter 14</b> encryption is:
    <ol start="1">
       <li>Remove all spaces.</li>
       <li>Reverse string.</li>
       <li>Encode with Base64.</li>
    </ol>
</br>
<div style="clear:both;"></div>
<br/>
<p>
Anyway here they are:<br/>
<br/>
<pre class="long">



    [0 ] <span style="color:rgb(192,28,28);">`Max vhlm hy max unl wkboxk ingva B nlxw mh ingva fr hpg mktglyxkl`</span>,
    <span style="color:rgb(30,132,43);">// DECODED (ROT) via crackKevin.exe:</span>
    <span style="color:rgb(30,132,43);">// the cost of the bus driver punch i used to punch my own transfer</span>
    <span style="color:rgb(30,132,43);">// Answer: $15</span>


    [1 ] <span style="color:rgb(192,28,28);">`Estd mzzv esle elfrse xp szh ez ncplep yph topyetetpd hspy T hld l acp-eppy`</span>,
    <span style="color:rgb(30,132,43);">// DECODED (ROT) via crackKevin.exe:</span>
    <span style="color:rgb(30,132,43);">// this book that taught me how to coeate new identities when i was a pre-teen</span>
    <span style="color:rgb(30,132,43);">// Answer: The Paper Trip</span>

    [2 ] <span style="color:rgb(192,28,28);">`pbzfsobp dkfobtpkx lq pbkfi ppbkfpry aoxtolc iixz lq abpr bobt pbzfsba cl bmvq obail bpbeQ`</span>,
    <span style="color:rgb(30,132,43);">// DECODED (reverse + ROT)</span>
    <span style="color:rgb(30,132,43);">// Reverse string: Qebpb liabo qvmb lc absfzbp tbob rpba ql zxii clotxoa yrpfkbpp ifkbp ql xkptbofkd pbosfzbp</span>
    <span style="color:rgb(30,132,43);">// ROT:            These older type of devices were used to call forward business lines to answering services</span>
    <span style="color:rgb(30,132,43);">// Answer: "diverters"</span>

    [3 ]</span>  <span style="color:rgb(192,28,28);">`gsvmznvlugsvnzrmuiznvhrszxpvwzgfhxrmgsvzikzmvgwzbh`</span>,
    <span style="color:rgb(30,132,43);">// DECODED (Atbash cypher commonly known as "pig latin") by "Kahootbird" and "xenex"</span>
    <span style="color:rgb(30,132,43);">// gsv mznv lu gsv nzrmuiznvh r szxpvw zg fhx rm gsv zikzmvg wzbh</span>
    <span style="color:rgb(30,132,43);">// the name of the mainframes i hacked at usc in the arpanet days</span>
    <span style="color:rgb(30,132,43);">// Q: "I took a course in this subject when I ran from the Juvenile authorities"</span>
    <span style="color:rgb(30,132,43);">// A: DEC TOPS-20 or DEC 20</span>

    [4 ]</span>  <span style="color:rgb(192,28,28);">`jbi ujt veo eco ntk iwa lhc eeo anu uir trs hae oni rfn irt toh imi ets shs !eu`</span>,
    <span style="color:rgb(30,132,43);">// DECODED (by "xenex"): Column Transposition - Key 321.</span>
    <span style="color:rgb(30,132,43);">// i t o o k a c o u r s e i n t h i s s u : "I took a course in this su"</span>
    <span style="color:rgb(30,132,43);">// b j e c t w h e n i r a n f r o m t h e : "bject when I ran from the "</span>
    <span style="color:rgb(30,132,43);">// j u v e n i l e a u t h o r i t i e s ! : "Juvenile authorities      "</span>
    <span style="color:rgb(30,132,43);">// Q: "I took a course in this subject when I ran from the Juvenile authorities"</span>
    <span style="color:rgb(30,132,43);">// A: In chapter 5 you will find the answer, which is "Criminal Justice."</span>

    [5 ]</span>  <span style="color:rgb(192,28,28);">`bmFtZXRoZWNvbXBhbnl3aGVyZWJvbm5pZXdhc2VtcGxveWVkd2hlbndlc3RhcnRlZGRhdGluZw==`</span>,
    <span style="color:rgb(30,132,43);">// DECODED (remove spaces + Base64)</span>
    <span style="color:rgb(30,132,43);">// Base64: namethecompanywherebonniewasemployedwhenwestarteddating</span>
    <span style="color:rgb(30,132,43);">// Add missing spaces:Name the company where bonnie was employed when we started dating</span>
    <span style="color:rgb(30,132,43);">// Answer: GTE</span>

    [6 ] <span style="color:rgb(192,28,28);">`multbqncannqenabrhfgacnqogehchetbkkebmsqgkncchebr`</span>,
    <span style="color:rgb(30,132,43);">// DECODED (by "xenex"): Substitution cipher (Key: GTE, the answer of the previous question)</span>
    <span style="color:rgb(30,132,43);">// Letter  : ABCDEFGHIJKLMNOPQRSTsUVWXYZ</span>
    <span style="color:rgb(30,132,43);">// Becomes : GTEABCDFHIJKLMNOPQRSUVWXYZ</span>
    <span style="color:rgb(30,132,43);">// Decoded: numberofdoorcodesihadforpacificbellcentraloffices</span>
    <span style="color:rgb(30,132,43);">// Spaces: Number of door codes I had for Pacific Bell central offices</span>
    <span style="color:rgb(30,132,43);">// Answer: 11</span>

    [7 ] <span style="color:rgb(192,28,28);">`'siass nuhmil sowsra amnapi waagoc ifinti dscisf iiiesf ahgbao staetn itmlro`</span>,
    <span style="color:rgb(30,132,43);">// DECODED (Column transposition)
    <span style="color:rgb(30,132,43);">// 'siass
    <span style="color:rgb(30,132,43);">// nuhmil
    <span style="color:rgb(30,132,43);">// sowsra
    <span style="color:rgb(30,132,43);">// amnapi
    <span style="color:rgb(30,132,43);">// waagoc
    <span style="color:rgb(30,132,43);">// ifinti
    <span style="color:rgb(30,132,43);">// dscisf
    <span style="color:rgb(30,132,43);">// iiiesf
    <span style="color:rgb(30,132,43);">// ahgbao
    <span style="color:rgb(30,132,43);">// staetn
    <span style="color:rgb(30,132,43);">// itmlro
    <span style="color:rgb(30,132,43);">// From left to right and bottom up:
    <span style="color:rgb(30,132,43);">// i said i wasn't this famous magician while being a smart ass top rison officials
    <span style="color:rgb(30,132,43);">// Answer:  "David Copperfield" (thanks to kahoot :) !).

    [8 ] <span style="color:rgb(192,28,28);">`tvifafwawehes hsesoonvtlimaeloemtcagmen irnoerrldony`</span>,
    [9 ] <span style="color:rgb(192,28,28);">`gnkusr ooursnsisti ttnotoihiec rolwaintmlk ovtgp`</span>,
    <span style="color:rgb(30,132,43);">// Very likely a Vigenere encryption, should try to use vigenere.exe on that</span>

    [10] <span style="color:rgb(192,28,28);">`ow gw ty kc qb eb nm ht ud pc iy ty ik tu zo dp gl qt hd`</span>,
    <span style="color:rgb(30,132,43);">// DECODED by Kahootbird (Fairplay cipher) </span>
    <span style="color:rgb(30,132,43);">// mybrotheradamlistenedtothistypeofmusic</span>
    <span style="color:rgb(30,132,43);">// My brother adam listened to this type of music</span>
    <span style="color:rgb(30,132,43);">// Solved with <a http://www.quinapalus.com/cgi-bin/playfair?plt=&cpt=ow+gw+ty+kc+qb+eb+nm+ht+ud+pc+iy+ty+ik+tu+zo+dp+gl+qt+hd&dict=0&reps=on&ent=Search</span>this tool</a></span>

    [11] <span style="color:rgb(192,28,28);">`idniidhsubrseognteiuignuhrzdalrd ietfetinmeablnigorcsnuatoieclei`</span>,
    <span style="color:rgb(30,132,43);">// DECODED (Column transposition by kahoot)</span>
    <span style="color:rgb(30,132,43);">// The trick was to add a return carriage after the space:</span>
    <span style="color:rgb(30,132,43);">// idniidhsubrseognteiuignuhrzdalrd </span>
    <span style="color:rgb(30,132,43);">// ietfetinmeablnigorcsnuatoieclei</span>
    <span style="color:rgb(30,132,43);">// Now read top to bottom and left to right:</span>
    <span style="color:rgb(30,132,43);">// i identified this number as belonging to eric using unauthorized caller id </span>
    <span style="color:rgb(30,132,43);">// Answer: 310-837-5412</span>
    
    [12] <span style="color:rgb(192,28,28);">`qclgjq'acrjcrlmqnyrcpgursmzyddmbcnngrgmfupceylyk`</span>,

    [13] <span style="color:rgb(192,28,28);">`c2VuaWxzJ2RhZHltbm9zcGF0ZXJpd2VodHRjZW5ub2NlcmRuYXNlbGVnbmFzb2xvdHlsZm90ZGFob2h3dG5lZ2F5dGlydWNlc2xsZWJjYXBlaHQ=`</span>,
    <span style="color:rgb(30,132,43);">// DECODED (remove space + inverse + Base64):</span>
    <span style="color:rgb(30,132,43);">// Base64: senils'dadymnospateriwehttcennocerdnaselegnasolotylfotdahohwtnegaytirucesllebcapeht</span>
    <span style="color:rgb(30,132,43);">// Reverse: thepacbellsecurityagentwhohadtoflytolosangelesandreconnectthewiretapsonmydad'slines</span>
    <span style="color:rgb(30,132,43);">// Add missing spaces: the pacbell security agent who had to fly to los angeles and reconnect the wiretaps on my dad's lines</span>
    <span style="color:rgb(30,132,43);">// Answer: Darrell Santos</span>

    [14] <span style="color:rgb(192,28,28);">`ud mn cf ub mw re lb is ba of gx ty qc qh il ea ym nx bz ub he cf th is`</span>,
    [15] <span style="color:rgb(192,28,28);">`7\3|2\9|3\5|4/0/8/2|6\7/0/4\4\5/6/6\5/7/8/9|7\8/7|9\5/9\2\3\5\7/8|2/0/8|2/6|6|2|7\7\7\0\4\9|`</span>,
    [16] <span style="color:rgb(192,28,28);">`100 0000 10 1 01 001 00 1000 1 010 11 000 0 0000 11 000 00011 10000 11111 11110 11000 00111 10000 11111 10000 11111`</span>,
    <span style="color:rgb(30,132,43);">// DECODED: This is Morse code but each letter the translation ('1' -> '.', '0' ->'-') is reversed to ('1' -> '-', '0' ->'.')!</span>
    <span style="color:rgb(30,132,43);">// Unmorsed: WHATNUMBERISTHIS8659221010</span>
    <span style="color:rgb(30,132,43);">// Added spaces: WHAT NUMBER IS THIS 8659221010</span>
    <span style="color:rgb(30,132,43);">// Added dashes: WHAT NUMBER IS THIS 865-922-1010</span>
    <span style="color:rgb(30,132,43);">// It seems for the number the pattern must be changed again:</span>
    <span style="color:rgb(30,132,43);">// Q: WHAT NUMBER IS THIS 310-477-6565:</span>
    <span style="color:rgb(30,132,43);">// A: The LA Headquarters of the FBI.</span>

    [17] <span style="color:rgb(192,28,28);">`6365696a647a727573697775716d6d6e736e69627a74736a6f7969706469737967647163656c6f71776c66646d63656d78626c6879746d796f6d71</span>
         <span style="color:rgb(192,28,28);">747765686a6a71656d756c70696b6a627965696a71`</span>,
    [18] <span style="color:rgb(192,28,28);">`hranmoafignwoeoeiettwsoeheneteelaefnbaethscrdniyajspwrl`</span>,
    [19] <span style="color:rgb(192,28,28);">`yo kb pn oc ox rh oq kb oh kp ge gs yt yt hg sa li mt ob sa po po mk pl md`</span>,
    [20] <span style="color:rgb(192,28,28);">`77726e6b7668656a77676b6b276c6d6b6274616672656567776c6a7368697a70726f6d79656c`</span>,
    [21] <span style="color:rgb(192,28,28);">`opoybdpmwoqbcpqcygagpcgxbpusapdluscplchxwoisgyeasdcpopdhadfyaethis`</span>,
    [22] <span style="color:rgb(192,28,28);">`1001 0111 01 00 0 0 101 011 1111 1110 1011 1111 101 0110 1111 1101 110 010 100 0 0100 11 1011 1011 000 10 101 01`</span>,
        <span style="color:rgb(30,132,43);">// this is NOT Morse code :( !</span>

    [23] <span style="color:rgb(192,28,28);">`anhgynnrtfafaqgmbhsuuzkzfbhbfk`</span>,
    [24] <span style="color:rgb(192,28,28);">`nhyitekmnryoogmwefehocttntoauttosumooalgei`</span>,
    [25] <span style="color:rgb(192,28,28);">`11 01000 000 111 010 0 011 0010 000 010 11 10 1101 01 01 1 000 1  1111 01 0 011 1   010 1 1000 000 010  01 00 01 01 </span>
          <span style="color:rgb(192,28,28);">011 00 1101 0010 1 010 1 10 0 001101 110010  001101 110010 001101 100 0000 1 10 101  0 111 0 10 010 0101 0000 11 10 </span>
          <span style="color:rgb(192,28,28);">001 10 1 011 00 100 1 10 0 00 0 00 1 000`</span>,
        <span style="color:rgb(30,132,43);">// this is NOT Morse code :( !</span>

    [26] <span style="color:rgb(192,28,28);">`laeaslarhawpuiolshawzadxijxkjgvvbaxavlowyuuhdsxausmrmbulbegukseq`</span>,
    [27] <span style="color:rgb(192,28,28);">`qnxpnebielnudqqpbibecua3m'llswhmmhrdzucclsfvqmdunepbkreezkarsnngpkgmscdnkr`</span>,
    [28] <span style="color:rgb(192,28,28);">`70776d61766374666f2770636d6167797a786977786f78656a7974696465737073786f65696f64706a6f766b636165686573677069637a617886172`</span>,
    [29] <span style="color:rgb(192,28,28);">`eyiyibemhemijixvpyiocjkxdwwxdazvtkaazrvl`</span>,
    [30] <span style="color:rgb(192,28,28);">`usygbjmqeauidgttlcflcflgqmfqhyhwurqmbxzoqmnpmjhlneqsctmglahp`</span>,
    [31] <span style="color:rgb(192,28,28);">`tpdwxjw'viyegmzbecfvpcqtuwdinpfhzvvfadzbkfoevcnseozxffdlvrdo'jwsjkzllzwapfrvhuaqz`</span>,
    [32] <span style="color:rgb(192,28,28);">`010 1 0001 101 0 111 000 100001 01 101 001 00 111 00 00 1111 000 01 111 1 10 000 0000 1001 000 11 0000 0 111 0 0 </span>
          <span style="color:rgb(192,28,28);">0101 010 110 111 111 0 1111 1 101 111 1101 110 01 00 010 111 000 0100 111 01 100 00`</span>,
        <span style="color:rgb(30,132,43);">// this is NOT Morse code :( !</span>

    [33] <span style="color:rgb(192,28,28);">`eafeihchqqlndcinrarnfhqdvmlqnmcrlphaccqmqefkzhlslnstmqgmma`</span>,
    [34] <span style="color:rgb(192,28,28);">`ifdmnbbnqitnsobmmmtthdkhqbqzpo"nduqz"zhnemccxhyaninaxanf`</span>,
    [35] <span style="color:rgb(192,28,28);">`kgqmicewdnfmastcefkxlkqshgrfsspotxuesqvcohxttpcuvhnxawypuwzdt`</span>,
    [36] <span style="color:rgb(192,28,28);">`0\6\2/7\4/2\4\8\2|8|6|7\0\4\3/2|8/7/3\2/2/5|6/4|8\7\6\6\3\2|3/3\7/4|6/0/3|7/0\6|8|9/4\4/6/5/3|5|0\8\9\7/4|4/4|8\5/3/3|5|8|4/0\5|8/2/`</span>,
    [37] <span style="color:rgb(192,28,28);">`001101 110010 001101 110010 001101 110010 001101 110010 111 00 011 00 10 110 0000 11 00 1001 110 0100 111 10 11 00 1101</span> 
          <span style="color:rgb(192,28,28);">1001 0100 10 100 11 01 101 0010 11 101 0010 11 101 011 111 000 100 010 1001 001 1 101 01 010 1010 01 0 1110 10 0111 010 010`
        <span style="color:rgb(30,132,43);">// this is NOT Morse code :( !</span>



</pre>

			</p>
			
<h2>Chapters 16</h2>		
<p>
Chapter 16 was morse code but with alternating translation patter (1 -> '.', 0 ->'-') OR (1 -> '-', 0 ->'.'):

<pre class="long">

    100 0000 10 1 01 001 00 1000 1 010 11 000 0 0000 11 000 00011 10000 11111 11110 11000 00111 10000 11111 10000 11111
    
    .-- ---- .- . -. --. -- .--- . -.- .. --- - ---- .. --- ---.. .---- ..... ....- ..--- --... .---- ..... .---- .....
    W*AENGMJEKIOT*IO8154271515

    -.. .... -. - .- ..- .. -... - .-. -- ... . .... -- ... ...-- -.... ----- ----. --... ..--- -.... ----- -.... -----
    DHNTAUIBTRMSEHMS3609726060
    
    
    WHATNUMBERISTHIS8659221010

    WHAT NUMBER IS THIS 865-922-1010


</pre>
<p>
This is just a ridiculous encryption pattern...I am not sure I am going to attempt to crack the rest of the code since there is no educational value in pursuing.
</p>

<h2>Chapters 17, 24, 33 and 36</h2>		
<p>
The hardcover featured a code similar to those and it turned out to be Morse code. I tried to convert those but no dice.<br/>
Same thing trying to use <code>CrackKevin.exe</code> on the resulting unmorsed strings.

</p>




<h2>Overall impression</h2>		
<p>
The codes from the hardcoder edition allowed to learn a lot about difference encoding/encryption but it seems those are more about designing crazy translations (i.e: alternating morse code, reverse on top of base64...)...so the educational aspect of the challenges is much less perspectible here. Since there is a price at the end I can understand why it is done this way but I don't think I will keep on working on them if I am not going to lean anything.<br/>
<br/>
<u><b>EDIT (June 20, 2012) :</u></b> After collaborating with a few other cryptanalyst (xenex and Kahootbird) I have to admit there is a real 
educational value in working on those ie: learning more about "column transposition" and Atbash.
</p>




<h2>Interesting approach</h2>		
<p>
I have received an email from kahoot:
<pre class="long">


    Another note of interest,  I made a <a href="solver.zip">program to solve vigenere ciphers</a>
    via a word/name based attack of words/names used in the book. I have an
    electronic copy of Ghost In The Wires as well as a hardback.. I
    copy/pasted a chapter into a text file, ran it through the same Bible word
    sorter as on my site to organize every word/name alphabetically and lower
    case, then put it through a vigenere cipher program I made and tested.
    What this effectively done is allowed me to look at the output of about a
    hundred or so words tried from the corrosponding chapter as the problem
    briefly for a solution. I tried it for problems [7] and [9] from chapters
    8 and 10 you'd labelled as "should try vigenere.exe".. no luck.

    I'm attaching the C source file zipped with a few text files you could try
    should you want to verify what I'm saying or try for any of the ciphers or
    just look at the code.

    Sufficed to say problems [7] and [9] you have labelled as "probably
    vigenere" are probably not vigenere. At least not from text from the same
    chapter..

    I know it's not a solution but I hope that's helpful nonetheless..

    kahootbird
    
    
</pre>
</p>








<!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

