<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Knowledge Stack, books, software engineer."/>
		<meta name="Description" content="The Best Books I ever read: Suggestions for a software engineer."/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>The Best Books I ever read: Suggestions for a software engineer.</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       January 15th, 2013</div>
   <h1>The Best Tech Books I read</h1>
   <p id="paperbox">
	     <script type="text/javascript">
  var disqus_identifier = "book_suggestions_2013";
</script>

<style type="text/css">
.shadowed-book{
  box-shadow: rgb(119, 119, 119) 3px 3px 3px;
  border-color: rgb(180, 180, 180);
  border-style: solid;
  border-width: 1px;
  margin-right: 12px;
}

div.bild {
    text-align:left;
width: 100%;
}

.justified_img {
display: inline-block;
margin: 20px;
}​
</style>
<br/>I have gathered here the few books I consider to be masterpiece about computer stacks. There are two for each levels of the stacks:<br/>
<ul>
    <li>Hardware.</li>
    <li>Operating Systems.</li>
    <li>Programming Language.</li>
    
</ul>
<p>And since the lack of enthousiam is the root of mediocrity I have also added a category "Inspiration" .
<div style="clear:both"/>
</p>
              


<br/>      
<h2>Hardware</h2>
<p id="paperbox">
<img src="code.png"  class="shadowed-book" style="float:left;"/><a href="http://www.amazon.com/Code-Language-Computer-Hardware-Software/dp/0735611319/ref=sr_1_1?ie=UTF8&qid=1358293457&sr=8-1&keywords=code+hidden+language">Code: The Hidden Language of Computer Hardware and Software</a><br/>
    Charles Petzold's masterpiece explains how hardware works to the deep down. Starting from scratch, with countless drawings, information flows from the pages to your brain without effort.
Explaining like if you were 5 years old, it follows perfectly the book quality rule: "Quality is inversely proportional to its size".
<div style="clear:both"/>
<br/>
<p id="paperbox">
<img src="computer_org_design.png" class="shadowed-book" style="float:left;"/><a href="http://www.amazon.com/Computer-Organization-Design-Fourth-Architecture/dp/0123747503/ref=sr_1_1?s=books&ie=UTF8&qid=1358293499&sr=1-1&keywords=computer+organization+and+design">Computer Organization and Design</a><br/>
Excellent description of modern CPU internals and how to reach Software/Hardware synergy. Prefetching, cacheline or Out-Of-Order execution (to name only a few) are clearly explained. If the "Code" book is the sparkle, "Organization and Design" is the explosion.
<div style="clear:both"/>
<br/>
<p id="paperbox">
<br/>
<b><u>Trivia :</u></b> An example of speed improvement due to good hardware knowledge: Doom stored textures 
horizontally in RAM to take full advantage of the cacheline.<br/>
<br/>
<b><u>Trivia :</u></b> An other example of speed improvement due to good hardware knowledge: OpenGL Interleaved 
arrays are faster than separate arrays (thanks to cacheline again).
</p>






<br/>
<h2>Operating Systems</h2>
<p id="paperbox">
Whether it is to perform I/O, display something on the screen or communicate on the network you program will have to leave user-space at some point. What happens in kernel-space is explained here.<br/>
<br/>
<img src="op_systems.png" class="shadowed-book" style="float:left;"/><a href="http://www.amazon.com/Modern-Operating-Systems-3rd-Edition/dp/0136006639/ref=pd_sim_b_1">Modern Operating Systems </a><br/>
Virtual Time, Virtual Memory, Virtual Filesystem, System calls, Sleep/Busy Locks and Process scheduler (to name only a few key concepts) are clearly explained in this great book by Tanenbaum.
<div style="clear:both"/>
<br/>
<p id="paperbox">
<img src="linux_prog_intef.png" class="shadowed-book" style="float:left;"/><a href="http://www.amazon.com/Linux-Programming-Interface-System-Handbook/dp/1593272200/ref=sr_1_1?s=books&ie=UTF8&qid=1358291843&sr=1-1&keywords=the+linux+programming+interface">The Linux Programming Interface</a><br/>
Have you ever wondered how <code>malloc</code> is implemented by the C Library ? This book offers a top-down approach to understand what the Operating System can do for your application/library. A departure from the bottom-up description of "Operating Systems: Design and Implementation" that may be easier for some readers. A must have regardless.
<div style="clear:both"/>

<p id="paperbox">
<br/>
<b><u>Trivia :</u></b> An example of speed improvement due to good knowledge of page-fault: <a href="https://bugzilla.mozilla.org/show_bug.cgi?id=627591">Firefox boots two seconds faster thanks to DLL preloading</a>.
<p id="paperbox">
</p>






<br/>
<h2>Programming Language</h2>
<p id="paperbox">
Most of my code is C and I discussed the best books for the C programming Language <a href="../c/index.php">in a previous article</a>. 
I hope to be able to recommend the two best C++ books soon.<br/>
<div class="bild">
<img src="c.png" class="shadowed-book justified_img"/>
<img src="c_reference.png" class="shadowed-book justified_img"/>
<img src="expert.png" class="shadowed-book justified_img"/>
</div>
</p>








<br/>
<h2>Inspiration</h2>
<p id="paperbox">
Three components lead to success:
<ul><li>Passion.</li><li>Skills</li><li>Luck.</li></ul>
<p>Most of us have Passion and Skills. It is very inspiring to 
see what happen when Luck is also part of the equation:<br/>
<br/>

<img src="pixar_touch.png" class="shadowed-book" style="float:left;"/>
  <a href="http://www.amazon.com/Pixar-Touch-Vintage-David-Price/dp/0307278298/ref=sr_1_2?ie=UTF8&qid=1358291346&sr=8-2">The Pixar Touch</a>:<br/> 
They should have gone broke and failed several times...but instead flew to Infinity and Beyond ! Many delicious technical trivias 
(early days of Framebuffers, texture mapping) and great anecdotes about human rivalties/survival: Passion, Skills and a LOT of Luck.  
Also: Crazy schedules.
<div style="clear:both"/>
<br/>
<p id="paperbox">
<img src="masters_doom.png" class="shadowed-book" style="float:left;"/>
  <a href="http://www.amazon.com/Masters-Doom-Created-Transformed-Culture/dp/0812972155/ref=sr_1_1?s=books&ie=UTF8&qid=1358291377&sr=1-1">Masters of Doom</a>:<br/> 
  Passion, Binary Space Partition and a little bit of Luck ! Also: Crazy schedules.
<div style="clear:both"/>

</p>   



<br/>
<h2>Adapting the stack</h2>
<p id="paperbox">
The books mentioned should satisfy most stacks but it is paramount to adapt it to your specific needs. Since I do a fair amount of network programming those times, I would certainly include
the masterpiece: "<a href="http://www.amazon.com/TCP-Guide-Comprehensive-Illustrated-Protocols/dp/159327047X/ref=sr_1_6?s=books&ie=UTF8&qid=1358377001&sr=1-6">The TCP/IP Guide</a>".<br/>
<br/>My past career as a 3D-engine developer involved a lot of Computer Graphics, I would have mentioned the following:<br/>
<br/>
<img src="realtime_rendering.png" class="shadowed-book" style="float:left;"/><a href="http://www.amazon.com/Real-Time-Rendering-Third-Tomas-Akenine-Moller/dp/1568814240/ref=sr_1_1?s=books&ie=UTF8&qid=1358291525&sr=1-1&keywords=real+time+rendering">Real-Time Rendering</a><br/>
An extensive reference that describes the recent realtime rendering techniques. An essential map that will help you to know where you want to dig deeper. A CG Classic.
<div style="clear:both"/>
<br/>
<p id="paperbox">
<img src="abrash_black_book.png" class="shadowed-book" style="float:left;"/><a href="http://www.amazon.com/Michael-Abrashs-Graphics-Programming-Special/dp/1576101746/ref=sr_1_1?s=books&ie=UTF8&qid=1358291481&sr=1-1&keywords=michael+abrash">Michael Abrash's Graphics Programming Black Book</a><br/>
A very old book that still contains very good lessons (especially planes mathematics) but really an inspiring celebration of Michael Abrash's motto: "Do what you Love, work with humility and Good Things will come eventually".
<div style="clear:both"/>
  </p>        


<br/>
<br/>
<h2>All together</h2>
<p id="paperbox">
<div style="text-align: center; width:100%;">
<img src="DSC_1081.JPG" class="shadowed"/>
</div>
<br/>
I was tempted to add "
<a href="http://www.amazon.com/TCP-Guide-Comprehensive-Illustrated-Protocols/dp/159327047X/ref=sr_1_6?s=books&ie=UTF8&qid=1358377001&sr=1-6">
  The TCP/IP Guide</a>" and "<a href="http://www.amazon.ca/Hacking-The-Art-Exploitation-Edition/dp/1593271441/ref=sr_1_1?ie=UTF8&qid=1358436506&sr=8-1">Hacking : The Art of Exploitation</a>".
</p>   
<!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

