<script type="text/javascript">
  var disqus_identifier = "Game_Engine_Black_Book_PostMortem";
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Game Engine Internals, Game Engine Black Book, Wolfenstein 3D internals"/>
		<meta name="Description" content="Game Engine Internals, Game Engine Black Book, Wolfenstein 3D internals"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
	
 	
		
		<title>Game Engine Black Book Release announcement</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       September 7th, 2017</div>
   <h1>Game Engine Black Book Postmortem</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="gebb.png" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         
        <!-- Add fancyBox -->
  <link rel="stylesheet" href="../fancybox/source/jquery.fancybox.css?v=2.1.5" type="text/css" media="screen" />
  <script type="text/javascript" src="../fancybox/source/jquery.fancybox.pack.js?v=2.1.5"></script>
 <script type="text/javascript">
$(".preview")
    .attr('rel', 'gallery')
    .fancybox({
        padding : 0,
        nextEasing: 'none',
        prevEasing: 'none',
        nextEffect: 'elastic',
        prevEffect: 'elastic',
    });

 </script>


    <style>

 .comment{color: rgb(66,135,65);}
 .keyword{color: rgb(182,16,162);}
 .literal{color: rgb(218,37,36);}

 .include{color: rgb(117,85,119);}

 .numbers{color: rgb(96,0,205);}

 .blackPre{
     background-color :black;
     color: white;
 }

 .screenshot{
    box-shadow: rgb(119, 119, 119) 3px 3px 3px;
    display: block;
    margin-left: auto;
    margin-right: auto;
    margin-top: 10px;
    margin-bottom: 15px;
 }

h4 {
 
  border-bottom: 0px;
  font-size: 15px;
}

  pre{
    font: 12px courrier,monospace;
  }
 </style>
 <p>
  I am pleased to announce that the Game Engine Black Book about Wolfenstein 3D has shipped. It is 316 pages, full color
  and made of three parts describing the hardware
  of 1991, id Software tools, and the game engine internals. You can read a
   <a href="https://books.google.com/books/about/Game_Engine_Black_Book.html?id=Lq4yDwAAQBAJ">preview</a> on Google Books and buy it here: <br/>
  <ul>
    <li><a href="https://www.amazon.com/Game-Engine-Black-Book-Wolfenstein/dp/1539692876">Amazon.com</a> (<a href="https://www.amazon.fr/Game-Engine-Black-Book-Wolfenstein/dp/1539692876">.fr</a>, <a href="https://www.amazon.de/Game-Engine-Black-Book-Wolfenstein/dp/1539692876">.de</a>, <a href="https://www.amazon.co.uk/Game-Engine-Black-Book-Wolfenstein/dp/1539692876">.co.uk</a>, <a href="https://www.amazon.ca/Game-Engine-Black-Book-Wolfenstein/dp/1539692876">.ca</a>,...).
      <li><a href="https://play.google.com/store/books/details/Fabien_Sanglard_Game_Engine_Black_Book?id=Lq4yDwAAQBAJ">Google Play Books</a> for web browsers, Android devices, and iOS devices.
  </ul>
  <p>
    It took me three years to complete this project. It had its fair share of heavy winds and bumpy roads. I thought it could benefit some writers in the making to give a 
   postmortem and share what I learned in the process.
    <div style="clear:both;"></div>









    <h1>First attempt</h1>
    <p id="paperbox">
      I started the project in July 2014 shortly after accepting a new full-time position in California. I picked Google Doc to do the writing and <a href="https://www.gliffy.com/">Gliffy</a> for the drawing. I worked on it every evening and by August I thought
      I would have a 140 pages booklet within an other month. I <a href="../Game_Engine_Black_Book/index.php">updated the status</a> on my website as "almost done". I uploaded the PDF on <a href="https://www.createspace.com">createspace.com</a>, ordered a proof print and the result was horrible. The screenshots had lost all their pixels and my drawings were blurry. On the left is what I saw on my screen and on the right is what I saw once printed. Notice on the right how bilinear filtering blurred the pixels.<br/>
      <br/>
    <br/>
      <a class="preview" href="assets_difference/lamp_no_bilinear.png"><img src="assets_difference/lamp_no_bilinear.png" alt=""/></a> &nbsp;&nbsp;
      <a class="preview" href="assets_difference/lamp_bilinear.png"><img src="assets_difference/lamp_bilinear.png" alt=""/></a> 
      <br/> 
      <br/>
      I knew about the 300 dpi rule and I confidently ignored it, assuming printer would use "nearest neighbor" magnification. It turns out some printer use nearest neighbor and some use bilinear filtering. <a href="https://www.createspace.com">createspace.com</a> did not do what I was hoping for. The solution was to upscale assets and use vectorial format for drawings instead of rasterized format. I started converting the assets and the GUI did not like it. It could takes seconds to scroll to the next page. To use a web-based tool to edit a book featuring hundreds of screenshots in 2250x1400 like the <i>Game Engine Black Book</i> was a BAD idea. I ran into other limitations like no support for vectorial drawings and no possibility to pick the page color. I was clearly not using the right tool for the job.<br/>


  <h1>Switching tools</h1>
    <p id="paperbox">
       I googled around to find out what technical authors used. Something that would be more adapted to my niche usecase. I ended up dropping WYSIWYG and go minimalistic with Sublime Text editor, pdfLatex to compile tex into PDF, Inkscape for vectorial drawings and GitHub for source control. With this setup I was able to create new command in LateX to use lightweight 75 DPI assets while writing and swap the command definition to use 300 DPI assets when compiling the book for printing. From typing to compiling the PDF, everything was fast.<br/>
      <br/>
      Everything was fast as long as you knew what you were doing. I was used to jump into new programming languages and I assumed LateX would be no different. It turned out learning LaTeX on the go made the project advanced at the speed of an hangover sloth. It sucked my energy because I literally had to Google everything I was trying to do. From bolding font to creating a simple array, things that would have taken me seconds with Google Docs or HTML now took hours. I spent evenings struggling and <a href="https://twitter.com/fabynou/status/517208724939632640">decyphering compiler errors</a>. I would run into weird issues when using poorly documented packages. For example package "listings" renders code listing on Safari with weird white lines artifacts. On Chrome it looks ok.<br/>
      <br/>
      <a class="preview" href="assets_difference/code_without_artifacts.png"><img src="assets_difference/code_without_artifacts.png" alt=""/></a>&nbsp;&nbsp;
      <a class="preview" href="assets_difference/code_with_artifacts.png"><img src="assets_difference/code_with_artifacts.png" alt=""/></a><br/>       
      <br/>
      All this friction resulted in evenings pursuing what felt like side quests. I ended up losing all motivation. By October 2014 I had burned out. I stopped submitting commit to github and the <i>Game Engine Black Book</i> was dead.<br/>

    
<br/>


     
      <br/>
      <img src="timeline.png"/><br/>
      <center>
      <div style="font-size: 80%">GitHub commits over time.</div>
    </center>
      <br/> 
    </p>

<h1>Hibernation</h1>
    <p id="paperbox">
      The project stayed in limbo for two years after that. As you can see on the graph above, I picked it up again around <a href="https://twitter.com/fabynou/status/683013864355528704">Christmas 2015</a> but I got frustrated again pretty fast and as soon as I returned to work I stopped working on the Black Book. 
    </p>

<h1>Blessing in disguise</h1>
    <p id="paperbox">
      In October 2016 I injured a shoulder while training at the climbing gym. It was so bad I could not move my arm anymore. I started doing PT to recover and I found myself with a lot of time
      at home on my non climbing hands. I dusted off my github project "gebbwolf3d". I attempted a third time to get going and reached the same dead end.<br/>
      <br/>
      Being stubborn, I tried a different approach. I recognized that what destroyed my motivation was the slow pace of progress. Going to bed after hours of struggle was disheartening. I came up with a plan. I monitored myself and if I started to feel frustrated with a drawing or a graph or a table, I would simply draw it on paper, take a picture and import it as a raster. It looked horrible but that was a placeholder which allowed me to move forward no matter how limited my LaTeX skills were. This adjustment turned out to be all I needed. At Google they say that "speed is a feature". Speed is paramount in a 3D engine. It turned out to be important for me too.<br/>
      <br/>
      As I witnessed my shoulder sustain more and more weight at PT, more and more pages were added to the book. And also drawings, plenty plenty of drawings. By the end of January 2017 my shoulder had fully recovered and it was clear I was also going to be able to finish the book. Because createspace took one week to print and ship a proof, I used that time as resting spots. The seven proof prints are clearly visible on the graph as well as the final push. 
    </p>

<h1>Writing is 90%, proofreading the other 90%</h1>
    <p id="paperbox">
      Writing and drawing was difficult but proof reading was excruciating. To read the same thing over and over again lead to losing perspective and fatigue. I understand now why so many bad movies are released by Hollywood. When you work on something for too long you cannot tell anymore if it is good or if it is bad. I was lucky to have amazing people around me volunteering to proof read. I would have never published the book without them.<br/>
      <br/>
</p>
<h1>Take Away</h1>
    <p id="paperbox">
It was great to make a dream come true and learn so much about technology from the past. To understand how programmers from the 90s strived like us. The spirit it takes today to reach new frontier is the same it took 20 years ago. It helped me to look at my work with a positive attitude and more confidence. And recognize that we do what we do "not because it is easy but because it is hard".<br/>
<br/> 

If I were to take away only one thing from this beautiful adventure it will be the support I received. To read detailed answers to my obscure questions about EMS from the original team and passionate enthusiasts. To see people volunteer their collection of 386 to run benchmarks for me. To witness someone carefully print a proof on an A4 and take the time to read it. To see a co-worker who often spend 9 hours a day at work take the time on his weekend to fix my horrible typos. To see my brother on the other side of the planet figure out VGA masks. These things moved me more than anything. Their kindness and generosity were humbling.
      </p>
    <h1>Recommended Readings</h1>
    <p>
      <a href="https://play.google.com/store/books/details/Fabien_Sanglard_Game_Engine_Black_Book?id=Lq4yDwAAQBAJ">
          <img width="25%" src="gebb_ebook.png"/></a>
      </a>    
      &nbsp;&nbsp;
      <a href="https://www.amazon.com/Game-Engine-Black-Book-Wolfenstein/dp/1539692876">
        <img width="25%"  src="gebb_paper.png"/>
      </a>
    </p>
    
<!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

