<script type="text/javascript">
  var disqus_identifier = "globeAndMailArticle";
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="GlobeAndMail article, Fluid, iPhone"/>
		<meta name="Description" content="GlobeAndMail article about Fluid"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>GlobeAndMail article featuring Fluid and Fabien Sanglard</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       March, 26th 2010</div>
   <h1>I would never have thought...</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="mainImage.jpg" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         			
			March 26th, 2010 was a great day. Not only did I found <a href="http://memsetsoftware.com/">Memset Software, Inc</a>, it was also the day The Globe And Mail published a <a href="http://www.theglobeandmail.com/report-on-business/rob-magazine/the-age-of-the-app/article1510836/">nice article</a> about iPhone success stories. I was very flattered to see my story both open and close the article.<br/><br/>
I have to say I am amazed by the turn of events. I originally wrote this piece of code so I would have something to show when going for iPhone interviews. I picked a fluid effect because it's fairly difficult to implement and also because  I wanted to be able to touch the water with my fingers instead of a mouse cursor since I first hacked one in a Java applet (via a well know demoscene trick).<br/>
<br/>
The tremendous success was as total surprise. In less than a week the application was the AppStore Worldwide #1, reaching 1 million downloads. In the following months I received many many emails, some people were requesting features but most just congratulated me for an application they loved to spend time with. People were using it to relax, to entertain their kids, to put photos of their girlfriends or wives in the background, or to pull pranks on their friends. On top of this, several business opportunities and job offers came up from all around the world.
<div style="clear:both;"></div>


<h3>The article from the Globe & Mail</h3>
<p id="paperbox">



<a href="../fd_proxy/globeAndMailArticle/page1.jpg"><img style="display:inline; margin-top: 15px; margin-right: 45px; box-shadow: rgb(119, 119, 119) 3px 3px 3px;" src="../fd_proxy/globeAndMailArticle/page1Prev.jpg"/></a>
<a href="../fd_proxy/globeAndMailArticle/page2.jpg"><img style="display:inline; margin-top: 15px; margin-right: 45px; box-shadow: rgb(119, 119, 119) 3px 3px 3px;" src="../fd_proxy/globeAndMailArticle/page2Prev.jpg"/></a>
<a href="../fd_proxy/globeAndMailArticle/page3.jpg"><img style="display:inline; margin-top: 15px; margin-right: 45px; box-shadow: rgb(119, 119, 119) 3px 3px 3px;" src="../fd_proxy/globeAndMailArticle/page3Prev.jpg"/></a>
<br/>
<a href="../fd_proxy/globeAndMailArticle/page4.jpg"><img style="display:inline; margin-top: 15px; margin-right: 45px; box-shadow: rgb(119, 119, 119) 3px 3px 3px;" src="../fd_proxy/globeAndMailArticle/page4Prev.jpg"/></a>
<a href="../fd_proxy/globeAndMailArticle/page5.jpg"><img style="display:inline; margin-top: 15px; margin-right: 45px; box-shadow: rgb(119, 119, 119) 3px 3px 3px;" src="../fd_proxy/globeAndMailArticle/page5Prev.jpg"/></a>
<a href="../fd_proxy/globeAndMailArticle/page6.jpg"><img style="display:inline; margin-top: 15px; margin-right: 45px; box-shadow: rgb(119, 119, 119) 3px 3px 3px;" src="../fd_proxy/globeAndMailArticle/page6Prev.jpg"/></a>


<br/>
<br/>
</p>
<h3>Source code
			</h3>
			<p id="paperbox">
Numerous emails I receive ask me how it's done and to "please" send the source code. While it's not rocket science (and quite frankly if I was able to do it: anyone can do it), I will probably release the source code near the end of the year.
</p>
			
<br/>
<h3>What now ?
			</h3>
			<p id="paperbox">
This incredible adventure only confirms the greatest advice I have ever read:<br/>
<br/>
<i>&#8220;I think there’s a worthwhile lesson to be learned from all this, a lesson that I’ve seen hold true for many other people, as well. If you do what you love, and do it as well as you can, good things will eventually come of it. Not necessarily quickly or easily, but if you stick with it, they will come.&#8221;</i>
<br/><br/>
<i> -Michael Abrash: Graphic Programming Black Book : Chapter 60 about Compiling BSP Trees</i>
<br/>
<br/>
Amen.<br/>
<br/>
Happy hacking guys ;) !
</p>

<!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

