<script type="text/javascript">
  var disqus_identifier = "Doom3_Documentation";
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Doom3 BFG  Documentation, id tech4, id tech 5"/>
		<meta name="Description" content="Doom3 BFG Documentation"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>Doom3 BFG Documentation</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       August 31st, 2013</div>
   <h1>Doom3 BFG Documentation</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="doom_documentation.png" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         
    
    <style> 
table.credits{
    
    background: #fff;
   font: 12px 'DejaVu Sans';
    box-shadow: rgb(119, 119, 119) 3px 3px 3px;
    margin: 0px 0px 0px 15px;
    
}
  table.credits { width:97%; a:link:color:rgb(0, 136, 204);}
table.credits thead { background:transparent; }
  
  table.credits th { white-space:nowrap; }
  table.credits thead th { border-left:1px solid #ccc;  border-top:1px solid #ccc; padding:9px 9px 3px; color:#999; }
  table.credits tbody th,
  table.credits tbody td { border-top:1px solid #ccc; padding:6px 9px; }
  table.credits tbody th { padding:7px 0 7px 0; text-align:center; color:#999; }
  table.credits tbody th b { color:#333; font-weight:normal; }
  table.credits tbody td { border-left:1px solid #ccc; }
  
  table.credits tbody .session { background:#d4e6fa url(session_bgblue.png) repeat-x 0 0; }
  table.credits tbody .session.alt { background:#e9ecf0 url(session_bggray.png) repeat-x 0 0; }
  table.credits tbody .session h2 { font-size:1em; margin-bottom:0; color:rgb(0, 136, 204); }
  table.credits tbody .session .hud-content { display:none; }

  td.right
  {
    border-right:1px solid #ccc;
  }
  
  
  
  blockquote.style1 
  {
      
      padding: 8px;
      
      width: 80%;
      
      background-color: #eeeeee;
      border: 1px solid #dddddd;
      
      
      margin: 5px;
      background-image: url(../quake2/images/openquote1.gif);
      background-position: top left;
      background-repeat: no-repeat;
      text-indent: 23px;
    
    }
    
    blockquote.style1 span 
    {
      display: block;
      font-style:italic;
      background-image: url(../quake2/images/closequote1.gif);
      background-repeat: no-repeat;
      background-position: bottom right;
      text-align: justify;
    }
    
    
    
    
  
  </style> 
Since the two code reviews about <a href="../doom3/index.php">Doom3</a> and <A href="doom3_bfg/index.php">Doom3-BFG</a> are a starting point for many game programmers,
id Software developer Jan Paul Van Waveren (a.k.a Mr Elusive) one of the men behind Doom 3 
sent me a list of all the documents/publications related to idtech4 engine.<br/>
<br/>
They are very good, especially the <a href="DOOM-3-BFG-Technical-Note.pdf">DOOM 3 BFG Technical Note</a> which elaborate on "Compute Vs Memory". Here they are:<br/>
<br/>
<u><b>Trivia :</b></u> "Mr Elusive" nickname comes from back in the days when he was one of the first to use a mouse to play Doom I.
<div style="clear:both;"/>
</p>



<br/>
<h2>Doom III documentation and publications</h2>
<p>

<a href="CarmackOnShadowVolumes.txt">On Shadow Volumes</a><br/>
John Carmack<br/>
id Software, May 2000<br/>
<br/>
<a href="0301002.pdf">Practical and Robust Stenciled Shadow Volumes for Hardware-Accelerated Rendering</a><br/>
Cass Everitt, Mark J. Kilgard<br/>
NVIDIA developer site, August 2002<br/>
<br/>
<a href="37725-293747_293747.pdf">Slerping Clock Cycles</a><br/>
J.M.P. van Waveren<br/>
Intel Software Network, June 2006<br/>
<br/>
<a href="37726-293748.pdf">From Quaternion to Matrix and Back</a><br/>
J.M.P. van Waveren<br/>
Intel Software Network, June 2006<br/>
<br/>
<a href="37727-293749.pdf">The Skeleton Assembly Line</a><br/>
J.M.P. van Waveren<br/>
Intel Software Network, June 2006<br/>
<br/>
<a href="37728-293750.pdf">Fast Skinning</a><br/>
J.M.P. van Waveren<br/>
Intel Software Network, June 2006<br/>
<br/>
<a href="37729-293751.pdf">Deriving Triangle Plane Equations</a><br/>
J.M.P. van Waveren<br/>
Intel Software Network, June 2006<br/>
<br/>
<a href="37730-293752.pdf">Shadow Volume Construction</a><br/>
J.M.P. van Waveren<br/>
Intel Software Network, June 2006<br/>
<br/>
<a href="The-DOOM-III-Network-Architecture.pdf">The DOOM III Network Architecture</a><br/>
J.M.P. van Waveren<br/>
id Software, March 2006<br/>
<br/>

<a href="Automated-Static-and-Dynamic-Obstacle-Avoidance-in-Arbitrary-3D-Polygonal-Worlds.pdf">Automated Static and Dynamic Obstacle Avoidance in Arbitrary 3D Polygonal Worlds</a><br/>
J.M.P. van Waveren, L.J.M. Rothkrantz<br/>
Editor: Xing-Jian Jing<br/>
Motion Planning, ISBN 978-953-7619-01-5, June 2008<br/>
<br/>
<a href="http://www.amazon.ca/Math-Primer-Graphics-Development-Edition/dp/1568817231/ref=dp_ob_title_bk">3D Math Primer for Graphics and Game Development, 2nd Edition</a><br/>
Fletcher Dunn & Ian Parberry<br/>
A K Peters/CRC Press, Nov 2011<br/>
Pages 418-422: Volumetric lights<br/>
<br/>
<a href="DOOM-3-BFG-Technical-Note.pdf">The DOOM III BFG Technical Notes</a><br/>
J.M.P. van Waveren<br/>
id Software, October 2013<br/>
<br/>
</p>



    
  <!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

