OBJS = commands.obj getline.obj getwords.obj main.obj object.obj \
	parser.obj rooms.obj

game.exe: $(OBJS)
	link $(OBJS),$@;

commands.obj: commands.c game.h defs.h
getline.obj: getline.c utils.h
getwords.obj: getwords.c utils.h
main.obj: main.c game.h utils.h
object.obj: object.c game.h defs.h
parser.obj: parser.c defs.h game.h utils.h
rooms.obj: rooms.c game.h defs.h
