<script type="text/javascript">
  var disqus_identifier = "ssd" ;
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Solid State Drive, MacPro"/>
		<meta name="Description" content="How a Solid State Drive increased the performances of a MacPro by a factor 2."/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>"SSD reboot your thinking"...</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="https://fabiensanglard.net/" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="http://fabiensanglard.net/" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="http://fabiensanglard.net/about/">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="http://fabiensanglard.net/faq/">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="http://fabiensanglard.net/rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="http://fabiensanglard.net/rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="http://fabiensanglard.net/rss.xml" />
<div id="date">
       March 17, 2012</div>
   <h1>"SSD reboot your thinking"...</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="ssd.png" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         


I started to look into Solid State Drives while studying "id Tech5": The 3D engine powering Rage by id Software. One of 
the numerous innovations is called MegaTexture (also known as "Sparse Virtual Texturing"). It is a technology that allows artists to use gigabytes of texture without worrying about
running out of RAM at runtime. The engine detects what is visible and then streams the necessary texture from 
the storage drive up to the Video RAM where it is used for rendition.<br/>
<br/>
The graphic result looks <a target="_blank" href="http://www.youtube.com/watch?v=8ui6j35YDbU">pretty good</a> running on 
a Hard Disk Drive 
but it <a target="_blank" href="http://www.youtube.com/watch?v=yHZXCvjZ-_g">flies when used with a Solid State Drive</a>.<br/>
<br/>
Director of R&D John Carmack <a target="_blank" href="http://www.intel.com/content/www/us/en/solid-state-drives/ssd-520-gaming-id-software-video.html">
said a few words</a> about how SSD performances "reboot" the old dichotomy: "RAM" Vs "Storage Drive".


<br/>
<br/>
After much reading about TRIM support, SandForce and performances degradations I opted for an OCZ Vertex 3 and an Intel serie 520 that
 I promptly installed in my MacPro. Here are my impressions after one week.<br/>

</p>

<br/><br/>
<h2>WOW !!!</h2>
<p id="paperbox">
Performances are <b><u>PHENOMENAL</u></b>. 
If you are a professional developer and you are not using Solid State Drive you are losing time on a daily basis. 
Swapping from HDD to SSD is the biggest performance boost I have experimented as a programmer and I cannot encourage you more to go for it as soon as possible.<br/>
<br/>
<ul>
<li>XCode loads instantly.</li>
<li>Eclipse takes 2 seconds to startup.</li>
<li>Compiling Doom3 from scratch with Visual Studio 2010 take 3 minutes (Just don't forget the 
<a href="http://msdn.microsoft.com/en-us/library/bb385193.aspx">/MP</a> flag).</li>
<li>Compiling Doom3 from scratch with XCode 4 takes 2 minutes.</li> 
<li>Even the notorious mammoth Adobe Photoshop loads in 1 seconds.</li>
</ul>
<p>
<br/>
Not only programs go faster, the boot time is reduced considerably. The MacPro I am using can reboot under Windows 7 within 20 seconds.<br/>
<br/>

                                                                      
			</p>
      <br/><br/>
      <h2>How to mount a 2.5" SSD on a 3.5" MacPro.</h2>
      <p id="paperbox">
      It is not that easy to mount a 2.5" SSD drive since the racks of the MacPro expect a 3.5" HDD with vertical screws and leftmost SATA location.<br/>
      <br/>
      
      Some people just seem 
      to <a target="_blank"  href="http://www.everymac.com/systems/apple/mac_pro/faq/mac-pro-how-to-replace-hard-drive-install-ssd.html">ignore the problem</a>:<br/>
      <br/>
      <div style="text-align:center;">
      <img style="padding:5px; background-color: white; box-shadow: 3px 3px 7px #777;" width="800"  src="../lazy_load/grey.gif" data-original="/fd_proxy/ssd/ssd_ignore_problem.jpeg"/>
      </div>
      <br/>
      <br/>
      What you see here is an SSD mounted horizontally with all its weight resting on its SATA connector. 
      If you know what "moment of force"  is you know it cannot be good on the long run. I hope they did not have to carry the MacPro too much.<br/>
      <br/>
      Some try to be creative with <a target="_blank" href="http://forums.macrumors.com/showthread.php?t=1157499">more or less esthetic success</a>:<br/>
      <br/>
      <u>The old duck-tape trick:</u><br/>
      <br/>
      <div style="text-align:center;">
      	<img style="padding:5px; background-color: white; box-shadow: 3px 3px 7px #777;" width="800"  src="../lazy_load/grey.gif" data-original="/fd_proxy/ssd/poor_craft1.png"/>
      </div>
      <br/>
      <br/>
      <br/>
      <u>The more elegant pierced CD shaped adapter:</u><br/>
      <br/>
      <div style="text-align:center;">
      	<img style="padding:5px; background-color: white; box-shadow: 3px 3px 7px #777;" width="800"  src="../lazy_load/grey.gif" data-original="/fd_proxy/ssd/nice_craft.jpeg"/><br/>
      </div>
      <br/>
      </p>
       <br/><br/>
      <h2>2.5" SSD Adapter for MacPro.</h2>
      <p id="paperbox">
      
      Needless to say I felt fortunate to find an adapter that would meet the MacPro vertical screwing/leftmost connector requirements: AdaptaDrive. <Br/><Br/>
         
       <div style="text-align:center;">
	      <br/>
	      <img style="padding:5px; background-color: white; border-color:#444; box-shadow: 3px 3px 7px #777;" width="700"  src="../lazy_load/grey.gif" data-original="/fd_proxy/ssd/step1.jpg"/><br/>
	      <br/>
	      <img style="padding:5px; background-color: white; box-shadow: 3px 3px 7px #777;" width="700"  src="../lazy_load/grey.gif" data-original="/fd_proxy/ssd/step2.jpg"/><br/>
	      <br/>
	      <img style="padding:5px; background-color: white; box-shadow: 3px 3px 7px #777;" width="700"  src="../lazy_load/grey.gif" data-original="/fd_proxy/ssd/step3.jpg"/><br/>
	      <br/>
	      <img style="padding:5px; background-color: white; box-shadow: 3px 3px 7px #777;" width="700"  src="../lazy_load/grey.gif" data-original="/fd_proxy/ssd/step4.jpg"/><br/>
	      <br/>
	      <img style="padding:5px; background-color: white; box-shadow: 3px 3px 7px #777;" width="700"  src="../lazy_load/grey.gif" data-original="/fd_proxy/ssd/step5.jpg"/><br/>
	      <br/>
	      <img style="padding:5px; background-color: white; box-shadow: 3px 3px 7px #777;" width="700"  src="../lazy_load/grey.gif" data-original="/fd_proxy/ssd/step6.jpg"/><br/>
	      </p>
       </div>                                                               
                                                            





                                                                      
<!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

