<script type="text/javascript">
  var disqus_identifier = "doom3" ;
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Doom3 Source Code Review, id tech4"/>
		<meta name="Description" content="Doom3 Source Code Review"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
	
 	
		
		<title>Doom3 Source Code Review: Profiling</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       June 8, 2012</div>
   <h1>Doom3 Source Code Review: Profiling (Part 4 of 6) <a href="scripting_vm.php">>></a></h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="icons/doom3_icon_desaturated.png" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         
		
XCode comes with a great tool for profiling: <a href="https://developer.apple.com/library/mac/#documentation/developertools/conceptual/InstrumentsUserGuide/Introduction/Introduction.html">Instruments</a>. I used it in sampling mode during a playing session (removing the game loading and level GPU pre-caching altogether):<br/>
<br/>
<div style="clear:both;"></div>

<h2>Overview</h2>
<p>
<img class="shadowed" src="../lazy_load/grey.gif" data-original="/fd_proxy/doom3/profiling_1.png" style="float:right; width:559px; height: 224px; margin: 0 0px 0 20px;" /><br/>
The high level loop shows the three threads running in the process:
<ul>
<li>Main thread where gamelogic and rendition occur.</li>
<li>Auxiliary thread were inputs are collected and sound effects are mixed.</li>
<li>Music thread (consuming 8% of resources), created by CoreAudio and calling <code>idAudioHardwareOSX</code> at regular intervals (note: sound effects are done with OpenAL but do not run in their own thread).</li>
</ul>
<div style="clear:both;margin-bottom:10px;">&nbsp;</div>  


<h2>Main Thread</h2>
<p>
<img class="shadowed" src="../lazy_load/grey.gif" data-original="/fd_proxy/doom3/profiling_2.1.png" style="float:left; width:415px; height: 194px; margin: 0 40px 0 15px;" />
The Doom 3 MainThead runs...<code>QuakeMain</code>! Amusingly the team that ported Quake 3 to Mac OS X must have reused some old code. Inside the time repartition is as follow:
<ul>
<li>65% dedicated to graphic rendition (<code>UpdateScreen</code>).</li>
<li>25% dedicated to gamelogic: This is surprisingly high for an id Software game.</li>
</ul>
<br/>
<br/>
<div style="clear:both;margin-bottom:10px;">&nbsp;</div> 


<h2>Game Logic</h2>
<p>
<img class="shadowed" src="../lazy_load/grey.gif" data-original="/fd_proxy/doom3/profiling_3.png" style="float:right; width:408px; height: 304px; margin: 0 0px 0 20px;" />

<p>
<u>The gamelogic occurs in gamex86.dll space (or game.dylib on Mac OS X):</u><br/>
<br/>
The game logic account for 25% of the Main Thread time which is unusually high. Two reasons:
<ul>
<li>I.A: The virtual machine is run and allows entities to think. All of the bytecode is interpreted and the scripting language seems to have been overused.</li>
<li>The Physic engine is more complex (LCP solvers) and hence more demanding than previous games. It is run on each object and include ragdoll and interactions solving.</li>
</ul>
<br/>
<br/>
<div style="clear:both;margin-bottom:10px;">&nbsp;</div> 
</p>


<h2>Renderer</h2>
<p>
<img class="shadowed" src="../lazy_load/grey.gif" data-original="/fd_proxy/doom3/profiling_4.png" style="float:right; width:412px; height: 95px; margin: 20px 0px 0 20px;" />
As previously described the renderer is made of two parts:
<ul>
<li>Frontend (<code>idSessionLocal::Draw</code>) accounting for 43.9% of the rendition process. Note that <code>Draw</code> is a pretty poor name since the frontend does not perform a single draw call to OpenGL !
</li>
<li>Backend (<code>idRenderSessionLocale:EndFrame</code>) accounting for 55.9% of the rendition process.
</li>
</ul>
<br/>
<p>
The load distribution is pretty much even and it is not that surprising since:
<ul>
  <li>The frontend performs a lot of calculation with regard to Visual Surface Determination.</li>
  <li>The frontend also performs model animation and shadow silhouette finding.</li>
  <li>The frontend upload vertices to the GPU.</li>
<li>The backend spends a lot of time setting up parameters for the shaders and communicating with the GPU (i.e: submitting triangles indices or per vertex normal matrix for bumpmapping in <code>glDrawElements</code>).</li>
</ul> 
<div style="clear:both;margin-bottom:10px;">&nbsp;</div> 


<h2>Renderer: Frontend</h2>
<p>
<img class="shadowed" src="../lazy_load/grey.gif" data-original="/fd_proxy/doom3/profiling_5.png" style="float:right; width:455px; height: 241px; margin: 0 0px 0 20px;" />
<u>Renderer FontEnd:</u>
<br/><br/>
No surprise here, most of the time (91%) is spent uploading data to the GPU in VBOs (<code>R_AddModelSurfaces</code>). A little bit of time (4%) is visible when going through areas, trying to find all interactions (<code>R_AddLightSurfaces</code>). A minimal amount (2.9%) is spent in Visual Surface Determination: Traversing the BSP and running the portal system.
</p>
<div style="clear:both;margin-bottom:10px;">&nbsp;</div> 


<h2>Renderer: Backend</h2>
<p>
<img class="shadowed" src="../lazy_load/grey.gif" data-original="/fd_proxy/doom3/profiling_6.png" style="float:left; width:453px; height: 191px; margin: 0 40px 0 15px;" />
<u>Renderer BackEnd:</u><br/>
<br/>
The backend obviously triggers a buffer swap (<code>GLimp_SwapBuffers</code>) and spend some time synchronizing (10%) with the screen since the game was running in double buffering environment.
5% is the cost of avoiding totally overdraw with a first pass aiming to populate the Z-Buffer first (<code>RB_STS_FillDepthBuffer</code>).
<br/>
<div style="clear:both;margin-bottom:10px;">&nbsp;</div>


<h2>Flat stats</h2>
<p>
<img class="shadowed" src="../lazy_load/grey.gif" data-original="/fd_proxy/doom3/profiling_7.png" style="margin-left: auto; margin-right: auto; width:453px; height: 191px; margin: 0 20px 0 0px;" /><br/><br/>

If you feel like loading the Instruments trace and exploring yourself: <a href="../fd_proxy/doom3/doom3instrument.trace.zip">Here it the profile file</a>.

            </p>




<!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

