<script type="text/javascript">
  var disqus_identifier = "second_Reality_Code_Review" ;
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Second Reality, Future Crew, Second Reality source code"/>
		<meta name="Description" content="Second Reality source code review"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>Second Reality Code Review  Part 1</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       August 16th, 2013</div>
   <h1>Second Reality Code Review: Part 1 (Introduction)</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="second_reality.png" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         
<style type="text/css">
.shadowed-book{
  box-shadow: rgb(119, 119, 119) 3px 3px 3px;
  
 
  
  margin-right: 12px;
}

</style>

On July 23, 2013 the source code of Second Reality <a href="https://github.com/mtuomi/SecondReality">was released</a>. Like many, I was eager to look at the internals of a demo that inspired me so much over the last 20 years.<br/>
<br/>
I was expecting a monolithic mess of assembly but instead I found a surprisingly elaborated architecture, mixing several languages in an elegant way. The code is something like I had never seen before that perfectly represents two essential aspects of demomaking :
<ul>
   <li>Team work.</li>
   <li>Obfuscation.</li>
</ul>
<br/>
As usual I have cleaned up my notes into an article: I hope it will save some a few hours and maybe inspire others to read more source code and become better engineers.<br/>
<br/>
<a href="index.php">Part 1:  Introduction</a><Br/>
<a href="second_reality_engine.php">Part 2: Engine</a><Br/>
<a href="second_reality_dis.php">Part 3: Demo Interrupt Server</a><Br/>
<a href="second_reality_dev_Vs_Prod.php">Part 4: Dev Vs Prod</a><Br/>
<a href="second_reality_parts.php">Part 5: Parts</a><Br/>
<div style="clear:both;">
</div>

 <br/>
<h3>The Demo</h3>
<p>
  Before starting with the code, here is a link to a HD video capture (by Michael Huth) of the legendary demo. Nowadays, it is the only
  way to fully experiment the marvel without graphic glitches (even DOSBox cannot run it properly).<br/>
  <br/> 
<iframe style="margin: 0 auto;display:block;width:100%; height:auto; aspect-ratio: 4 / 3;" src="https://www.youtube.com/embed/KTjnt_WSJu8" frameborder="0" allowfullscreen></iframe>
</p>

 <br/>
<h3>First contact with the code</h3>
<p id="paperbox">
  The source code is hosted on GitHub. It is one <code>git</code> command away :<br/>
  <pre class="long">


   git clone git@github.com:mtuomi/SecondReality.git

  </pre>
  <p>
    At first the content is confusing: 32 folders and a mysterious <code>U2.EXE</code>
    that won't run under DosBox.<br/>
    <br/>
    <img class="shadowed" src="first_contact.png" style="margin-left:auto; margin-right:auto; display: block; width: 803px; height: 244px;" />
    <br/>
    <br/>
    The working title of the demo was "Unreal 2" (the first "Unreal" was Future Crew's previous demo, released for the first Assembly in 1992). Only later during development the name was changed to "Second Reality". This explains "U2.EXE" but not why it doesn't work...<br/>
    <br/>
    <br/>
    Runnig <a href="http://cloc.sourceforge.net/">CLOC</a> provides interesting metrics:<br/>
 <pre class="long">


    -------------------------------------------------------------------------------
    Language                     files          blank        comment           code
    -------------------------------------------------------------------------------
    Assembly                        99           3029           1947          33350
    C++                            121           1977            915          24551
    C/C++ Header                     8             86            240            654
    make                            17            159             25            294
    DOS Batch                       71              3              1            253
    -------------------------------------------------------------------------------
    SUM:                           316           5254           3128          59102
    -------------------------------------------------------------------------------


  </pre>
  <p>
    <br/>
    <ul>
      <li>The codebase is "only" 50% assembly.</li>
      <li>The codebase is almost twice as big as Doom engine.</li>
      <li>Seventeen makefiles are there. Why not only one ?</li>
    </ul>
  </p>

   <br/>
<h3>Running the demo</h3>
    <p>
      It is hard to figure it out but it is possible to run what was released via DosBox: You have to rename <code>U2.EXE</code> and run it form the right place. 
      Once I learned about the internals of the code, it made a lot of sense: <br/>
      <br/>
      <pre class="long">

        CD MAIN
        MOVE U2.EXE DATA/SECOND.EXE
        CD DATA
        SECOND.EXE

      </pre>
      <p>
      <br/>
      Et voila !<BR/>
      <br/>
      <img src="demo.png" style="width: 100%; height: auto; box-shadow: rgb(119, 119, 119) 3px 3px 3px; margin-left:auto; margin-right:auto; display: block;aspect-ratio:4/3;" />
<p/>
		
<br/>
<h3>Architecture</h3>
<p id="paperbox">
Back in the 90s, the demo was mostly distributed via floppy disks. After unzipping, two big files would be installed : <code>SECOND.EXE</code> and <code>REALITY.FC</code>: <br/>
<pre class="long">


    .               &lt;DIR&gt;         01-08-2013 16:40
    ..              &lt;DIR&gt;         01-08-2013 16:40
    FCINFO10 TXT           48,462 04-10-1993 11:48
    FILE_ID  DIZ              378 04-10-1993 11:30
    README   1ST            4,222 04-10-1993 12:59
    REALITY  FC           992,188 07-10-1993 12:59 
    SECOND   EXE        1,451,093 07-10-1993 13:35
        5 Files(s)     2.496,343 Bytes.
        2 Dir(s)     262,111,744 Bytes free.


</pre>
<p>
<p>Coming from a game developer background I always expected the big picture to be :<br/>
<ul>
<li><code>SECOND.EXE</code>: The engine with all effects in the executable.</li>
<li><code>REALITY.FC</code>: The assets (music, sound effects, images) in a proprietary/encrypted format ala Doom <code>WAD</code>.</li>
</ul>
<p>
But after reading <a href="https://github.com/fabiensanglard/SecondReality/blob/master/MAIN/PACK.C"><code>MAIN/PACK.C</code></a> I discovered that I was completely wrong :
The "Second Reality" engine is just a Loader and an Interrupt server (called DIS). Each scene (also called "PART") during the demo is a full self-contained DOS executable. Each parts are loaded by the Loader and started one after an other. The PARTs are stored in encrypted form
at the end of <code>SECOND.EXE</code> :<br/>
<br/>
<img src="architecture.png" style="margin-left: auto; margin-right: auto; display: block; width: 470px; height: 299px;" />
<br/>
<ul>
<li><code>REALITY.FC</code> contains the two musics played during the demo (with padding and a marker at the beginning for obfuscation).</li>
<li><code>SECOND.EXE</code> contains a loader and a Demo Interrupt Server (DIS).</li>
<li>Appended after the end of <code>SECOND.EXE</code>, the 32 PARTs of the demo as DOS executables (encrypted).</li>
</ul>
<p>
This architecture offers many advantages :
<ul>
   <li>Improved collaborative process in the team: Each member of the team can work independently on its PART as long as it produces an executable with a <code>_start</code> symbol and remains within the memory budget (450K).</li>
   <li>Encrypting the EXEs at the end of <code>SECOND.EXE</code> and having them loaded at runtime made reverse engineering harder.</li>
   <li>Fast startup : The Loader and DIS are only 20K. DOS loads them super fast.</li>
   <li>Easy memory management: Once a PART is done, the loader overrides it with the next PART and free ALL the allocated memory. </li>
   <li>No asset manager/loader needed: As seen later each PART had its assets (mostly images) 
    compiled within the code: Loading an EXE also loaded all the images it needed like a nice package.</li>
    <li>Any language could be used to program a PART: C, Assembly ... and Pascal can be found in the code.</li>
</ul>
</p>


 <br/>
<h3>Recommended readings</h3>
<p>
  The three pillars to understand Second Reality source code are VGA, Assembly and PC architecture (PIC&PIT Programming). Here are incredibly helpful links :<br/>
  <ul>
    <li>VGA Architecture: <a href="http://www.stanford.edu/class/cs140/projects/pintos/specs/freevga/home.htm">FreeVGA Project</a></li>
    <li><a href="http://cs.smith.edu/~thiebaut/ArtOfAssembly/artofasm.html">The Art of Assembly</a> (especially <a href="http://cs.smith.edu/~thiebaut/ArtOfAssembly/CH17/CH17-1.html">chapter 17</a> about  Interrupts and ISRs).</li>
    <li><a href="http://wiki.osdev.org/PIT">8254 PIT Programming</a></li>
    <li>Since the source if packed with "FAR" and "NEAR" pointers, it would be useful to read Intel's <a href="http://download.intel.com/products/processor/manual/253665.pdf">Basic Architecture Documentation</a>, especially Chapter 4.3 about "Pointers Data Types".</li>
    <li>The ubiquitous Michael Abrash articles from <a href="http://www.gamedev.net/page/resources/_/technical/graphics-programming-and-theory/graphics-programming-black-book-r1698">Graphic Programming Black Book</a>:  <a href="http://downloads.gamedev.net/pdf/gpbb/gpbb3.pdf">Chapter 3</a>: (Zen Timer and PIT), <a href="http://downloads.gamedev.net/pdf/gpbb/gpbb24.pdf">Chapter 24</a>: VGA tour, Chapters <a href="http://downloads.gamedev.net/pdf/gpbb/gpbb47.pdf">47</a>,<a href="http://downloads.gamedev.net/pdf/gpbb/gpbb48.pdf">48</a> and <a href="http://downloads.gamedev.net/pdf/gpbb/gpbb49.pdf">49</a>: (Mode X).</li>
  </ul>
  
</p>

<br/>
<h3>Next</h3>
<p id="paperbox">
  <a href="second_reality_engine.php">Second Reality Engine</a>
</p>


<!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

