<script type="text/javascript">
  var disqus_identifier = "second_Reality_Code_Review" ;
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Second Reality, Future Crew, Second Reality source code"/>
		<meta name="Description" content="Second Reality source code review"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>Second Reality Code Review  Part 3</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="https://fabiensanglard.net/" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="http://fabiensanglard.net/" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="http://fabiensanglard.net/about/">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="http://fabiensanglard.net/faq/">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="http://fabiensanglard.net/rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="http://fabiensanglard.net/rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="http://fabiensanglard.net/rss.xml" />
<div id="date">
       August 16th, 2013</div>
   <h1>Second Reality Code Review: Part 3 (DIS)</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="second_reality.png" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         
<style type="text/css">
.shadowed-book{
  box-shadow: rgb(119, 119, 119) 3px 3px 3px;
  
 
  
  margin-right: 12px;
}

</style>

Second Reality's Demo Interrupt Server (DIS) provides services to each PARTs, 
ranging from inter-parts-communication to synchronization with the VGA. Here are a few pointers if you want to read more about this component. 
<br/>

 <br/>
<a href="index.php">Part 1:  Introduction</a><Br/>
<a href="second_reality_engine.php">Part 2: Engine</a><Br/>
<a href="second_reality_dis.php">Part 3: Demo Interrupt Server</a><Br/>
<a href="second_reality_dev_Vs_Prod.php">Part 4: Dev Vs Prod</a><Br/>
<a href="second_reality_parts.php">Part 5: Parts</a><Br/>
<br/>
<div style="clear:both;">
</p>


<h3>DIS Services</h3>
<p id="paperbox">
  The DIS provides services to a PART while it runs. A list of the functions can be found in <a href="https://github.com/fabiensanglard/SecondReality/blob/master/DIS/DIS.H"><code>DIS/DIS.H</code></a>.
  The most important services :
  <ul>
      <li>Inter-PARTs communication (<code>dis_msgarea</code>) : The DIS provides three buffers of 64 bytes each so a PART can receive parameters from the loader or the previous PART.</li>
      <li>Copper emulation (<code>dis_setcopper</code>) : Amiga Copper simulator that enable operations to be triggered by the VGA state.</li>
      <li>Dev / Prod mode (<code>dis_indemo</code>) : Allowed a PART to know if it was running in DEV mode (and hence had to perform video initializations) or if it was being run from the Loader in PROD mode.</li>
      <li>VGA frame counting (<code>_dis_getmframe</code>)</li>
      <li>VGA retrace waiting (<code>dis_waitb</code>).</li>
  </ul>
  <p>
  

<p/>

<h3>Demo Interrupt Server code</h3>
<p id="paperbox">
 The DIS source is also 100% ASM...and moderately well commented:
  <ul>
    <li><a href="https://github.com/fabiensanglard/SecondReality/blob/master/DIS/DIS.ASM"><code>DIS/DIS.ASM</code></a> (Interrupt hander installed at int <code>0fch</code>).</li>
    <li><a href="https://github.com/fabiensanglard/SecondReality/blob/master/DIS/DISINT.ASM"><code>DIS/DISINT.ASM</code></a> (Actual DIS routines).</li>
    <li>Since Second Reality is also partially written in C, there is a C Interface: <a href="https://github.com/fabiensanglard/SecondReality/blob/master/DIS/DISC.H"><code>DIS/DIS.H</code></a> and <a href="https://github.com/fabiensanglard/SecondReality/blob/master/DIS/DISC.ASM"><code>DIS/DISC.ASM</code></a>.</li>
  </ul>
</p>


<h3>How it works</h3>
<p id="paperbox">
   The DIS is installed as an Interrupt Handler for software int <code>0fch</code>.<br/>
   The cool thing is that is can run from within <code>SECOND.EXE</code> when the demo is running
   or as a resident program (<a href="http://en.wikipedia.org/wiki/Terminate_and_Stay_Resident">TSR</a>) for dev mode.<br/>
   <br/>
   This flexibility allows PART of the demo to be tested directly and individually during development :<br/>
  <pre class="long">


                          <span style="color:blue;">// Let's pretend we are a FC developer and want to start the STAR part directly.</span>
  C:\>CD DDSTARS            
  C:\DDSTARS>K

  ERROR: DIS not loaded. 

                          <span style="color:red;">// Oops, the PART could not find the DIS at int 0fch.</span>
  C:\DDSTARS>CD ..\DIS
  C:\DIS>DIS

  Demo Int Server (DIS) V1.0   Copyright (C) 1993 The Future Crew
  BETA VERSION - Compiled: 07/26/93 03:15:53 
  Installed (int fc).
  NOTE: This DIS server doesn't support copper or music synchronization!
                          <span style="color:blue;">// DIS is installed, let's try again.</span>

  C:\DIS>CD ../DDSTARS
  C:\DDSTARS>K


  </pre>
  <p>
    <div style="text-align:center; display:block; width:100%; margin-left:auto; margin-right:auto;">Et Voila !
    </div>
    <br/>
    <img src="DDSTARTS.EXE.png" style="box-shadow: rgb(119, 119, 119) 3px 3px 3px;  display:block; margin-left:auto; margin-right:auto; width:639px;height:398px;"/>

  
  <br/>
  <br/>
   
</p>

<h3>Copper</h3> 
<p id="paperbox">
  <img src="copper_emu.png" style="float:right; margin-left:20px; width:296px; height:394px;"/>
  </br>
  The "Copper" was a co-processor loved by Amiga demomakers. Part of the <A href="http://en.wikipedia.org/wiki/Original_Chip_Set">Original Chip Set</a>
  , it allowed execution of a programmed instruction stream, synchronized with the video hardware.
  The PC had no such co-processor and Future Crew had to write a Copper simulator that run within the DIS.<br/>
 <br/>
 FC used the 8254-PIT and 8259-PIC chipset from the PC in order to simulate a Copper. They build a system <a href="https://github.com/fabiensanglard/SecondReality/blob/master/MAIN/COPPER.ASM#L96">synchronized with the VGA</a> frequency that could trigger a custom routines in <a href="https://github.com/fabiensanglard/SecondReality/blob/master/DIS/DIS.H#L53">three vertical retrace locations</a> :<br/>
 <ul>
    <li>Location 0 : After display start (about scan line 25)</li>
    <li>Location 1 : Just before retrace (AVOID USING THIS IF POSSIBLE)</li>
    <li>Location 2 : In the retrace</li>
  </ul>
  <p>
    How it is done can be read in <a href="https://github.com/fabiensanglard/SecondReality/blob/master/MAIN/COPPER.ASM#L94"><code>MAIN/COPPER.ASM</code></a> (and see drawing to the right) :
    <ol>
     <li>The 8254 chip timer is adjusted to trigger an IRQ0 at desired frequency.</li>
     <li>The interrupt 8h handler (which is called by the 8259 PIC upon receiving an IRQ0) is changed to <code>intti8</code> routine <a href="https://github.com/fabiensanglard/SecondReality/blob/master/MAIN/COPPER.ASM#L105">here</a>.</li>
   </ol>
   <p>
    <Br/>
    Note: The frame counting service of the DIS is actually provided by the copper simulator.
<div style="clear:both;" /> 
</p>

<h3>Next</h3>
<p id="paperbox">
  
  <a href="second_reality_dev_Vs_Prod.php">Second Reality DEV Vs PROD</a>
</p>


	<!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

