<script type="text/javascript">
  var disqus_identifier = "second_Reality_Code_Review" ;
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Second Reality, Future Crew, Second Reality source code"/>
		<meta name="Description" content="Second Reality source code review"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>Second Reality Code Review  Part 2</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       August 16th, 2013</div>
   <h1>Second Reality Code Review: Part 2 (Engine)</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="second_reality.png" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         

<style type="text/css">
.shadowed-book{
  box-shadow: rgb(119, 119, 119) 3px 3px 3px;
  
 
  
  margin-right: 12px;
}

</style>

As mentioned in the previous page, Second Reality backbone is made of :
<ul>
  <li>A DOS executable Loader.</li>
  <li>A Memory manager (simple stack pool)</li>
  <li>A Demo Interrupt Server (DIS).</li>
</ul>
<p>
  The goal of this page is to provide pointers for any programmer that would want to read the Engine and the Loader (The DIS is on the next page).<br/>
  <br/>
<a href="index.php">Part 1:  Introduction</a><Br/>
<a href="second_reality_engine.php">Part 2: Engine</a><Br/>
<a href="second_reality_dis.php">Part 3: Demo Interrupt Server</a><Br/>
<a href="second_reality_dev_Vs_Prod.php">Part 4: Dev Vs Prod</a><Br/>
<a href="second_reality_parts.php">Part 5: Parts</a><Br/>
 <br/>
<h3>Engine code</h3>
<p id="paperbox">
  The code of the engine is 100% ASM but it is very well written and fairly well commented :
  <ul>
    <li><a href="https://github.com/fabiensanglard/SecondReality/blob/master/MAIN/U2.ASM"><code>MAIN/U2.ASM</code></a> (core).</li>
    <li><a href="https://github.com/fabiensanglard/SecondReality/blob/master/MAIN/U2A.ASM"><code>MAIN/U2A.ASM</code></a> (utilities).</li>
    <li><a href="https://github.com/fabiensanglard/SecondReality/blob/master/MAIN/VMODE.ASM"><code>MAIN/VMODE.ASM</code></a> (VGA routines).</li>
  </ul>
  <p>
    In terms of pseudo-code it can be summarized as follow :
 <pre class="long">

    exemus  db 'STARTMUS.EXE',0
    exe0    db 'START.EXE',0
    ...
    exe23   db 'ENDSCRL.EXE',0

    <span style="color:blue;">start:</span>
       cli                         <span style="color:green;">; Disable all interrupts</span>
       mov     ah,4ah              <span style="color:green;">; Deallocate all memory</span>
       call checkall               <span style="color:green;">; Check for 570,000 bytes of mem, 386 CPU and VGA</span>
       call file_getexepath        
       call dis_setint             <span style="color:green;">; Install Demo Interrupt Server on Interrupt 0fch</span>
       call file_initpacking       <span style="color:green;">; Check exe signature (no tempering) !</span>
       call file_setint            <span style="color:green;">; Replace DOS routines (only OPENFILE, SEEK and READ) on Interrupt 021h</span>
       call flushkbd               <span style="color:green;">; Flush the keyboard buffer</span>
       
       call  checkcmdline          <span style="color:green;">; check/process commandline</span>

       <span style="color:green;">;======== Here we go! ========</span>
       call vmode_init             <span style="color:green;">; Init VGA (not necessarly Mode13h or ModeX), each PARTs had its own resolution</span>

       mov si,OFFSET exe0
       call executehigh            <span style="color:green;">; loaded to high in memory. Used for loading music loaders and stuff.</span>
   
       call  _zinit <span style="color:green;">; Start music</span>
       call  restartmus

       mov   si,OFFSET exe1     <span style="color:green;">;Parameter for partexecute: Offset to exec name</span>
       call  partexecute
       <span style="color:green;">; Execute all parts until exe23</span>

       call fademusic
       <span style="color:green;">;======== And Done! (or fatal exit) ========</span>

    <span style="color:blue;">fatalexit:</span>
       mov cs:notextmode,0
       call vmode_deinit

  </pre>
<p>
  The steps are pretty straight forward to read:
  <ol>
    <li>Installs the DIS interrupt server at Interrupt <code>0fch</code> (Note: did they pick "FC" for "Future Crew"?).</li>
    <li>Replace DOS system calls at Interrupt <code>021h</code> 
  (more on that in the <a href="second_reality_dev_Vs_Prod.php">Dev Vs Prod</a> page).</li>
    <li>Upload the music to the soundcard via EMS memory.</li>
    <li>Start the music.</li>
    <li>Execute each part of the demo.</li>
    <li>Done !</li>
</ol>
    <p>
  <br/>
 Details of the <code>execute</code> routines :
 <pre class="long">

 <span style="color:blue;">execute:</span>
      cld
      call  openfile <span style="color:green;">; Open the DOS executable for this PART</span>
      call  loadexe  <span style="color:green;">; loads the specified exe file to memory, does relocations and creates psp</span>
      call  closefile
      call  runexe   <span style="color:green;">;runs the exe file loaded previously with loadexe.</span>
                     <span style="color:green;">; returns after exe executed, and frees the memory</span>
                     <span style="color:green;">; it uses.</span>

  </pre>
<p>

<p/>

<br/>
<h3>Memory manager</h3>
<p id="paperbox">
   There were many legends about Second Reality using an elaborated memory manager via the MMU but
   there is no trace of this in the engine. Memory management is actually delegated to DOS :
   The engine starts by <a href="https://github.com/fabiensanglard/SecondReality/blob/master/MAIN/U2.ASM#L644">deallocating all the RAM</a> and
   then distribute it <a href="https://github.com/fabiensanglard/SecondReality/blob/master/MAIN/U2A.ASM#L81">on demand</a>.
   The only fancy trick is the ability to allocated RAM from the end of the heap: This is done using the return value of DOS
   malloc <a href="http://cs.smith.edu/~thiebaut/ArtOfAssembly/CH13/CH13-5.html#HEADING5-10">when too much RAM is requested</a>.
</p>

<h3>Next</h3>
<p id="paperbox">
  <a href="second_reality_dis.php">Second Reality DIS</a>
</p>


	<!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

