<script type="text/javascript">
  var disqus_identifier = "second_Reality_Code_Review" ;
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Second Reality, Future Crew, Second Reality source code"/>
		<meta name="Description" content="Second Reality source code review"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>Second Reality Code Review  Part 4</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       August 16th, 2013</div>
   <h1>Second Reality Code Review: Part 4 (DEV Vs Prod)</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="second_reality.png" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         
<style type="text/css">
.shadowed-book{
  box-shadow: rgb(119, 119, 119) 3px 3px 3px;
  
 
  
  margin-right: 12px;
}


</style>

While reading the source code of Second Reality, the most striking aspect was how much attention the team 
 dedicated to make the switch DEV to PROD seamless.<br/>
<br/>
<a href="index.php">Part 1:  Introduction</a><Br/>
<a href="second_reality_engine.php">Part 2: Engine</a><Br/>
<a href="second_reality_dis.php">Part 3: Demo Interrupt Server</a><Br/>
<a href="second_reality_dev_Vs_Prod.php">Part 4: Dev Vs Prod</a><Br/>
<a href="second_reality_parts.php">Part 5: Parts</a><Br/>
<br/>
<div style="clear:both;">
</p>

<h3>Development</h3>
<p id="paperbox">
	<img src="sc_dev.png" style="width: 368px; height: 396px; float:left; margin-right: 20px"/>In Development mode, each component of the demo was an individual executable.
  <ul  style="overflow: auto;">
    <li>The DIS was loaded in a resident TSR and accessed via Interrupt <code>0fch</code>.<br/>
    <li>The loader calls the DOS Interrupt <code>21h</code> in order to Open, Read, Seek and Close files.<br/>
    </ul>
  <p>
    This DEV configuration is advantageous :
  <ul style="overflow: auto;">
     <li>Each coder and graphist could work on an executable and test it individually without impacting the rest of the team.</li>
     <li>The full demo could be tested at any moment via the small <code>SECOND.EXE</code> (without all the EXE appended at the end). Each PART executable was loaded via a DOS <code>021h</code> interrupt from a separate file.</li>
   </ul>
   <div style="clear:both;">
   </p>

   <br/>
   <h3>Production (Demo mode)</h3>
<p id="paperbox">
	<img src="sc_prod.png" style="width: 368px; height: 391px; float:right; margin-left:20px;"/>
  In Production mode, the small <code>SECOND.EXE</code> (containing the Loader), the DIS and the EXE Parts were merged into a fat <code>SECOND.EXE</code>.<br/>
<ul style="overflow: auto;">
  
    <li>The DIS is still accessed via <code>0fch</code> Interrupt.</li>
    <li>The DOS 21h API was patched with custom FC routines that would open files from the end of the fat <code>SECOND.EXE</code> file.
    </ul>
    <p>
  This DEV configuration is advantageous in terms of loading speed and anti-reverse-engineering...but most of all, from a PART programming or loading perspective : NOTHING changes form DEV to PROD.<br/>

  <div style="clear:both;">
  <br/>
</p> 

<h3>Next</h3>
<p id="paperbox">
  <a href="second_reality_parts.php">Second Reality Parts</a>
</p>



	<!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

