<script type="text/javascript">
  var disqus_identifier = "mobile_progressive_playback";
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Deep magic, VLC, moov atom, mdata atom"/>
		<meta name="Description" content="MOV and MP4 containers: Workaround from the shadooow !"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>Progressive playback: An atom story.</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       November, 15th 2011</div>
   <h1>Progressive playback: An atom story.</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="exploded-andy-small.jpg" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         			
			
				I have been doing a lot of work with video containers recently, especially figuring out interoperability between iOS/Android and optimizing 
				progressive playback. In particular it seems Android devices fail to perform progressive playback on certain files while iOS and VLC succeed:<br/>
				<br/>
				Why ?<br/>
				<br/>
				As usual understanding things to the deep down proved extremely worthy.
				<br/>
				<div style="clear:both;"></div>
				</p>
				
			<br/>
			<h3>Analysis</h3><br/>
			<p id="paperbox">	
				
				<img src="../fd_proxy/mobile_progressive_playback/mov_format_good.png" style="float:left;padding-right:35px;"/>
				A movie file is called a container. There are several kind of containers but the most common on mobile platforms are:<br/>
				<br/>
				<ul>
					<li>Apple's MOV/Quicktime.</li>
					<li>MP4: design is based on MOV.</li>
					<li>3GP: design is also based on MOV.</li>
				</ul>	
				<p>
				<br/>
				Within the container, datas are organized as "ATOM"s. As you can see in the drawing on the left a typical movie container features
				four atoms:<br/>
				<br/>
				<ol>
					<li><code>ftyp</code> atom: The magic number part of the file. The body of this atom also contains the branding and 
					version of the container format. 
					With quicktime/MOV it is always "<code>qt&nbsp;&nbsp;</code>".</li>
					<li><code>moov</code> atom: The metadatas, containing codec description used in the <code>mdata</code> atom. 
					It also contains sub-atoms "<code>stco</code>" and "<code>co64</code>" which are absolute pointers to keyframes in the <code>mdata</code> atom.</li>
					<li><code>wide</code> atom: A dirty hack explained later.</li>
					<li><code>mdata</code> atom: The interleaved compressed audio and video streams. Account for 95% of the file size. Most of the time codecs used are H.263 for video and AAC for audio.</li>
				</ol>
				<br/>
				<p>
				<u>Note :</u> Why is the <code>wide</code> atom a dirty hack ? Because its only purpose in life is to be overwritten: 
				Atom size are coded on 4 bytes. 
				Hence an <code>mdata</code> atom maximum size is 4GB. To allow itself to grow further the <code>mdata</code> atom header 
				can be moved up by 8 bytes thanks to
				the padding and a special atom header can be used in order to code its size on 8 bytes instead of 4....
				and raise the limit from 4 GigaBytes to 9 ExaBytes.
				<br/>
				
				<br/>
				Now when a file like this is accessed over HTTP, the player performs progressive playback as follow:
				<ol>
					<li>Receives the "<code>ftyp</code>" atom and check that the container format, version and branding are supported.</li>
					<li>Receives the "<code>moov</code>" atom, check that the required codec are available and use the "<code>stco</code>" sub-atoms to 
					start decoding the video and audio streams.</li>
					<li>Receives the "<code>mdat</code>" atom, buffer the content and make it available so codec can decompress it.</li>
					
				</ol>	
				<br/>
				<p>
				Since the "<code>ftyp</code>" and "<code>moov</code>" are a few KB, progressive playback can start within a few seconds.
				<br/>
				<br/>
				<br/>
			
			</p>	
			
			
			
			<h3>Problem</h3><br/>
			<p id="paperbox">	
			<img src="../fd_proxy/mobile_progressive_playback/mov_format_good.png" style="float:left;padding-right:35px;"/>
			<img src="../fd_proxy/mobile_progressive_playback/mov_format.png" style="float:right;padding-left:35px;"/>
					In order to start playing a movie file right away its metadata contained in the "<code>moov</code>" atom is paramount to the player. If the movie file
					atoms are ordered as previously described everything work as expected...but most video editors (ffmpeg, quicktime, flash video) 
					generate atoms in the wrong order (as seen on the right): With the "<code>moov</code>" atom last.<br/>
					<br/>
					If you try to load a file structured like this on an Android device over the 
				internet, you get an error message like this:<br/>
				<br/>
				    <div class="post">
					<a  href="../fd_proxy/mobile_progressive_playback/device-2011-11-16-154323.png">
						<img  src="../fd_proxy/mobile_progressive_playback/device-2011-11-16-154323.png"/><br/>
					</a>
					</div>
				<br/>

				Progressive playback is not possible and you have to download the entire file before you can start watching the video.
				But if we try to open this file with an iOS device or VLC they are able to start playback within seconds:<br/>
				<br/>
				How ?<br/>
				<br/><br/><br/>
				The answer is pretty obvious and can be observed via WireShark:<br/>
				<br/>
				 	<div class="post">
						<a href="../fd_proxy/mobile_progressive_playback/wireshark.png"><img src="../fd_proxy/mobile_progressive_playback/wireshark.png"/></a>
					</div>			
								<br/>
				<br/>
				
				iOS and VLC open a second HTTP connection to the server using the not so well known "<code>Range</code>" HTTP header:<Br/>
				<Br/>
				<ol>
					<li>The first HTTP request features a "<code>Range: bytes=0-</code>" HTTP header field. So the movie is downloaded from the start.</li>
					<li>As soon the the player detects a "<code>mdat</code>" atom without the "<code>moov</code>" atom it opens a second connection with 
					a "<code>Range: bytes=4726467-</code>" HTTP header field. This skip most of the file up to the end and retrieve the "<code>moov</code>" atom.</li>
				</ol>	
				<p>
				Thanks to the second connection, the "<code>moov</code>" atom is retrieved faster and progressive playback can start right away without waiting
				for the entire file to be downloaded.<Br/>
				<Br/>
				</p>
			
			
			
			<h3>Solution</h3><br/>
			<p id="paperbox">
			Android videoplayer elect NOT to open a second connection but wait for the entire file to download. The only solution is to fix those files and reorder the atoms inside. This can be done:<br/>
			<ul>
				<li>Oldskool way using some C code from FFMPEG's 
				<a href="../fd_proxy/mobile_progressive_playback/qt-faststart.c"><code>qt-faststart.c</code></a>. 
				The code moves the "<code>moov</code>" atom at the top of the file and update all the "<code>stco</code>" sub-atoms pointers by adding the proper offset.</il>
				<li>Using iOS AV Foundation framework and a few lines of Objective-C (you can also convert from MOV to MP4 since Android cannot read MOV):
					<br/>
					<pre class="long">
					
					
    #import &lt;AVFoundation/AVAsset.h&gt;
    #import &lt;AVFoundation/AVAssetExportSession.h&gt;
    #import &lt;AVFoundation/AVMediaFormat.h&gt;
    
    
    + (void) convertVideoToMP4AndFixMooV: (NSString*)filename toPath:(NSString*)outputPath
    {    
	    
        NSURL *url = [NSURL fileURLWithPath:finename];    
        AVAsset *avAsset = [AVURLAsset URLAssetWithURL:url options:nil];
    
    
        AVAssetExportSession *exportSession = [AVAssetExportSession
                                           exportSessionWithAsset:avAsset
                                           presetName:AVAssetExportPresetPassthrough];
    
    
        exportSession.outputURL = [NSURL fileURLWithPath:outputPath];
        exportSession.outputFileType = AVFileTypeAppleM4V;   
    
        
        // This should move the moov atom before the mdat atom,
        // hence allow playback before the entire file is downloaded
        exportSession.shouldOptimizeForNetworkUse = YES;     
     
    
        [exportSession exportAsynchronouslyWithCompletionHandler:
        ^{
        
              if (AVAssetExportSessionStatusCompleted == exportSession.status) {} 
              else if (AVAssetExportSessionStatusFailed == exportSession.status) {
                  NSLog(@"AVAssetExportSessionStatusFailed");
              } 
              else 
              {
                  NSLog(@"Export Session Status: %d", exportSession.status);
              }
         }];
    }
    
					
					</pre>
				</li>
			</ul>
			
			</p>
</p>			

<!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

