<script type="text/javascript">
  var disqus_identifier = "Tunnel";
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Java, Tunnel effect, oldschool, oldskool, old school, raster, Java BufferedImage"/>
		<meta name="Description" content="Oldschool Tunnel effect with JAVA"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>Tunnel Java oldschool</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       March 8th, 2008</div>
   <h1>Tunnel effect</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="Tunnel2.jpg" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         	The Tunnel effect is probably the oldest effect ever. I think even Wozniak hacked one on Apple II. Nowaday, it's pretty easy to program, our machines have so much speed that you can brutecalcule everything on the fly. But how did they reach 30 frames per secondes on boxes as powerfull as a microwave?<br/> 
				The non technical answer is: <br/><br/>It's a trick !				Computer graphic is machiavelli's world: It doesn't matter how you do it as long as it looks Ok.<br/><br/> <cite> Perception IS reality...</cite><br/>
				
			</p>




<h3>Try it and source code
			</h3>
			<p id="paperbox">
				<ul>
					<li>Run it (<a title="Universal Java Version" href="applet/index.html">Applet</a>)</li>
					<li>Run it (<a title="C++ Windows version" href="Tunnel.zip">win32 build</a>)</li>
					<li>Source code: <a href="html/renderer/Renderer.java.html">Renderer.java</a>, <a href="html/renderer/Modeler.java.html">Modeler.java</a>, <a href="html/renderer/modelers/Tunnel.java.html">Tunnel.java</a>, <a href="html/renderer/modelers/Vector.java.html">Vector.java</a>.</li>
				</ul>
			</p>
			
			
			<br/>
			<h3>History
			</h3>
			<p id="paperbox">
				I discover demomaker's universe with a software considered one of the best in all time: Second Reality by Future Crew. It was running on a 486 DX2 and it was breathtaking. Released in 1994, more than 10 years later it still looks damn good and you can check it out on <a href="http://www.youtube.com/watch?v=8G_aUxbbqWU">YouTube</a>.<br/><br/>
				Since then I've always followed the scene, not programming myself but being an enthousiast.<br/>
			</p>
			
			<br/>
			<h3>How they did it.
			</h3>
			<p id="paperbox">
				
				Key world is: Precalculation.<br/>
				<br/>
				There was no GPU or graphic card whatsoever at this time, everything was done with the CPU. This is called software rendition and it means you have to do EVERYTHING ! Namely it means that you start your loop wih an empty array, decide the color of every single pixels and then send the entiere thing to the screen.<br/><br/>
				It's the only "hard" part to get: the program precalculates the texture's coordinates only once and so for the entiere screen. With a screen resolution of 256*256, it's 65536 array raster (the pixels).<br/>
				<br/>
				<br/>
				
				<pre class="long">


    // Pregenerating the mapping pixel/coordinate.
    for(int x = 0; x < scrWidth; x++)
        for(int y = 0; y < scrHeight; y++)
        {
            distances[x][y] = (int)

            (	(30.0 * TEXTUREHEIGHT / 
                 Math.sqrt(x - scrWidth /2.0) * (x - scrWidth /2.0) + (y - scrHeight /2.0) * (y - scrHeight /2.0))
            ) % TEXTUREHEIGHT);
 		        
            angles[x][y] = (int)(0.5* TEXTUREWIDTH * Math.atan2(y - scrHeight /2.0, x - scrWidth /2.0) / Math.PI);<br/>
        }


				</pre>
				
				
				
				<p>
				How do we get this perception of movement if nothing move then ?
				Well, you don't move, the tunnel is not moving either, but the texture is "slidding" on the Tunnel.<br/>
				
				So the main program loop is very small because there we are only shifting the texture on the right and to the up:<br/>	
				</p>
				<br/>	
				
				<pre class="long">


    //calculate the shift values out of the animation value
    shiftX =  (int)(TEXTUREWIDTH  + animation);
    shiftY =  (int)(TEXTUREHEIGHT +movement);// / rotation);

    for(int y = 0,cursor=0; y &lt; scrHeight; y++)
        for(int x = 0; x &lt; scrWidth; x++,cursor++)
        { 
            static int c_x = (distances[x][y] + shiftX) % TEXTUREWIDTH;
            static int c_y = (angles[x][y] + shiftY) % TEXTUREHEIGHT;

            renderer.offScreenRaster[cursor] = texture[c_x + c_y * TEXTUREWIDTH] ;
    }


        </pre>
				</p>
        
        	<br/>
				<h3>Reference
			</h3>
			<p id="paperbox">
				Two excellent articles by Lode: <a href="http://student.kuleuven.be/~m0216922/CG/tunnel.html">The Tunnel effect</a> (moved <a href="https://lodev.org/cgtutor/tunnel.html">here</a>). And the <a href="http://student.kuleuven.be/~m0216922/CG/xortexture.html">XOR Texture</a> (moved <a href="https://lodev.org/cgtutor/xortexture.html">here</a>).
			</p>
			</p>
			
			
<!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

