<script type="text/javascript">
  var disqus_identifier = "RayTracing";
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Java, Java Raytracing, oldschool, oldskool, old school, Interpolation, Java BufferedImage"/>
		<meta name="Description" content="Oldschool Tunnel effect with JAVA"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>Java Raytracing</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       March 8th, 2008</div>
   <h1>Free direction Tunnel effect</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="RayTracing.png" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         <style type="text/css">
	img.pixel{
    image-rendering: pixelated;
    image-rendering: -moz-crisp-edges;
    image-rendering: crisp-edges;
}
</style>


	After finalizing the <a href="../Tunnel/index.php">Tunnel Effect</a>, I wanted to go for something a little bit harder and I came across this fantastic <a href="freeDirectionTunnel.txt">text</a> by BlackAxe / KoLOr (1997).<br/>
					
					<br/>Seriously, this paper is so well written that I have nothing to add. Only that I learned the golden rule in computer graphic:<br/>
					<br/>
					<cite>Perception is reality..</cite><br/><br/>
					Using raytracing technique, you can get a "Free direction Tunnel effect", much more sophiticated than the first Tunnel. The only hard part to understand (and I guess it was intentional) is when it comes to "interpolation", which is the essence of the trick.
				</p>
				
				
				<br/>
				<h3>Try it and source
				</h3>
				<p id="paperbox">
				<ul>
	<li>Basic raytracing</li>
	<li>Interpolated raytracing 10x faster</li>
	<li><a href="src.zip">Source code</a> (Eclipse project: 29KB)</li>
	
</ul>
				</p>
				

				<h3>First implementation
				</h3>
				
				<p id="paperbox">
					If you follow the procedure described you get a raytraced Free direction Tunnel.....running at 7 frames per secondes: You can check it out <a href="applet/index.html">Here</a>.<br/>
					Beautiful but slow. <br/>
					
				</p>
				
					
				<h3>Second implementation with interpolations
				</h3>
					The second interpolation only cast a ray each 8 pixels and then interpolate the texture. The result is slighty less pretty but 10x faster !
					Since the tunnel is moving fast, the lost of quality is almost invisible compared to the speed gain :<br/>
					<br/>
				<p id="paperbox">
					<table style="width:100%;">
						<tr>
							<td style="width: 48%;">
							    <img src="InterpolatedMini.JPG" style="border: 1px black solid;" />
						    </td>
						    <td style="width: 48%;">
							    <img src="noInterpolatedMini.JPG" style="border: 1px black solid;" />
							</td>

						</tr>
					</table>
				</p>		
				
<!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

