<script type="text/javascript">
  var disqus_identifier = "vr_headset";
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Virtual Reality Headset Oculus Rift"/>
		<meta name="Description" content="Virtual Reality Headset Oculus Rift Programming"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>Oculus Rift</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       July 31, 2012</div>
   <h1>Oculus Rift: Motion Tracker development</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="vr_headset_icon.png" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         
Virtual Reality headsets have been consistently disappointing for several decades now. Three reasons come to mind in order to explain this state of things:
<ul>
<li>The hardware is expensive: The latest <a href="http://store.sony.com/webapp/wcs/stores/servlet/ProductDisplay?catalogId=10551&storeId=10151&langId=-1&productId=8198552921666383670&XID=O:hmz%20t1:dg_tv_gglsrch:e&k_id=2acaec79-9452-d9a9-1a9e-000000e154e1#">Sony HMZ-T1</a> is 799$.</li>
<li>The hardware is not good enough: The motion sensor, screen latency and screen limited Field of View are unable to provide a feeling of immersion.</li>
<li>The software is non-existent: No major studio has ever supported VR Headsets.</li>
</ul>
<p>
<br/>
But things are about to change thanks to a device to be released this September via kickstarter funding: the <a href="http://oculusvr.com/?page_id=1">Oculus rift</a>.

<div style="clear:both;">
</div>


<h3>Oculus RIFT</h3>
<p id="paperbox"> 
Palmer Luckey the man behind the project has managed to put together a set of outstanding components that provide very low latency and a significantly increased field of view ; he also managed
to keep the price under 250$. This tackle the two first problems related to hardware. <br/>
<br/>
<img src="../lazy_load/grey.gif" data-original="/fd_proxy/vr_headset/oculus-rift.jpg" style=" margin: 10px 10px 10px 0px; box-shadow: rgb(119, 119, 119) 3px 3px 3px; width: 600px; height: 273px; margin-left: auto; margin-right: auto; display: block;">

<br/>
As for the software, Luckey secured id Software to support the device officialy: Doom3 BFG Edition will be compatible out-of-the-box. Valve is also confirmed to be working on Portal compatibility:<br/>
<br/>

<div style="width:100%; text-align:center;">
  <iframe width="853" height="480" src="https://www.youtube.com/embed/UyuMVazQPos" frameborder="0" allowfullscreen></iframe>
</div>
<br/>
<u>EDIT :</u> The <a href="http://www.kickstarter.com/projects/1523379957/oculus-rift-step-into-the-game">kickstarter project opened on August 1st</a> and reached its 250,000$ goal within an hour. The hype around this thing is beyond everything I have ever seen in the field. Looks amazing:<br/>
<br/>
<img src="../lazy_load/grey.gif" data-original="/fd_proxy/vr_headset/photo-full.jpeg" style=" margin: 10px 10px 10px 0px; box-shadow: rgb(119, 119, 119) 3px 3px 3px; width: 560px; height: 420px; margin-left: auto; margin-right: auto; display: block;">
<br/>
<img src="../lazy_load/grey.gif" data-original="/fd_proxy/vr_headset/draw.png" style=" margin: 10px 10px 10px 0px; box-shadow: rgb(119, 119, 119) 3px 3px 3px; width: 516px; height: 290px; margin-left: auto; margin-right: auto; display: block;">
</p>

<h3>Motion Sensor: FSRK-USB-2</h3>
<p id="paperbox"> 
Unfortunately developers will get their hands on an Oculus RIFT only starting November 2012. But if you are eager to start developing you can ordered the motion tracker chipset that will be used: Hillcrest's <a href="http://www.hillcrestlabs-devstore.com/servlet/the-14/FSRK-dsh-USB-dsh-2/Detail">FSRK-USB-2</a>. It is a very tiny printed board that you can connect via micro-USB:<br/>
<br/>
<img src="../lazy_load/grey.gif" data-original="/fd_proxy/vr_headset/DSC_00072.JPG" style="margin: 0px 10px 10px 0px; box-shadow: rgb(119, 119, 119) 3px 3px 3px; width: 900px; height: 602px; margin-left: auto; margin-right: auto; display: block;"/>

<br/>
<img src="../lazy_load/grey.gif" data-original="/fd_proxy/vr_headset/FSRK-USB-2.png" style="margin: 0px 10px 10px 0px; box-shadow: rgb(119, 119, 119) 3px 3px 3px; width: 896px; height: 706px; margin-left: auto; margin-right: auto; display: block;"/>
<br/>
<br/>
</p>
<h3>Deviceless development</h3>
<p>
The software used to receive signal from the motion tracker is called <a href="http://libfreespace.hillcrestlabs.com/">libfreespace</a>. It is built on top of <a href="http://www.libusb.org/">libusb</a> and comes with many examples that make it easy to integrate to any engine.<br/>
<br/>
With a little bit of electrical tape and Windows 8 sunglasses it is possible to build a unglamourous but efficient prototype and experiment with headtracking:<br/>
<br/>
<img src="../lazy_load/grey.gif" data-original="/fd_proxy/vr_headset/DSC_0015.JPG" style="margin: 0px 10px 10px 0px; box-shadow: rgb(119, 119, 119) 3px 3px 3px; width: 1024px; height: 602px; margin-left: auto; margin-right: auto; display: block;"><br/>
<br/>
<img src="../lazy_load/grey.gif" data-original="/fd_proxy/vr_headset/DSC_0021.JPG" style="margin: 0px 10px 10px 0px; box-shadow: rgb(119, 119, 119) 3px 3px 3px; width: 1024px; height: 602px; margin-left: auto; margin-right: auto; display: block;"><br/>
<br/>
<a href="../fd_proxy/vr_headset/DSC_0024.JPG">The complete "deviceless" setup...</a><br/>
</p>

<h3>Integration to a 3D engine</h3>
<p id="paperbox"> 
Integrating libfreespace inputs to a 3D engine can be done in a few minutes with the following architecture:<br/>
<br/>
<img src="../lazy_load/grey.gif" data-original="/fd_proxy/vr_headset/archi.png" style="margin: 0px 20px 10px 0px;width: 625px; height: 352px; margin-left: auto; margin-right: auto; display: block;"><br/>
<br/>
The engine spawns a "pump" thread: An infinite loop that will endlessly requests the motion sensor orientation via <code>freespace_readMessage</code>. The result is stored in a synchronized array. Upon rendering the engine just get the latest orientation know via the shared variable without waiting for communication via libfreespace: This brings latency down a lot since the time waiting for system calls to return from the USB bus is spent in the "pump" Thread and not in the "Engine" Thread.<br/>
<br/>
You can also request a specific firmware from Hillcrest Labs that crank up frequency from 125Hz to 250Hz which will reduce latency further. You also need to enable Triple Buffering. Finally, the source code can be found <a href="https://github.com/fabiensanglard/Quake-2">on GitHub</a>.<br/>
<div style="clear:both;"/>
<br/>
<div style="width:100%; text-align:center;">
   <iframe width="853" height="480" src="https://www.youtube.com/embed/hwmN0cWo_hw" frameborder="0" allowfullscreen></iframe>
</div>
<p>
Once the motion tracking events are integrated to the engine, the video output also has to be significantly altered: 
<ul>
   <li>The screen must two rendition from two point of view: One for the left eye and one for the right eye, side by side.</li>
   <li>Each eye image must also be distorted by the inverse amount operated by the physical lenses in the Oculus RIFT: This is called "pre-warping"</li>
</ul>
<p>
In the end the result has to look like this:</br>
<br/>
<img src="../lazy_load/grey.gif" data-original="/fd_proxy/vr_headset/oculus-rift-pre-warp.jpg" 
style="margin: 0px 20px 10px 0px;width: 600px; height: 379px; margin-left: auto; margin-right: auto; display: block;"><br/>
<br/>
<p>
In practice this is done as follow:<br/>
<ul>
  <li>Render each eye one after an other to an offscreen surface (with OpenGL this would be a Frame Buffer Object).</li>
  <li>Use a special shader to perform the warping while moving from FBO to the framebuffer.</li>
</ul>
</p>



			
	<!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

