<script type="text/javascript">
  var disqus_identifier = "Duke3D_Code_Review" ;
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Duke Nukem 3D: Build Engine Internals"/>
		<meta name="Description" content="Duke Nukem 3D: Build Engine Internals"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>Duke Nukem 3D: Build Engine Internals</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       February 14th, 2013</div>
   <h1>Duke Nukem 3D: CODE LEGACY (PART 3 OF 4) <a href="chocolate_duke_nukem_3D.php">>></a></h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="duke3d.png" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         <i>Build</i> is an outstanding engine and the numerous games it powered brought very much deserved fame and fortune to both
parties: Ken Silverman and 3D Realms.<br/>
<br/>
 Ken Silverman completed his contract: 
 He delivered the binary of an astonishing 3D engine with <a href="BUILDINF.TXT">well documented methods and assets formats</a>. 
 As a testimony of his skills, 3D Realms <a href="../fd_proxy/duke3d/Duke_credit.png">credited him</a> with "Ken '
 I can do that' Silverman".<br/>
<br/>
But <i>Build</i> development was focused on features and performances, not portability or readability. Having read the code I believe 
open source developers stayed away from it because :
<ul>
     <li>It is discouragingly hard to read and extract knowledge from.</li>
     <li>It was not portable.</li>
</ul>
<p>
I have listed on this page a few of the difficulties I identified. I also released  <a href="chocolate_duke_nukem_3D.php">
Chocolate Duke Nukem 3D</a> a port that address those issues. Because I wanted people to remember what treasure of ingenuity
 it took to build a 3D engine back then. But also because I wanted people to understand how a teenager driven by passion contributed to
  one of the greatest game of all time.
 
 </p>
 
<Br/>


<h3>Hard to understand</h3>
<p id="paperbox">
</p>
  <ul>
    <li>Only three modules makes the entire codebase hard to mentally break down in sub-modules.</li>
    <li><code>typedef</code> and <code>struct</code> are not used internally (only used for public data:<code>sectortype</code>,
     <code>walltype</code> and <code>spritetype</code>). Only arrays of primitive data types. 
     (i.e: <a href="https://github.com/fabiensanglard/vanilla_duke3D/blob/master/SRC/CACHE1D.C#L232">GRP Filesystem</a>):
        <pre class="long">

    static <span style="color:blue">long</span> numgroupfiles = 0;
    static <span style="color:blue">long</span> gnumfiles[MAXGROUPFILES];
    static <span style="color:blue">long</span> groupfil[MAXGROUPFILES] = {-1,-1,-1,-1};
    static <span style="color:blue">long</span> groupfilpos[MAXGROUPFILES];
    static <span style="color:blue">char</span> *gfilelist[MAXGROUPFILES];
    static <span style="color:blue">long</span> *gfileoffs[MAXGROUPFILES];

    static <span style="color:blue">char</span> filegrp[MAXOPENFILES];
    static <span style="color:blue">long</span> filepos[MAXOPENFILES];
    static <span style="color:blue">long</span> filehan[MAXOPENFILES]
        </pre>
    </li>
    <li>Comments are sparce. This makes math methods difficult to understand (i.e: <a href="https://github.com/fabiensanglard/vanilla_duke3D/blob/master/SRC/ENGINE.C#L2733">inside</a>):
      <pre  class="long">

    inside (<span style="color:blue">long</span> x, <span style="color:blue">long</span> y, <span style="color:blue">short</span> sectnum){    
        walltype *wal;
        <span style="color:blue">long</span> i, x1, y1, x2, y2;
        <span style="color:blue">unsigned long</span> cnt;

        <span style="color:blue">if</span> ((sectnum < 0) || (sectnum >= numsectors)) <span style="color:blue">return</span>(-1);

        cnt = 0;
        wal = &wall[sector[sectnum].wallptr];
        i = sector[sectnum].wallnum;
        <span style="color:blue">do</span>{
            y1 = wal->y-y; y2 = wall[wal->point2].y-y;
            <span style="color:blue">if</span> ((y1^y2) < 0){
            x1 = wal->x-x; x2 = wall[wal->point2].x-x;
            <span style="color:blue">if</span> ((x1^x2) >= 0) cnt ^= x1; <span style="color:blue">else</span> cnt ^= (x1*y2-x2*y1)^y2;
            }
            wal++; i--;
        } <span style="color:blue">while</span> (i);
        <span style="color:blue">return</span>(cnt>>31);
    }
      </pre>
    </li>
    <li>The drawing routines were x86 hand optimized assembly. Those were ported back to C later but there are still <a href="https://github.com/fabiensanglard/vanilla_duke3D/blob/master/SRC/drawing_routines/A.C">extremely hard to read</a> as well.</li>
    <li>Symbols names are sometimes <a href="https://github.com/fabiensanglard/vanilla_duke3D/blob/master/SRC/ENGINE.C#L130">controversial</a>:
            <pre  class="long">

    <b>static</b> <span style="color:blue">long</span> xb1[MAXWALLSB], yb1[MAXWALLSB], xb2[MAXWALLSB], yb2[MAXWALLSB];
    <b>static</b> <span style="color:blue">long</span> rx1[MAXWALLSB], ry1[MAXWALLSB], rx2[MAXWALLSB], ry2[MAXWALLSB];
    <b>static</b> <span style="color:blue">short</span> p2[MAXWALLSB], thesector[MAXWALLSB], thewall[MAXWALLSB];

            </pre>
      .</li>
    <li>Magic numbers (especially when manipulating walls, floor and ceiling) <a href="https://github.com/fabiensanglard/chocolate_duke3D/blob/master/Engine/src/engine.c#L2220">are mysterious</a>.</li>
    <li>The main Translation Units (game.c and engine.c) are so big that they slow down IDE. Sometimes to the point of crashing XCode.</li>
  </ul>

    <p>
     

  </p>







<h3>Hard to port</h3>
<p id="paperbox">
  <ul>
    <li>Assumed Little-Endian CPU.</li>
    <li>Used <code>long</code> type across the engine expecting them to always be 32 bits wide.</li>
    <li>Assumed 32 bits addresses and manipulated them as integers.</li>
    <li>Features hand optimized x86 assembly with no C fallback.</li>
    <li>Expected 120 ticks per frame: The way DOS timer worked.</li>
    <li>No abstraction layer. Calls to filesystem/renderer were raw.</li>  
  </ul>

</p>




<br/>
<h3>Lost ressources</h3>
<style type="text/css">
blockquote.style1 
  {
      
      padding: 8px;
      
      width: 80%;
      
      background-color: #eeeeee;
      border: 1px solid #dddddd;
      
      
      margin: 5px;
      background-image: url(../quake2/images/openquote1.gif);
      background-position: top left;
      background-repeat: no-repeat;
      text-indent: 23px;
    
    }
    
    blockquote.style1 span 
    {
      display: block;
      font-style:italic;
      background-image: url(../quake2/images/closequote1.gif);
      background-repeat: no-repeat;
      background-position: bottom right;
      text-align: justify;
    }
</style>
<p id="paperbox">
  Ken Silverman once kindly collaborated to the <a href="http://www.jonof.id.au/">JonoF</a> port and posted many explanation of his algorithms. 
  Unfortunately the <a href="http://www.jonof.id.au/forum/">forum had to be taken down</a> due to spam. It seems all those precious information 
  are gone :( !<br/>
  <br/>
  <blockquote class="style1" style="margin-left:6em;">
<br/>
  <span style="margin-left">
  It is with disappointment that I've closed the forum on this site. Spam bots made it impossible to keep it under control,
   and although there is some valuable content within its posts, it's just not worth my or the other moderators' time to maintain it.<br/>
<br/>
  I suggest you head over to the Duke4.net forums if you want to remain involved in the community.<br/>
  <br/>
  <br/>
</span>
</blockquote>
</p>
            
<!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

