<script type="text/javascript">
  var disqus_identifier = "Duke3D_Code_Review" ;
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Duke Nukem 3D Code Review"/>
		<meta name="Description" content="Duke Nukem 3D Code Review"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>Duke Nukem 3D Code Review</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="https://fabiensanglard.net/" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="http://fabiensanglard.net/" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="http://fabiensanglard.net/about/">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="http://fabiensanglard.net/faq/">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="http://fabiensanglard.net/rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="http://fabiensanglard.net/rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="http://fabiensanglard.net/rss.xml" />
<div id="date">
       February 14th, 2013</div>
   <h1>Duke Nukem 3D Code Review:  INTRODUCTION (PART 1 OF 4) <a href="build_engine_internals.php">>></a></h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="duke3d.png" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         Since I left my job at Amazon I have spent a lot of time reading great source code. 

<a href="http://fabiensanglard.net/doomIphone/doomClassicRenderer.php">Having</a> 
<a href="http://fabiensanglard.net/quakeSource/index.php">exhausted</a>
<a href="http://fabiensanglard.net/wolf3d/index.php">the</a>
<a href="http://fabiensanglard.net/quake3/index.php">insanely</a> 
<a href="http://fabiensanglard.net/quake2/index.php">good</a> 
<a href="http://fabiensanglard.net/doom3/index.php">idSoftware</a> 
<a href="http://fabiensanglard.net/doomIphone/doomClassicRenderer.php">pool</a>, 
	the next thing to read was one of the 
  <a href="http://en.wikipedia.org/wiki/List_of_best-selling_PC_video_games">greatest
	game of all time</a> : 
Duke Nukem 3D and the engine powering it named "<i>Build</i>".<br/>
<br/>
It turned out to be a difficult experience: 
The engine delivered great value and ranked high in terms of speed, stability and memory consumption 
but my enthousiasm met a source code controversial in terms
of organization, best practices and comments/documentation. This reading session taught me a lot about code 
legacy and what helps a software live long.<br/>
<br/>
As usual I cleaned up <a href="notes.txt">my notes</a> into an article. I hope it will inspire some of us to 
read more source code and become better engineers.<br/>
<br/>
<a href="index.html">Part 1: Overview.</a><br/>
<a href="build_engine_internals.php">Part 2: Engine Internals.</a><br/>
<a href="code_legacy.php">Part 3: Engine legacy.</a><br/>
<a href="chocolate_duke_nukem_3D.php">Part 4: Chocolate Duke Nukem 3D.</a><br/>
<br/>
I would like to thanks <b>Ken Silverman</b> for proof-reading this article: His patience and diligent replies to my emails were instrumental.
<div style="clear:both;">

</p>

<h3>Genesis</h3>
<p id="paperbox"> 
Duke Nukem 3D is not one codebase but <b>two</b> :
<ul>
<li><i>Build</i> engine: Providing rendition, network, filesystem and caching services.</li>
<li>Game Module: Using <i>Build</i>'s services in order to generate a gaming experience.</li>
</ul>
<p>
Why such a division? Because back in 1993, when development started, very few people had the skills and dedication 
to produce a good 3D engine. When 3D Realms
decided to write a game that would challenge <i>Doom</i>, they had to find the technology that would power it. That 
is where Ken Silverman enters the picture.<br/>
<br/>
According to his <a href="http://advsys.net/ken/build.htm">well-documented website</a> and 
<a href="http://www.3drealms.com/news/2006/02/the_apogee_legacy_8.html">interview</a>, Ken Silverman 
(18 years old at the time) wrote a 3D engine at home and sent a demo for evaluation to 3D Realms.
 They found his skills promising and worked out a deal:<br/>
<br/>
<img src="../lazy_load/grey.gif" data-original="/fd_proxy/duke3d/duke_nukem_dev_team.png" 
style=" margin: 10px 10px 10px 0px; width: 629px; height: 349px; margin-left: auto; margin-right: auto; display: block;"/>
<br/>
<br/>
Silverman would write a new engine for 3D Realms but he would keep the source code.
He would only deliver a <u>binary static library</u> (<code>Engine.OBJ</code>) with an <code>Engine.h</code>
 header file. The 3D Realms team on their side would take care of developing the Game module (<code>Game.OBJ</code>) 
 and would also release the final executable <code>DUKE3D.EXE</code>.
<br/>
<br/>
Unfortunately both part of the game were not open sourced simultaneously:
<ul>
  <li>The Engine module source code was released by Ken Silverman on June 20, 2000 .</li>
  <li>The Game module source code was released by 3D Realms on April 1, 2003.</li>
</ul>
<p>
As a result the full source code was available 7 years after the game was released.<br/>
<br/>
<u><b>Trivia :</u></b> The name of the engine "<i>Build</i>" was chosen by Ken Silverman when creating the directory
 for the new engine: He used a <a href="http://advsys.net/ken/build.htm">thesaurus to search for a synonyms of "Construction"</a>.
</p>

<h3>First contact</h3>
<p id="paperbox">
<img src="../lazy_load/grey.gif" data-original="/fd_proxy/duke3d/duke3d_project.png" style="border-style: solid;
border-width: 1px; float:left; margin: 10px 20px 10px 0px; box-shadow: rgb(119, 119, 119) 3px 3px 3px; width: 267px; height: 695px;">
Since the original code released rotted a long time ago (It was targeted to Watcom C/C++ compiler and DOS systems) I tried to find 
something
like <a href="http://www.chocolate-doom.org/wiki/index.php/Chocolate_Doom">Chocolate doom</a>: A port that
 accurately reproduces the experience of Duke Nukem 3D as it was played in the 90s and would flawlessly compile on modern systems.<br/>
 <br/>
 It turned out the Duke Nukem open source community is not very active anymore: Most ports have rotted again, 
 some have MacOS 9 PowerPC targets and the only one still maintained (<a href="http://eduke32.com/">EDuke32</a>) 
 has evolved too far from the original code. 
 I ended up working with <a href="http://vision.gel.ulaval.ca/~klein/duke3d/">xDuke</a> even though it did not 
 compile on Linux or Mac OS X (which ruled out XCode: An outstanding IDE when it comes to reading code and profiling).<br/>
 <br/>
 xDuke's Visual Studio Solution is fidele to the original workflow. It features two projects: Engine and Game: The "Engine" 
 project compiles to a static
 library (<code>Engine.lib</code>) and the "Game" project (featuring the <code>main</code> method) links  against it in order
 to generate a <code>duke3D.exe</code>.<br/>
 <br/>
 Upon opening VS, the engine source felt unwelcoming with difficult filenames (<code>a.c</code>, <code>cache1d.c</code>). 
 Opening those files reveals something
  hostile to the eyes and the mind.
 An  example among many others from <a href="https://github.com/fabiensanglard/vanilla_duke3D/blob/master/SRC/ENGINE.C#L1280">
 Engine.c (line 693)</a>:<br/>
 <br/>
 <pre class="long" style="margin: 0 0 0 300px; font-size: 10px;">
 
 
  <span style="color:blue;">if</span> ((globalorientation&0x10) > 0) globalx1 = -globalx1, globaly1 = -globaly1, globalxpanning = -globalxpanning;
  <span style="color:blue;">if</span> ((globalorientation&0x20) > 0) globalx2 = -globalx2, globaly2 = -globaly2, globalypanning = -globalypanning;
  globalx1 <<= globalxshift; globaly1 <<= globalxshift;
  globalx2 <<= globalyshift;  globaly2 <<= globalyshift;
  globalxpanning <<= globalxshift; globalypanning <<= globalyshift;
  globalxpanning += (((<span style="color:blue;">long</span>)sec->ceilingxpanning)<<24);
  globalypanning += (((<span style="color:blue;">long</span>)sec->ceilingypanning)<<24);
  globaly1 = (-globalx1-globaly1)*halfxdimen;
  globalx2 = (globalx2-globaly2)*halfxdimen;
 
 
 </pre>
 </br>
	 <u><b>Note :</b></u> If a file/variable name features a number: it is probably not a good name !<br/>
	 <br/>
<u><b>Trivia :</b></u> The last part of <code>game.c</code> features a 
<a href="https://github.com/fabiensanglard/chocolate_duke3D/blob/master/Game/src/game.c#L10795">draft of Duke V scenario</a> ! 
 <br/>

  <div style="clear:both"/>
 <br/>
 <p>
 <b><u>Note :</u></b> xDuke port uses SDL but the cross-platform API advantage is lost 
 to WIN32 timers (<code>QueryPerformanceFrequency</code>). It seems the 
 SDL Timer used to be too innacurate in order to emulate DOS 120Hz tick rate.<br/>
 <br/>
</p>
                                                                                                          
<h3>Building</h3>
 <p id="paperbox">
 After setting up SDL and DirectX header/lib location the code will build in one click: That is very pleasant. The only last part is to get
 a <code>DUKE3D.GRP</code> asset file and the game runs....well kinda :/.... SDL seems to have some palette issues with Vista/Windows 7:<br/>
 <br/>
 <img src="../lazy_load/grey.gif" data-original="/fd_proxy/duke3d/palette_bug.png" 
 style="margin-left: auto; box-shadow: rgb(119, 119, 119) 3px 3px 3px;
 margin-right: auto; display: block; width: 640px; height: 480px"/>
 <br/>
 <br/>
 Running in Windowed Mode (or better, use Windows 8) seems to fix the issue:</br>
 <br/>
 <img src="../lazy_load/grey.gif" data-original="/fd_proxy/duke3d/palette_fix.png" 
 style="margin-left: auto; box-shadow: rgb(119, 119, 119) 3px 3px 3px;
 margin-right: auto; display: block; width: 640px; height: 480px"/>

</p>












<h3>Immersion</h3>
<p id="paperbox"> 
  Now the game is running. Within the first seconds <i>Build</i> shines with, in order: <br/>
    <ul>
      <li>Sloped floors.</li>
      <li>Realistic environments.</li>
      <li>Free fall.</li>
      <li>Feeling of true 3D.</li>
    </ul>
    <p>
      The last point is probably what struck players the most in 1996. 
      The level of immersion experienced was unprecedented. Even when
the technology reached its limit because of 2D maps, Todd Replogle and Allen Blum implemented "sector effectors" allowing to teleport the
player and improve the feeling of evolving in a three dimensional world. This feature is used in the legendary "L.A Meltdown" map:<br/>
<br/>

When the player jumps in the ventilation shaft:<br/>
<p>
<div id="box">
  <img src="../lazy_load/grey.gif" data-original="/fd_proxy/duke3d/duke_top_roof.png" 
  style=" box-shadow: rgb(119, 119, 119) 3px 3px 3px; margin: 10px 10px 10px 0px; width:491px ; height:380px;"/>
  <img src="../lazy_load/grey.gif" data-original="/fd_proxy/duke3d/level1_map.png" 
  style="box-shadow: rgb(119, 119, 119) 3px 3px 3px; margin: 10px 10px 10px 0px; width:506px ; height:380px;"/><br/>
</div>
                                                                                                  <br/>
A sector effectors triggers and teleports the player at a totally different location on the map just before "landing" :<br/>
<div id="box">
  <img src="../lazy_load/grey.gif" data-original="/fd_proxy/duke3d/duke_post_jump.png" 
  style=" box-shadow: rgb(119, 119, 119) 3px 3px 3px; margin: 10px 10px 10px 0px; width:491px ; height:380px;"/>
    <img src="../lazy_load/grey.gif" data-original="/fd_proxy/duke3d/duke_map_post_jump.png" 
  style="box-shadow: rgb(119, 119, 119) 3px 3px 3px; margin: 10px 10px 10px 0px; width:506px ; height:380px;"/><br/>

</div>
<br/>
<u><b>Trivia :</b></u> Ever since, 3D engines have tried to improve immersion with better graphics. Things may take a 
new direction with the release of the Virtual Reality device "<a href="https://fabiensanglard.net/vr_headset/index.php">The Oculus Rift</a>".
<br/>
<br/>
Great games age nicely and Duke Nukem is no exception: Twenty years later the game is still incredibly fun to play. Except now we can start digging in the source!
<div style="clear:both;">

</p>













<br/>
<h3>Engine Library Overview</h3>

<img src="../lazy_load/grey.gif" data-original="/fd_proxy/duke3d/engine_archi.png" style="margin-right: 20px;
 float:left; display: block; width: 305px; height: 215px"/>

 <p id="paperbox">
The engine code is in one file of 8503 lines with 10 master functions (<code>Engine.c</code>) and two auxiliary files:
<div>
<ul style="margin-left:320px;">
<li>
<code>cache1.c</code>: Contains the virtual filesystem (sic) and the cache system routines.</li>
<li>
<code>a.c</code>: A C reverse-engineered implementation of what used to be highly optimized x86 assembly. 
It works but is a monstruous pain in the ass to read :( !
</li>
</ul>
</div>
<p>                                                                                                                                                             <p>
Three translation units and few functions makes the high level architecture
 hard to comprehend. Unfortunately this is not the only difficulties a reader will face.<br/>
<br/>
As full page is dedicated to the engine: <a href="build_engine_internals.php"><i>Build</i> Engine Internals.</a> <br/>                                                                                                                

<div style="clear:both;"></div>
</p>
                                                                                                          
<br/>                                                                                                          
<h3>Game Module Overview</h3>
  <img src="../lazy_load/grey.gif" data-original="/fd_proxy/duke3d/game_archi.png" style="margin-right: 20px;
 float:left; display: block; width: 306px; height:431 px"/>
<p id="paperbox">


  <br/>
The game module is built completely on top of the Engine module, the way an operating system's system calls are used by a process: Anything the game
does is done thought <i>Build</i> (drawing, loading assets, filesystem, caching system, ...). 
The only exception is the sounds/music system which <i>Game</i> completely owns.
<br/><br/>
Since I was mostly interested in the engine I did not read it in depth. 
But it shows more experience and organization: 15 files divide the source into clear modules.  
It even features a <code>types.h</code> (precursor of <code>stdint.h</code>) in order to improve portability.<br/>
<br/>
A few interesting things :
<ul  style="margin-left:320px;">
   <li><code>game.c</code> is a beast featuring 11,026 lines of code.</li> 
   <li><code>menu.c</code>" features a 3000 lines "switch case".</li>
   <li>Most methods have "void" parameters and return "void". Everything goes via global variables.</li>
   <li>Methods naming does not use camelCase or NAMESPACE prefix.</li>
   <li>Features a neat parser/lexer even though token values are 
    <a target="github" href="https://github.com/fabiensanglard/chocolate_duke3D/blob/master/Game/src/gamedef.c#L459">passed via decimal</a>
     values instead of <a href="https://github.com/fabiensanglard/chocolate_duke3D/blob/master/Game/src/gamedef.c#L52"><code>#define</code></a>.</li>
</ul>
<p>
Overall this part code is easy to read and understand.

<div style="clear:both;"></div>
</p>

<h3>Source code legacy</h3>
<p id="paperbox">
Looking at the innumerable ports that spawned Doom/Quake, I was always puzzled to see so few ports of
 Duke Nukem 3D. The same question arose when the engine was ported to OpenGL only when Ken Silverman decided
 to do it himself.<br/>
 <br/>Now that I have looked at the code I can risk an explanation in a
dedicated page: <a href="code_legacy.php">The legacy of Duke Nukem 3D source code.</a>
</p>


<h3>Chocolate Duke Nukem 3D</h3>
<p id="paperbox">
Admiring the engine and loving the game so much, I could not let things this way: 
I started <a href="https://github.com/fabiensanglard/chocolate_duke3D">Chocolate Duke Nukem 3D</a>, a port of the Vanilla source code 
  with two goals in mind:
  <ul>
      <li>Education: Easy to read/understand and very portable.</li>
      <li>Fidelity: The gaming experience should be similar to what ran in 1996 on our 486s.</li>
  </ul>
<p>
I hope this inntiative will help the code to find a new legacy. The key modifications are described in <a href="chocolate_duke_nukem_3D.php">
Chocolate Duke Nukem 3D page</a>.
</p>

<h3>Recommended readings</h3>
<p id="paperbox">
None. Go rock climbing: It is awesome !<br/>
If really you insist, read <a href="id&#32;as&#32;Super-Ego-&#32;The&#32;Creation&#32;of&#32;Duke&#32;Nukem&#32;3D.pdf">id as Super-Ego: The Creation of Duke Nukem 3D</a>
</p>
<!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

