<script type="text/javascript">
  var disqus_identifier = "Learning_Hardware";
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Learning Legendary Hardware"/>
		<meta name="Description" content="Learning Legendary Hardware"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>Learning Legendary Hardware</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       October 7th, 2013</div>
   <h1>Learning Legendary Hardware</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="boing_tag2.png" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         
    
    <style>

 .comment{color: rgb(66,135,65);}
 .keyword{color: rgb(182,16,162);}
 .literal{color: rgb(218,37,36);}

 .include{color: rgb(117,85,119);}

 .numbers{color: rgb(96,0,205);}

h4 {
 
  border-bottom: 0px;
  font-size: 15px;
}

  pre{
    font: 12px courrier,monospace;
  }
 </style>
If you love software, you also try to understand the hardware to the deep down. It is not an 
easy task : There are many great programming books but few that explains hardware very well (as Michael Abrash <a href="http://www.phatcode.net/res/224/files/html/ch13/13-01.html">once wrote</a>: the Intel Documentation is "slightly more fun to read than the phone book"). In my quest
for knowledge, I found two hardware books to be outstanding:
<ul>
  <li><a href="http://www.amazon.com/Code-Language-Computer-Hardware-Software/dp/0735611319/ref=sr_1_1?ie=UTF8&qid=1358293457&sr=8-1&keywords=code+hidden+language">Code: The Hidden Language of Computer Hardware and Software</a>.</li>
  <li><a href="http://www.amazon.com/Computer-Organization-Design-Fourth-Architecture/dp/0123747503/ref=sr_1_1?s=books&ie=UTF8&qid=1358293499&sr=1-1&keywords=computer+organization+and+design">Computer Organization and Design</a>.</li>
  
</ul>

  Those books are good for "current" hardware but there is a lot to learn from previous generations. The cult machine <a href="http://spectrum.ieee.org/computing/hardware/amiga-the-computer-that-wouldnt-die">
That Wouldn't Die</a>, the Amiga with its elegant co-processor architecture is a vivid example:<br/>
<div style="clear:both;"></div>
<img src="amiga_architecture.png" style="margin-top:20px;display:block; margin-left:auto; margin-right:auto;"/><br/>
<br/>
Some parts were so good that Future Crew devteam wrote an <a href="../second_reality/second_reality_dis.php">Amiga Copper emulator for PC</a> in order to produce the legendary <a href="../second_reality/index.php">Second Reality</a>. But ultimately, its greatest asset (a small CPU with dedicated co-processors) became its greatest liability when it proved "uniquely unsuited to run DOOM".<br/>
<br/>
Older hardware are much simpler (the Atari 2600 did not even have a framebuffer). That simplicity lowers the learning curve and is less likely to discourage beginners. I consider them a good starting point before learning superScalared-cachelined-SMPed-MESIed-systems.<br/>
<br/>
A few dedicated engineers have documented those legendary machines by de-constructing the greatest applications they used to run.
<a href="http://mitpress.mit.edu/books/series/platform-studies">MIT Press</a> book editor has opened 
a <a href="http://platformstudies.com/examples.html">Platform Studies</a> section for them and they are incredibly pleasant to read:<br/>
<br/>
<br/>
<div style="width:100%;display:block;text-align:center;">
 
  <a href="http://www.amazon.com/The-Future-Was-Here-Commodore/dp/0262017202/ref=sr_1_1?ie=UTF8&qid=1381099473&sr=8-1&keywords=the+future+was+here"><img src="future-was-here-the-commodore-amiga.jpg" style="margin-right: 25px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/></a>
  <a href="http://www.amazon.com/Racing-Beam-Computer-Platform-Studies/dp/026201257X/ref=sr_1_1?ie=UTF8&qid=1381099490&sr=8-1&keywords=racing+the+beam"><img src="9780262012577.jpg" style="margin-right: 25px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/></a>
  <a href="http://www.amazon.com/Commodore-Company-Edge-Brian-Bagnall/dp/0973864966/ref=sr_1_1?ie=UTF8&qid=1381099504&sr=8-1&keywords=commodore+on+the+edge"><img src="on_the_edge.jpg" style="margin-right: 25px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/></a>
  <a href="http://www.amazon.com/Commodore-Amiga-Years-Brian-Bagnall/dp/0973864990/ref=sr_1_1?ie=UTF8&qid=1381099516&sr=8-1&keywords=commodore+the+amiga+years"><img src="commodore.png" style="margin-right: 25px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/></a>
  <a href="http://www.amazon.com/Codename-Revolution-Nintendo-Platform-Studies/dp/026201680X/ref=sr_1_1?ie=UTF8&qid=1381099458&sr=8-1&keywords=codename+revolution"><img src="9780262016803.jpg" style="margin-right: 25px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/></a><br/>
  <br/>
</div>
    <div style="clear:both;"></div>
</p>




<h2>The Future Was Here: The Commodore Amiga</h2>
<p>
  <a href="http://www.amazon.ca/The-Future-Was-Here-Commodore/dp/0262017202">
The Future Was Here: The Commodore Amiga</a> takes the most iconic applications of the Amiga in order to progressively explain the overall architecture :<br/>
<br/>
<img src="amiga_architecture.png" style="display:block; margin-left:auto; margin-right:auto; width:603px;height:369px;"/>
<div style="display:block; text-align:center; width:100%; font-size:92%;"><u>The Amiga 1000 hardware architecture</u></div>
<br/>
 <br/>
 <img src="boing.png" style="float:left; margin-right: 25px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
Chapter one is all about the legendary <a href="http://www.youtube.com/watch?v=qwFbWkr71wA&t=129">Boing</a> demo. It explains :
<ul style="overflow: auto;">
  <li>The Bitplanes based Display system.</li>
  <li>Denise ViewPort.</li>
  <li>Denise capability to set bitplane offset individually.</li>
  <li>Paula Sound chip.</li>
</ul> 
<u><b>Bonus :</b></u> Check out the <a href="http://www.youtube.com/watch?v=cJcO628yCcU">Making-off video</a>.
<div style="clear:both;"></div>
  <br/>
  <img src="deluxePaint.png" style="float:right; margin-right: 25px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
The book then switch to Deluxe Paint internals and  demonstrates :
<ul style="overflow: auto;">
   <li>The different graphic modes available (including EHB).</li>
   <li>Agnus DMA Blittering.</li>
   <li>Agnus Copper chip.</li>
   <li>Difference between Fast RAM / Chip RAM.</li>
   
</ul>
<div style="clear:both;"></div>
</p>

<img src="juggler.gif" style="float:left; margin-right: 25px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
Next is the Juggler which is a base to describe :
<ul style="overflow: auto;">
   <li>The Amiga HAM graphic mode allowing 4096 colors on screen: A late hack that proved paramount for raytracers and digital photography.</li>
 </ul>
<p>
   I won't spoil the rest but the list goes on an on, including the genlock so instrumental to the <a href="http://www.youtube.com/watch?v=GTb6zX7Hd5I">rotoscoping used in Another World</a>, AmigaOS, The DemoScene (with a strong emphasis on the beloved Copper) and an in-depth analysis of a Shmup :
   <a href="http://www.youtube.com/watch?v=eXBpMCVicic">Menace</a> that featured hardware collision detection.<br/>
<br/>
The final chapter "The way the future Was" takes an interesting point of view on the end of the Amiga. Instead of the usual Commodore blaming, the author points towards the innovative design of the machine itself and its inability to run...DOOM.
  <div style="clear:both;"></div>
</p>


<br>
<h2>Racing the Beam</h2>
<p>
  If you think programming those days is hard, think of the Atari VCS architecture: 128 bytes of RAM, 
  one color per sprite scanline and NO framebuffer (you had to pace your renderer to the TV electron beam).<br/>
  <br/>
  <img src="atari_architecture.png" style="display:block; margin-left:auto; margin-right:auto;width:460x;height:407px;"/>
  <div style="display:block; text-align:center; width:100%; font-size:92%;"><u>The Atari 2600 hardware architecture</u></div>
  <br/>
  <a href="http://www.amazon.com/Racing-Beam-Computer-Platform-Studies/dp/026201257X/ref=sr_1_1?ie=UTF8&qid=1381099490&sr=8-1&keywords=racing+the+beam">Racing the Beam: The Atari Video Computer System</a> is a great book which explains the Atari 2600 hardware via six games deconstructions: 
  <ul>
    <li><a href="http://www.youtube.com/watch?v=3m86ftny1uY">Combat</a></li>
    <li><a href="http://www.youtube.com/watch?v=sdZahXk-e9Y">Adventure</a></li>
    <li><a href="http://www.youtube.com/watch?v=HL2p2ANFlQ4">Pac-Man</a></li>
    <li><a href="http://www.youtube.com/watch?v=pvjajVf3BEc">Yar's Revenge</a></li>
    <li><a href="http://www.youtube.com/watch?v=MhXMYw1lXY0">PitFall!</a></li>
    <li><a href="http://www.youtube.com/watch?v=6SkWIPKFrxk">Star-Wars: The empire Strikes Back</a></li>
  </ul>
  The many tricks and the backstories of the machine and games are mesmerizing.<br/>
  <br/>
  As a Bonus, read Landon Dyer (Dadhacker)'s blog about the post 2600 story of Atari: <a href="http://www.dadhacker.com/blog/?p=995">The Atari ST (part 1)</a>, <a href="http://www.dadhacker.com/blog/?p=1000">The Atari ST (part 2)</a> and <a href="http://www.dadhacker.com/blog/?p=987">Donkey Kong and Me</a>.
</p>

<br>
<h2>Codename Revolution: The Nintendo Wii Platform</h2>
<p>
  Not very technical (although it details the Wii Remote greatly), it translates well the deliberated "Power isn't everything" of the Wii.
</p>



<h2>Commodore: A Company on the Edge</h2>
<p>
  Note focused on the technical side either but featuring the key events of the history of Commodore, from MOS Technology to The Fall in 1992-1994.
  A great follow up if you enjoyed "The Future was Here".
</p>

<h2>Commodore: The Amiga years</h2>
<p>
  A book dedicated to the Amiga that unfortunately keep on being delayed :( ! Let's keep on hoping.
</p>

<br>
<h2>Recommended Readings</h2>
<p>
  <div style="width:100%;display:block;text-align:center;">

  <a href="http://www.amazon.com/The-Future-Was-Here-Commodore/dp/0262017202/ref=sr_1_1?ie=UTF8&qid=1381099473&sr=8-1&keywords=the+future+was+here"><img src="future-was-here-the-commodore-amiga.jpg" style="margin-right: 25px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/></a>
  <a href="http://www.amazon.com/Racing-Beam-Computer-Platform-Studies/dp/026201257X/ref=sr_1_1?ie=UTF8&qid=1381099490&sr=8-1&keywords=racing+the+beam"><img src="9780262012577.jpg" style="margin-right: 25px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/></a>
  <a href="http://www.amazon.com/Commodore-Company-Edge-Brian-Bagnall/dp/0973864966/ref=sr_1_1?ie=UTF8&qid=1381099504&sr=8-1&keywords=commodore+on+the+edge"><img src="on_the_edge.jpg" style="margin-right: 25px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/></a>
  <a href="http://www.amazon.com/Commodore-Amiga-Years-Brian-Bagnall/dp/0973864990/ref=sr_1_1?ie=UTF8&qid=1381099516&sr=8-1&keywords=commodore+the+amiga+years"><img src="commodore.png" style="margin-right: 25px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/></a>
   <a href="http://www.amazon.com/Codename-Revolution-Nintendo-Platform-Studies/dp/026201680X/ref=sr_1_1?ie=UTF8&qid=1381099458&sr=8-1&keywords=codename+revolution"><img src="9780262016803.jpg" style="margin-right: 25px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/></a><br/>
 </div>
  <br/>
  <p>
  <b>Bonus :</b> The PDF explaining cachelined-SMPed-MESIed-systems <a href="whymb.2010.06.07c.pdf">Memory Barriers: a Hardware View for Software Hackers</a> like if you were five.
  </p>
</p>



    
  <!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

