<script type="text/javascript">
  var disqus_identifier = "shmup";
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="iPhone 3D engine, openGL ES 1.1, openGL ES 2.0, bumpMapping, shadowMapping, tutorial, specularMapping, Source Code"/>
		<meta name="Description" content="Iphone 3D engine"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>SHMUP, the best iPhone/iTouch/iPad shoot'em up</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       October 19th, 2010</div>
   <h1>Shmup</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="shmup.jpg" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         	
	<style> 
table.credits { width:70%; a:link:color:rgb(0, 136, 204);}
table.credits thead { background:transparent; }
table.credits th { white-space:nowrap; }
table.credits thead th { border-left:1px solid #ccc;  border-top:1px solid #ccc; padding:9px 9px 3px; color:#999; }
table.credits tbody th,
table.credits tbody td { border-top:1px solid #ccc; padding:6px 9px; }
table.credits tbody th { padding:7px 0 7px 0; text-align:center; color:#999; }
table.credits tbody th b { color:#333; font-weight:normal; }
 
table.credits tbody td { border-left:1px solid #ccc; width:182px; }
table.col3 tbody td { width:248px; }
table.col2 tbody td { width:382px; }
table.credits tbody .session { background:#d4e6fa url(session_bgblue.png) repeat-x 0 0; }
table.credits tbody .session.alt { background:#e9ecf0 url(session_bggray.png) repeat-x 0 0; }
table.credits tbody .session h3 { font-size:1em; margin-bottom:0; color:rgb(0, 136, 204); }
table.credits tbody .session .hud-content { display:none; }
 
div .box { padding:0 25px; width:850px; background:#f7f7f7 url(box_bg.gif) repeat-y 0 0; }
	</style> 

	"SHMUP" is the name of a multiplayer 3D shoot'em up I wrote for iOS platform (iPhone/iPad/iTouch). I couldn't find a decent 3D shooter on the AppStore so I decided to write a game that I would enjoy. The goal was to produce a gorgeous, instant fun game that would run on iOS, PC and xBox360. Its 3D engine was crafted with C, passion and a bit of assembly to deliver an incredible 60 frames per seconds on any platform.  <br/>
<br/>
<br/>
<u>March 14, 2001:</u> SHMUP has received a stellar review from <code>shmupemall.com</code>, you can read the article <a href="http://forum.shmupemall.com/viewtopic.php?f=5&t=617&sid=3b431e34a51d477071d0d0ecd8ec60df">here</a> (archive <a href="Archive.zip">here</a>).<br/>
<br/>
<div style="clear:both;"></div>


<h3>Link to AppStore</h3>
	
	<p id="paperbox">
		<br/>
<a href="http://itunes.apple.com/us/app/shmup/id337663605?mt=8"><img src="appStoreP1.jpg" style="margin-left: auto; margin-right: auto; display: block; box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/></a>

 <br/><br/>
A lot of efforts were made and time spent thinking the 3D engine, the gameplay and the ships (here is an example of one of the many concept arts for the <u>HAB</u>: Heavy Armored Bomber) :<br/>
<br/>
<a href="http://itunes.apple.com/us/app/shmup/id337663605?mt=8">
	<img src="appStoreHAB.jpg" style="margin-left: auto; margin-right: auto; display: block; box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/></a>

 <br/><br/>
I hope you will enjoy it ;) !
			</p>
<br/>



<h3>Screenshots</h3>
	
	<p id="paperbox">
		
		<a  href="../fd_proxy/shmup/scene00001_t=04033.png">
	    <img style="box-shadow: rgb(119, 119, 119) 3px 3px 3px;" src="../fd_proxy/shmup/scene00001_t=04033.jpg"/></a>
		
		&nbsp;
		<a  href="../fd_proxy/shmup/scene00002_t=71250.png">
	    <img style="box-shadow: rgb(119, 119, 119) 3px 3px 3px;" src="../fd_proxy/shmup/scene00002_t=71250.jpg"/></a>
&nbsp;
<a  href="../fd_proxy/shmup/scene00002_t=30433.png">
	    <img style="box-shadow: rgb(119, 119, 119) 3px 3px 3px;" src="../fd_proxy/shmup/scene00002_t=30433.jpg"/></a>

		&nbsp;
		<a  href="../fd_proxy/shmup/scene00001_t=70633.png">
	    <img style="box-shadow: rgb(119, 119, 119) 3px 3px 3px;" src="../fd_proxy/shmup/scene00001_t=70633.jpg"/></a>
		&nbsp;
		<a  href="../fd_proxy/shmup/scene00001_t=55266.png">
	    <img style="box-shadow: rgb(119, 119, 119) 3px 3px 3px;" src="../fd_proxy/shmup/scene00001_t=55266.jpg"/></a>

<br/><br/><br/>
	</p>

<h3>Video</h3>

	<p id="paperbox">
<table cellspacing="0" cellpadding="0" border="0" style="width:100%;"><tr><td align="center"> 

<video width="320" height="480" preload="none" poster="../fd_proxy/shmup/scene00002_t=71250.png" controls>
  <source src="../fd_proxy/shmup_wip/shipped/iphone/act1.mov" type="video/mp4">
  Your browser does not support the video tag.
</video>
</td></tr></table> 
	</p>

<h3>Credits</h3>
	<br/>
	<p id="paperbox">
&nbsp;I worked on "SHMUP" for more than 18months but plenty of people contributed at some point. Here is the list of people that were significantely involved.<br/>
 <br/>
<table align="center" style="background-color: white;" class="credits" cellspacing="0" cellpadding="0" border="0"  a:link:color:rgb(0, 136, 204);">
<tbody>
<tr><td colspan="2" style=" border-right:1px solid #ccc;" align="center"><b>Credits</b></td></tr>
<tr><td >Producer </td><td align="center" style=" border-right:1px solid #ccc;">Fabien Sanglard</td></tr>
<tr><td >3D engine and code </td><td align="center" style=" border-right:1px solid #ccc;">Fabien Sanglard </td></tr>
<tr><td >Graphics </td><td align="center" style=" border-right:1px solid #ccc;">Fabien Sanglard </td></tr>
<tr><td ">Music</td><td align="center" style=" border-right:1px solid #ccc;">Future Crew</td></tr>
<tr><td colspan="2" style=" border-right:1px solid #ccc;">&nbsp;</td></tr>
<tr><td ">3D artists</td><td align="center" style=" border-right:1px solid #ccc;">Phil Walker</td></tr>
<tr><td "></td><td align="center" style=" border-right:1px solid #ccc;">Mike Jensen</td></tr>

<tr><td "></td><td align="center" style=" border-right:1px solid #ccc;">Sean Weisman</td></tr>
<tr><td colspan="2" style=" border-right:1px solid #ccc;">&nbsp;</td></tr>

<tr><td style=" ">Special Thanks</td><td align="center" style=" border-right:1px solid #ccc;"  align="center">Jeremy Vernet</td></tr>
<tr><td style=""></td><td align="center" style="border-right:1px solid #ccc;"  align="center">Soojin Yi</td></tr>
<tr><td style="border-bottom:1px solid #ccc; "></td><td align="center" style="border-bottom:1px solid #ccc; border-right:1px solid #ccc;"  align="center">Aurelien Sanglard</td></tr>
<!--
<tr><td "></td><td align="center" style=" border-right:1px solid #ccc;">Aurelien Sanglard</td></tr>

<tr><td style="border-bottom:1px solid #ccc;" ></td><td </td
--></tr>
</tbody>
</table>
	</p>

<h3>Music</h3>
	
	<p id="paperbox">
	The music may sound familiar to oldschoolers. It comes from one of the greatest hack of all time: "Second Reality" by Future Crew. Yes a deal was signed so I could use the music.
	</p>

<h3>Technique</h3>

	<p id="paperbox">
I will be writing several technical entries in the next months, a few things that will be covered:
<ul>
<li>IPhone video generation.</li>
<li>How the visible surface determination is performed.</li>
<li>Memory management</li>
<li>The choice of the language: C vs C++.</li>
<li>Genesis.</li>
</ul>
	</p>






	
<!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

