<script type="text/javascript">
  var disqus_identifier = "Mykaruga";
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Java, LWJGL, OpenGL, OpenGL Binding, Timer, tick, LWJGL sprite animation"/>
		<meta name="Description" content="Prototyp Proof of concept using Java OpenGL Binding LWJGL"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>MyKaruga</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       August 10th, 2008</div>
   <h1>Java .OBJ loader</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="ObjLoaderMini.png" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         

For the next game in C++, I wrote an OBJ Loader. I decided to port it to JAVA and used my favorite Java OpenGL binding for rendition: LWJGL.
<div style="clear:both;"></div>
			</p>

	
	<h3>Try it and Source Code</h3>
			
			<p id="paperbox">
				
					<ul>
						<li><a href="javawavefrontloader.jnlp">Try it</a>(JNLP).</li>
						<li><STRIKE>Source Code</STRIKE>. The loader has became quit popular, <b>Victor Martin</b> from pixelnerve.com will now maintain it. The source Code is <a href="http://www.pixelnerve.com/processing/libraries/objimport/">here</a>.</li>
						</ul>
				
			</p>
			

			<h3>Features
			</h3>
			
			<p id="paperbox">
				This Java OBJ Loader support:
					<ul>
						<li> Groups </li>
						<li> Vertex, Normal, Texture coordinate</li>
						<li> MTL (material) references.</li>
						<li> Texture Loading (including Alpha for PNG)</li>
						<li> LWJGL Rendition with DisplayList </li>
					</ul>
					<br/>	
			</p>
			<p id="paperbox">	
					
				This Java OBJ Loader DOES NOT support:
					<ul>
						<li> Relative vertex references. </li>
						<li> Anything other than GL_TRIANGLE and GL_QUAD polygons</li>
					</ul>
					
			</p>
			



			<h3>How-To
			</h3>
			
			<p id="paperbox">
				I extracted the Ikaruga Models to test this loader. If anybody wonder how to do it, this is what you need:
				<ul>
						<li>An Ikaruga CD (DreamCast prefered)</li>
						<li>A PVR viewer (PVR is the texture format in the dreamcast) ( Use <a href="tools/Pvr2Png.exe">Pvr2png</a> for batch conversion and <a href="tools/PVRViewer.rar">PVRViewer</a> for special files). A bit or reading about the Sega PVT GBIX format: <a href="tools/segaPVRFormat.txt">here</a></li>
						<li>A PVM decompressor (PVR files are stored inside PVM archives). <a href="tools/pvmupk.exe">pvmupk</a> will do the job.</li>
						<li>A NJ (Sega/DreamCast format object model format, AKA Ninja) reader. I used Exmldnet, but their version is bugged (texture names are truncated among other things). As they were kind enough to publish the source code, I fixed it. Fix was sent but there is no update, so in the meantime you can download the latest version from <a href="ExMldNet.zip">here</a>.</li>
						<li>A lot of enthousiasm ;) !</li>																			
				</ul>
			</p>
			






			<h3>Screenshots
			</h3>
			
				<p id="paperbox">
					In case you wonder, the kanji on the right in each screenshot mean "Never give up"...
				
			<br/>

			<a href="ScreenShot4.png" style="float : left; margin : 5px;">
				<div class="img-wrapper">
					<div>
						<img src="ScreenShot4Mini.png"/>
					</div>
				</div>
			</a>
			<a href="ScreenShot5.png" style="float : left; margin : 5px;">
				<div class="img-wrapper">
					<div>
						<img src="ScreenShot5Mini.png"/>
					</div>
				</div>
			</a>
			<a href="ScreenShot6.png" style="float : left; margin : 5px;">
				<div class="img-wrapper">
					<div>
						<img src="ScreenShot6Mini.png"/>
					</div>
				</div>
			</a>
			<div style="clear:both;"></div>
</p>
<!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

