<script type="text/javascript">
  var disqus_identifier = "timer_and_framerate";
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Game timers: Issues and solutions, variable framerate"/>
		<meta name="Description" content="Game timers: Issues and solutions, variable framerate"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>Game timers: Issues and solutions of variable framerate</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       December 25th, 2012</div>
   <h1>Game timers: Issues and solutions.</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="time.png" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         When I started game programming I ran into an issue common to most aspiring game developers: The naive infinite loop resulted in 
variable framerate and variable time difference that made the game <b>nondeterministic</b>.  It is a problem 
that Supreme Commander/Demigod developer Forrest Smith described well in
<a href="http://www.forrestthewoods.com/synchronous-rts-engines-and-a-tale-of-desyncs/">Synchronous Engine Architecture</a> (<a href="http://www.altdevblogaday.com/2011/07/09/synchronous-rts-engines-and-a-tale-of-desyncs/">mirror</a>).<br/>
<br/>
Since I came up with a simple solution in my <a href="https://itunes.apple.com/us/app/shmup-lite/id407588246?mt=8">last engine</a> I wanted to share it here: Maybe it will save a few hours to someone :) !<br/>
<div style="clear:both;">

<h3>Problem: Variable framerate and Variable timeslices.</h3>
<p id="paperbox"> 

When I started engine development I used a naive game loop that would:
 <ol>
<li>Retrieve the time difference (timeslice) since the last screen update.</li>
<li>Update the world according to inputs and timeslice.</li>
<li>Render the state of the world to the screen.</li>
</ol>
	
<p>

It looked as follow :

<pre class="long">


    <span style="color:blue;">int</span> lastTime = Timer_Gettime();


    <span style="color:blue;">while</span> (<span style="color:green;">1</span>){

      <span style="color:blue;">int</span> currentTime = Timer_Gettime();
      <span style="color:blue;">int</span> <b>timeSlice</b> = currentTime - lastTime ;

      UpdateWorld(<b>timeSlice</b>);
      RenderWorld();

      lastTime = currentTime;
    }


</pre>
<br/>
<p>
<br/>
With a fast renderer the game world is updated with tiny time differences (timeslice) of  16-17 milliseconds (60Hz) and everything is fine. 
<br/>The key concept is that <u>timeslices at which the game is simulated 
are variables in size</u> :<br/>
<br/>
<img src="../lazy_load/grey.gif" data-original="variable_timeslices.png" style=" margin: 10px 10px 10px 0px; width: 692px; height: 160px; margin-left: auto; margin-right: auto; display: block;">
<br/>
This architecture does work but is limited: The weakness in the design is that simulating the world accurately is tied to having small timeslices (a.k.a high framerate).
Problems arise if the framerate drops too much: Updating at 30Hz instead of 60Hz may move objects so much that collisions are missed (In a game such as <a href="../shmup/index.html">SHMUP</a> that 
was a big problem):
<br/>
<br/>
<img src="../lazy_load/grey.gif" data-original="game_updates.png" style=" margin: 10px 10px 10px 0px; width: 661px; height: 260px; margin-left: auto; margin-right: auto; display: block;">
<br/>
<br/>
There are algorithms to palliate to this problem but this naive design has many more flaws. The fundamental difficulty is not the length of a timeslice but its variability:<br/>
<ul>

   <li>Record user inputs and replaying a game session (for debugging or entertainment) becomes difficult since the timeslice 
   	are different. This is true even if the replay machine is the machine that originally recorded the session since the operating system system calls will
   	never have the same duration.</li>
   </ul>
<p>
<br/>
<img src="../lazy_load/grey.gif" data-original="problem.png" style=" margin: 10px 10px 10px 0px; width: 776px; height: 257px; margin-left: auto; margin-right: auto; display: block;">
<br/>
<p?>
This issue can also be solved by recording the simulation time along with inputs but the game engine design is now becoming messy. Besides, there is an other issue:<ul>
<li>If your game is network based and you need to run several simulations simultaneously on different machines with identical inputs: The time slices 
	will not match and small difference will appear until the simulation on each machines are <a href="http://www.altdevblogaday.com/2011/07/09/synchronous-rts-engines-and-a-tale-of-desyncs/">out of sync</a> !</li>
</ul>
<h3>Solution: Fixed timeslices.</h3>
<p id="paperbox"> 
There is an elegant approach to fix everything at the cost of a small latency: Update the game timer at a fixed rate inside a second loop.

<pre class="long">


    <span style="color:blue;">int</span>  gameOn = 1
    <span style="color:blue;">int</span> simulationTime = 0;

    <span style="color:blue;">while</span> (<span style="color:green;">1</span>){

      <span style="color:blue;">int</span> realTime = Gettime();

      <span style="color:blue;">while</span> (simulationTime < realTime){
             simulationTime += <span style="color:green;">16</span>; <span style="color:green;">//Timeslice is ALWAYS 16ms.</span> 
             UpdateWorld(<span style="color:green;">16</span>);
      }

      RenderWorld();
    }


</pre>
<p>
This tiny change dissociates rendition and simulation as follow:
<br/>
<img src="../lazy_load/grey.gif" data-original="solution.png" style=" margin: 10px 10px 10px 0px; width: 703x; height: 183px; margin-left: auto; margin-right: auto; display: block;">
<br/>
The engine now simulates the world with <b><u>CONSTANT</u></b> timeslices, regardless of network latency/renderer performances.<br/>
<br/>
It  allows simple and elegant code for replay recording/playback, solid collisions detection system...
but most importantly it allows simulation running on different machines to be synchronized as long as the same input/random feeds are provided.<br/>
</p>
<h3>Before you patent it...</h3>
<p id="paperbox"> 
The joy of "discovering" this approach was short lived: This system is very well known in the game industry and is actually the keystone of games such as 
Starcraft II or id Software engines  !<br/>
<br/>
 
</p>
<h3>Further readings</h3>
<p id="paperbox"> 
  <ul>
    <li><a href="http://turborilla.com/timestepping/">Timestepping</a> by Peter Sundqvist </il>
    <li><a href="http://gafferongames.com/game-physics/fix-your-timestep/">Fix your timestep</a> by Glenn Fiedler: Take the idea further and also mentions interpolations.</li>
  </ul>
</p>
<h3>Merry Christmas....</h3>
<p>
  ...and Happy Hacking guys ;) !
  </p>
</div>
<!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

