    
<script type="text/javascript">
  var disqus_identifier = "Books_Algo_Datastructures";
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Algorithms and Datastructures"/>
		<meta name="Description" content="Algorithms and Datastructures"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
	
 	
		
		<title>Algorithms and Datastructures</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       Feb 13th, 2014</div>
   <h1>Algorithms and Data structures books: One size doesn't fit them all</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="icon_books_algo_datastructures.png" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         

    <!-- Add fancyBox -->
	<link rel="stylesheet" href="../fancybox/source/jquery.fancybox.css?v=2.1.5" type="text/css" media="screen" />
	<script type="text/javascript" src="../fancybox/source/jquery.fancybox.pack.js?v=2.1.5"></script>
<p>
	Over the years running this moderately popular website, I have been asked many times what is the best book
	about Algorithms and Data Structures. The answer is always "It depends" !<br/>
	<br/>
	It depends on how the programmer's brain works and what kind of notation he is comfortable with. 
	There are many flavors of mindset out there but it usually comes down to two metrics :
	<ul>
	    <li>Mathematics</li>
	    <li>Illustrations</li>
	</ul>
	<p> 
	Here are five good books that rank differently on those metrics and will fit different preferences :<br/>
	<ul>
		<li><a href="http://www.amazon.com/Algorithm-Design-Manual-Steven-Skiena/dp/1848000693/ref=sr_1_1?s=books&ie=UTF8&qid=1392328703&sr=1-1&keywords=algorithms+manual">The Algorithm Design Manual</a> by Steven S Skiena.</li>
		<li><a href="http://www.amazon.com/Computer-Programming-Volumes-1-4A-Boxed/dp/0321751043/ref=sr_1_1?s=books&ie=UTF8&qid=1392328799&sr=1-1&keywords=the+art+of+computer+programming#selectedObb=rbb_rbb_trigger">The Art of Computer Programming</a> by Donald E. Knuth.</li>
		<li><a href="http://www.amazon.com/Programming-Interviews-Exposed-Secrets-Landing/dp/1118261364">Programming Interviews Exposed</a> by John Mongan, Noah Kindler and Eric Giguere.</li>
		<li><a href="http://www.amazon.com/Algorithms-4th-Robert-Sedgewick/dp/032157351X/ref=sr_1_1?s=books&ie=UTF8&qid=1392328641&sr=1-1&keywords=algorithm">Algorithms</a> by Robert Sedgewick and  Kevin Wayne.</li>
		
		<li><a href="http://www.amazon.com/Introduction-Algorithms-Thomas-H-Cormen/dp/0262033844/ref=sr_1_1?s=books&ie=UTF8&qid=1392328730&sr=1-1&keywords=introduction+to+algorithms">Introduction to Algorithms</a> by Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest and Clifford Stein.</li>
		
	</ul>
	<div style="clear:both;"></div>
			</p>

<h2>About Mathematics</h2>
<p id="paperbox">
	If the importance of good illustrations is obvious, here is more insight about the mathematic metric:
	I first noticed it while reading <a href="http://www.amazon.com/Real-Time-Shadows-Elmar-Eisemann/dp/1568814380/ref=sr_1_1?ie=UTF8&qid=1391105083&sr=8-1&keywords=real+time+shadow">Real-time Shadows</a>.
	Near the beginning of the ouvrage, readers would come across the following line:<br/>
	<pre class="long">


		(p,q) := { r | r := p + α ( q - p) , 0 < α < 1 }    *

	</pre>
	<p>
		The author must have felt bad about it because they included a footnote :<br/>

	<pre class="long">


		* This says that the segment (p,q) consists of all points r that between p and q.

	</pre>
	<p>
		<br/>
		The footnote was raising the question: When should we describe something with mathematics instead of words ?
		When is is better for the reader ? There is no absolute answer because some people prefer the mathematic form while others prefer the English
		form. <br/>
		<br/>
		<u><b>Trivia :</b></u> <a id="rts" href="real-time-shadows.jpg">Here is the page</a> in question just for reference.<br/>
		<br/>
		Over the years I have found that there are two kinds of programmers :
		<ul>
			<li>Those that can use mathematics notation.</li>
			<li>Those that are confused and furthermore discouraged by mathematic notation.</li>
		</ul>
	<p>
		I used to attribute dislike of mathematics to laziness but I changed my mind: Some people have different brains and respond
		differently to "mathematicness". Try to learn yourself and acknowledge how your brain likes to have things explained.
		<script type="text/javascript">
	$(document).ready(function() {
	    $("#rts").fancybox({
	          helpers: {
	              title : {
	                  type : 'float'
	              }
	          }
	      });
    });
	</script>
	</p>

<br/>
<h2>Programming Interviews Exposed</h2>
<p id="paperbox">
	<a id="single_1" href="books/programming_interview_exposed.jpg" >
	<img src="books/thumb_programming_interview_exposed.jpg" style="float:left; margin-right: 15px; margin-top:10px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
	</a>
	<script type="text/javascript">
	$(document).ready(function() {
	    $("#single_1").fancybox({
	          helpers: {
	              title : {
	                  type : 'float'
	              }
	          }
	      });
    });
	</script>

	Programming Interviews Exposed is a slim book that can be read within a few hours. No mathematic notation and few drawing:It doesn't cover a lot but provides enough to look good during an interview.<br/>
	<a id="inter1" href="snippets/inter1.png"><img src="snippets/inter1_s.png" style="float:left; margin-right: 15px; margin-top: 15px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/></a>
<a id="inter2" href="snippets/inter2.png"><img src="snippets/inter2_s.png" style="float:left; margin-right: 15px; margin-top: 15px;box-shadow: rgb(119, 119, 119) 3px 3px 	3px;"/></a>
<a id="inter3" href="snippets/inter3.png"><img src="snippets/inter3_s.png" style="float:left; margin-right: 15px; margin-top: 15px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/></a>


 <script type="text/javascript">
	$(document).ready(function() {
	    $("#inter1").fancybox({
	          helpers: {
	              title : {
	                  type : 'float'
	              }
	          }
	      });
	     $("#inter2").fancybox({
	          helpers: {
	              title : {
	                  type : 'float'
	              }
	          }
	      });
	     $("#inter3").fancybox({
	          helpers: {
	              title : {
	                  type : 'float'
	              }
	          }
	      });
	 });
	</script>
	<div style="clear:both;"/>
</p>	

<br/>
<h2>Algorithms</h2>
<p id="paperbox">
	<a id="single_2" href="books/algorithms.jpg" >
	<img src="books/thumb_algorithms.jpg" style="float:left; margin-right: 15px; margin-top:15px; box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
	</a>
	<script type="text/javascript">
	$(document).ready(function() {
	    $("#single_2").fancybox({
	          helpers: {
	              title : {
	                  type : 'float'
	              }
	          }
	      });
	 });
	</script>

Algorithms 4th edition is a Masterpiece. It covers many topic, features many drawings, no mathematics notation and variable traces to help follow each algorithms chronology.
 Each A&D are progressively introduced with increasing complexity.<br/>
 <a id="snip_algo1" href="snippets/algo1.png"><img src="snippets/algo1_s.png" style="float:left; margin-right: 15px; margin-top: 15px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/></a>
<a id="snip_algo2" href="snippets/algo2.png"><img src="snippets/algo2_s.png" style="float:left; margin-right: 15px; margin-top: 15px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/></a>
<a id="snip_algo3" href="snippets/algo3.png"><img src="snippets/algo3_s.png" style="float:left; margin-right: 15px; margin-top: 15px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/></a>


 <script type="text/javascript">
	$(document).ready(function() {
	    $("#snip_algo1").fancybox({
	          helpers: {
	              title : {
	                  type : 'float'
	              }
	          }
	      });
	     $("#snip_algo2").fancybox({
	          helpers: {
	              title : {
	                  type : 'float'
	              }
	          }
	      });
	     $("#snip_algo3").fancybox({
	          helpers: {
	              title : {
	                  type : 'float'
	              }
	          }
	      });
	 });
	</script>
 <div style="clear:both;"/>
</p>	

<br/>
<h2>The Algorithm Design Manual</h2>
<p id="paperbox">
	<a id="single_3" href="books/Algorithm-Design-Manual.jpg">
	<img  src="books/thumb_Algorithm-Design-Manual.jpg" style="float:left; margin-right: 15px; margin-top:2px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
	</a>

	<script type="text/javascript">
	$(document).ready(function() {
	    $("#single_3").fancybox({
	          helpers: {
	              title : {
	                  type : 'float'
	              }
	          }
	      });
	 });
	</script>
	The Algorithm Design Manual is the Masterpiece from the other side: With a fair amount of mathematical notation and few illustations. Skiena war-stories are amazing and so is the HitchHiker's Guide.<br/>

<a id="algo_design1" href="snippets/algo_design1.png"><img src="snippets/algo_design1_s.png" style="float:left; margin-right: 15px; margin-top: 15px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/></a>
<a id="algo_design2" href="snippets/algo_design2.png"><img src="snippets/algo_design2_s.png" style="float:left; margin-right: 15px; margin-top: 15px;box-shadow: rgb(119, 119, 119) 3px 3px 	3px;"/></a>
<a id="algo_design3" href="snippets/algo_design3.png"><img src="snippets/algo_design3_s.png" style="float:left; margin-right: 15px; margin-top: 15px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/></a>


 <script type="text/javascript">
	$(document).ready(function() {
	    $("#algo_design1").fancybox({
	          helpers: {
	              title : {
	                  type : 'float'
	              }
	          }
	      });
	     $("#algo_design2").fancybox({
	          helpers: {
	              title : {
	                  type : 'float'
	              }
	          }
	      });
	     $("#algo_design3").fancybox({
	          helpers: {
	              title : {
	                  type : 'float'
	              }
	          }
	      });
	 });
	</script>

	<div style="clear:both;"/>
</p>	


<br/>
<h2>Introduction to Algorithms</h2>
<p id="paperbox">
	<a id="single_4" href="books/Clrs3.jpeg">
	<img src="books/thumb_Clrs3.jpg" style="float:left; margin-right: 15px; margin-top:33px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
	</a>
	<script type="text/javascript">
	$(document).ready(function() {
	    $("#single_4").fancybox({
	          helpers: {
	              title : {
	                  type : 'float'
	              }
	          }
	      });
	 });
	</script>
	Often used in universities (and <a id="frita" href="IMG_5755.JPG">French Engineer School</a>), It is the cold extensively covered truth with heavy mathematics
	and rare old looking drawings.<br/>

	<a id="ita1" href="snippets/ita1.png"><img src="snippets/ita1_s.png" style="float:left; margin-right: 15px; margin-top: 15px;box-shadow: rgb(119, 119, 119) 3px 3px 3px; width: 25%""/></a>
<a id="ita2" href="snippets/ita2.png"><img src="snippets/ita2_s.png" style="float:left; margin-right: 15px; margin-top: 15px;box-shadow: rgb(119, 119, 119) 3px 3px 	3px; width: 25%""/></a>
<a id="ita3" href="snippets/ita3.png"><img src="snippets/ita3_s.png" style="float:left; margin-right: 15px; margin-top: 15px;box-shadow: rgb(119, 119, 119) 3px 3px 3px; width: 25%"/></a>


 <script type="text/javascript">
	$(document).ready(function() {
	    $("#ita1").fancybox({
	          helpers: {
	              title : {
	                  type : 'float'
	              }
	          }
	      });
	     $("#ita2").fancybox({
	          helpers: {
	              title : {
	                  type : 'float'
	              }
	          }
	      });
	     $("#ita3").fancybox({
	          helpers: {
	              title : {
	                  type : 'float'
	              }
	          }
	      });
	 });
	</script>



	<script type="text/javascript">
	$(document).ready(function() {
	    $("#frita").fancybox({
	          helpers: {
	              title : {
	                  type : 'float'
	              }
	          }
	      });
	 });
	</script>
	<div style="clear:both;"/>
</p>	

<br/>
<h2>The Art of Computer Programming</h2>
<p id="paperbox">
	<a id="single_5" href="books/taocp.jpg">
	<img  src="books/thumb_taocp.jpg" style="float:left; margin-right: 15px; margin-top: 0px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
</a>
	
	</a>
	<script type="text/javascript">
	$(document).ready(function() {
	    $("#single_5").fancybox({
	          helpers: {
	              title : {
	                  type : 'float'
	              }
	          }
	      });
	 });
	</script>
	The legendary TAOCP take things to an other level: All references use a mythical machine invented for the book: The polyunsaturated computer MIX. Heavy on math. Few drawings. Gorgeous but also bad for self-esteem.<br/>
	<a id="taocp1" href="snippets/taocp1.png"><img src="snippets/taocp1_s.png" style="float:left; margin-right: 15px; margin-top: 15px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/></a>
<a id="taocp2" href="snippets/taocp2.png"><img src="snippets/taocp2_s.png" style="float:left; margin-right: 15px; margin-top: 15px;box-shadow: rgb(119, 119, 119) 3px 3px 	3px;"/></a>
<a id="taocp3" href="snippets/taocp3.png"><img src="snippets/taocp3_s.png" style="float:left; margin-right: 15px; margin-top: 15px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/></a>


 <script type="text/javascript">
	$(document).ready(function() {
	    $("#taocp1").fancybox({
	          helpers: {
	              title : {
	                  type : 'float'
	              }
	          }
	      });
	     $("#taocp2").fancybox({
	          helpers: {
	              title : {
	                  type : 'float'
	              }
	          }
	      });
	     $("#taocp3").fancybox({
	          helpers: {
	              title : {
	                  type : 'float'
	              }
	          }
	      });
	 });
	</script>




	<div style="clear:both;"/>
</p>

<!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

