<script type="text/javascript">
  var disqus_identifier = "mtg_93-94_four_Season";
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Magic The Gathering Old school: Four Seasons in SF Bay Area"/>
		<meta name="Description" content="Magic The Gathering Old School: Four Seasons in SF Bay Area"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>Magic The Gathering Old school: Four Seasons in SF Bay Area</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="https://fabiensanglard.net/" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="http://fabiensanglard.net/" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="http://fabiensanglard.net/about/">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="http://fabiensanglard.net/faq/">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="http://fabiensanglard.net/rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="http://fabiensanglard.net/rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="http://fabiensanglard.net/rss.xml" />
<div id="date">
       January 16th, 2016</div>
   <h1>Magic The Gathering Old school: Four Seasons in SF Bay Area</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="index.php"style="display:none;" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
          

<link href="../lightbox/css/lightbox.css" rel="stylesheet">
<script src="../lightbox/js/lightbox-plus-jquery.js"></script>
<script>
    lightbox.option({
      'resizeDuration': 100,
      'wrapAround': true,
      'fitImagesInViewport' : true
    })
</script>

<link rel="stylesheet" href="../js/highslide.css" type="text/css" />
<style type="text/css">
.highslide-dimming {
	background: black;
}

.closebutton {
   position: relative;
   top: -15px;
   left: 15px;
   width: 30px;
   height: 30px;
   cursor: pointer;
   background: url(../js/graphics/close.png);
   /* NOTE! For IE6, you also need to update the highslide-ie6.css file. */
}

 .screenshot{
    box-shadow: rgb(119, 119, 119) 3px 3px 3px;
    display: block;
    margin-left: auto;
    margin-right: auto;
    margin-top: 10px;
    margin-bottom: 15px;
 }
</style>

<script type="text/javascript">
    hs.graphicsDir = '../js/graphics/';
</script>

<style>
 figcaption {

font-style: italic;
font-variant: small-caps;

}
</style>




Antiquities expansion  (released in March 1994) featured a card called Mishra Factory. The first land that could turn into a man is likely 
the best card in the Old School format. It also happen to feature four different artworks: Winter, Spring, Fall and Summer: One for each of the four seasons.<br/>
<br/>
From left to right: Spring, Fall, Winter and Summer<br/>
<br/>
<a href="photos/4_seasons_flat.jpg" data-lightbox="image-1" data-title="Four Seasons Decks">
<img class="screenshot" src="photos/4_seasons_flat.jpg"/><br/>
</a>
<br/>
I always loved the Mishra Factories and they gave me an idea: Since a lot of friends want to try Old School but don't have a deck for it, 
I would built a few for them to play.
Each deck would feature a full set of a season. Each deck would represent a significant archetype of the Old School format:<br/>
<br/>
<a href="photos/4_seasons.jpg" data-lightbox="image-1" data-title="Four Seasons Decks">
<img class="screenshot" src="photos/thumbs/4_seasons.jpg"/><br/>
</a>
<br/>
<a href="photos/4_seasons_inside.jpg" data-lightbox="image-1" data-title="Four Seasons Decks">
<img class="screenshot" src="photos/thumbs/4_seasons_inside.jpg"/><br/>
</a>
<br/> So far it has been really well received: I usually bring the four decks to a friend's place and I only ask to pick a season. 
It is pretty cool way to start an evening and feel like we are back to 1993.
<br/>


<h1>Winter</h1>
<div style="float:right; margin-left:20px;">
  <a href="photos/winter.png" data-lightbox="image-1" data-title="Four Seasons Decks">
<img src="photos/thumbs/winter_small.png"/><br/>
</a>
</div>
Having lived in Canada for ten years: Winter is cold, Winter is absence of light and Winter is death. The natural color to use was Black. 
The deck started as a MonoBlack but did poorly. I morphed it into a Deadguy Ale and it was more able to deal with the three other seasons.<br/>
<br/>
<u><b>Trivia:</b></u> Do you know where the name "DeadGuy Ale" came from? 
<figure>
  <img src="photos/thumbs/dead_guy_ale.png"/>
  <figcaption>Yes, the name comes from a beer brand!</figcaption>
</figure>  
<div style="clear: both;"/>


<a href="photos/deadguyale.jpg" data-lightbox="image-1" data-title="Four Seasons Decks">
<img class="screenshot" src="photos/thumbs/deadguyale.jpg"/><br/>
</a>
<br/>

I am still debating replacing the Icy Manipulators with two fireballs. The rest of the deck is pretty solid.

<!--
<pre class="long" style="width:70%">
</pre>
-->
<div style="clear: both;"/>

As you may have read in a previous <a href="https://fabiensanglard.net/mtg_93-94_Poor_cards/index.php">article</a> I have a thing for cards with an history. 
 This desk features some of my most beat up cards. The beauty is in the eye of the beholder as people say...</br>
<br/>
<a href="photos/beatup.jpg" data-lightbox="image-1" data-title="Four Seasons Decks">
<img class="screenshot" src="photos/thumbs/beatup.jpg"/><br/>
</a>
<br/><br/>
A sexy playset of winter. Beat up. 
<br/><br/>
<img class="screenshot" src="photos/thumbs/winter_playset.jpg"/><br/>









<br/>
<h1>Summer</h1>
<div style="float:right; margin-left:20px;">
<img  src="photos/thumbs/summer_small.png"  style="margin-bottom: 12px;"  />
</div> 
Summer is sun, Summer is Life and Summer is light. It is the opposite of Winter. It had to be a White Weenie. 
You can tell how much I like this deck since it is almost full black border (sadly the Black Lotus with is CE).<br/>
<br/>
This deck went through several iterations. I came in second place in Berkley with it:<br/>
<a href="photos/ww_in_the_making.jpg" data-lightbox="image-1" data-title="Four Seasons Decks">
<img class="screenshot" src="photos/thumbs/ww_in_the_making.jpg"/><br/>
</a>
<br/>
I eventually decided to cut Balance and Army of Allah. I also replaced the Strip Mine with an extra plain since I got mana screwed a few times.
The deck intentionally runs low on mana sources and rely on land tax.<br/>
The deck is played monotonically: Drop a lot of treats very fast, remove whatever is in the way with Swords and Disenchants. As soon as the 
board is advantageous: Wipe
all the lands with Armageddon.


<div style="clear: both;"/>


<a href="photos/ww.jpg" data-lightbox="image-1" data-title="Four Seasons Decks">
<img class="screenshot" src="photos/thumbs/ww.jpg"/><br/>
</a>












<br/>
<h1>Fall</h1>
<div style="float:right; margin-left:20px;">

<a href="photos/fall.png" data-lightbox="image-1" data-title="Four Seasons Decks">
<img src="photos/thumbs/fall_small.png"/><br/>
</a>

</div>
Fall is red. The obvious deck to make was Burn. But to make it really competitive, representative of the format and also add a touch of nostalgia it had
to be a Lestree Zoo Deck. The list is not what Bertrand played originally during the first World Championship 
(<a href="https://fabiensanglard.net/mtg_93-94_Toronto/event1.php">and what we replayed in Toronto</a>). It has been modified after much playtesting.<br/>
<br/>
The Philosophy of this deck is twofolds:
<ul>
  <li>Drop a creature turn one or two. Do 4-6 damage.</li>
  <li>Finish your opponent with Lightning Bolt, Chain Lightning and Psionic Blast</li>
</ul>
While the Serendib Efreets and the Gorillas are no brainers I still question if I should have an other Ernahm Djinn instead of the Elvish Archers. 
The Whirling Devish can look bizarre but they are very good against Juzamns and can grow pretty fast against "Spring" deck.
<br/>
This desk looks strong but it has one huge weakness, called 
<!--
<a href="photos/bottle.jpg" data-lightbox="image-1" data-title="Four Seasons Decks">
<img src="photos/thumbs/bottle.jpg"/><br/>
</a>-->
City in a bottle which can  wipe out the entire first row. If the bottle doesn't come too early during the game the deck can still do well since it usually finishes 
with Burns.<br/>
<br/>
<!--
<pre class="long" style="width:70%">
</pre>
-->
<div style="clear: both;"/>
<a href="photos/zoo.jpg" data-lightbox="image-1" data-title="Four Seasons Decks">
<img class="screenshot" src="photos/thumbs/zoo.jpg"/><br/>
</a>
<br/>













<br/>
<h1>Spring</h1>
<div style="float:right; margin-left:20px;">
<img  src="photos/thumbs/spring_small.png"  style="margin-bottom: 12px;"  />
</div>
Finally was Spring: When nature comes back to live after surviving Winter. Surviving it the spirit of "The Deck" which you will face at ANY tournament you go. 
The Deck is also how I got into Old School: In 2009, before Magnus and his marvelous <a href="http://oldschool-mtg.blogspot.com/">blog</a>
I stumbled upon the pictures of a guy going old school at a Vintage event. I never got to know who played it but I was hooked instantly to the idea of playing old decks:<br/>
<br/>
<a href="photos/seed.jpeg" data-lightbox="image-1" data-title="Four Seasons Decks">
<img class="screenshot" src="photos/thumbs/seed.jpg"/><br/>
</a><br/>
<a href="photos/seed2.jpeg" data-lightbox="image-1" data-title="Four Seasons Decks">
<img class="screenshot" src="photos/thumbs/seed2.jpg"/><br/>
</a>
<br/>
<br/>
Notice he is playing a version closer to what Brian Weissman pioneered (with Moat). The version I built i as copy of <a href="http://oldschool-mtg.blogspot.no/p/n00bcon-7-top8.html">NoobCon 7 winner</a><br/>
<br/>

<a href="photos/deck.jpg" data-lightbox="image-1" data-title="Four Seasons Decks">
<img class="screenshot" src="photos/thumbs/deck.jpg"/><br/>
</a>

<!--
<pre class="long" style="width:70%">
</pre>
-->
<div style="clear: both;"/>
<br/>
This deck features a cool set of signed Cities by Mark Pool.<br/>
<br/>
<img src="photos/thumbs/cities.jpg"/><br/>
<br/>
I especially like the alter with a face in the sky where he re-purposed the sun into an eye :) !
<br/>
<a href="photos/city_alter.jpg" data-lightbox="image-1" data-title="Four Seasons Decks">
<img class="screenshot" src="photos/thumbs/city_alter.jpg"/><br/>
</a><br/>
<br/>
$40 a piece one year ago but now <a href="http://sales.starcitygames.com/carddisplay.php?product=16862">$200</a> each these days 
due to the explosion of MtG Old School community: Beta Jayemdae Tome<br/>
<br/>
<img class="screenshot" src="photos/thumbs/tomes.jpg"/><br/>
<br/>



<br/>
<h1>Let's play !!</h1>
<p>
  If you live in San Francisco Bay area I would love to play with you ! Shot me an email :) !



<!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

