<script type="text/javascript">
  var disqus_identifier = "Ghost_in_the_Wires";
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Kevin Mitnick, Ghost in The Wire, Cracking, Decyphering"/>
		<meta name="Description" content="Kevin Mitnick, Ghost in The Wire, Cracking, Decyphering"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>Cracking Kevin Mitnick's Ghost in The Wire.</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       September, 8th 2011</div>
   <h1>Solving Kevin Mitnick's Ghost in The Wires encrypted messages.</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="icon.jpg" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         
				I received today my copy of Kevin Mitnick's book: 
				<a href="http://www.amazon.com/Ghost-Wires-Adventures-Worlds-Wanted/dp/0316037702">Ghost in The Wires</a>.
				It is a great read so far. But even more interesting are the ciphered sentences at the beginning of 
				each chapters. I am trying to solve all of them but if you can contribute: comment or send me an email !<br/>
				<br/>
				<br/>
				<u>EDIT (September 11, 2011 1:04am):</u> All codes have been broken, this page is the complete solution to "Ghost in The Wires".
				<br/>
				<br/>
				<u>Post-mortem :</u> Most of the cryptograms were simple constant ROT and the program I wrote to solve them proved very efficient. The program was inspired by an excellent book by Simon Singh: 
				<a href="http://www.amazon.com/Code-Book-Science-Secrecy-Cryptography/dp/0385495323/ref=sr_1_1?ie=UTF8&qid=1316405428&sr=8-1">The Code Book: 
				The Science of Secrecy from Ancient Egypt to Quantum Cryptography"</a>. In this book Singh described how Alan Turing exploited the <i>cribs</i> 
				in Nazy Enigma encrypted messages by looking for the probable location of the german word "WETTER" ("weather" in english). The "colossus" 
				could only test 5 letters in order to find the key of the day but nowadays the raw power allowed me to test all possible rotations searching for 
				cribs in Mitnik sentences (since most seemed to be "questions": the program automatically searched for "WHAT","WHY,"WHERE" and others words usually found at the beginning of a sentence). 
				This method allowed to decrypt 50% of the messages within 30 seconds...and since the other 50% can be decrypted using the answer from the previous question:
				 Almost all cryptograms were decoded thanks to Turin's work to break Enigma....60 years ago. </a>
				<br/>
				
			</p>

<h3>The Challenge</h3><br/>
			<p id="paperbox">
				If you want to play around, here are all the ciphered strings:<br/>
				<pre  class="long">
				 
				
 char* cypheredText[] = 
 {
	/*1 SOLVED*/
	"yjcv ku vjg pcog qh vjg uauvgo wugf da jco qrgtcvqtu vq ocmg htgg rjqpg ecnnu ?",
	
	/*2 SOLVED*/
	"wbth lal voe htat oy voe wxbirtn vfzbqt wagye C poh aeovsn vojgav ?",
	
	/*3 SOLVED*/
	"Nyrk grjjnfiu uzu Z xzmv kf jvklg re rttflek fe Kyv Rib ?",
	
	/*4 SOLVED*/
	"Flle ujw esc wexp mo xsp kjr hsm hiwwcm, \"Wplpll stq lec qma e wzerg mzkk!\" ?",
    
	/*5 SOLVED*/
	"Bmfy ytbs ini N mnij tzy ns zsynq ymj Ozajsnqj Htzwy qtxy ozwnxinhynts tajw rj ?",
	
	/*6 SOLVED*/
	"Kyoo olxi rzr Niyovo Cohjpcx ojy dn T apopsy ?",
	
	/*7 SOLVED*/
	"Kvoh wg hvs boas ct hvs Doqwtwq Pszz sadzcmss kvc fsor hvs wbhsfboz asac opcih am voqywbu oqhwjwhwsq cjsf hvs voa forwc ?" ,
	
	/*8 SOLVED*/
	"Iwh xwqv wpvpj fwr Vfvyj qks wf nzc ncgsoo esg psd gwc ntoqujvr ejs rypz nzfs ?",
	
	/*9 SOLVED*/
	"Hsle td esp epcx qzc dzqehlcp mfcypo zy esp nsta esle Yzglepw dpye xp ?",
	
	/*10 SOLVED*/
	"Bprf cup esanqneu xmm gtknv amme U biiwy krxheu Iwqt Taied ?",
	
	/*11 SOLVED*/
	"Lwpi idlc sxs bn upiwtg axkt xc lwtc X bdkts xc lxiw wxb ?",
	
	/*12 SOLVED*/
	"Yhlt xak tzg iytfrfad RanBfld squtpm uhst uquwd ce mswf tz wjrwtsr a wioe lhsv Ecid mwnlkoyee bmt oquwdo't ledn mp acomt ?",
	
	/*13 SOLVED*/
	"Zkdw lv wkh qdph ri wkh SL ilup wkdw zdv zluhwdsshg eb Sdflilf Ehoo ?",
    
	/*14 SOLVED*/
	"Plpki ytw eai rtc aaspx M llogw qj wef ms rh xq ?",
    
	/*15 SOLVED*/
	"Ituot oaybmzk ymwqe ftq pqhuoq ftmf Xqiue geqp fa buow gb mzk dmpua eusmxe zqmd Qduo ?",
	
	/*16 SOLVED*/
	"Kwth qzrva rbq lcq rxw Svtg vxcz zm vzs lbfieerl nsem rmh dg ac oef'l cwamu ?",
	
	/*17 SOLVED*/
	"Epib qa bpm vium wn bpm ixizbumvb kwuxtmf epmzm Q bziksml lwev Mzqk Pmqvh ?",
	
	/*18 SOLVED*/
	"Khkp wg wve kyfcqmm yb hvh TBS oeidr trwh Yhb MmCiwus Wko ogvwgxar hr ?",
	
	/*19 SOLVED*/
	"Rcvo dn ivhz ja ocz omvinvxodji oj adiy v kzmnji'n njxdvg nzxpmdot iphwzm pndib oczdm ivhz viy yvoz ja wdmoc ?",
	
	/*20 SOLVED*/
	"Wspa wdw gae ypte rj gae dilan lbnsp loeui V tndllrhh gae awvnh \"HZO, hzl jaq M uxla nvu\"",
	
	/*21 SOLVED*/
	"4A 75 6E 67 20 6A 6E 66 20 62 68 65 20 61 76 70 78 61 6E 7A 72 20 74 76 69 72 61 20 67 62 \
	 20 47 72 65 65 6C 20 55 6E 65 71 6C 3F ",
	
	
	/*22 SOLVED*/
	"Gsig cof dsm fkqeoe vnss jo farj tbb epr Csyvd Nnxub mzlr ut grp lne ?",
	
	/*23 SOLVED*/
	"Fqjc nunlcaxwrl mnerln mrm cqn OKR rwcnwcrxwjuuh kanjt fqnw cqnh bnjalqnm vh jyjacvnwc rw Ljujkjbjb ?",
	
	/*24 SOLVED*/
	"Xvof jq qis bmns lg hvq thlss ktffb J cifsok EAJ uojbthwsbhlsg ?",
	
	/*25 SOLVED*/
	"Cngz zuct ngy znk grsg sgzkx lux znk xkgr Kxoi Ckoyy ?",
	
	/*26 SOLVED*/
	"Aslx jst rlxi bx ns wgzzcmgw UP jnsh hlrjf nyk TT seq s cojorpdw pssx gxmyeie ao bzy glc ?",
	
	/*27 SOLVED*/
	"85 102 121 114 32 103 113 32 114 102 99 32 108 121 107 99 32 109 100 32 114 102 99 32 122 109 105 113 \
	 114 109 112 99 32 71 32 100 112 99 111 115 99 108 114 99 98 32 103 108 32 66 99 108 116 99 112 63",
	
	
	/*28 SOLVED*/
	"Phtm zvvvkci sw mhx Fmtvr VOX Ycmrt Emki vqimgv vowx hzh L cgf Ecbst ysi ?",
	
	/*29 SOLVED*/
	"126,147,172,163, 040, 166,172,162, 040, 154,170, 040, 157,172,162,162,166,156,161,143, 040, 145,156,161,\
	 040, 163,147,144, 040, 115,156,165,144,153,153, 040, 163,144,161,154,150,155,172,153, 040, 162,144,161,165,\ 
	 144,161, 040, 150,155, 040, 122,172,155,040,111,156,162,144,077",
	
	/*30 SOLVED*/
	"Ouop lqeg gs zkds ulv V deds zq lus DS urqstsn't wwiaps ?",
	
	/*31 SOLVED*/
	"Alex B25 rixasvo hmh M ywi xs xli HQZ qemrjveqi ?",
	
	/*32 SOLVED*/
	"Caem alw Ymek Xptq'd tnwlchvw xz lrv lkkzxv ?",
	
	/*33 SOLVED*/
	"Ozg ojglw lzw hshwj gf AH Khggxafy lzsl BKR skcww ew stgml ?",
	
	/*34 SOLVED*/
	"Nvbx nte hyv bqgs pj gaabv jmjmwdi whd hyv UVT'g Giuxdoc Gctcwd Hvyqbuvz hycoij ?",
	
	/*35 SOLVED*/
	"2B 2T W 2X 2Z 26 36 2P 36 2V 3C W 3A 32 39 38 2Z W 3D 33 31 38 2V 36 3D W \
	2R 2Z W 3E 3C 2V 2X 2Z 2Y W 3E 39 W 2R 32 2V 2E W 2V 3A 2V 3C 3E 37 2X 38 3E \
	W 2X 39 37  3A 36 2Z 2S 1R",
	
	/*36 SOLVED*/
	"Lsar JSA cryoi ergiu lq wipz tnrs dq dccfunaqi zf oj wqpctkiel dpzpgp I jstcgo cu dy hgq ?",
	
	/*37 SOLVED*/
	"V2hhdCBGQkkgYWdlbnQgYXNrZWQgU3VuIE1pY3Jvc3lzdGVtcyB0byBjbGFpbSB0aGV51Gxvc3QgODAgbWlsbGlvbiBkb2xsYXJzPw==",
	
	/*38 SOLVED*/
	"100-1111-10-0 011-000-1-111 00-0100 1101-10-1110-000-101-11-0-1 \
	0111-110-00-1001-1-101 111-0-11-0101-010-1-101 111-10-0100 11-00-11",

 };

</pre>
<p>
			</p>
			
			
			
			
			
			
			
			
			
			
			
			
			<h3>One: Rough Start</h3><br/>
			<cite>yjcv ku vjg pcog qh vjg uauvgo wugf da jco qrgtcvqtu vq ocmg htgg rjqpg ecnnu ?</cite><br/><br/>
			<p id="paperbox">
			Looks a lot like words. And it is the first chapter so it is probably the easiest and most known cypher
			off all time: ROT-2

<pre  class="long">
					

            yjcv ku vjg pcog qh vjg uauvgo wugf da jco qrgtcvqtu vq ocmg htgg rjqpg ecnnu ?
            what is the name of the system used by ham operators to make free phone calls ?
			
			
			</pre> 
			<p>
			<u>Note :</u> There is a good tool online that also provide frequency analysis: 
			<a href="http://web.forret.com/tools/rot13.asp?">ROT-13 encrypt/decrypt (Caesar cipher)</a>. The frequency 
			distribution is consistent with a ROT encryption:<br/>
			<br/>
			<u>Edit :</u> I wrote a quick C program called CrackKevin.exe to automate ROT testing. <a href="main.c.txt">Here it is</a>. It works by testing all 26 ROT and then searching
				for keyword in the deciphered string. The <a href="output.txt">output</a> helped to identify very fast a ROT candidate and solved 
				17 out of the 38 encrypted strings ;) !<br/>
				<br/>
			<br/>
			<b><u>Answer : "autopatch"</u></b>
			<!--
			<br/>
			<div class="img-wrapper">
						<div>
							  <img src="1-analyze.jpg" />
						</div>
					</div>	
					
			<br/>
			<br/>
			<img src="1-analyze-DONE.jpg" /><br/>
			</p>
			-->
			
			
			
			<br/><br/>
			<h3>Two: Just visiting</h3><br/>
			<cite>wbth lal voe htat oy voe wxbirtn vfzbqt wagye C poh aeovsn vojgav ?</cite><br/><br/>
			<p id="paperbox">
			I am working on it.The question mark indicate that the first word has to be among:
			<pre  class="long">
			
			
        - What
        - How
        - Why
        - When
        - Where
        - Which
			
			
			</pre>
			<p>
			Since the cypher does not seem to be encoding spaces, we can conclude the first work is four letters long so it is either "what" or "when".
			Now a bit of shooting in the dark:<br/>
			<br/>
			<pre  class="long">
			
			
      WBTH - WHEN = "22,1,19,7" - "22,7,4,13" =  "0,-6,15,- 6" 
      WBTH - WHAT = "22,1,19,7" - "22,7,0,19" =  "0,-6,19,-12"
      
      If we loop on a 0-25 array (example: -6 is actually +20, 19 is 19, -12 is 14)
      
      WBTH - WHEN = "0,20,15,20" = AUPU
      WBTH - WHAT = "0,20,19,14" = AUTO			 
				 
			
			</pre>
			<p>
			Now "AUTO" is interesting because it is the beginning on the answer to the last question: "autopatch". Writing a quick <href ="vigenere.c.txt">program</a> called Vigenere.exe to 
			test this proved right. This is Vigenere keybased ROT, the rotation is not a constant value. Instead the ROT value for each letter
			comes from the key characters.<br/>
			<br/>
			
			<pre  class="long">
			
			   
          wbth lal voe htat oy voe wxbirtn vfzbqt wagye C poh aeovsn vojgav ?
        - auto pat cha utop at cha utopatc hautop atcha u top atchau topatc
        = what was the name of the central office where i was almost caught ?
			   
			
			</pre>
			<p>
			<br/>
			<b><u>Answer : "Sunset-Gower"</u></b><br/>
			<br/>
			Acknowledgment: Thanks to Krzysztof Narkowicz and Geoff Salmon for helping finding out about Vigenere cypher.<br/>
			<br/>
			<u>Edit :</u>I wrote an other C program called Vigenere.exe to speedup the Vigenere key testing process. <a href="vigenere.c.txt">Here it is</a>. And here are the <a href="outVigenere.txt">outputs</a>.
			</p>
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			<br/><br/>
			<h3>Three: Original sin</h3><br/>
			<cite>Nyrk grjjnfiu uzu Z xzmv kf jvklg re rttflek fe Kyv Rib ?</cite><br/><br/>
			<p id="paperbox">
			Solved with CrackKevin.exe ROT16 was a valid candidate:<br/>
			<br/>
			<pre  class="long">
					
			
            Nyrk grjjnfiu uzu Z xzmv kf jvklg re rttflek fe Kyv Rib ?
            What password did I give to setup an account on The Ark ?
			
			
			</pre> 
			<p>
			<u>Note :</u> It seems odd chapters are using ROT-X permutation.<br/>
			<br/>
			<b><u>Answer : "jelly"</u></b><br/>
			<br/>
			</p>
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			<br/><br/>
			<h3>Four: Escape Artist</h3><br/>
			<cite>Flle ujw esc wexp mo xsp kjr hsm hiwwcm, "Wplpll stq lec qma e wzerg mzkk!" ?</cite><br/><br/>
			<p id="paperbox">
			According to "Hateyou" from fohguild.org the quotation is for "Search his car for a logic bomb!" (a quote from the chapter).
			
			Using Vigenere.exe with key = "jelly":
			
			<pre  class="long">
			
			
          Flle ujw esc wexp mo xsp kjr hsm hiwwcm, "Wplpll stq lec qma e wzerg mzkk!"  ?
        - jell yje lly jell yj ell yje lly jellyj   ellyje lly jel lyj e llyje llyj
        = what was the name of the man who yelled, "search his car for a logic bomb!" ?
			
			
			</pre>
			<p>
			"Hateyou"'s intuition was correct. I am impressed by this.<br/>
			<br/>
			<b><u>Answer : "Steve Cooley"</u></b><br/>
			<br/>
			</p>
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			<br/><br/>
			<h3>Five: All your phone lines belong to me</h3><br/>
			<cite>Bmfy ytbs ini N mnij tzy ns zsynq ymj Ozajsnqj Htzwy qtxy ozwnxinhynts tajw rj ?</cite><br/><br/>
			<p id="paperbox">
			Solved with CrackKevin.exe: ROT5
						<pre  class="long">
					
			
            Bmfy ytbs ini N mnij tzy ns zsynq ymj Ozajsnqj Htzwy qtxy ozwnxinhynts tajw rj ?
            What town did I hide out in until the Juvenile Court lost jurisdiction over me ?
						
			</pre> 
			<p>
			<br/>
			<br/>
			<b><u>Answer : "oroville"</u></b><br/>
			<br/>
			</p>
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			<br/><br/>
			<h3>Six: Will hack for love</h3><br/>
			<cite>Kyoo olxi rzr Niyovo Cohjpcx ojy dn T apopsy?</cite><br/><br/>
			<p id="paperbox">
			Using Vigenere.exe with key = "oroville":<br/>
			<br/>
			<pre  class="long">
			
			
             Kyoo olxi rzr Niyovo Cohjpcx ojy dn T apopsy ?
           - orov ille oro villeo roville oro vi l leorov	 
           = what game did sandra lambert ask if i played ?	   
			
			</pre>
			<p>
			<br/>
			<br/>
			<b><u>Answer : "hearts"</u></b><br/>
			<br/>
			</p>
			
			
			
			
			
			
			
			
			<br/><br/>
			<h3>Seven: Hitched in Haste</h3><br/>
			<cite>Kvoh wg hvs boas ct hvs Doqwtwq Pszz sadzcmss kvc fsor hvs wbhsfboz asac opcih am voqywbu oqhwjwhwsq cjsf hvs voa forwc?</cite><br/><br/>
			<p id="paperbox">
			
			The 4 "hvs" left no doubt: ROT19 but Solved with CrackKevin.exe anyway ;) !
			
			<pre  class="long">
					
			
     Kvoh wg hvs boas ct hvs Doqwtwq Pszz sadzcmss kvc fsor hvs wbhsfboz asac opcih am voqywbu oqhwjwhwsq cjsf hvs voa forwc?
     WHAT IS THE NAME OF THE PACIFIC BELL EMPLOYEE WHO READ THE INTERNAL MEMO ABOUT MY HACKING ACTIVITIEC OVER THE HAM RADIO
						
			</pre> 
			<p>
			<br/>
			<br/>
			<b><u>Answer : "Bill Cook"</u></b><br/>
			<br/>
			</p>
						
			
			
			
			
			
			
			
			<br/><br/>
			<h3>Eight: Lex Luthor</h3><br/>
			<cite>Iwh xwqv wpvpj fwr Vfvyj qks wf nzc ncgsoo esg psd gwc ntoqujvr ejs rypz nzfs ?</cite><br/><br/>
			<p id="paperbox">
			Using Vigenere.exe with key = "billcook":
			
			<pre  class="long">
			
			
          Iwh xwqv wpvpj fwr Vfvyj qks wf nzc ncgsoo esg psd gwc ntoqujvr ejs rypz nzfs ?
        - bil lcoo kbill coo kbill coo kb ill cookbi llc ook bil lcookbil lco okbi llco
        = how much money did lenny owe me for losing the bet for cracking the door code ?
			
			
			</pre>
			<p>
			<br/>
			<b><u>Answer : "150$"</u></b><br/>
			<br/>
			</p>
			
			
			
			
			
			
			
			
			
			
			<br/><br/>
			<h3>Nine: The Kevin Mitnick Discount Plan</h3><br/>
			<cite>Hsle td esp epcx qzc dzqehlcp mfcypo zy esp nsta esle Yzglepw dpye xp ?</cite><br/><br/>
			<p id="paperbox">
			Again, the double "esp" was quite suspicious: ROT22 still Solved with CrackKevin.exe.
						<pre  class="long">
					
			
     Hsle td esp epcx qzc dzqehlcp mfcypo zy esp nsta esle Yzglepw dpye xp ?
     WHAT IS THE TERM FOR SOFTWARE BURNED ON THE CHIP THAT NOVATEL SENT ME ?
						
			</pre> 
			
			 <p>
			<br/>
			<b><u>Answer : "firmware"</u></b><br/>
			<br/>
			</p>
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			<br/><br/>
			<h3>Ten: Mystery Hacker</h3><br/>
			<cite>Bprf cup esanqneu xmm gtknv amme U biiwy krxheu Iwqt Taied ?</cite><br/><br/>
			<p id="paperbox">
			Using Vigenere.exe with key = "firmware":<br/>
			<br/>
			<pre  class="long">
			
			
             Bprf cup esanqneu xmm gtknv amme U biiwy krxheu Iwqt Taied ?
           - firm war efirmwar efi rmwar efir m waref irmewa refi rmwar
           = what guy answered the phone when i first called eric heinz ?  
			
			</pre>
			<p>
			<br/>
			<b><u>Answer : "Henry Spiegel"</u></b><br/>
			<br/>
			</p>
			
			
			
			
			
			
			<br/><br/>
			<h3>Eleven: Foul play</h3><br/>
			<cite>Lwpi idlc sxs bn upiwtg axkt xc lwtc X bdkts xc lxiw wxb ?</cite><br/><br/>
			<p id="paperbox">
			ROT-(-11)
			<pre  class="long">
					
			
     Lwpi idlc sxs bn upiwtg axkt xc lwtc X bdkts xc lxiw wxb ?
     WHAT TOWN DID MY FATHER LIVE IN WHEN I MOVED IN WITH HIM
						
			</pre> 
			<p>
			<br/>
			<b><u>Answer : "calabasas"</u></b><br/>
			<br/>
			</p>			
			
			
			
			<br/><br/>
			<h3>Twelve: You Can Never Hide</h3><br/>
			<cite>Yhlt xak tzg iytfrfad RanBfld squtpm uhst uquwd ce mswf tz wjrwtsr a wioe lhsv Ecid mwnlkoyee bmt oquwdo't ledn mp acomt ?</cite><br/><br/>
			<p id="paperbox">
			Using Vigenere.exe with key = "calabasas":<br/> 
			<pre  class="long">
					
			
     Yhlt xak tzg iytfrfad RanBfld squtpm uhst uquwd ce mswf tz wjrwtsr a wioe lhsv Ecid mwnlkoyee bmt oquwdo't ledn mp acomt ?
    -cala bas asc alabasas calabas ascala basa scala ba sasc al abasasc a laba sasc alab asascalab asa scalab a sasc al abasa 
     what was the internal pacbell system that could be used to wiretap a line that eric mentioned but wouldn't tell me about ?
						
			</pre> 
			<p>
			<br/>
			<b><u>Answer : "SAS"</u></b><br/>
			<br/>
			</p>	
			
			
			
			
			
			
			
			
			
			<br/><br/>
			<h3>Thirteen: The Wiretapper</h3><br/>
			<cite>Zkdw lv wkh qdph ri wkh SL ilup wkdw zdv zluhwdsshg eb Sdflilf Ehoo ?
			</cite><br/><br/>
			<p id="paperbox">
			 Solved with CrackKevin.exe (ROT4)
			
			 <pre  class="long">
			 
			 
       Zkdw lv wkh qdph ri wkh SL ilup wkdw zdv zluhwdsshg eb Sdflilf Ehoo ?
       what is the name of the pi firm that was wiretapped by pacific bell ?
			
			</pre> 
			<p>
			<br/>
			<b><u>Answer : "teltec"</u></b><br/>
			<br/>
			
			</p>
			
			
			
			
			
			
			
			
			
			
			<br/><br/>
			<h3>Fourteen: You Tap Me, I Tape You</h3><br/>
			<cite>Plpki ytw eai rtc aaspx M llogw qj wef ms rh xq ?	</cite><br/><br/>
			<p id="paperbox">
				Using Vigenere.exe with key = "teltec":<br/> 
			<pre  class="long">
					
			
     Plpki ytw eai rtc aaspx M llogw qj wef ms rh xq ?
    -telte cte lte cte ltect e ltect el tec te lt ec  
     where was the pay phone i asked my dad to go to ?
						
			</pre> 
			<p>
			<br/>
			<b><u>Answer : "teltec"</u></b><br/>
			<br/>
			</p>
			
			
			
			
			
			
			
			
			
			
			
			
			<br/><br/>
			<h3>Fiteen: "How the Fuck Did You Get That ?"</h3><br/>
			<cite>Ituot oaybmzk ymwqe ftq pqhuoq ftmf Xqiue geqp fa buow gb mzk dmpua eusmxe zqmd Qduo ?</cite><br/><br/>
			<p id="paperbox">
			 Solved with CrackKevin.exe (ROT21)
			
			 <pre  class="long">
			 
			 
       Ituot oaybmzk ymwqe ftq pqhuoq ftmf Xqiue geqp fa buow gb mzk dmpua eusmxe zqmd Qduo ?
       which company makes the device that lewis used to pick up any radio sigals near eric ?
			
			</pre> 
			<p>
			<br/>
			<b><u>Answer : "optoelectronics"</u></b><br/>
			<br/>
			
			</p>
			
			
			
			
			
			
			
			
			
			<br/><br/>
			<h3>Sixteen: Crashing Eric's Private Party</h3><br/>
			<cite>Kwth qzrva rbq lcq rxw Svtg vxcz zm vzs lbfieerl nsem rmh dg ac oef'l cwamu ?</cite><br/><br/>
			<p id="paperbox">
			Using Vigenere.exe with key = "optoelectronics":<br/>
			<br/>
			<pre  class="long">
			
			
             Kwth qzrva rbq lcq rxw Svtg vxcz zm vzs lbfieerl nsem rmh dg ac oef'l cwamu ?
           - opto elect ron ics opt oele ctro ni cso ptoelect roni cso pt oe lec t ronic	 
           = what month and day did eric tell me the wiretaps were put on my dad's lines ? 
			
			</pre>
			<p>
			<br/>
			<br/>
			<b><u>Answer : "January 27"</u></b><br/>
			<br/>
			</p>
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			<br/><br/>
			<h3>Seventeen: Pulling Back the Curtain</h3><br/>
			<cite>Epib qa bpm vium wn bpm ixizbumvb kwuxtmf epmzm Q bziksml lwev Mzqk Pmqvh ?</cite><br/><br/>
			<p id="paperbox">
			Solved with CrackKevin.exe ROT25 was a valid candidate:<br/>
			<br/>
			<pre  class="long">
					
			
            Epib qa bpm vium wn bpm ixizbumvb kwuxtmf epmzm Q bziksml lwev Mzqk Pmqvh ?
            what is the name of the apartment complex where i tracked down eric heinz ?
			
			
			</pre> 
			<p>
			<br/>
			<b><u>Answer : "oakwood"</u></b><br/>
			<br/>
			</p>
			
			
			
			
			
			
			
			
			
			
			<br/><br/>
			<h3>Eighteen: Traffic Analysis</h3><br/>
			<cite>Khkp wg wve kyfcqmm yb hvh TBS oeidr trwh Yhb MmCiwus Wko ogvwgxar hr ?</cite><br/><br/>
			<p id="paperbox">
			Using Vigenere.exe with key = "oakwood":<br/>
			<br/>
			<pre  class="long">
			
			
             Khkp wg wve kyfcqmm yb hvh TBS oeidr trwh Yhb MmCiwus Wko ogvwgxar hr ?
           - oakw oo doa kwoodoa kw ood oak woodo akwo odo akwoodo akw oodoakwo od	 
           = what is the acronym of the fbi squad that ken mcguire was assigned to ?
			
			</pre>
			<p>
			<br/>
			<br/>
			<b><u>Answer : "wcc3"</u></b><br/>
			<br/>
			
			</p>
			
			
			
			
			
			
			
			
			
			
			
			
			<br/><br/>
			<h3>Nineteen: Revelations</h3><br/>
			<cite>Rcvo dn ivhz ja ocz omvinvxodji oj adiy v kzmnji'n njxdvg nzxpmdot iphwzm pndib oczdm ivhz viy yvoz ja wdmoc ?</cite><br/><br/>
			<p id="paperbox">
			Solved with CrackKevin.exe ROT12 was a valid candidate:<br/>
			<br/>
			<pre  class="long">
					
			
            Rcvo dn ivhz ja ocz omvinvxodji oj adiy v kzmnji'n njxdvg nzxpmdot iphwzm pndib oczdm ivhz viy yvoz ja wdmoc ?
            what is name of the transaction to find a person's social security number using their name and date of birth ?
			
			
			</pre> 
			<p>
			<br/>
			<b><u>Answer : "alphadent"</u></b><br/>
			<br/>
			</p>
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			<br/><br/>
			<h3>Twenty: Reverse String</h3><br/>
			<cite>Wspa wdw gae ypte rj gae dilan lbnsp loeui V tndllrhh gae awvnh "HZO, hzl jaq M uxla nvu" ?</cite><br/><br/>
			<p id="paperbox">
			Using Vigenere.exe with key = "alphadent":<br/>
			<br/>
			<pre  class="long">
			
			
             Wspa wdw gae ypte rj gae dilan lbnsp loeui V tndllrhh gae awvnh "HZO, hzl jaq M uxla nvu" ?
           - alph ade nta lpha de nta lphad ental phade n talphade nta lphad  alp  had ent e ntal pha	 
           = what was the name of the steak house where i answered the phone "dmv, how can i help you" ?
			
			</pre>
			<p>
			<br/>
			<br/>
			<b><u>Answer : "bob burns"</u></b><br/>
			<br/>
			
			</p>
			
			
			
			
			
			
			
			<br/><br/>
			<h3>Twenty-One: Cat and Mouse</h3><br/>
			<cite>4A 75 6E 67 20 6A 6E 66 20 62 68 65 20 61 76 70 78 61 6E 7A 72 20 74 76 69 72 61 20 67 62 20 47 72 65 65 6C 20 55 6E 65 71 6C 3F</cite><br/><br/>
			<p id="paperbox">
				Those are hexadecimal value encoding a string:<br/>
				<Br/>
				<pre  class="long">
				
				
    char cypher21[] =
    {  0x4A,0x75,0x6E,0x67,0x20,0x6A,0x6E,0x66,0x20,0x62,0x68,0x65,0x20,0x61,
       0x76,0x70,0x78,0x61,0x6E,0x7A,0x72,0x20,0x74,0x76,0x69,0x72,0x61,0x20,
       0x67,0x62,0x20,0x47,0x72,0x65,0x65,0x6C,0x20,0x55,0x6E,0x65,0x71,0x6C,0x3F,
    };


    int main(int argc, char** argv)
    {
        printf("%s\n",cypher21);

        return 1;
    }

    
    Output: "Jung jnf bhe avpxanzr tvira gb Greel Uneql ?"
    
    
</pre>
<p>
				Sent "Jung jnf bhe avpxanzr tvira gb Greel Uneql ?" to CrackKevin.exe
			<pre  class="long">
					
			
                             Jung jnf bhe avpxanzr tvira gb Greel Uneql ?
    [21]: Candidate (ROT20): what was our nickname given to terry hardy ?
						
			</pre> 
				<p>
			<br/>
			<b><u>Answer : "klingon"</u></b><br/>
			<br/>
			</p>
			
			
			
			
			
			
			
			
			
			
			
			
			
			
				<br/><br/>
			<h3>Twenty-Two: Detective Work</h3><br/>
			<cite>Gsig cof dsm fkqeoe vnss jo farj tbb epr Csyvd Nnxub mzlr ut grp lne ?</cite><br/><br/>
			<p id="paperbox">
			Using Vigenere.exe with key = "klingon":<br/>
			<br/>
			<pre  class="long">
			
			
             Gsig cof dsm fkqeoe vnss jo farj tbb epr Csyvd Nnxub mzlr ut grp lne ?
           - klin gon kli ngonkl ingo nk ling onk lin gonkl ingon klin go nkl ing	 
           = what was the secret name we used for the wells fargo code of the day ?
			
			</pre>
			<p>
			<br/>
			<br/>
			<b><u>Answer : ""</u></b><br/>
			<br/>
			
			</p>
			
			
			
			
			
			
			
			
			
			
			
			
						
			<br/><br/>
			<h3>Twenty-Three: Raided</h3><br/>
			<cite>Fqjc nunlcaxwrl mnerln mrm cqn OKR rwcnwcrxwjuuh kanjt fqnw cqnh bnjalqnm vh jyjacvnwc rw Ljujkjbjb ?</cite><br/><br/>
			<p id="paperbox">
			Solved with CrackKevin.exe ROT24 was a valid candidate:<br/>
			<br/>
			<pre  class="long">
					
			
            Fqjc nunlcaxwrl mnerln mrm cqn OKR rwcnwcrxwjuuh kanjt fqnw cqnh bnjalqnm vh jyjacvnwc rw Ljujkjbjb ?
            what electronic device did the fbi intentionally break when they searched my apartment in calabasas ?
			
			
			</pre> 
			<p>
			<br/>
			<b><u>Answer : "boombox"</u></b><br/>
			<br/>
			</p>
			
			
			
			
	
			
			
			<br/><br/>
			<h3>Twenty-Four: Vanishing Act</h3><br/>
			<cite>Xvof jq qis bmns lg hvq thlss ktffb J cifsok EAJ uojbthwsbhlsg ?</cite><br/><br/>
			<p id="paperbox">
			Using Vigenere.exe with key = "boombox":<br/>
			<br/>
			<pre  class="long">
			
			
             Xvof jq qis bmns lg hvq thlss ktffb J cifsok EAJ uojbthwsbhlsg ?
           - boom bo xbo ombo xb oom boxbo ombox b oombox boo mboxboomboxbo
           = what ic the name of the store where i outran dmv investigators ?
			
			</pre>
			<p>
			<br/>
			<b><u>Answer : "kinko"</u></b><br/>
			<br/>
			</p>
			
			
			
			
			<br/><br/>
			<h3>Twenty-Five: Harry Houdini</h3><br/>
			<cite>Cngz zuct ngy znk grsg sgzkx lux znk xkgr Kxoi Ckoyy ?</cite><br/><br/>
			<p id="paperbox">
			Solved with CrackKevin.exe ROT1 was a valid candidate:<br/>
			<br/>
			<pre  class="long">
					
			
            Cngz zuct ngy znk grsg sgzkx lux znk xkgr Kxoi Ckoyy ?
            what town has the alma mater for the real eric weiss ?
			
			
			</pre> 
			<p>
			<br/>
			<b><u>Answer : ""</u></b><br/>
			<br/>
			</p>
			
			

			
			
			<br/><br/>
			<h3>Twenty-Six: Private Investigator</h3><br/>
			<cite>Aslx jst rlxi bx ns wgzzcmgw UP jnsh hlrjf nyk TT seq s cojorpdw pssx gxmyeie ao bzy glc ?</cite><br/><br/>
			<p id="paperbox">
			Using Vigenere.exe with key = "ensburgell":<br/>
			<br/>
			<pre  class="long">
			
			
             Aslx jst rlxi bx ns wgzzcmgw UP jnsh hlrjf nyk TT seq s cojorpdw pssx gxmyeie ao bzy glc ?
           - ensb urg elle ns bu rgellens bu rgel lensb urg el len s burgelle nsbu rgellen sb urg ell
           = wftw pbn name of my favorite tv show where the pi had a business card printer in his car ?
			
			</pre>
			<p>
			<b><l>WTF with the bugged beginning of the sentence ?!?!</b></l><br/>
			<br/>
			<br/>
			<b><u>Answer : ""</u></b><br/>
			<br/>
			</p>
			
			
			
			
			
			
			
			<br/><br/>
			<h3>Twenty-Seven: Here Comes the Sun</h3><br/>
			<cite>85 102 121 114 32 103 113 32 114 102 99 32 108 121 107 99 32 109 100 32 114 102 99 32 122 109 105 113 114 109 112 99 32 71 32 100 112 99 111 115 99 108 114 99 98 32 103 108 32 66 99 108 116 99 112 63</cite><br/><br/>
			<p id="paperbox">
			The string is decimal value for characters:
			
			<pre  class="long">
			
			
    char cypher27[] = {
     85, 102, 121, 114,  32, 103, 113,  32, 114, 102,  99,  32, 108, 121, 107,  99,  32, 109, 100,  32,
    114, 102,  99,  32, 122, 109, 105, 113, 114, 109, 112,  99,  32,  71,  32, 100, 112,  99, 111, 115,
     99, 108, 114,  99,  98,  32, 103, 108,  32,  66,  99, 108, 116,  99, 112,  63};

    int main(int argc, char** argv)
    {
	    printf("%s\n",cypher27);

	    return 1;
    }
			
    Output: "Ufyr gq rfc lykc md rfc zmiqrmpc G dpcosclrcb gl Bcltcp ?"		
			
			</pre>
			<p>
			Sent "Ufyr gq rfc lykc md rfc zmiqrmpc G dpcosclrcb gl Bcltcp ?" to CrackKevin.exe
			<pre  class="long">
					
			
                            Ufyr gq rfc lykc md rfc zmiqrmpc G dpcosclrcb gl Bcltcp ?
    [27]: Candidate (ROT9): what is the name of the bokstore i frequented in denver ?
						
			</pre> 
			
			</p>			
			
			
			
			
			
			
			
			
			
			
			
				<br/><br/>
			<h3>Twenty-Eight: Trophy Hunter</h3><br/>
			<cite>Phtm zvvvkci sw mhx Fmtvr VOX Ycmrt Emki vqimgv vowx hzh L cgf Ecbst ysi ?</cite><br/><br/>
			<p id="paperbox">
			Using Vigenere.exe with key = "tatteredcover":<br/>
			<br/>
			<pre  class="long">
			
			
             Phtm zvvvkci sw mhx Fmtvr VOX Ycmrt Emki vqimgv vowx hzh L cgf Ecbst ysi ?
           - tatt eredcov er tat tered cov ertat tere dcover tatt ere d cov ertat ter
           = what version of the micro tac ultra lite source code did i ask alisa for ?
			
			</pre>
			<p>
			<br/>
			<br/>
			<b><u>Answer : ""</u></b><br/>
			<br/>
			</p>
			
			
			
			
			
			
			
			
			
			
			
			<br/><br/>
			<h3>Twenty-Nine: Departure</h3><br/>
			<cite>126 147 172 163 040 166 172 162 040 154 170 040 157 172 162 162 166 156 161 143 040 145 156 161 040 163 147 144 040 115 156 165 144 153 153 040 163 144 161 154 150 155 172 153 040 162 144 161 165 144 161 040 150 155 040 122 172 155 040 111 156 162 144 077</cite><br/><br/>
			<p id="paperbox">
			040 is seen very often in this serie and is also very interesting because it is also "space" in octal notation:<br/>
			<br/>
			
			<pre  class="long">
			
    char text[] =
    {
	    
    126,147,172,163,               //WHAT ?
    040,
    166,172,162,                   //WAS ?
    040,
    154,170,
    040,
    157,172,162,162,166,156,161,143,
    040,
    145,156,161,
    040,
    163,147,144,
    040,
    115,156,165,144,153,153,
    040,
    163,144,161,154,150,155,172,153,
    040,
    162,144,161,165,144,161,
    040,
    150,155,
    040,
    122,172,155,
    040,
    111,156,162,144,077
    
    }		
			
			
			</pre>
			<p>
			So all character are consistently encoded. Let's try to print out the octal value:<br/>
			<br/>
			<pre  class="long">
			
			
       #include &lt;stdio.h&gt;
			
       char text[] ={
	   0126,0147,0172,0163, 040, 0166,0172,0162, 040, 0154,0170, 040, 0157,\
       0172,0162,0162,0166,0156,0161,0143, 040, 0145,0156,0161, 040, 0163,0147,0144, 040,\
       0115,0156,0165,0144,0153,0153, 040, 0163,0144,0161,0154,0150,0155,0172,0153, 040,\
       0162,0144,0161,0165,0144,0161, 040, 0150,0155, 040, 0122,0172,0155,040,0111,0156,\
       0162,0144,077
       };

       int main(int argc, char** argv)
       {
          printf("%s\n",text);
         return ;
       }
			
       Output: 	Vgzs vzr lx ozrrvnqc enq sgd Mnudkk sdqlhmzk rdqudq hm Rzm Inrd?¦!	
			</pre>
			
		<p>
		Sending this to CrackKevin.exe -> ROT8
		<pre  class="long">
		
		Vgzs vzr lx ozrrvnqc enq sgd Mnudkk sdqlhmzk rdqudq hm Rzm Inrd?
		what was my password for the novell terminal server in san jose?
		
		</pre>
			</p>
			
			
			
			
			
			
			
			
			
			<br/><br/>
			<h3>Thirty: Blindsided</h3><br/>
			<cite>Ouop lqeg gs zkds ulv V deds zq lus DS urqstsn't wwiaps ?</cite><br/><br/>
			<p id="paperbox">
			Using Vigenere.exe with key = "snowbird":<br/>
			<br/>
			<pre  class="long">
			
			
             Ouop lqeg gs zkds ulv V deds zq lus DS urqstsn't wwiaps ?
           - snow bird sn owbi rds n owbi rd sno wb irdsnow b irdsno
           = what kind of lock did i pick in the hr manager's office ?
			
			</pre>
			<p>
			<br/>
			<br/>
			<b><u>Answer : ""</u></b><br/>
			<br/>
			</p>
			
			
			
			
			
			
			
			
			
			
			
			
			<br/><br/>
			<h3>Thirty-One: Eyes in the Sky</h3><br/>
			<cite>Alex B25 rixasvo hmh M ywi xs xli HQZ qemrjveqi ?</cite><br/><br/>
			<p id="paperbox">
			Solved with CrackKevin.exe (ROT3):
			
			<pre  class="long">
					
			
    Alex B25 rixasvo hmh M ywi xs xli HQZ qemrjveqi ?
    what x25 network did i use to the dmv mainframe ?
						
			</pre> 
			
			</p>			
			
			
			
			
			
			
			
			
			
			<br/><br/>
			<h3>Thirty-Two: Sleepless in Seattle</h3><br/>
			<cite>Caem alw Ymek Xptq'd tnwlchvw xz lrv lkkzxv ?</cite><br/><br/>
			<p id="paperbox">
			Using Vigenere.exe with key = "gtetelenet":<br/>
			<br/>
			<pre  class="long">
			
			
             Caem alw Ymek Xptq'd tnwlchvw xz lrv lkkzxv ?
           - gtet ele netg tete l enetgtet el ene tgtete
           = what was lile elam's password to her server ?
			
			</pre>
			<p>
			<br/>
			<br/>
			<b><u>Answer : ""</u></b><br/>
			<br/>
			</p>
			
			
			
			
			
			
			
			
			
			
					
			
			
	
			
			<br/><br/>
			<h3>Thirty-Three: Hacking the Samurai</h3><br/>
			<cite>Ozg ojglw lzw hshwj gf AH Khggxafy lzsl BKR skcww ew stgml ?</cite><br/><br/>
			<p id="paperbox">
			Solved with CrackKevin.exe (ROT15):
			
			<pre  class="long">
					
			
    Ozg ojglw lzw hshwj gf AH Khggxafy lzsl BKR skcww ew stgml ?
    who wrote the paper on ip spoofing that jsz askee me about ?
						
			</pre> 
			
			</p>			
					
		
			
			
			
			
			
			<br/><br/>
			<h3>Thirty-Four: Hiding in the Bible Belt</h3><br/>
			<cite>Nvbx nte hyv bqgs pj gaabv jmjmwdi whd hyv UVT'g Giuxdoc Gctcwd Hvyqbuvz hycoij ?</cite><br/><br/>
			<p id="paperbox">
			Using Vigenere.exe with key = "robertmorris":<br/>
			<br/>
			<pre  class="long">
			
			
             Nvbx nte hyv bqgs pj gaabv jmjmwdi whd hyv UVT'g Giuxdoc Gctcwd Hvyqbuvz hycoij ?
           - robe rtm orr isro be rtmor risrobe rtm orr isr o bertmor risrob ertmorri srober
           = what was the type of phone service for the mdc's federal public defender phones ?
			
			</pre>
			<p>
			<br/>
			<br/>
			<b><u>Answer : ""</u></b><br/>
			<br/>
			</p>
			
			
			
			
			
			
			
			
			
			
			<br/><br/>
			<h3>Thirty-Five: GameOver</h3><br/>
			<cite>2B 2T W 2X 2Z 26 36 2P 36 2V 3C W 3A 32 39 38 2Z W 3D 33 31 38 2V 36 3D W 2R 2Z W 3E 3C 2V 2X 2Z 2Y W 3E 39 W 2R 32 2V 2E W 2V 3A 2V 3C 3E 37 2X 38 3E W 2X 39 37  3A 36 2Z 2S 1R</cite><br/><br/>
			<p id="paperbox">
			Just like in 29, we can notice the repeating W pattern: Could it be space? <br/>
			<br/>
			<pre  class="long">
			
			
    2B 2T 
    W 
    2X 2Z 26 36 2P 36 2V 3C 
    W 
    3A 32 39 38 2Z 
    W 
    3D 33 31 38 2V 36 3D 
    W 
    2R 2Z 
    W 
    3E 3C 2V 2X 2Z 2Y 
    W 
    3E 39 
    W 
    2R 32 2V 2E 
    W 
    2V 3A 2V 3C 3E 37 2X 38 3E 
    W 
    2X 39 37  3A 36 2Z 2S 1R			
			
			
			</pre>
			<p>
			Since this is probably a question this would mean that is starts with IS => 2B=I 2T = S. "ikp" confirmed my intuition: This 
			is base36 encoding. I wrote a tiny <a href="mainBase36.c.txt">program</a> to convert base36 to ASCII:
			<pre  class="long">
			
			
			Se ikNrargx vnutk yomtgry ck zxgikj zu cngV gvgxzsitz iusvrkd?
			
			
			</pre>
			<p>
			Now sending it to CrackKevin.exe: ROT20 came back positive:<br/>
			<br/>
			<pre  class="long">
			
			
			My cellular phone signals were traced to what apartment complex?
			
			
			</pre>
			
			</p>
			
			
			
			
			
			
			
				
			<br/><br/>
			<h3>Thirty-Six: An FBI Valentive</h3><br/>
			<cite>Lsar JSA cryoi ergiu lq wipz tnrs dq dccfunaqi zf oj wqpctkiel dpzpgp I jstcgo cu dy hgq ?</cite><br/><br/>
			<p id="paperbox">
			Using Vigenere.exe with key = "playersclub":<br/>
			<br/>
			<pre  class="long">
			
			
             Lsar JSA cryoi ergiu lq wipz tnrs dq dccfunaqi zf oj wqpctkiel dpzpgp I jstcgo cu dy hgq ?
           - play ers clubp layer sc lubp laye rs clubplaye rs cl ubplayers clubpl a yerscl ub pla ye
           = what fbi agent tried to look into my briefcase in my cpartment before i locked it on him ?
			
			</pre>
			<p>
			<br/>
			<br/>
			<b><u>Answer : ""</u></b><br/>
			<br/>
			</p>
			
			
			
			
			
			
			
			<br/><br/>
			<h3>Thirty-Seven: Winning the scrapegoat Sweepstakes.</h3><br/>
			<cite>V2hhdCBGQkkgYWdlbnQgYXNrZWQgU3VuIE1pY3Jvc3lzdGVtcyB0byBjbGFpbSB0aGV51Gxvc3QgODAgbWlsbGlvbiBkb2xsYXJzPw==</cite>
			<p id="paperbox">
			The "==" at the end is typical of base64 encoding padding:
			<pre  class="long">
			
			
    V2hhdCBGQkkgYWdlbnQgYXNrZWQgU3VuIE1pY3Jvc3lzdGVtcyB0byBjbGFpbSB0aGV51Gxvc3QgODAgbWlsbGlvbiBkb2xsYXJzPw==
    What FBI agent asked Sun Microsystems to claim they lost 80 million dollars?
			
			
			</pre> 
			</p>
			
			
			
			<br/><br/>
			<h3>Thirty-Eight: Winning the scrapegoat Sweepstakes.</h3><br/>
			<cite>100-1111-10-0 011-000-1-111 00-0100 1101-10-1110-000-101-11-0-1 0111-110-00-1001-1-101 111-0-11-0101-010-1-101 111-10-0100 11-00-11</cite>
			<p id="paperbox">
			
			<pre  class="long">
			
			
    100-1111-10-0                 //WHAT?
    011-000-1-111                 //WAS ?
    00-0100                       
    1101-10-1110-000-101-11-0-1 
    0111-110-00-1001-1-101 
    111-0-11-0101-010-1-101 
    111-10-0100 
    11-00-11
			
			
			
			</pre>
			<p>
			As suggested by "ikp", this is morse code.
			<pre class="long">
			
	.-- .... .- -                  //WHAT 
    -.. --- . ...                  //DOES
    
    -- .-..                        //ML
    ..-. .- ...- --- .-. .. - .    //FAVORITE       
    -... ..- -- .--. . .-.         //BUMPER 
    ... - .. -.-. -.- . .-.        //STICKER 
    ... .- -.--                    //SAY
    .. -- ..                       //? 
    
			
			
			
			</pre
			
			<p>
			<br/>
			<b><u>Answer : ""</u></b><br/>
			<br/>
			</p>
			
			
			
			
			<!--
			
			Are you naive or stupid:
			
			I guess when your friends are peope who are breaking the law, you're naive if you expect loyalty
			
			-->
<h3>Recommended readings</h3>
<p >
Of course read Kevin Mitnik's book. Try to get different perspectives with Tsutomu Shimomura/John Markoff version in "Takedown". Finally read bit about cryptography with "The Code Book" a delicious read!<br/> 
				<br/> 
				<a href="http://www.amazon.com/Ghost-Wires-Adventures-Worlds-Wanted/dp/0316037702"><img src="../fd_proxy/Ghost_in_the_Wires/gitw.png" style="margin: 0 5px 0 0;"></a> 
				<a href="http://www.amazon.com/Code-Book-Science-Secrecy-Cryptography/dp/0385495323/ref=sr_1_1?ie=UTF8&qid=1316405428&sr=8-1"><img src="../fd_proxy/Ghost_in_the_Wires/tcd.png" style="margin: 0 5px 0 0px;"></a> 
				<a href="http://www.amazon.com/Takedown-Pursuit-Americas-Computer-Outlaw-/dp/0786889136/ref=sr_1_2?ie=UTF8&qid=1316410604&sr=8-2"><img src="../fd_proxy/Ghost_in_the_Wires/td.png" style="margin: 0 5px 0 0px;"/></a> 

</p>



</p>

<!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

