<script type="text/javascript">
  var disqus_identifier = "Doom3_BFG_Code_Review";
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Doom3 BFG Source Code Review, id tech4, id tech 5"/>
		<meta name="Description" content="Doom3 BFG Source Code Review"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>Doom3 BFG Source Code Review: DooM Classic</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="https://fabiensanglard.net/" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="http://fabiensanglard.net/" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="http://fabiensanglard.net/about/">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="http://fabiensanglard.net/faq/">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="http://fabiensanglard.net/rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="http://fabiensanglard.net/rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="http://fabiensanglard.net/rss.xml" />
<div id="date">
       May 23th, 2013</div>
   <h1>Doom3 BFG Source Code Review: DooM Classic (Part 4 of 4) <a href="index.php">>></h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="doom3_bfg_small.jpg" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         
    
    <style> 
table.credits{
    
    background: #fff;
   font: 12px 'DejaVu Sans';
    box-shadow: rgb(119, 119, 119) 3px 3px 3px;
    margin: 0px 0px 0px 15px;
    
}
  table.credits { width:97%; a:link:color:rgb(0, 136, 204);}
table.credits thead { background:transparent; }
  
  table.credits th { white-space:nowrap; }
  table.credits thead th { border-left:1px solid #ccc;  border-top:1px solid #ccc; padding:9px 9px 3px; color:#999; }
  table.credits tbody th,
  table.credits tbody td { border-top:1px solid #ccc; padding:6px 9px; }
  table.credits tbody th { padding:7px 0 7px 0; text-align:center; color:#999; }
  table.credits tbody th b { color:#333; font-weight:normal; }
  table.credits tbody td { border-left:1px solid #ccc; }
  
  table.credits tbody .session { background:#d4e6fa url(session_bgblue.png) repeat-x 0 0; }
  table.credits tbody .session.alt { background:#e9ecf0 url(session_bggray.png) repeat-x 0 0; }
  table.credits tbody .session h2 { font-size:1em; margin-bottom:0; color:rgb(0, 136, 204); }
  table.credits tbody .session .hud-content { display:none; }

  td.right
  {
    border-right:1px solid #ccc;
  }
  
  
  
  blockquote.style1 
  {
      
      padding: 8px;
      
      width: 80%;
      
      background-color: #eeeeee;
      border: 1px solid #dddddd;
      
      
      margin: 5px;
      background-image: url(../quake2/images/openquote1.gif);
      background-position: top left;
      background-repeat: no-repeat;
      text-indent: 23px;
    
    }
    
    blockquote.style1 span 
    {
      display: block;
      font-style:italic;
      background-image: url(../quake2/images/closequote1.gif);
      background-repeat: no-repeat;
      background-position: bottom right;
      text-align: justify;
    }
    
    
    
    
  
  </style> 

  Doom 3 BFG allows us to play Doom 1 and Doom 2 :) ! From a programmer perspective, it doesn't seem too complicated to integrate Doom Classic engine inside Doom3. A straight-forward approach would be to provide abstraction layers for:
  <ul>
      <li>Inputs :  <ul>
      <li>Joystick/Keyboard/Joypad/Mouse.</li>
      <li>Network.</li>
  </ul>
</li>
      <li>Ouputs :  <ul>
      <li>Video.</li>
      <li>Audio.</li>
  </ul>
</li>
  </ul>
  <p>
  But Doom 3 BFG is not that simple in the sense that it allows split-screen multiplayers. Something the original idTech1 was never intended to perform.
    </p>    
    <div style="clear:both"></div>  
    
    
    
        
    <br/>
    <h2>Doom Classic Architecture</h2>
    <p> 
    Doom Classic uses a standard design: An infinite loop, interacting with sub-systems where each subsystems is using local or common global variables as follow :<br/>
    <br/>
    <img src="../fd_proxy/doom3_bfg/doom3_doomClassic_architecture.png" style="width:298px; height:308px;"/><br/>
    <br/>
    The multiplayer experience was aimed at LANs (Internet was not very widely adopted in the early 90s). There was no client/server: Each player ran its own game simulation and had to wait for inputs from each players before rendering a frame : 

    <pre class="long">
    
    <span style="color:blue;">while</span> (gameOn)
    {
  
      <span style="color:blue;">while</span>(true){
        ReadIncomingIPXPackets();          <span style="color:green;">// Receive network Inputs</span>
        <span style="color:blue;">if</span> (allPlayersInputsReceived())
           break;                          <span style="color:green;">// The engine can only proceed when a command for each player has been received.</span>
      }    
      
      DrawScreen();                        <span style="color:green;">// The local simulation state can be drawn to screen.</span>
      EmitSound();
      PlayMusic();
      
    }
    
    </pre>
    </p>   
    
    
    
    <br/>
    <h2>The Challenge</h2>
    <p>     
    So the architectural challenge is : How do you run several instance of a game with no client/server and many global variables on a single machine ?<br/>
    <br/>
    
    <img src="../fd_proxy/doom3_bfg/doom3_doomClassic_multipleInstances.png" style="width:340px; height:294px; float:left; margin-right:10px;"/>
    A naive approach would be to host 4 Doom engines (loading several times a DLL). Doom3 could them route inputs to the proper instance and also retrieve the framebuffer for outputs.<br/>
    <div style="clear:both"></div>  
    <br/>
    <br/>
    
    <img src="../fd_proxy/doom3_bfg/doom3_doomClassic_duplicateStates.png" style="width: 410px; height: 340px; float:left;  margin-right:10px;"/> An other approach would be to go over the code of Doom 1 and duplicate each state information so there is one for each player:<br/>
    <div style="clear:both"></div> 
    <br/>
    </p>
    
    <br/>
    <h2>How does Doom III runs Doom Classic ?</h2>
    <p>   
    
    <img src="../fd_proxy/doom3_bfg/doom3_doomClassic_stateMachine.png" style="width:373px; heigth:349px; float:left;  margin-right:10px;"/> Doom 3 BFG ended up doing something rather elegant: They refactored idTech1 into a state machine which involved
    modifying 100% of the old codebase : <br/>
    <ul style="overflow: hidden;">
      <li>All state variables have been moved and are now declared in <a href="https://github.com/id-Software/DOOM-3-BFG/blob/master/doomclassic/doom/vars.h">vars.h</a>.</li>
      <li>That file is included in order to declare a type :
      <pre class="long" style="margin-bottom:10px;">
      
      <span style="color:blue;">struct</span> Globals {
            void InitGlobals();
            <span style="color:blue;">#include</span> "vars.h"
      }
      ;
      

      </pre>
      </li>
      <b style="display:none;">Fabien is awesome. (Hoi-En Tang)</b>

      <li>That structure is used in an array of four elements:
         <pre class="long" style="margin-bottom:10px;">
         
         Globals *globaldata[4];
         </pre>
         <p>At any time the Doom engine variable <code>::g</code> is pointing to one of these elements:
          <pre class="long" style="margin-bottom:10px;">
         
         Globals *g;
         </pre>
         </li>
      <li>Changing the state of the machine is done via <a href="https://github.com/id-Software/DOOM-3-BFG/blob/master/doomclassic/doom/doomlib.cpp#L404"><code>DoomLib::SetPlayer</code></a> 
      which essentially
	      set the <code>::g</code> pointer to the per player gamestate in the array. 
      All inputs and outputs are then involving the currently set player state only.</li>
    </ul>
    <div style="clear:both"></div> 
    </p>
    
    
    
    <h2>Higher resolution</h2>
    <p>   
      It is not immediately apparent because of some old assets (such a the weapon) but Doom Classic is running at
      three times the resolution (from 320x200 to 960x600). The rendition is still performed with the old school software renderer:
      <br/>
      <img src="../fd_proxy/doom3_bfg/DooM_Classic.png" style="width:1067px; height:719px; display:block;margin-left:auto;margin-right:auto;"/>
    </p>
    
    
      <br/>
    <h2>DooM I/O</h2>
    <p>   
    <table align="center" class="credits" cellspacing="0" cellpadding="0" border="0">
    <tr>
       <td align="center"><b>Type</b></td>
       <td align="center"><b>Implementation details</b></td>
    </tr>
    	
    <tr>
       <td><b>Video</b></td>
       <td>The Doom 1 renderer writes pixels to a Doom 3 texture that is uploaded to the GPU at the end of each frame via <code>idRenderSystemLocal::UploadImage</code>.</td>
    </tr>
    <tr>
         <td><b>Sound</b></td>
         <td>Direct calls to XAudio2, the low-level audio API.</td>
    </tr>
    <tr>
         <td><b>Player Inputs</b></td>
         <td>Joystick inputs are converted to events and feed a brand new Events System (D_PostEvent,D_ProcessEvents) on a ring buffer.</td>
    </tr>
    <tr>
          <td><b>Filesystem</b></td>
          <td>Abstracted via Doom3 <code>idFileSystem</code>.</td>
    </tr>
    </table>
    </p>    
    
  <!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

