<script type="text/javascript">
  var disqus_identifier = "Doom3_BFG_Code_Review";
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Doom3 BFG Source Code Review, id tech4, id tech 5"/>
		<meta name="Description" content="Doom3 BFG Source Code Review"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>Doom3 BFG Source Code Review: Introduction</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="https://fabiensanglard.net/" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="http://fabiensanglard.net/" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="http://fabiensanglard.net/about/">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="http://fabiensanglard.net/faq/">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="http://fabiensanglard.net/rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="http://fabiensanglard.net/rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="http://fabiensanglard.net/rss.xml" />
<div id="date">
       May 23th, 2013</div>
   <h1>Doom3 BFG Source Code Review: Introduction (Part 1 of 4) <a href="threading.php">>></h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="doom3_bfg_small.jpg" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         
    
    <style> 
table.credits{
    
    background: #fff;
   font: 12px 'DejaVu Sans';
    box-shadow: rgb(119, 119, 119) 3px 3px 3px;
    margin: 0px 0px 0px 15px;
    
}
  table.credits { width:97%; a:link:color:rgb(0, 136, 204);}
table.credits thead { background:transparent; }
  
  table.credits th { white-space:nowrap; }
  table.credits thead th { border-left:1px solid #ccc;  border-top:1px solid #ccc; padding:9px 9px 3px; color:#999; }
  table.credits tbody th,
  table.credits tbody td { border-top:1px solid #ccc; padding:6px 9px; }
  table.credits tbody th { padding:7px 0 7px 0; text-align:center; color:#999; }
  table.credits tbody th b { color:#333; font-weight:normal; }
  table.credits tbody td { border-left:1px solid #ccc; }
  
  table.credits tbody .session { background:#d4e6fa url(session_bgblue.png) repeat-x 0 0; }
  table.credits tbody .session.alt { background:#e9ecf0 url(session_bggray.png) repeat-x 0 0; }
  table.credits tbody .session h2 { font-size:1em; margin-bottom:0; color:rgb(0, 136, 204); }
  table.credits tbody .session .hud-content { display:none; }

  td.right
  {
    border-right:1px solid #ccc;
  }
  
  
  
  blockquote.style1 
  {
      
      padding: 8px;
      
      width: 80%;
      
      background-color: #eeeeee;
      border: 1px solid #dddddd;
      
      
      margin: 5px;
      background-image: url(../quake2/images/openquote1.gif);
      background-position: top left;
      background-repeat: no-repeat;
      text-indent: 23px;
    
    }
    
    blockquote.style1 span 
    {
      display: block;
      font-style:italic;
      background-image: url(../quake2/images/closequote1.gif);
      background-repeat: no-repeat;
      background-position: bottom right;
      text-align: justify;
    }
    
    
    
    
  
  </style> 

  On November 26, 2012 id Software released the source code of <a href="https://github.com/id-Software/DOOM-3-BFG">Doom 3 BFG 
  edition</a> (only one month after the game hit the stores). The 10 years old <a href="http://en.wikipedia.org/wiki/Id_Tech_4">idTech 4</a> engine has been updated with some
   of the technology found in <a href="http://en.wikipedia.org/wiki/Id_Tech_5">idTech 5</a> (the game engine running 
   <a href="http://en.wikipedia.org/wiki/Rage_(video_game)">Rage</a>) and it was an interesting reading session.<br/>
  <br/>
  I call it "idTech4 prime" since it is idTech4 powered up with idTech5 :<br/>
  <ul>
     <li>Threading system.</li>
     <li>Sound system.</li>
     <li>Resources system.</li>
  </ul>  
  <p> 
    By far the most appealing aspect is the Threading System: Doom 3 was developed at the dawn of the multi-cores era 
    when few PCs were SMP capable. Now the rules have changed, <a href="http://en.wikipedia.org/wiki/Apple_A5">even 
    cellphones feature multiple cores</a>
    and a game engine must be multi-threaded in order to use the full potential of a machine: In this regard, idTech5 "Jobs System" 
    is elegant.
    <br/>
<br/>
  I have cleaned up my notes into this article. I hope it will inspire people to read more source code and become better engineers.<br/>
  <br/>
  <a href="index.html">Part 1: Introduction</a>.<br/>
  <a href="threading.php">Part 2: Multi-threading</a>.<br/>
  <a href="renderer.php">Part 3: Renderer</a>.<br/>
  <a href="DooM_Classic.php">Part 4: DooM Classic integration</a>.<br/>
  <br/>
  <u><b>Edit May 24th, 2013 :</b></u> Thanks for the <a href="https://twitter.com/ID_AA_Carmack/status/337660683732803584">tweet</a> from John Carmack :) ! 
    </p>    
    <div style="clear:both"></div>  
    
    
    
        
     <br/>
    <h2>First contact</h2>
    <img style="width:265px; height:250px; margin-right: 20px; float: left; box-shadow: rgb(119, 119, 119) 3px 3px 7px; width: 265px; height: 250px; display: block;" 
    src="../lazy_load/grey.gif" data-original="/fd_proxy/doom3_bfg/doom3_bfg_vs2010.png"/>
    
    The first contact with Doom 3 BFG is excellent since you can get a working executable in two steps:<br/>
    <br/>
       1. Get the source from GitHub :<br/>
       <br/>
           <pre class="long" style="margin-left:285px;">


    git clone https://github.com/id-Software/DOOM-3-BFG

          </pre>
          <p>
       2. Open Visual Studio 2010 Express and hit F8 for "Build".<br/>
       <br/>
       Done ! <br/>
       <br/>
        <br/>
       <b><u>Note :</u></b> If Direct3D SDK is installed, the full project compiles with 5 minimal warnings in less than a minute.<br/>
       </p>
       







    <br/>
    <h2>Debug Mode</h2>
    <p>     
   Only three steps to start tinkering with Visual Studio 2010 Express :<br/> 
   <br/> 
   1. Update the Debug command parameters to Steam assets location.<br/>
 <pre class="long">


    +set fs_basepath "C:\Program Files\Steam\SteamApps\common\DOOM 3 BFG Edition" +set r_fullscreen 0

          </pre>
          <p>
    2. Set the Startup Project to "Doom3BFG".<br/>
    <br/>
    3. Hit F5.
    <p>
    <img src="../fd_proxy/doom3_bfg/dev_mode.png" style="width:900px;height:549px; display:block;margin-left:auto;margin-right:auto;" />
    </p>












    <br/>
    <h2>Source code readability</h2>
    <p>
    <u><b>C++ subset :</b></u><br/>
    <br/>
    Doom 3 BFG is written in C++, a language so vast that it can be used to generate great code but also abominations 
    that will <a href="https://code.google.com/p/v8/source/browse/branches/3.0/src/api.cc#1294">make your eyes bleed</a>.
    Fortunately id Software settled for a C++ subset close to "C with Classes" which flows down the brain with little resistance:
    <ul>
    
    <li>No exceptions.</li>
    <li>No References (use pointers).</li>
    <li>Minimal usage of templates.</li>
    <li>Const everywhere.</li>
    <li>Classes.</li>
    <li>Polymorphism.</li>
    <li>Inheritance.</li>
    </ul>
    <p>
    And despite being heavily multi-threaded, the source does not employ smart pointers or Boost: What a relief (those usually make the code unreadable).
    <br/>
    <br/>
    <u><b>Comments :</b></u><br/>
    <br/>
    Comments are plenty and useful since they are usually one sentence describing what the next block does for each important parts of a function. Here is an example from <code>ParallelJobList.cpp</code> :<br/>
    
    <pre class="long">

    
    <span style="color:blue;">int</span> idJobThread::Run() {

	threadJobListState_t threadJobListState[MAX_JOBLISTS];
	<span style="color:blue;">int</span> numJobLists = 0;
	<span style="color:blue;">int</span> lastStalledJobList = -1;

	<span style="color:blue;">while</span> ( !IsTerminating() ) {

    <span style="color:green;">// fetch any new job lists and add them to the local list</span>
		<span style="color:blue;">if</span> ( numJobLists < MAX_JOBLISTS && firstJobList < lastJobList ) {
			threadJobListState[numJobLists].jobList = jobLists[firstJobList & ( MAX_JOBLISTS - 1 )].jobList;
			threadJobListState[numJobLists].version = jobLists[firstJobList & ( MAX_JOBLISTS - 1 )].version;
			threadJobListState[numJobLists].signalIndex = 0;
			threadJobListState[numJobLists].lastJobIndex = 0;
			threadJobListState[numJobLists].nextJobIndex = -1;
			numJobLists++;
			firstJobList++;
		}
    
    <span style="color:green;">// if the priority is high then try to run through the whole list to reduce the overhead</span>
    <span style="color:green;">// otherwise run a single job and re-evaluate priorities for the next job</span>
    <span style="color:blue;">bool</span> singleJob = ( priority == JOBLIST_PRIORITY_HIGH ) ? <span style="color:blue;">false</span> : jobs_prioritize.GetBool();

    <span style="color:green;">// try running one or more jobs from the current job list</span>
    <span style="color:blue;">int</span> result = threadJobListState[currentJobList].jobList->RunJobs( threadNum, threadJobListState[currentJobList], singleJob );


    </pre>
   <p>
    Overall the reader gets an immediate understanding of each part of an algorithm and I hope it will inspire people to write better code: Modern software development
    is not about being an ace programmers anymore. It is about being a team player that empowers co-workers with:
    <ul>
      <li>Elegant design.</li>
      <li>Easy to read and commented code implementing it.</li>
    </ul>
    <p>
    Doom 3 BFG ranks high on both those metrics.
    </p>
      
    
    
    
    
    <br/>
    <h2>What has changed ?</h2>
    <p>
      The Visual Studio solution has been cleaned up:
      <table style="width:100%; text-align:center;">
         <tr>
            <td style="width:50%; font-weight:bold; ">Old Doom 3</td>
            <td style="width:50%; font-weight:bold; ">New Doom 3 BFG</td>
         </tr>
         <tr>
            <td><img style="box-shadow: rgb(119, 119, 119) 3px 3px 7px;"  width: 257px; height: 248px; src="../lazy_load/grey.gif" data-original="/fd_proxy/doom3/doom3_vs2010.png"></td>
            <td><img style="box-shadow: rgb(119, 119, 119) 3px 3px 7px;"  width: 265px; height: 250px; src="../lazy_load/grey.gif" data-original="/fd_proxy/doom3_bfg/doom3_bfg_vs2010.png"></td>
         </tr>
    </table>
      <ul>
        <li>Gone the two "Game" projects (one for Doom III classic and the other for "Ressurection") : Game is now an unified project.</li>
        <li>Gone cURL: Doom III does not download things anymore.</li>
        <li>Gone the silly DoomDLL name...that was actually generating <code>DOOM3.EXE</code>.</li>
        <li>Gone the outdated Maya tools to export md5 models, animations and camera path.</li>
        <li>Gone TypeInfo that provided in-house RTTI/Introspection.</li>
      </ul>
      <p>
      <br/>
      <u>Summary of the projects in Doom 3 BFG solution</u>:
    <table align="center" class="credits" cellspacing="0" cellpadding="0" border="0" >
  <tbody>
    <tr>
      <td align="center" >
        <b>Projects</b>
      </td>
      <td align="center" >
        <b>Builds</b>
      </td>
      <td align="center" style="font-weight:bold; border-right:1px solid #ccc; text-align:left;">
        Observations
      </td>
    </tr>
    <tr>
      <td align="center" >Amplitude</td>
      <td align="center" >Amplitude.lib</td>
      
      <td align="center" style=" border-right:1px solid #ccc; text-align:left;">Used for Doom Classic: Tool to adjust WAV amplitude.</td>
    </tr>
    <tr>
      <td align="center"  >Doom3BFG</td>
      <td align="center"  >Doom3BFG.exe</td>
      
      <td align="center" style=" border-right:1px solid #ccc; text-align:left;">Doom 3 BFG Engine.</td>
    </tr>
    <tr><td align="center" >doomclassic</td>
      <td align="center" >doomclassic.lib</td>
      
      <td align="center" style=" border-right:1px solid #ccc; text-align:left;">Heavily refactored Doom1/2 game engine.</td>
    </tr>
    <tr>
      <td align="center"  >external</td>
      <td align="center"  >external.lib</td>
      
      <td align="center" style=" border-right:1px solid #ccc; text-align:left;">
      jpeg-6 and zlib source code.
      </td>
    </tr>
    
    <tr>
      <td align="center"  >Game-d3xp</td>
      <td align="center"  >Game-d3xp.lib</td>
      
      <td align="center" style=" border-right:1px solid #ccc; text-align:left;">
      Unified Game library, featuring original + extension + new levels. Note that it compiles to a static library now instead of a DLL.
      </td>
    </tr>
    <tr>
      <td align="center" style="border-bottom:1px solid #ccc; border-right:1px solid #ccc;">idLib</td>
      <td align="center" style="border-bottom:1px solid #ccc; border-right:1px solid #ccc;">idLib.lib</td>
      
      <td align="center" style="border-bottom:1px solid #ccc; border-right:1px solid #ccc; text-align:left;">
      The id software Toolkit providing abstracted filesystem, threading, containers.
      </td>
    </tr>
    <tr>
      <td align="center"  >timidity</td>
      <td align="center"  >timidity.lib</td>
      
      <td align="center" style=" border-right:1px solid #ccc; text-align:left;">
      Used for Doom Classic: Convert a MIDI input to WAV format.
      </td>
    </tr>
    
  </tbody>
  </table>    
    </p>
    
    <br/>
    <h2>New Architecture</h2>
    <p>
      <img src="../fd_proxy/doom3_bfg/doom3bfg_architecture.png" style="width: 520px; 380px; float:right; margin-left:10px;"/>
      The architecture differs significantly from the <a href="https://fabiensanglard.net/fd_proxy/doom3/doom3_diagram2.png">original Doom III</a>: The solution now compiles into one 
      monolithic executable (Doom III compiled to one executable
      and one DLL containing the game logic).<br/>
      <br/>
      This was motivated by two reasons (according to the main Developer Brian Harris ):
      <ul>
        <li>Consoles such as PS3/Xbox360 don't have very good support for dlls.</li>
        <li>Speed up development. With dlls, you have to be very careful about memory -- you can't allocate in one and free in the other. This makes things much more difficult and creates very hard to track down bugs.</li>
    </ul>
      <div style="clear:both"></div>
    </p>
    
    <br/>
    <h2>Console driven changes</h2>
    <p>
    Targeting the Xbox 360 and the PS3 on top of PCs resulted in many important updates:
    <ol>
      <li>As previously mentioned the entire game is contained in one executable.</li>
      <li>The game used to store assets in various PAK files (which were zip archives). The high latency of DVD readers pushed id Software to use a "Resource System": One file containing all the assets for one level is loaded in one batch.</li>
      <li>Doom3 assets used to be all text based (ref). In order to lower loading time, some of the assets such as models and animations are now binary (<code>.bmd5mesh</code> and <code>.bmd5anim</code>).</li>
      <li>Doom3 was designed to run at 640x480 with a 4:3 aspect ratio. Since TV and Monitors are now 16:9, all the menu have been redone. Probably in order to speed up development, 
      they are implemented in Adobe Flash. Doom3 BFG runs its own Flash interpreter (<code>/neo/swf/</code> folder). Again Flash was used in order to speed up development.</li>
      <li>The renderer shaders have been rewritten using GLSL 1.5. HLSL shaders can be converted on the fly.<br/></li>
      <li>In order to have acceptable framerate, the "Flash light" could not
          be used simultaneously with weapons on PC. Now with Doom 3 BFG it can be duck taped on weapons but for performances
          reason it won't cast any shadows.
          </li>
      <li>Since all menus are cross-platforms, the PC has lost much of the renderer settings: We get a simple version that satisfies both PC and Consoles.</li>
    </ol>
    </p>
    
    
    
    
    <br/>
    <h2>Multi-threading</h2>
    <p>
      <img src="../fd_proxy/doom3_bfg/doom3_idParallelJobManager_thumb.png" style="width: 251px; height: 248px; float:left; margin-right:10px;"/>
       The new and the old engine materialize the shift of paradigm that occurred over the past 10 years:
       The "free lunch" is over and game engines must be designed with multi-threading in mind in order to wrap around multi-core machines.<br/>
       <br/>
      Hence the most appealing thing to read from Doom III BFG is idTech5 threading architecture. A detailed review can be found on a <a href="threading.php">dedicated page</a>.
       <div style="clear:both"></div>
    </p>
    
  
    
    <br/>
    <h2>Renderer</h2>
    <p>
      <img src="../fd_proxy/doom3_bfg/renderer_threading_model_mini.png" style="width: 251px; height:212px; float:left; margin-right:10px;"/>
      
    The Renderer has been updated: The two main changes are:
    <ul style="overflow: hidden;">
      <li>It runs on Open GL 3.2 Compatibility profile using GLSL 1.5 shaders.</li>
      <li>It is heavily multi-threaded (with up to four threads running concurrently).</li>
    </ul>
    <p>
      It is detailed in a <a href="renderer.php">dedicated page</a>.
       <div style="clear:both"></div>
    </p>
    
    
   
    
    <br/>
    <h2>Doom Classic</h2>
    <p>
    <img src="../fd_proxy/doom3_bfg/doom3_doomClassic_stateMachine_thumb.png" style="width:251px; height:235px; float:left; margin-right:10px;"/>
    Doom III BFG allows to play Doom 1 and Doom 2. <br/>
    <br/>
    At first it sounds like a trivial exercise to integrate the old Doom1 engine into the new Doom3 BFG: Just redirect all Inputs/Outputs ! But allowing multiple players in split-screen on PS3 and Xbox360 involved doing something idTech1 was never meant to perform.<br/>
    <br/>More in the <a href="DooM_Classic.php">dedicated page</a>.
     <div style="clear:both"></div>
    </p>
    
    
    <br/>
    <h2>Recommended Readings</h2>
    <p>
      <br/>
      <u>Mathematics for Game Programming :</u><br/>
      <br/>
    <a href="crap.txt"><img src="../fd_proxy/doom3_bfg/books/math_for_3D_game_programming.jpg" style="width: 159px; height:200px; float:left; margin-right:10px;"/></a>
    <a href="http://www.amazon.com/Math-Primer-Graphics-Game-Development/dp/1568817231/ref=sr_1_1?s=books&ie=UTF8&qid=1367597689&sr=1-1&keywords=math+primer+game"><img src="../fd_proxy/doom3_bfg/books/math_primer.jpg"  style="width: 162px; height:200px; float:left; margin-right:20px;"/></a>
    A few years ago I bought the famous <a href="http://www.amazon.com/Mathematics-Programming-Computer-Graphics-Second/dp/1584502770/ref=sr_1_3?s=books&ie=UTF8&qid=1367597590&sr=1-3&keywords=Mathematics+for+3d+Game+Programming+and+Computer+Graphics">Mathematics for 3D Game Programming and Computer Graphics</a>.
    ..which is horrible and almost useless (more for mathematicians than game programmers). 
    After that I stayed away from proclaimed "math for games books". Thanks to a co-worker I recently came across 
    <a href="http://www.amazon.com/Math-Primer-Graphics-Game-Development/dp/1568817231/ref=sr_1_1?s=books&ie=UTF8&qid=1367597689&sr=1-1&keywords=math+primer+game">3D Math Primer for Graphics and Game Development</a> 
    which is THE math book that any Game Developer MUST have on his bookshelf. If you don't have it already, order it <a href="http://www.amazon.com/Math-Primer-Graphics-Game-Development/dp/1568817231/ref=sr_1_1?s=books&ie=UTF8&qid=1367597689&sr=1-1&keywords=math+primer+game">now</a>. As far as I know it is the only book that features
    all visualization tricks such as "see a dot product like a projection" and other gems. <br/>
    <div style="clear:both;"/>
       

    <p>
      <br/>
      <br/>
    <u>Systems :</u><br/>
    <br/>
    <a href="http://www.intel.com/content/www/us/en/processors/architectures-software-developer-manuals.html"><img src="../fd_proxy/doom3_bfg/books/intel_doc.jpg" style="width:331px; height:247px; float:left; margin-right:10px;"/></a>
    If like me you have an interest in Operating System internals and enjoy discovering how things work when you leave user-space, you will appreciate <a href="http://www.intel.com/content/www/us/en/processors/architectures-software-developer-manuals.html">Intel64 and IA-32 System Programming Guide</a>.
    It is well written and features many drawing detailing implementation specifics that are usually left out 
    in OS books.
    <div style="clear:both;"/>

    <p>
      <br/>
      <br/>
    <u>Inspiration :</u><br/>
    <br/>
    <a href="http://www.amazon.com/The-Way-Zen-Alan-Watts/dp/0375705104/ref=sr_1_1?ie=UTF8&qid=1368480701&sr=8-1&keywords=way+of+zen"><img src="../fd_proxy/doom3_bfg/books/way-of-zen.jpg" style="width: 134px; height:200px; float:left; margin-right:53px;"/></a>
    <a href="http://www.amazon.com/Oh-Places-Youll-Dr-Seuss/dp/0679805273/ref=sr_1_1?s=books&ie=UTF8&qid=1368480725&sr=1-1&keywords=place+you%27ll+go"><img src="../fd_proxy/doom3_bfg/books/Oh,_the_Places_You'll_Go.jpg" style="width: 144px; height: 200px; float:left; margin-right:30px;"/></a>
    And since I could not work without inspiration and internal peace, here are two books that helped me a lot.
    They are really good: 98 and &#190; percent guaranteed :) !
    <div style="clear:both;"/>
    </p>    
    
    <br/>
    <h2>Next</h2>
    <p>
      <a href="threading.php">Threading system</a>.
    </p>
    
  <!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

