<script type="text/javascript">
  var disqus_identifier = "Fluid";
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Fluid simulation on iPhone"/>
		<meta name="Description" content="Fluid simulation on iPhone"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>Fluid</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       April 15, 2009</div>
   <h1>Fluid</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="fluide.jpg" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         
I finally finished "Fluid", a FREE interactive water simulation for iPhone. While it is being reviewed by Apple, 
here is a short article describing how it's done....and the source code ;) ! Download for iphone: <br/>
				<img src="carvedAppStore.png"/>

		<div style="clear:both;"></div>
<h3>Video</h3>

	<center>
		<object width="425" height="344"><param name="movie" value="http://www.youtube.com/v/H3Kp4W3Wke0&hl=en&fs=1"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="https://www.youtube.com/v/H3Kp4W3Wke0&hl=en&fs=1" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="425" height="344"></embed></object>
		</center>				
			</p>
			

			
			<h3>Simulation
			</h3>
			<p id="paperbox">This water simulation uses a very old algorithm based on two heightmaps:<br/>
				<ul>
			 		<li>Take the screen and slice it as a grid (the more slices, the better it looks). This is done via a double array (<code>int simulation1[][]</code>), olding the height of each wave,</li>
			 		<li>In order to animate, we will need an other array: <code>int simulation2[][]</code>, with the exact same dimension as simulation1.</li>
			 		<li>To make everything move, use the following algorithm:</li>
			 	</ul>
			 	<pre>
			 		
	#define CURRENT_HEIGHTMAP (* simulation1)
	#define PREVIUS_HEIGHTMAP (* simulation2)

	for(x=1; x<=FLOTSIZE; x++)
	for(y=1; y<=FLOTSIZE; y ++)
	{
		CURRENT_HEIGHTMAP[x][y] = 
			((PREVIUS_HEIGHTMAP[x-1][y]+
			PREVIUS_HEIGHTMAP[x+1][y]+
			PREVIUS_HEIGHTMAP[x][y-1]+
			PREVIUS_HEIGHTMAP[x][y+1]) / 2) - CURRENT_HEIGHTMAP[x][y];
			
		//Drag (otherwise water never stop moving)
		CURRENT_HEIGHTMAP[x][y] -= CURRENT_HEIGHTMAP[x][y] * DRAG;		
	}

			 	</pre>
<p>
			 	And that's it! Set an initial height perturbation in the last state, iterate at 30fps: Voila des vagues !
</p>
			 </p>
			
			
			<h3>Rendition
			</h3>
<p id="paperbox">
	From the heigthmap, we then generate a mesh. Assuming that every pixel ray come to the mesh at (0,0,-1), we can generate a perturbated View Vector. We use these pertubated vectors to offest the textures coordinates.
	
</p>
			
			<h3>Performance
			</h3>
<p id="paperbox">
	Right now, only reflection and refraction are simulated via a bottom texture and an environment map texture. The rendition requires two passes.<br/>
	I tried to add the caustics but without multi texturing, this would have requiered a third pass, unafforable for now.<br/>
	<br/>
	<br/>
	Running at 30fps:<br/>
	<br/>
	<ul>
		<li>179 200 fragments op/frame( 320 * 280 * 2).</li>
		<li>13 680 vertices/frame. (6840 * 2)</li>
		<li>6 960 faces/frame (3480 * 2)</li>
	</ul>

</p>		
			<h3>Updates
			</h3>
<cite>February 23, 2011.</cite><br/>
<h3>Cannot see the menu in Fluid2 ?</h3><br/>


<p id="paperbox">
In Fluid2 the menu does not appear automatically: You can bring it up by pressing FIVE FINGERS simultaneously on the screen :) !
</p>


<cite> October 26th, 2011.</cite><br/>
<h3>iOS 5 iPad: Disabled "album" button :( !</h3><br/>
<p id="paperbox">
I've received numerous emails mentioning Fluid and Fluid2's "Choose from album" button is disabled for iPad users. The issue has been identified and 
and updated version has been sent to Apple. It should be out shortly ;) ! 
</p>
</br></br>

<cite> April 12, 2011.</cite><br/>
<h3>iPad "Change background" bug</h3><br/>
<p id="paperbox">
I've received numerous emails from users mentioning they cannot select a picture from an album since they updated to iOS 4.3.1. It seems the last update broke this feature, but I have fixed this issue now and submitted a new build to Apple, hopefully it will be approved soon.
</p>
</br></br>
	

<cite> July 02, 2010.</cite><br/>
<h3>iOS 4 crash :( !</h3><br/>
<p id="paperbox">
I've received numerous emails mentioning Fluid and Fluid2 crash on second launch after updating to iOS 4. I've worked around the clock to generate a patch and it is now sent to Apple. I've also contacted the hotline so it will be considered an emergency fix. I keep my finger crossed it won't take too long to get to you guys.
</p>
</br></br>
		
			

<cite> June 29, 2009.</cite><br/>
<h3>Is "Fluid" too fast ?!</h3><br/>
                        <p id="paperbox">
A few person emailed me since the released of "Fluid v1.3". It seems that it is running too fast now. The reason this issue was undetected is that I am doing all my testing on my personnal iPhone (First generation). Fluid v1.3 is using the optimized engine of <a href="http://phobos.apple.com/WebObjects/MZStore.woa/wa/viewSoftware?id=317959717&mt=8">"Fluid 2"</a> but I did not notice the change until I saw the application running on my friend's 3GS.<br/>
</br>
<u>The solution</u><br/>
<br/>
I'm getting a 3GS from the Apple Store this afternoon, I will release a fix tonight: "Fluid v1.4" and "Fluid 2.1". The speed will be constant with ability to control it further via a slider. I hope Apple won't take forever to released them.<br/>
<br/>
<u>Screenshot of the upcoming update</u>
<br/><br/><img src="fluidSpeedSlider.jpg" style="padding: 5px;"/><br/>
</p>
<br/><br/>
<cite>June 9, 2009.</cite><br/><br/>
                        <h3>3,000,000 downloads...version 2.0 released !</h3><br/>
                        <p id="paperbox">
I am very proud to announce the release of "Fluid 2" on the Appstore !
Check it out: <br/><br/><a href="http://itunes.apple.com/WebObjects/MZStore.woa/wa/viewSoftware?id=317959717&mt=8"><img src="carvedAppStore.png"/></a><br/> <br/><br/>
More freedom on the menu:<br/>
<br/>
<ul>
<li>Ability to make a wish by throwing a coin in the water.
<li>Ability to change the color of that water.
<li>Ability to set the friction level.
<li>Option panel is now hidden by default.
<li>Lot and lot of bug fixes.
</ul>
</p>

<p>
                        <img src="fluid2_1.jpg" style="padding: 5px;"/><img src="fluid2_2.jpg" style="padding: 5px;"/><br/>
                        <img src="fluid2_3.jpg" style="padding: 5px;"/><img src="fluid2_4.jpg" style="padding: 5px;" />
                        </p>


<br/><br/>
			<cite>May 14, 2009.</cite><br/><br/>
			<h3>1,000,000 downloads...version 1.2 coming !</h3><br/>
			<p id="paperbox">
				Never I would have expected so many downloads. I've received numerous positive review for the version 1.1 of Fluid.<br/>
				I'm working hard on fixing every bug reported, I just sent the version 1.2 to Apple:
				<ul>
					<li>Background modification now works for any picture of any format.</li>
					<li>Music is no longer mandatory, iPod music will keep playing if you turn Fluid's music off.</li>
					<li>Music button never gets out of sync.</li>
				</ul>
				<p>
					Next week, I will keep fixing bug in order to release a version 1.3...and also "Fluid Premium". Stay tuned.
				</p>

			</p>
			<br/>
			<br/>
			<br/>
			<cite>May 9, 2009.</cite><br/><br/>
	

			<h3>700,000 downloads...and counting !</h3><br/>
			<p id="paperbox">	
				Not bad for what was supposed to be just a "demo" during my job hunting process.<br/>
			 A lot of people have asked for a music and ability to change the background. Version 1.1 is currently being reviewed by Apple and will allow this:<br/><br/>
			<ul>
				<li>Option panel by pressing four fingers simultaneously.</li>
				<li>Ability to change background.</li>
				<li>Zen music (Lullaby by Ghost which you can listen <a href="https://www.youtube.com/watch?v=acEYrld-9sQ">here</a>).</li>
				<li>Support for multi-fingers.</li>
			</ul>
			<p>
			<img src="menu.jpg" style="padding: 5px;"/><img src="selection.jpg" style="padding: 5px;"/><br/>
			<img src="camera.jpg" style="padding: 5px;"/><img src="go.jpg" style="padding: 5px;" />
			</p>
			</p>
<br/>

		
					 	

				

<br/>
    <div style="clear:both;"></div>
</p>
<!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>


