<script type="text/javascript">
  var disqus_identifier = "mtg_93-94_Toronto";
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Magic The Gathering Old school: Format 93/94 in Toronto"/>
		<meta name="Description" content="Magic The Gathering: Format 93/94 in Toronto"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>Magic The Gathering Old school: Format 93/94 in Toronto</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       November 1st, 2012</div>
   <h1>Magic The Gathering Old school: Format 93/94 in Toronto</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="event2.php" style="display:none;" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
          


<script type="text/javascript" src="../js/highslide-full.js"></script>

<script type="text/javascript">
   hs.dimmingOpacity = 0.75;
</script>

<link rel="stylesheet" href="../js/highslide.css" type="text/css" />
<style type="text/css">
.highslide-dimming {
	background: black;
}

.closebutton {
   position: relative;
   top: -15px;
   left: 15px;
   width: 30px;
   height: 30px;
   cursor: pointer;
   background: url(../js/graphics/close.png);
   /* NOTE! For IE6, you also need to update the highslide-ie6.css file. */
}

</style>

<script type="text/javascript">
    hs.graphicsDir = '../js/graphics/';
</script>


On December 15th, 2012 we gathered again to playtest several 93/94 deck. Here are a few pictures of the event:<br/>
<br/>
<a  href="event2/DSC00054.jpeg" class="highslide" onclick="return hs.expand(this,{wrapperClassName: 'borderless floating-caption', dimmingOpacity: 0.75, align: 'center'})">
  <img src="event2/thumb/DSC00054_thumb.png" style="box-shadow: #777 3px 3px 3px; margin: 15px 15px 0px 0px;"   />
</a>
<a  href="event2/DSC00061.jpeg" class="highslide" onclick="return hs.expand(this,{wrapperClassName: 'borderless floating-caption', dimmingOpacity: 0.75, align: 'center'})">
  <img src="event2/thumb/DSC00061_thumb.png" style="box-shadow: #777 3px 3px 3px; margin: 15px 15px 0px 0px;"   />
</a>
<a  href="event2/DSC00065.jpeg" class="highslide" onclick="return hs.expand(this,{wrapperClassName: 'borderless floating-caption', dimmingOpacity: 0.75, align: 'center'})">
  <img src="event2/thumb/DSC00065_thumb.png" style="box-shadow: #777 3px 3px 3px; margin: 15px 15px 0px 0px;"   />
</a>
<br/><br/><br/>
Chaos Orb turned out to be A LOT OF FUN :
<br/>
<a  href="event2/DSC00063.jpeg" class="highslide" onclick="return hs.expand(this,{wrapperClassName: 'borderless floating-caption', dimmingOpacity: 0.75, align: 'center'})">
  <img src="event2/thumb/DSC00063_thumb.png" style="box-shadow: #777 3px 3px 3px; margin: 15px 15px 0px 0px;"   />
</a>
<a  href="event2/DSC00062.jpeg" class="highslide" onclick="return hs.expand(this,{wrapperClassName: 'borderless floating-caption', dimmingOpacity: 0.75, align: 'center'})">
  <img src="event2/thumb/DSC00062_thumb.png" style="box-shadow: #777 3px 3px 3px; margin: 15px 15px 0px 0px;"   />
</a>
<br/><br/>
Three decks emerged very strongly from the day:<br/>
<br/>
Brandon's All Black:<br/>
<a  href="event2/64042_4084813532808_134731186_n.jpeg" class="highslide" onclick="return hs.expand(this,{wrapperClassName: 'borderless floating-caption', dimmingOpacity: 0.75, align: 'center'})">
  <img src="event2/thumb/64042_4084813532808_134731186_n_thumb.png" style="box-shadow: #777 3px 3px 3px; margin: 15px 15px 0px 0px;"   />
</a><br/>
<br/>
David's "boring" keeper:<br/>
<a  href="event2/167471_10100377107630891_1697462540_n.jpeg" class="highslide" onclick="return hs.expand(this,{wrapperClassName: 'borderless floating-caption', dimmingOpacity: 0.75, align: 'center'})">
  <img src="event2/thumb/167471_10100377107630891_1697462540_n_thumb.png" style="box-shadow: #777 3px 3px 3px; margin: 15px 15px 0px 0px;"   />
</a><br/>
<br/>
Andrew's manadrained Zoo:<br/>
<a  href="event2/DSC_0791.JPG" class="highslide" onclick="return hs.expand(this,{wrapperClassName: 'borderless floating-caption', dimmingOpacity: 0.75, align: 'center'})">
  <img src="event2/thumb/DSC_0791_thumb.png" style="box-shadow: #777 3px 3px 3px; margin: 15px 15px 0px 0px;"   />
</a>
<a  href="event2/DSC_0792.JPG" class="highslide" onclick="return hs.expand(this,{wrapperClassName: 'borderless floating-caption', dimmingOpacity: 0.75, align: 'center'})">
  <img src="event2/thumb/DSC_0792_thumb.png" style="box-shadow: #777 3px 3px 3px; margin: 15px 15px 0px 0px;"   />
</a>

<br/>
<br/>
On a personnal basis: I played 15 games and won 2 :/ !

<!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

