<script type="text/javascript">
  var disqus_identifier = "mtg_93-94_Toronto";
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="1994 MTG Championship Final Rewinded"/>
		<meta name="Description" content="1994 MTG Championship Final Rewinded"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>1994 MTG Championship Final Rewinded</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       November 1st, 2012</div>
   <h1>1994 MTG Championship Final Rewinded</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="event1.php" style="display:none;" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
          


<script type="text/javascript" src="../js/highslide-full.js"></script>

<script type="text/javascript">
   hs.dimmingOpacity = 0.75;
</script>

<link rel="stylesheet" href="../js/highslide.css" type="text/css" />
<style type="text/css">
.highslide-dimming {
	background: black;
}

.closebutton {
   position: relative;
   top: -15px;
   left: 15px;
   width: 30px;
   height: 30px;
   cursor: pointer;
   background: url(../js/graphics/close.png);
   /* NOTE! For IE6, you also need to update the highslide-ie6.css file. */
}

</style>

<script type="text/javascript">
    hs.graphicsDir = '../js/graphics/';
</script>


On Wednesday, November 7th 2012 we re-played the <a href="https://www.wizards.com/Magic/Magazine/Article.aspx?x=mtgcom/feature/226zakdiary">MTG 1994 world championship 
final</a> between ZAK DOLAN and BERTRAND LESTREE. Here are the decks, pictures and reports of the event.


<div style="clear: both;"/>


<h1>Zak Dolan's 1994 Champion Deck</h1>

<p id="paperbox">

<div style="float:right; margin-left:20px;">
<img  src="icy.png"  style="margin-bottom: 12px;"  />
<br/>
<img  src="tundra.png" style="margin-bottom: 12px;"    /> 
<br/>
<img  src="stasis.png"  style="margin-bottom: 12px;"   />
<br/>
<img  src="howling.png"  style="margin-bottom: 12px;"   />

</div>
Zan Dolan's "Keeper/Statis" decklist can be found <a href="http://www.wizards.com/magic/magazine/article.aspx?x=mtg/daily/deck/37">here</a>.
<br/><br/>
<img  src="../fd_proxy/mtg/newdecks/DSC_0022.JPG" style="margin: 10px auto; display: inline;"   />
<div style="clear: both;"/>
</p>


<h1>Bertrand Lestree's 1994 finalist Deck</h1>

<p id="paperbox">

<div style="float:right; margin-left:20px;">
<img  src="psionic.png"  style="margin-bottom: 12px;"  />
<br/>
<img  src="channel.png" style="margin-bottom: 12px;"    /> 
<br/>
<img  src="fireball.png"  style="margin-bottom: 12px;"   />
<br/>
<img  src="chain.png"  style="margin-bottom: 12px;"   />

</div>

Bertrand Lestree's "Zoo/This should have been the world champion" decklist can be found 
<a href="https://www.wizards.com/Magic/Magazine/Article.aspx?x=mtgcom/feature/226zakdiary">here</a>. Note that the Chaos Orb was replaced by a Sylvan Library for the final.
<br/><br/>
<img  src="../fd_proxy/mtg/newdecks/DSC_0025.JPG" style="margin: 10px auto; display: inline;"   />
<div style="clear: both;"/>
</p>

</p>



<h1>Pictures of the 1994 Final rematch</h1>

<p id="paperbox">

Andrew decided to play like it is <b>really</b> 1994 and proceeded to remove all cards from their sleeves.<br/>
<a  href="../fd_proxy/mtg/final_1994/IMG_3265.JPG" class="highslide" onclick="return hs.expand(this,{wrapperClassName: 'borderless floating-caption', dimmingOpacity: 0.75, align: 'center'})"><img src="../fd_proxy/mtg/final_1994/thumbnails/IMG_3265_thumb.png" style="box-shadow: #777 3px 3px 3px; margin: 15px 15px 0px 0px;"  /></a>
<a  href="../fd_proxy/mtg/final_1994/IMG_3271.JPG" class="highslide" onclick="return hs.expand(this,{wrapperClassName: 'borderless floating-caption', dimmingOpacity: 0.75, align: 'center'})"><img src="../fd_proxy/mtg/final_1994/thumbnails/IMG_3271_thumb.png" style="box-shadow: #777 3px 3px 3px; margin: 15px 15px 0px 0px;"   /></a>
<br/><br/>
As if it is was not badass enough he topped it by riffle shuffling his deck: P9 and dual lands included:<br/>
<br/>
<iframe width="560" height="315" src="http://www.youtube.com/embed/r6CgZakp-9A?list=UUiYMOn8yevrfOIrRnpfYeag&amp;hl=en_GB" frameborder="0" allowfullscreen></iframe><br/>
<br/>
Eventually we proceeded to play the final like it's 1994: France vs USA:
<br/>
<a  href="../fd_proxy/mtg/final_1994/IMG_3270.JPG" class="highslide" onclick="return hs.expand(this,{wrapperClassName: 'borderless floating-caption', dimmingOpacity: 0.75, align: 'center'})"><img src="../fd_proxy/mtg/final_1994/thumbnails/IMG_3270_thumb.png" style="box-shadow: #777 3px 3px 3px; margin: 15px 15px 0px 0px;"    /></a>
<a  href="../fd_proxy/mtg/final_1994/IMG_3273.JPG" class="highslide" onclick="return hs.expand(this,{wrapperClassName: 'borderless floating-caption', dimmingOpacity: 0.75, align: 'center'})"><img src="../fd_proxy/mtg/final_1994/thumbnails/IMG_3273_thumb.png" style="box-shadow: #777 3px 3px 3px; margin: 15px 15px 0px 0px;" "   /></a>
<a  href="../fd_proxy/mtg/final_1994/IMG_3277.JPG" class="highslide" onclick="return hs.expand(this,{wrapperClassName: 'borderless floating-caption', dimmingOpacity: 0.75, align: 'center'})"><img src="../fd_proxy/mtg/final_1994/thumbnails/IMG_3277_thumb.png" style="box-shadow: #777 3px 3px 3px; margin: 15px 15px 0px 0px;" "   /></a>
<br/>



<a  href="../fd_proxy/mtg/final_1994/IMG_3279.JPG" class="highslide" onclick="return hs.expand(this,{wrapperClassName: 'borderless floating-caption', dimmingOpacity: 0.75, align: 'center'})"><img src="../fd_proxy/mtg/final_1994/thumbnails/IMG_3279_thumb.png" style="box-shadow: #777 3px 3px 3px; margin: 15px 15px 0px 0px;"   /></a>

<a  href="../fd_proxy/mtg/final_1994/IMG_3283.JPG" class="highslide" onclick="return hs.expand(this,{wrapperClassName: 'borderless floating-caption', dimmingOpacity: 0.75, align: 'center'})"><img src="../fd_proxy/mtg/final_1994/thumbnails/IMG_3283_thumb.png" style="box-shadow: #777 3px 3px 3px; margin: 15px 15px 0px 0px;"   /></a>
<br/>
<br/>
<br/>
Two typical ways to finish the game for Zak Dolan's deck: Two Serra angels beating....or Ivory Tower at 41 Health Points:
<br/>
<a  href="../fd_proxy/mtg/final_1994/IMG_3285.JPG" class="highslide" onclick="return hs.expand(this,{wrapperClassName: 'borderless floating-caption', dimmingOpacity: 0.75, align: 'center'})"><img src="../fd_proxy/mtg/final_1994/thumbnails/IMG_3285_thumb.png" style="box-shadow: #777 3px 3px 3px; margin: 15px 15px 0px 0px;"   /></a>
<a  href="../fd_proxy/mtg/final_1994/IMG_3287.JPG" class="highslide" onclick="return hs.expand(this,{wrapperClassName: 'borderless floating-caption', dimmingOpacity: 0.75, align: 'center'})"><img src="../fd_proxy/mtg/final_1994/thumbnails/IMG_3287_thumb.png" style="box-shadow: #777 3px 3px 3px; margin: 15px 15px 0px 0px;"   /></a>

<br/>

<br/>
Side time. Bertrand Lestree's post side deck is a BEAST. The addition of Serendib Efreet instead of the Birds of Paradise makes it so much more efficient that they probably should have been maindeck. The maindeck Birds remain a mystery to us: <br/>
<a  href="../fd_proxy/mtg/final_1994/IMG_3293.JPG" class="highslide" onclick="return hs.expand(this,{wrapperClassName: 'borderless floating-caption', dimmingOpacity: 0.75, align: 'center'})"><img src="../fd_proxy/mtg/final_1994/thumbnails/IMG_3293_thumb.png" style="box-shadow: #777 3px 3px 3px; margin: 15px 15px 0px 0px;"   /></a>
<a  href="../fd_proxy/mtg/final_1994/IMG_3281.JPG" class="highslide" onclick="return hs.expand(this,{wrapperClassName: 'borderless floating-caption', dimmingOpacity: 0.75, align: 'center'})"><img src="../fd_proxy/mtg/final_1994/thumbnails/IMG_3281_thumb.png" style="box-shadow: #777 3px 3px 3px; margin: 15px 15px 0px 0px;"   /></a>
<br/>
<br/>


Some more games:
<br/>
<a  href="../fd_proxy/mtg/final_1994/IMG_3299.JPG" class="highslide" onclick="return hs.expand(this,{wrapperClassName: 'borderless floating-caption', dimmingOpacity: 0.75, align: 'center'})"><img src="../fd_proxy/mtg/final_1994/thumbnails/IMG_3299_thumb.png" style="box-shadow: #777 3px 3px 3px; margin: 15px 15px 0px 0px;"   /></a>
<a  href="../fd_proxy/mtg/final_1994/IMG_3301.JPG" class="highslide" onclick="return hs.expand(this,{wrapperClassName: 'borderless floating-caption', dimmingOpacity: 0.75, align: 'center'})"><img src="../fd_proxy/mtg/final_1994/thumbnails/IMG_3301_thumb.png" style="box-shadow: #777 3px 3px 3px; margin: 15px 15px 0px 0px;"   /></a>
<br/>
<br/>
And then we switched deck (at this point the score was 6-4 for Bertrand Lestree's creation). And it was my turn to WIN !
<br/>

<a  href="../fd_proxy/mtg/final_1994/IMG_3303.JPG" class="highslide" onclick="return hs.expand(this,{wrapperClassName: 'borderless floating-caption', dimmingOpacity: 0.75, align: 'center'})"><img src="../fd_proxy/mtg/final_1994/thumbnails/IMG_3303_thumb.png" style="box-shadow: #777 3px 3px 3px; margin: 15px 15px 0px 0px;"   /></a>
<a  href="../fd_proxy/mtg/final_1994/IMG_3275.JPG" class="highslide" onclick="return hs.expand(this,{wrapperClassName: 'borderless floating-caption', dimmingOpacity: 0.75, align: 'center'})"><img src="../fd_proxy/mtg/final_1994/thumbnails/IMG_3275_thumb.png" style="box-shadow: #777 3px 3px 3px; margin: 15px 15px 0px 0px;" "   /></a>
<br/>
<br/>
Two opening hands came close to be a first time win via the famous combo: Channel+Fireball+Black Lotus+Land....but we still managed to pull one of those in mid-game:<br/>

<a  href="../fd_proxy/mtg/final_1994/IMG_3305.JPG" class="highslide" onclick="return hs.expand(this,{wrapperClassName: 'borderless floating-caption', dimmingOpacity: 0.75, align: 'center'})"><img src="../fd_proxy/mtg/final_1994/thumbnails/IMG_3305_thumb.png" style="box-shadow: #777 3px 3px 3px; margin: 15px 15px 0px 0px;"   /></a>
<a  href="../fd_proxy/mtg/final_1994/IMG_3309.JPG" class="highslide" onclick="return hs.expand(this,{wrapperClassName: 'borderless floating-caption', dimmingOpacity: 0.75, align: 'center'})"><img src="../fd_proxy/mtg/final_1994/thumbnails/IMG_3309_thumb.png" style="box-shadow: #777 3px 3px 3px; margin: 15px 15px 0px 0px;"   /></a>
<a  href="../fd_proxy/mtg/final_1994/IMG_3311.JPG" class="highslide" onclick="return hs.expand(this,{wrapperClassName: 'borderless floating-caption', dimmingOpacity: 0.75, align: 'center'})"><img src="../fd_proxy/mtg/final_1994/thumbnails/IMG_3311_thumb.png" style="box-shadow: #777 3px 3px 3px; margin: 15px 15px 0px 0px;"   /></a>


<a  href="../fd_proxy/mtg/final_1994/IMG_3313.JPG" class="highslide" onclick="return hs.expand(this,{wrapperClassName: 'borderless floating-caption', dimmingOpacity: 0.75, align: 'center'})"><img src="../fd_proxy/mtg/final_1994/thumbnails/IMG_3313_thumb.png" style="box-shadow: #777 3px 3px 3px; margin: 15px 15px 0px 0px;"   /></a>
<br/>
<br/>
<br/>
Andrew decided to let the skills do the talking and managed to wipe my board and beat me with angels:<br/>

<a  href="../fd_proxy/mtg/final_1994/IMG_3315.JPG" class="highslide" onclick="return hs.expand(this,{wrapperClassName: 'borderless floating-caption', dimmingOpacity: 0.75, align: 'center'})"><img src="../fd_proxy/mtg/final_1994/thumbnails/IMG_3315_thumb.png" style="box-shadow: #777 3px 3px 3px; margin: 15px 15px 0px 0px;"   /></a>
<a  href="../fd_proxy/mtg/final_1994/IMG_3317.JPG" class="highslide" onclick="return hs.expand(this,{wrapperClassName: 'borderless floating-caption', dimmingOpacity: 0.75, align: 'center'})"><img src="../fd_proxy/mtg/final_1994/thumbnails/IMG_3317_thumb.png" style="box-shadow: #777 3px 3px 3px; margin: 15px 15px 0px 0px;"   /></a>
<a  href="../fd_proxy/mtg/final_1994/IMG_3319.JPG" class="highslide" onclick="return hs.expand(this,{wrapperClassName: 'borderless floating-caption', dimmingOpacity: 0.75, align: 'center'})"><img src="../fd_proxy/mtg/final_1994/thumbnails/IMG_3319_thumb.png" style="box-shadow: #777 3px 3px 3px; margin: 15px 15px 0px 0px;"   /></a>
<br/>
<br/>
Andrew's deck:<br/>
<a  href="../fd_proxy/mtg/final_1994/IMG_3323.JPG" class="highslide" onclick="return hs.expand(this,{wrapperClassName: 'borderless floating-caption', dimmingOpacity: 0.75, align: 'center', captionText: 'This is the caption text'})"><img src="../fd_proxy/mtg/final_1994/thumbnails/IMG_3323_thumb.png" style="box-shadow: #777 3px 3px 3px; margin: 15px 15px 0px 0px;"   /></a>
<br/>
<br/>
</p>
<h1>Post-mortem</h1>

<p id="paperbox">
In total we played 18 games: Bertrand Lestree: 11- Zak Dolan: 7. <br/>
<br/>
Zack Dolan's deck was not as bad as it looked on paper but It should never have won the final in 1995: The manabase proved unstable and it lack dedication: Trying to be Prison/Stasis and also Control but doing none of them consistently.
Sometimes you can get an Angel out and clone it for a victory but it is a rare occurence.<br/>
<br/>
The win condition seems to be <u>Library of Alexandria.</u> If you read the <a href="https://www.wizards.com/Magic/Magazine/Article.aspx?x=mtgcom/feature/226zakdiary">1994 
report</a> you will see that having the Library in starting hand is a HUGE advantage. In the end it is probable that Bertrand Lestree 
should have been the first MTG champion in 1994....but destiny decided otherwise.
</p>

<h1>Additional reading</h1>

<p id="paperbox">
  If you like old school deck or just want to learn more about the first MTG World Champion, here are a few more articles:
  <ul>
      <li>A Starcitygames.com exclusise: "<a href="http://www.starcitygames.com/magic/misc/20421_Untold_Legends_Early_Days.html">Untold Legends Early Days</a>".</li>
      
  </ul>
</p>

<!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

