<script type="text/javascript">
  var disqus_identifier = "mtg_93-94_old_cards";
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Magic The Gathering Old school: Poor/Heavily Played cards"/>
		<meta name="Description" content="Magic The Gathering Old school: Poor/Heavily Played cards"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>Magic The Gathering Old school: Poor/Heavily Played cards</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="https://fabiensanglard.net/" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="http://fabiensanglard.net/" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="http://fabiensanglard.net/about/">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="http://fabiensanglard.net/faq/">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="http://fabiensanglard.net/rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="http://fabiensanglard.net/rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="http://fabiensanglard.net/rss.xml" />
<div id="date">
       December 10th, 2015</div>
   <h1>Magic The Gathering Old school: Poor/Heavily Played cards</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="index.php" style="display:none;" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
          




<link rel="stylesheet" href="../js/highslide.css" type="text/css" />
<style type="text/css">
.highslide-dimming {
	background: black;
}

.closebutton {
   position: relative;
   top: -15px;
   left: 15px;
   width: 30px;
   height: 30px;
   cursor: pointer;
   background: url(../js/graphics/close.png);
   /* NOTE! For IE6, you also need to update the highslide-ie6.css file. */
}

</style>


<p>
Life scratches us. MTG cards are no exceptions. I remember playing 
with my neighbors on the sidewalk, with no sleeves. I like cards with an history.
How many Hypnotic Specter did this ruined Dark Ritual managed to cast ?
How many creatures did this Two-headed Giant of Floriys managed to slay back in the days? 
Memories of a time when Magic was played less seriously...and probably the way it was intended...
You are welcome to share your beatup cards in the comment section :) !<br/>


<p style="background-color:black;">
<img  src="pics/thumb/25784.png" style="margin: 10px; display: inline;"   />
<img  src="pics/thumb/10739.png" style="margin: 10px; display: inline;"   />
<img  src="pics/thumb/8030.png"  style="margin: 10px; display: inline;"   />

<img  src="pics/thumb/doppel.png" style="margin: 10px; display: inline;"   />
<img  src="pics/thumb/bolt.png" style="margin: 10px; display: inline;"   />
<img  src="pics/thumb/shivan.png" style="margin: 10px; display: inline;"   />

<img  src="pics/thumb/24938.png" style="margin: 10px; display: inline;"   />
<img  src="pics/thumb/birds.png" style="margin: 10px; display: inline;"   />
<img  src="pics/thumb/15850.png" style="margin: 10px; display: inline;"   />

<img  src="pics/thumb/12175.png" style="margin: 10px; display: inline;"   />
<img  src="pics/thumb/20785.png" style="margin: 10px; display: inline;"   />
<img  src="pics/thumb/6501.png" style="margin: 10px; display: inline;"   />

<img  src="pics/thumb/15852.png" style="margin: 10px; display: inline;"   />
<img  src="pics/thumb/16951.png" style="margin: 10px; display: inline;"   />
<img  src="pics/thumb/juzam.png" style="margin: 10px; display: inline;"   />

<img  src="pics/thumb/9568.png"  style="margin: 10px; display: inline;"   /> 
<img  src="pics/thumb/4277.png" style="margin: 10px; display: inline;"   /> 
<img  src="pics/thumb/city.png" style="margin: 10px; display: inline;"   />

<img  src="pics/thumb/willo.png"  style="margin: 10px; display: inline;"   /> 
<img  src="pics/thumb/black.png" style="margin: 10px; display: inline;"   /> 
<img  src="pics/thumb/nightmare.png" style="margin: 10px; display: inline;"   />

<img  src="pics/thumb/psionic.png" style="margin: 10px; display: inline;"   /> 
<img  src="pics/thumb/ali.png" style="margin: 10px; display: inline;"   />
<img  src="pics/thumb/mox_pearl.png" style="margin: 10px; display: inline;"   />

<img  src="pics/thumb/hypno.png" style="margin: 10px; display: inline;"   />
<img  src="pics/thumb/balance.png" style="margin: 10px; display: inline;"   />
<img  src="pics/thumb/solring.png" style="margin: 10px; display: inline;"   />
 
<img  src="pics/thumb/winter_orb.png" style="margin: 10px; display: inline;"   />
<img  src="pics/thumb/vampire.png" style="margin: 10px; display: inline;"   />
<img  src="pics/thumb/sinkhole.png" style="margin: 10px; display: inline;"   />

<img  src="pics/thumb/clone.png" style="margin: 10px; display: inline;"   />
<img  src="pics/thumb/lb.png" style="margin: 10px; display: inline;"   />
<div style="clear: both;"/>
</p>

<STYLE type=text/css>

h1, p { COLOR: #000000 /*The color of all the other text within the body of the page*/
{ 
</STYLE>



<!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

