<script type="text/javascript">
  var disqus_identifier = "doom3_macosx" ;
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Doom3 compilation instructions for Mac OS X."/>
		<meta name="Description" content="Doom3 compilation instructions for Mac OS X."/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>Doom3 compilation instructions for Mac OS X.</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       November, 25th 2011</div>
   <h1>Doom3 compilation instructions for Mac OS X.</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="doom3_macosx.jpg" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         


		<style>
		
		.post a img {

/* This centers the image */
display: block;
margin-left: auto;
margin-right: auto;

/* This adds the border */
padding:8px;
border:solid;
border-color: #dddddd #aaaaaa #aaaaaa #dddddd;
border-width: 1px 2px 2px 1px;
background-color:white;
}

</style>
		
		
			The source code of Doom3 has been released three days ago :) ! I have started to read it and I will probably write a code review if enough people are interested.<br/>
			<br/>
			According to the <code>README.txt</code>  the source code is building well with Visual Studio 2010 but it is not building at all on Mac OS X with XCode 4.0 ( it is actually very broken :( !).<br/>
			<br/>	
			Here are the instructions to get it to run.<br/>
			<br/>
			<u>Note :</u> If you do not want to redo all of this and just want to download Doom3 source code for Xcode 4,
			my fork is available here :<br/>
			<br/>
			<a href="https://github.com/fabiensanglard/Doom3-for-MacOSX-">github doom3 repo with Xcode 4.0 support</a>.
			
		    <br/>
			<br/>
			<!--
			<u>Edit :</u> I have received a few (rude) emails from GitHUB people asking why I did not fork the main repository and re-submit the fix to be merged in the "master" repository:
			<ol>
				<li>I do not believe someone at id is going to merge any fork back to the original release. In other words: There is no master repository. Usually the source is released and never updated (even for bug fixes). A fork would remain in "Pull Request" state forever with
				no visibility at all. It seems there is such a fork now but most people are unaware of it.
				<li>I do not have Visual Studio 2010 and hence cannot make sure my modifications did not break the PC build. I did not want to submit something that may be broken nor take ownership of any side effect bugs
				: This source code is released "as is".
			</ol>	
			<p>
			-->
			<u>Edit :</u> This post describes the entire process for educational purpose only. 
			If fixing the PowerPC intrinsic sheader was trivial ; 
			Fixing linker's <code>ld: bad codegen</code> or <code>ld: illegal text-relocoation </code> were 
			more difficult and I hope some will learn something in the process.
		    <br/>
			<br/>

			<u>Edit :</u> Thanks to John Carmack for <a href="http://twitter.com/#!/ID_AA_Carmack/status/140219823509602304">tweeting</a> about my website (<a href="johnc_tweet.png">mirror</a>).
		    <br/>
			<br/>



			<h3>1. Fix Architecture and Target SDK.</h3>
			<p id="paperbox">	
				
Open the project in neo/sys/osx/Doom3.xcodeproject:<br/>
<br/>
You should see this:<br/>
<br/>
 <div class="post">
					<a  href="../fd_proxy/doom3_macosx/step1.png">
						<img  src="../fd_proxy/doom3_macosx/step1_small.png"/><br/>
					</a>
					</div>

<br/>
<p>	
The first thing to notice is that all the <code>Target SDK</code> are missing:<br/>
<br/>
In all 5 projects:<br/>
<ul>
<li> Change "Architectures" from "ppc i386" to "32-bit Intel"
<li> Change baseSDK value to "Latest MacOSX"
</ul>
<p>
<u>Note:</u> There are two targets in the idlib project, make sure you update the architecture and target SDK in both.
</p>

<br/>
<h3>2. Fix all broken framework references.</h3>
			<p id="paperbox">	
<Br/>
<Br/>
Redefine the broken OpenGL.framework reference in the idlib's two targets:<br/>
<br/>
You should now have something that look like:<br/>
<br/>
<div class="post">
					<a  href="../fd_proxy/doom3_macosx/step2.png">
						<img  src="../fd_proxy/doom3_macosx/step2_small.png"/><br/>
					</a>
					</div>

<br/><br/>
Now is time to fix the missing Carbon.framework, IOKit.framework, OpenGL.framework, CoreAudio.framework references in Doom3 project:<br/>
<br/>
<div class="post">
					<a  href="../fd_proxy/doom3_macosx/step2.1.png">
						<img  src="../fd_proxy/doom3_macosx/step2.1_small.png"/><br/>
					</a>
					</div>

<br/>
</p>


<br/>
<h3>3. Fix ppc_intrinsics.h.</h3>
			<p id="paperbox">
			Since PowerPC are a thing of the past we need to remove all references:<br/>
			<br/>
			Try to build Doom3 Project:<br/>
			<br/>
			<div class="post">
					<a  href="../fd_proxy/doom3_macosx/step3.png">
						<img  src="../fd_proxy/doom3_macosx/step3_small.png"/><br/>
					</a>
					</div>

<br/><br/>
			<br/>
			<p>
The build will fail. It is because <code>PPC_INTRINSICS</code> is automatically defined if <code>MACOS_X</code> is defined (old times when all Macs were PowerPC). The fix is to be more subtle in <code>neo/idlib/math/Simd_AltiVec.h</code>
<pre  class="long">


    #define PPC_INTRINSICS


</pre>
<p>to
<pre  class="long">


   #if defined(MACOS_X) && defined(__ppc__)
     #define PPC_INTRINSICS
   #endif


</pre>
<p>
<u>Tip :</u> Double click on the error, it will take you right to the line you need to comment.

</p>




<br/>
<h3>4. Fix ld linker options.</h3>
			<p id="paperbox">
			
Try to build: It will fail again with this cryptic error message:
<pre  class="long">

    ld: bad codegen, pointer diff in __ZN10idAnimator11CreateFrameEib to global weak symbol __ZN6idCVarD1Ev for architecture i386
    Command /Developer/usr/bin/clang++ failed with exit code 1

</pre>
<p>
For some reason the five projects don't have the same linker flags and this is confusing ld:<br/>
<br/>
For all five projects, make sure:
<ul>
<li>Inline Methods Hidden are set to "No".
<li>Symbols Hidden by Default are set to "No".
</ul>
<p>
			<br/>
						<div class="post">
					<a  href="../fd_proxy/doom3_macosx/step4.png">
						<img  src="../fd_proxy/doom3_macosx/step4_small.png"/><br/>
					</a>
					</div>
<br/><br/>

</p>







<br/>
<h3>5. Fix C++ code.</h3>
			<p id="paperbox">
Let's try to compile again. Surprise it still doesn't work:<br/>
<br/>
			<br/>
						<div class="post">
					<a  href="../fd_proxy/doom3_macosx/step5.png">
						<img  src="../fd_proxy/doom3_macosx/step5_small.png"/><br/>
					</a>
					</div>
<br/><br/>
<pre  class="long">


    /Users/fabiensanglard/raid/dev/TTimo-doom3.gpl-
    1559777/neo/sys/osx/../../tools/compilers/aas/../../../idlib/containers/VectorSet.h:151:2: error:
     use of undeclared identifier 'Append' [3]


</pre>
<p>
The template code is not liked by LLVM, you need to change <code>VectorSet.h</code>:<br/>
<br/>
<pre  class="long">


    Append( v );


</pre>
<p>to
<pre  class="long">


   this->Append( v );


</pre>
</p>




<br/>
<h3>6. Fix more C++ code.</h3>
			<p id="paperbox">
Try to fail at building again: Yea !!!<br/>
<br/>
			<br/>
									<div class="post">
					<a  href="../fd_proxy/doom3_macosx/step6.png">
						<img  src="../fd_proxy/doom3_macosx/step6_small.png"/><br/>
					</a>
					</div>

<br/><br/>
This time it is a bunch of miscast and impossible implicit conversion from <code>long</code> to <code>GLint</code>:
<br/><br/><br/><br/>
<br/><br/><br/><br/>
<p>
First batch:
<pre  class="long">


   /Users/fabiensanglard/raid/dev/TTimo-doom3.gpl-1559777/neo/sys/osx/macosx_glimp.mm:412:26:{412:26-412:54}: 
   error: cannot initialize a parameter of type 'GLint *' (aka 'int *') with an rvalue of type 'long *' [3]


   /Users/fabiensanglard/raid/dev/TTimo-doom3.gpl-1559777/neo/sys/osx/macosx_glimp.mm:413:26:{413:26-413:54}: 
   error: cannot initialize a parameter of type 'GLint *' (aka 'int *') with an rvalue of type 'long *' [3]


   /Developer/SDKs/MacOSX10.6.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSOpenGL.h:117:28: 
   note: passing argument to parameter 'vals' here [3]



</pre>



<p>
Change <code>macosx_glimp.mm</code>:<br/>

<pre  class="long">


	[pixelFormat getValues: (long *) &glConfig.colorBits forAttribute: NSOpenGLPFAColorSize forVirtualScreen: 0];
	[pixelFormat getValues: (long *) &glConfig.depthBits forAttribute: NSOpenGLPFADepthSize forVirtualScreen: 0];
	[pixelFormat getValues: (long *) &glConfig.stencilBits forAttribute: NSOpenGLPFAStencilSize forVirtualScreen: 0];


</pre>
<p>to
<pre  class="long">

   
   [pixelFormat getValues: (int *) &glConfig.colorBits forAttribute: NSOpenGLPFAColorSize forVirtualScreen: 0];
	[pixelFormat getValues: (int *) &glConfig.depthBits forAttribute: NSOpenGLPFADepthSize forVirtualScreen: 0];
	[pixelFormat getValues: (int *) &glConfig.stencilBits forAttribute: NSOpenGLPFAStencilSize forVirtualScreen: 0];


</pre>
























<br/><br/><br/><br/>
<p>
More errors:
<pre  class="long">


   /Users/fabiensanglard/raid/dev/TTimo-doom3.gpl-1559777/neo/sys/osx/macosx_glimp.mm:1271:8:{1271:8-1271:28}:
   error: no matching function for call to 'CGLQueryRendererInfo' [3]


   /Users/fabiensanglard/raid/dev/TTimo-doom3.gpl-1559777/neo/sys/osx/macosx_glimp.mm:1283:9:{1283:9-1283:28}: 
   error: no matching function for call to 'CGLDescribeRenderer' [3]


   /Users/fabiensanglard/raid/dev/TTimo-doom3.gpl-1559777/neo/sys/osx/macosx_glimp.mm:1295:10:{1295:10-1295:29}:
    error: no matching function for call to 'CGLDescribeRenderer' [3]


   /Users/fabiensanglard/raid/dev/TTimo-doom3.gpl-1559777/neo/sys/osx/macosx_glimp.mm:1303:10:{1303:10-1303:29}:
    error: no matching function for call to 'CGLDescribeRenderer' [3]


   /Users/fabiensanglard/raid/dev/TTimo-doom3.gpl-1559777/neo/sys/osx/macosx_glimp.mm:1313:10:{1313:10-1313:29}:
    error: no matching function for call to 'CGLDescribeRenderer' [3]


</pre>

<p>
Change <code>macosx_glimp.mm</code>:<br/>
<pre  class="long">


    long rendererInfoIndex, rendererInfoCount = MAX_RENDERER_INFO_COUNT;
    long rendererIndex, rendererCount;
    long maxVRAM = 0, vram = 0;
    long accelerated;
    long rendererID;
    long totalRenderers = 0;


</pre>
<p>to
<pre  class="long">

   
    long rendererInfoIndex;
    GLint rendererInfoCount = MAX_RENDERER_INFO_COUNT;
    long rendererIndex;
    GLint rendererCount;
    long maxVRAM = 0;
    GLint vram = 0;
    GLint accelerated;
    GLint rendererID;
    long totalRenderers = 0;


</pre>













<br/><br/><br/><br/>
<p>Some more errors:
<pre  class="long">


   /Developer/SDKs/MacOSX10.6.sdk/usr/include/ucontext.h:42:2: error: #error ucontext routines are deprecated, 
   and require _XOPEN_SOURCE to be defined [2]



</pre>
<p>
Change <code>DoomController.mm</code>:<br/>

<pre  class="long">


  #import &lt;ucontext.h&gt;


</pre>
<p>to
<pre  class="long">

   
   #import &lt;sys/ucontext.h&gt;


</pre>
















<br/><br/><br/><br/>
<p>Still more errors:
<pre  class="long">


   /Users/fabiensanglard/raid/dev/TTimo-doom3.gpl-1559777/neo/sys/osx/DOOMController.mm:474:8:{474:11-474:121}:
    error: assigning to 'cpuid_t' from incompatible type 'int' [3]



</pre>
<p>
Change <code>DOOMController.mm</code>:<br/>

<pre  class="long">


   cpuid_t Sys_GetProcessorId( void ) 
   {
     cpuid_t cpuid = CPUID_GENERIC;
 	
     #if defined(__ppc__)
       cpuid |= CPUID_ALTIVEC;
     #elif defined(__i386__)
       cpuid |= CPUID_INTEL | CPUID_MMX | CPUID_SSE | CPUID_SSE2 | CPUID_SSE3 | CPUID_HTT | CPUID_CMOV | CPUID_FTZ | CPUID_DAZ;
     #endif
 	
     return cpuid;
 	
    }


</pre>
<p>to
<pre  class="long">

   
   cpuid_t Sys_GetProcessorId( void ) 
   {
     int cpuid = CPUID_GENERIC;
 	
     #if defined(__ppc__)
       cpuid |= CPUID_ALTIVEC;
     #elif defined(__i386__)
       cpuid |= CPUID_INTEL | CPUID_MMX | CPUID_SSE | CPUID_SSE2 | CPUID_SSE3 | CPUID_HTT | CPUID_CMOV | CPUID_FTZ | CPUID_DAZ;
     #endif
 	
     return static_cast&lt;cpuid_t&gt;(cpuid);
 	
    }


</pre>


















<br/><br/><br/><br/>
<p>Finally
<p>
Change <code>macosx_glimp.mm</code>:<br/>

<pre  class="long">


   common->Printf( "%8d kB total OpenAL audio memory used\n", ( alGetInteger( alGetEnumValue( (ALubyte*)
   "AL_EAX_RAM_SIZE" ) ) - alGetInteger( alGetEnumValue( (ALubyte*)"AL_EAX_RAM_FREE" ) ) ) >> 10 );


</pre>
<p>to
<pre  class="long">

   
   common->Printf( "%8d kB total OpenAL audio memory used\n", ( alGetInteger( alGetEnumValue(
   "AL_EAX_RAM_SIZE" ) ) - alGetInteger( alGetEnumValue( "AL_EAX_RAM_FREE" ) ) ) >> 10 );


</pre>

</p>








<br/>
<h3>7. Fix the compiler.</h3>
<p id="paperbox">
Try to build: Fail.<br/>
<br/>
<pre  class="long">


   ld: illegal text-relocoation (direct reference) to (global,weak) __ZN6idMatX11InverseSelfEv in
    /Users/fabiensanglard/TTimo-doom3.gpl-1559777/neo/sys/osx/build/Debug/libidlib_nopic.a(Matrix.o) 
    from __ZN6idMatX11InverseSelfEv in /Users/fabiensanglard/TTimo-doom3.gpl-1559777/neo/sys/osx/build/Debug/libidlib_nopic.a(Matrix.o) 
    for architecture i386

</pre>
<p>
It seems all the projects did not use the same compiler, some defaulted to Apple LLVM compiler 3.0 while some other did default to LLVM GCC 4.2. Set them all to LLVM GCC 4.2 (don't forget there are two target in the idlib project: idlib_pic and idlib_nopic).

</p>




<br/>
<h3>8. Fix the OpenAL weak reference.</h3>
<p id="paperbox">
The Doom3 project features a weak framework reference:<br/>
<pre  class="long">


   -weak_framework OpenAL


</pre>
<br/>
<p>
Remove this flag and add the <code>OpenAL.framework</code> instead.


</p>



<br/>
<h3>9. Remove the old curl lib reference.</h3>
<p id="paperbox">
Delete the curl project reference and add libcurl.dylib to the list of framework in Doom3 project. This will make the build process much faster.
</p>






<br/>
<h3>10. Don't build unused architectures.</h3>
<p id="paperbox">
Optional: For all projects: Set "Build active Architecture only" to Yes.
</p>







<br/>
<h3>11. Add libraries to linker.</h3>
<p id="paperbox">
The build will still fail at this point since the linker is missing the game.dylib and the libidklib_pic.a libraries. Add them to the project:
<br/>
			 <div class="post">
					<a  href="../fd_proxy/doom3_macosx/step11.png">
						<img  src="../fd_proxy/doom3_macosx/step11_small.png"/><br/>
					</a>
					</div>

<br/><br/>
<br/>
			 <div class="post">
					<a  href="../fd_proxy/doom3_macosx/step11.1.png">
						<img  src="../fd_proxy/doom3_macosx/step11.1.png"/><br/>
					</a>
					</div>

<br/><br/>

</p>







<br/>
<h3>12. Get the assets.</h3>
<p id="paperbox">
Dust out your Doom3 CDs:<br/>
			<br/>
			 <div class="post">
					<a  href="../fd_proxy/doom3_macosx/asset.jpg">
						<img  src="../fd_proxy/doom3_macosx/asset.jpg"/><br/>
					</a>
					</div>

<br/><br/>
<br/>
If you haven't bought it yet: it is <a href="http://store.steampowered.com/app/9050/">available on Steam</a> ;) ! Place the <code>base</code> folder just next to Doom3 executable. Copy <code>base/defaut.cfg</code> from the source release to the <code>base</code> folder from Steam.
<br/>
<br/>
			<br/>
			  <div class="post">
					<a  href="../fd_proxy/doom3_macosx/post_asset.png">
						<img  src="../fd_proxy/doom3_macosx/post_asset.png"/><br/>
					</a>
					</div>

<br/><br/>
<br/>
</p>






<br/>
<h3>13. Link game.dylib.</h3>
<p id="paperbox">


If you try to launch the game now it will crash at startup:<br/>
<br/>
<pre  class="long">


   Dyld Error Message:
   Library not loaded: /usr/local/lib/game.dylib
   Referenced from: /Users/dev/TTimo-doom3.gpl-1559777/neo/sys/osx/build/Debug/Doom 3.app/Contents/MacOS/Doom 3
   Reason: image not found


  </pre>
<p>
<br/>
Two solutions possible:
<ul>
<li>Copy <code>game.dylib</code> to <code>/usr/local/lib/</code> (or even better, create a symbolic link).
<li>Set "Dynamic Library Install Name" to "", this will make Doom3 search for the dylib locally.
</ul>

</p>






<br/>
<h3>14. Enjoy !</h3>
<p id="paperbox">
Let's try one last time:




<br/>
			<br/>

					<a  href="../fd_proxy/doom3_macosx/step13.0.png">
						<img  src="../fd_proxy/doom3_macosx/step13.0_small.png"/><br/>
					</a>
					
<br/><br/>
<br/>
			<br/>
<img src="../fd_proxy/doom3_macosx/step13.1_small.png"/>
<br/><br/>
<br/>
			<br/>
<img src="../fd_proxy/doom3_macosx/step13_small.png"/>
<br/><br/>
<br/><br/>
<br/><br/>
Happy Hacking guys ;) !

</p>			

</p>

    
  <!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

