<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Raytracing"/>
		<meta name="Description" content="Raytracing"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>Raytracing</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="https://fabiensanglard.net/" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="http://fabiensanglard.net/" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="http://fabiensanglard.net/about/">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="http://fabiensanglard.net/faq/">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="http://fabiensanglard.net/rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="http://fabiensanglard.net/rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="http://fabiensanglard.net/rss.xml" />
<div id="date">
       September 20th, 2013</div>
   <h1>Decyphering the Business Card Raytracer</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="businessCard_RayTracer.png" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         <script type="text/javascript">
  var disqus_identifier = "Decyphering_A_business_Card";
</script>



    
    <style>

 .comment{color: rgb(66,135,65);}
 .keyword{color: rgb(182,16,162);}
 .literal{color: rgb(218,37,36);}

 .include{color: rgb(117,85,119);}

 .numbers{color: rgb(96,0,205);}

  pre{
    font: 12px courrier,monospace;
  }
 </style>


I recently came across Paul Heckbert's business card raytracer. 
For those that have never heard of it: It is a very famous challenge in the Computer Graphics field that 
started on May 4th, 1984 via a post on <code>comp.graphics</code> by Paul Heckbert ( More about this in his article "<a href="http://books.google.ca/books?id=CCqzMm_-WucC&pg=PA375&lpg=PA375&dq=%22A+Minimal+Ray+Tracer%22&source=bl&ots=msmz42NHge&sig=rYEdHlY0zC2Sk_aPaZhzjMhyfj8&hl=en&sa=X&ei=2NQ8Utb2I-ae2gWHn4GYAg&ved=0CFEQ6AEwAw#v=onepage&q=%22A%20Minimal%20Ray%20Tracer%22&f=false">A Minimal Ray Tracer</a>" from the book <a href="http://www.amazon.ca/Graphics-Gems-IV-IBM-Version/dp/0123361559/ref=sr_1_1?ie=UTF8&qid=1379718285&sr=8-1&keywords=Graphics+Gems+IV">Graphics Gems IV</a>).<br>
<br>
The goal was to produce the source code for a raytracer...that would fit on the back of a business card.<br>
<br>
Andrew Kensler's version is <a href="http://www.cs.utah.edu/~aek/code/card.cpp">mesmerizing</a> and one of the 
greatest hack that I have seen. Since I am curious, I decided to deconstruct it: Here is what I understood.<br/>
<br/>
<u><b>Edit :</b></u> Andrew Kensler himself <a href="https://news.ycombinator.com/item?id=6425965">commented on Hacker News</a> and adressed/elaborated on my observations: Thanks you so much Andrew :) !
</p>

<br>
<h2>The Business Card Code</h2>

    
<pre class="long" style="width:30%; float:left; margin-right:5ch;">

  #include &lt;stdlib.h&gt;   // card &gt; aek.ppm
  #include &lt;stdio.h&gt;
  #include &lt;math.h&gt;
  typedef int i;typedef float f;struct v{
  f x,y,z;v operator+(v r){return v(x+r.x
  ,y+r.y,z+r.z);}v operator*(f r){return
  v(x*r,y*r,z*r);}f operator%(v r){return
  x*r.x+y*r.y+z*r.z;}v(){}v operator^(v r
  ){return v(y*r.z-z*r.y,z*r.x-x*r.z,x*r.
  y-y*r.x);}v(f a,f b,f c){x=a;y=b;z=c;}v
  operator!(){return*this*(1/sqrt(*this%*
  this));}};i G[]={247570,280596,280600,
  249748,18578,18577,231184,16,16};f R(){
  return(f)rand()/RAND_MAX;}i T(v o,v d,f
  &amp;t,v&amp;n){t=1e9;i m=0;f p=-o.z/d.z;if(.01
  &lt;p)t=p,n=v(0,0,1),m=1;for(i k=19;k--;)
  for(i j=9;j--;)if(G[j]&amp;1&lt;&lt;k){v p=o+v(-k
  ,0,-j-4);f b=p%d,c=p%p-1,q=b*b-c;if(q&gt;0
  ){f s=-b-sqrt(q);if(s&lt;t&amp;&amp;s&gt;.01)t=s,n=!(
  p+d*t),m=2;}}return m;}v S(v o,v d){f t
  ;v n;i m=T(o,d,t,n);if(!m)return v(.7,
  .6,1)*pow(1-d.z,4);v h=o+d*t,l=!(v(9+R(
  ),9+R(),16)+h*-1),r=d+n*(n%d*-2);f b=l%
  n;if(b&lt;0||T(h,l,t,n))b=0;f p=pow(l%r*(b
  &gt;0),99);if(m&amp;1){h=h*.2;return((i)(ceil(
  h.x)+ceil(h.y))&amp;1?v(3,1,1):v(3,3,3))*(b
  *.2+.1);}return v(p,p,p)+S(h,r)*.5;}i
  main(){printf("P6 512 512 255 ");v g=!v
  (-6,-16,0),a=!(v(0,0,1)^g)*.002,b=!(g^a
  )*.002,c=(a+b)*-256+g;for(i y=512;y--;)
  for(i x=512;x--;){v p(13,13,13);for(i r
  =64;r--;){v t=a*(R()-.5)*99+b*(R()-.5)*
  99;p=S(v(17,16,8)+t,!(t*-1+(a*(R()+x)+b
  *(y+R())+c)*16))*3.5+p;}printf("%c%c%c"
  ,(i)p.x,(i)p.y,(i)p.z);}}
 

</pre>
<center>

  
    <img src="minray.png" style="width:52%;"></center>
    <br>
    The code looks confusing but it compiles and run flawlessly! On my MacBook Air, it takes 27 seconds to generate the image on the right. If you want to run it yourself, save the code in a file named <code>card.cpp</code>, open a Terminal window and type:<br>
  <br>
  <pre style="width:100%;margin-left: 0;">

    c++ -O3 -o card card.cpp
    ./card &gt; card.ppm
  </pre>
  

<br>
<h2>Business Card Raycaster features</h2>
<p>
  The list of features is impressive :
  </p><ul>
    <li>The world is made of spheres which are carefully organized.</li>
    <li>There is a floor and it is textured.</li>
    <li>There is a sky and it has a nice gradient.</li>
    <li>Shadows are soft shadows.</li>
    <li>OMG, Depth of View blur: Are you kidding me ?</li> 
</ul>
<p>
  All that fitting on the back of a business card ! Let's see how it works !
</p>



<br>
<h2>Vector class</h2>
<p>
    </p>

<table width=100%>
  <tr>
    <td valign=top>
    <pre class="long" style="width:330px; float:left; margin-right:3ch;">
    <span style="color:blue;">
    #include &lt;stdlib.h&gt;   // card &gt; aek.ppm
    #include &lt;stdio.h&gt;
    #include &lt;math.h&gt;
    typedef int i;typedef float f;struct v{
    f x,y,z;v operator+(v r){return v(x+r.x
    ,y+r.y,z+r.z);}v operator*(f r){return
    v(x*r,y*r,z*r);}f operator%(v r){return
    x*r.x+y*r.y+z*r.z;}v(){}v operator^(v r
    ){return v(y*r.z-z*r.y,z*r.x-x*r.z,x*r.
    y-y*r.x);}v(f a,f b,f c){x=a;y=b;z=c;}v
    operator!(){return*this*(1/sqrt(*this%*
    this));}};</span>i G[]={247570,280596,280600,
    249748,18578,18577,231184,16,16};f R(){
    return(f)rand()/RAND_MAX;}i T(v o,v d,f
    &amp;t,v&amp;n){t=1e9;i m=0;f p=-o.z/d.z;if(.01
    &lt;p)t=p,n=v(0,0,1),m=1;for(i k=19;k--;)
    for(i j=9;j--;)if(G[j]&amp;1&lt;&lt;k){v p=o+v(-k
    ,0,-j-4);f b=p%d,c=p%p-1,q=b*b-c;if(q&gt;0
    ){f s=-b-sqrt(q);if(s&lt;t&amp;&amp;s&gt;.01)t=s,n=!(
    p+d*t),m=2;}}return m;}v S(v o,v d){f t
    ;v n;i m=T(o,d,t,n);if(!m)return v(.7,
    .6,1)*pow(1-d.z,4);v h=o+d*t,l=!(v(9+R(
    ),9+R(),16)+h*-1),r=d+n*(n%d*-2);f b=l%
    n;if(b&lt;0||T(h,l,t,n))b=0;f p=pow(l%r*(b
    &gt;0),99);if(m&amp;1){h=h*.2;return((i)(ceil(
    h.x)+ceil(h.y))&amp;1?v(3,1,1):v(3,3,3))*(b
    *.2+.1);}return v(p,p,p)+S(h,r)*.5;}i
    main(){printf("P6 512 512 255 ");v g=!v
    (-6,-16,0),a=!(v(0,0,1)^g)*.002,b=!(g^a
    )*.002,c=(a+b)*-256+g;for(i y=512;y--;)
    for(i x=512;x--;){v p(13,13,13);for(i r
    =64;r--;){v t=a*(R()-.5)*99+b*(R()-.5)*
    99;p=S(v(17,16,8)+t,!(t*-1+(a*(R()+x)+b
    *(y+R())+c)*16))*3.5+p;}printf("%c%c%c"
    ,(i)p.x,(i)p.y,(i)p.z);}}
  </pre>
</td>
<td style="padding: 5px;">
  The main trick that helps reducing the code size dramatically it to use two <code>define</code> :<br/>
  <ul style="overflow: auto;">
   <li>Define <code>i</code> as <code>int</code>.</li>
   <li>Define <code>f</code> as <code>float</code>.</li>
   </ul>
    <p>
  The other big space saver is the 'v' C++ class which is used for vector but also pixel processing.<br/>
  <br/>
  Here is the code formated, highlighted and commented:<br/>
   <br>
  <pre class="long" style="margin:0px;">

   <span class="include">#include</span> <span  class="literal">&lt;stdlib.h&gt;</span>   <span class="comment">// card &gt; aek.ppm</span>
   <span class="include">#include</span> <span  class="literal">&lt;stdio.h&gt;</span>
   <span class="include">#include</span> <span  class="literal">&lt;math.h&gt;</span>

   <span class="keyword">typedef int</span> i;       <span class="comment">//Save space by using 'i' instead of 'int'</span>
   <span class="keyword">typedef float</span> f;     <span class="comment">//Save even more space by using 'f' instead of 'float'</span>

   <span class="comment">//Define a vector class with constructor and operator: 'v'</span>
   <span class="keyword">struct</span> v{
      f x,y,z;  <span class="comment">// Vector has three float attributes.</span>
      v <span class="keyword">operator</span>+(v r){<span class="keyword">return</span> v(x+r.x,y+r.y,z+r.z);} <span class="comment">//Vector add</span>
      v <span class="keyword">operator</span>*(f r){<span class="keyword">return</span> v(x*r,y*r,z*r);}       <span class="comment">//Vector scaling</span>
      f <span class="keyword">operator</span>%(v r){<span class="keyword">return</span> x*r.x+y*r.y+z*r.z;}    <span class="comment">//Vector dot product</span>
      v(){}                                  <span class="comment">//Empty constructor</span>
      v <span class="keyword">operator</span>^(v r){<span class="keyword">return</span> v(y*r.z-z*r.y,z*r.x-x*r.z,x*r.y-y*r.x);} <span class="comment">//Cross-product</span>
      v(f a,f b,f c){x=a;y=b;z=c;}            <span class="comment">//Constructor</span>
      v <span class="keyword">operator</span>!(){<span class="keyword">return</span> *this*(<span  class="numbers">1</span> /sqrt(*this%*this));} <span class="comment">// Used later for normalizing</span>
   };

  </pre>
</td>
</tr>
</table>
  <div style="clear:both;"></div>
</p>

<br>
<h2>Random() and World database</h2>

<table width=100%>
  <tr>
    <td valign=top>
      <pre class="long" style="width:330px; float:left; margin-right:3ch;">
    
    #include &lt;stdlib.h&gt;   // card &gt; aek.ppm
    #include &lt;stdio.h&gt;
    #include &lt;math.h&gt;
    typedef int i;typedef float f;struct v{
    f x,y,z;v operator+(v r){return v(x+r.x
    ,y+r.y,z+r.z);}v operator*(f r){return
    v(x*r,y*r,z*r);}f operator%(v r){return
    x*r.x+y*r.y+z*r.z;}v(){}v operator^(v r
    ){return v(y*r.z-z*r.y,z*r.x-x*r.z,x*r.
    y-y*r.x);}v(f a,f b,f c){x=a;y=b;z=c;}v
    operator!(){return*this*(1/sqrt(*this%*
    this));}};i <span style="color:blue;">G[]={247570,280596,280600,
    249748,18578,18577,231184,16,16};f R(){
    return(f)rand()/RAND_MAX;</span>}i T(v o,v d,f
    &amp;t,v&amp;n){t=1e9;i m=0;f p=-o.z/d.z;if(.01
    &lt;p)t=p,n=v(0,0,1),m=1;for(i k=19;k--;)
    for(i j=9;j--;)if(G[j]&amp;1&lt;&lt;k){v p=o+v(-k
    ,0,-j-4);f b=p%d,c=p%p-1,q=b*b-c;if(q&gt;0
    ){f s=-b-sqrt(q);if(s&lt;t&amp;&amp;s&gt;.01)t=s,n=!(
    p+d*t),m=2;}}return m;}v S(v o,v d){f t
    ;v n;i m=T(o,d,t,n);if(!m)return v(.7,
    .6,1)*pow(1-d.z,4);v h=o+d*t,l=!(v(9+R(
    ),9+R(),16)+h*-1),r=d+n*(n%d*-2);f b=l%
    n;if(b&lt;0||T(h,l,t,n))b=0;f p=pow(l%r*(b
    &gt;0),99);if(m&amp;1){h=h*.2;return((i)(ceil(
    h.x)+ceil(h.y))&amp;1?v(3,1,1):v(3,3,3))*(b
    *.2+.1);}return v(p,p,p)+S(h,r)*.5;}i
    main(){printf("P6 512 512 255 ");v g=!v
    (-6,-16,0),a=!(v(0,0,1)^g)*.002,b=!(g^a
    )*.002,c=(a+b)*-256+g;for(i y=512;y--;)
    for(i x=512;x--;){v p(13,13,13);for(i r
    =64;r--;){v t=a*(R()-.5)*99+b*(R()-.5)*
    99;p=S(v(17,16,8)+t,!(t*-1+(a*(R()+x)+b
    *(y+R())+c)*16))*3.5+p;}printf("%c%c%c"
    ,(i)p.x,(i)p.y,(i)p.z);}}
  </pre>
</td>
<td>
  The next section also saves a lot of code by defining a <code>R</code> function that 
  return a random value within <code>[0.0f-1.0f]</code>. It is very useful for the stochastic sampling resulting
  in blur and soft-shadows.<br/>
  <br/>
  The <code>G</code> array encodes the location of the spheres. The integers are interpreted as 
  9 lines and 19 columns bit vector.<br>
  <br/>
  Here is the code formated, highlighted and commented :<br/>
  <br/>
  <pre class="long" style="margin:0px;">  

    <span class="comment">//The set of sphere positions describing the world.</span>
    <span class="comment">//Those integers are in fact bit vectors.</span>
   i G[]={<span  class="numbers">247570</span>,<span  class="numbers">280596</span>,<span  class="numbers">280600</span>,<span  class="numbers">249748</span>,<span  class="numbers">18578</span>,<span  class="numbers">18577</span>,<span  class="numbers">231184</span>,<span  class="numbers">16</span>,<span  class="numbers">16</span>};
   <span class="comment">
   /*
 
   16                    1    
   16                    1    
   231184   111    111   1    
   18577       1  1   1  1   1
   18578       1  1   1  1  1 
   249748   1111  11111  1 1  
   280600  1   1  1      11   
   280596  1   1  1      1 1  
   247570   1111   111   1  1 
 
   */
   </span>
   <span class="comment">// Random generator, return a float within range [0-1]</span>
   f R(){<span class="keyword">return</span>(f)rand()/RAND_MAX;}


</pre>
</td>
</tr>
</table>
    <div style="clear:both;"></div>
<p></p>

<br>
<h2>Main method</h2>
<p>
  The main method uses a simple image file format known as PPM. It is text based with a ridiculously simple header:
   <code>P6 [WIDTH] [HEIGHT] [MAX_VALUE]</code> followed by the RGB values for each pixels.<br/>
   For each 512x512 pixels in the image, the program samples (S) the color of 64 rays, accumulates the result and write it to the output (stdout).<br/>
  <br>
  It applies a bit of random delta on each ray origin and ray direction in order to produce a nice Depth of View effect.
</p>
<table width=100%>
  <tr>
    <td valign=top>
  <pre class="long" style="width:330px; float:left; margin-right:3ch;">
    
    #include &lt;stdlib.h&gt;   // card &gt; aek.ppm
    #include &lt;stdio.h&gt;
    #include &lt;math.h&gt;
    typedef int i;typedef float f;struct v{
    f x,y,z;v operator+(v r){return v(x+r.x
    ,y+r.y,z+r.z);}v operator*(f r){return
    v(x*r,y*r,z*r);}f operator%(v r){return
    x*r.x+y*r.y+z*r.z;}v(){}v operator^(v r
    ){return v(y*r.z-z*r.y,z*r.x-x*r.z,x*r.
    y-y*r.x);}v(f a,f b,f c){x=a;y=b;z=c;}v
    operator!(){return*this*(1/sqrt(*this%*
    this));}};i G[]={247570,280596,280600,
    249748,18578,18577,231184,16,16};f R(){
    return(f)rand()/RAND_MAX;}i T(v o,v d,f
    &amp;t,v&amp;n){t=1e9;i m=0;f p=-o.z/d.z;if(.01
    &lt;p)t=p,n=v(0,0,1),m=1;for(i k=19;k--;)
    for(i j=9;j--;)if(G[j]&amp;1&lt;&lt;k){v p=o+v(-k
    ,0,-j-4);f b=p%d,c=p%p-1,q=b*b-c;if(q&gt;0
    ){f s=-b-sqrt(q);if(s&lt;t&amp;&amp;s&gt;.01)t=s,n=!(
    p+d*t),m=2;}}return m;}v S(v o,v d){f t
    ;v n;i m=T(o,d,t,n);if(!m)return v(.7,
    .6,1)*pow(1-d.z,4);v h=o+d*t,l=!(v(9+R(
    ),9+R(),16)+h*-1),r=d+n*(n%d*-2);f b=l%
    n;if(b&lt;0||T(h,l,t,n))b=0;f p=pow(l%r*(b
    &gt;0),99);if(m&amp;1){h=h*.2;return((i)(ceil(
    h.x)+ceil(h.y))&amp;1?v(3,1,1):v(3,3,3))*(b
    *.2+.1);}return v(p,p,p)+S(h,r)*.5;}<span style="color:blue;">i
    main(){printf("P6 512 512 255 ");v g=!v
    (-6,-16,0),a=!(v(0,0,1)^g)*.002,b=!(g^a
    )*.002,c=(a+b)*-256+g;for(i y=512;y--;)
    for(i x=512;x--;){v p(13,13,13);for(i r
    =64;r--;){v t=a*(R()-.5)*99+b*(R()-.5)*
    99;p=S(v(17,16,8)+t,!(t*-1+(a*(R()+x)+b
    *(y+R())+c)*16))*3.5+p;}printf("%c%c%c"
    ,(i)p.x,(i)p.y,(i)p.z);}}</span>

  </pre>
</td><td>

  <pre class="long" style="margin:0px;">

  <span class="comment">// The main function. It generates a PPM image to stdout.</span>
  <span class="comment">// Usage of the program is hence: ./card &gt; erk.ppm</span>
  i main(){
    
     printf(<span class="literal">"P6 512 512 255 "</span>); <span class="comment">// The PPM Header is issued</span>
    
     <span class="comment">// The '!' are for normalizing each vectors with ! operator. </span>
     v g=!v(<span class="numbers">-6</span>,<span class="numbers">-16</span>,<span class="numbers">0</span>),       <span class="comment">// Camera direction</span>
       a=!(v(<span class="numbers">0</span>,<span class="numbers">0</span>,<span class="numbers">1</span>)^g)*<span class="numbers">.002</span>, <span class="comment">// Camera up vector...Seem Z is pointing up :/ WTF !</span>
       b=!(g^a)*.<span class="numbers">002</span>,        <span class="comment">// The right vector, obtained via traditional cross-product</span>
       c=(a+b)*-<span class="numbers">256</span>+g;       <span class="comment">// WTF ? See <A href="https://news.ycombinator.com/item?id=6425965">https://news.ycombinator.com/item?id=6425965</a>.</span>

     <span class="keyword">for</span>(i y=<span class="numbers">512</span></span>;y--;)    <span class="comment">//For each column</span>
     <span class="keyword">for</span>(i x=<span class="numbers">512</span>;x--;){   <span class="comment">//For each pixel in a line</span>
       
        <span class="comment">//Reuse the vector class to store not XYZ but a RGB pixel color</span>
        v p(<span class="numbers">13</span>,<span class="numbers">13</span>,<span class="numbers">13</span>);     // Default pixel color is almost pitch black
       
        <span class="comment">//Cast 64 rays per pixel (For blur (stochastic sampling) and soft-shadows.</span> 
        <span class="keyword">for</span>(i r=<span class="numbers">64</span>;r--;){ 
          
            <span class="comment">// The delta to apply to the origin of the view (For Depth of View blur).</span>
            v t=a*(R()-<span class="numbers">.5</span>)*<span class="numbers">99</span>+b*(R()-<span class="numbers">.5</span>)*<span class="numbers">99</span>; <span class="comment">// A little bit of delta </span>
                                           
            <span class="comment">// Set the camera focal point v(17,16,8) and Cast the ray </span>
            <span class="comment">// Accumulate the color returned in the p variable</span>
            p=S(v(<span class="numbers">17</span>,<span class="numbers">16</span>,<span class="numbers">8</span>)+t, <span class="comment">//Ray Origin</span>
                !(t*<span class="numbers">-1</span>+(a*(R()+x)+b*(y+R())+c)*<span class="numbers">16</span>) <span class="comment">// Ray Direction with random deltas</span>
                                                   <span class="comment">// for stochastic sampling</span>
                )*<span class="numbers">3.5</span>+p; <span class="comment">// +p for color accumulation</span>
        }
       
        printf(<span class="literal">"%c%c%c"</span>,(i)p.x,(i)p.y,(i)p.z);
       
     }
  }
  </pre>
</td></tr></table>


<br>
<h2>Sampler</h2>
<p>
    The Sampler (S) is a function that returns a pixel color for a given Point Origin (o) and Vector Direction (d). It is recursive if it hits 
  a sphere. If no sphere is hit by the ray (and a ray always ends up missing) then the function either returns a sky color gradient or a floor color based
  on a checkerboard texture.<br/>
  <br/>
  Remark the calls to <code>R</code> when computing the light direction: This is how the soft-shadows are generated.
  </p>
<table width=100%>
  <tr>
    <td valign=top>
  <pre class="long" style="width:330px; float:left; margin-right:3ch;">
    
    #include &lt;stdlib.h&gt;   // card &gt; aek.ppm
    #include &lt;stdio.h&gt;
    #include &lt;math.h&gt;
    typedef int i;typedef float f;struct v{
    f x,y,z;v operator+(v r){return v(x+r.x
    ,y+r.y,z+r.z);}v operator*(f r){return
    v(x*r,y*r,z*r);}f operator%(v r){return
    x*r.x+y*r.y+z*r.z;}v(){}v operator^(v r
    ){return v(y*r.z-z*r.y,z*r.x-x*r.z,x*r.
    y-y*r.x);}v(f a,f b,f c){x=a;y=b;z=c;}v
    operator!(){return*this*(1/sqrt(*this%*
    this));}};i G[]={247570,280596,280600,
    249748,18578,18577,231184,16,16};f R(){
    return(f)rand()/RAND_MAX;}i T(v o,v d,f
    &amp;t,v&amp;n){t=1e9;i m=0;f p=-o.z/d.z;if(.01
    &lt;p)t=p,n=v(0,0,1),m=1;for(i k=19;k--;)
    for(i j=9;j--;)if(G[j]&amp;1&lt;&lt;k){v p=o+v(-k
    ,0,-j-4);f b=p%d,c=p%p-1,q=b*b-c;if(q&gt;0
    ){f s=-b-sqrt(q);if(s&lt;t&amp;&amp;s&gt;.01)t=s,n=!(
    p+d*t),m=2;}}return m;}<span style="color:blue;">v S(v o,v d){f t
    ;v n;i m=T(o,d,t,n);if(!m)return v(.7,
    .6,1)*pow(1-d.z,4);v h=o+d*t,l=!(v(9+R(
    ),9+R(),16)+h*-1),r=d+n*(n%d*-2);f b=l%
    n;if(b&lt;0||T(h,l,t,n))b=0;f p=pow(l%r*(b
    &gt;0),99);if(m&amp;1){h=h*.2;return((i)(ceil(
    h.x)+ceil(h.y))&amp;1?v(3,1,1):v(3,3,3))*(b
    *.2+.1);}return v(p,p,p)+S(h,r)*.5;}</span>i
    main(){printf("P6 512 512 255 ");v g=!v
    (-6,-16,0),a=!(v(0,0,1)^g)*.002,b=!(g^a
    )*.002,c=(a+b)*-256+g;for(i y=512;y--;)
    for(i x=512;x--;){v p(13,13,13);for(i r
    =64;r--;){v t=a*(R()-.5)*99+b*(R()-.5)*
    99;p=S(v(17,16,8)+t,!(t*-1+(a*(R()+x)+b
    *(y+R())+c)*16))*3.5+p;}printf("%c%c%c"
    ,(i)p.x,(i)p.y,(i)p.z);}}

  </pre>
</td><td>


  <pre class="long" style="margin:0px;">

   <span class="comment">// (S)ample the world and return the pixel color for</span>
   <span class="comment">// a ray passing by point o (Origin) and d (Direction)</span>
   v S(v o,v d){
      f t;
      v n;
    
      <span class="comment">//Search for an intersection ray Vs World.</span>
      i m=T(o,d,t,n);

      <span class="keyword">if</span>(!m) <span class="comment">// m==0</span>
      <span class="comment">//No sphere found and the ray goes upward: Generate a sky color  </span>
      <span class="keyword">return</span> v(<span class="numbers">.7</span>,<span class="numbers">.6</span>,<span class="numbers">1</span>)*pow(1</span>-d.z,<span class="numbers">4</span>);

      <span class="comment">//A sphere was maybe hit.</span>
    
      v h=o+d*t,                    <span class="comment">// h = intersection coordinate</span>
      l=!(v(<span class="numbers">9</span>+R(),<span class="numbers">9</span>+R(),<span class="numbers">16</span>)+h*<span class="numbers">-1</span>),  <span class="comment">// 'l' = direction to light (random delta for shadows).</span>
      r=d+n*(n%d*<span class="numbers">-2</span>);               <span class="comment">// r = The half-vector</span>
 
      <span class="comment">//Calculated the lambertian factor</span>
      f b=l%n;
    
      <span class="comment">//Calculate illumination factor (lambertian coefficient > 0 or in shadow)?</span>
      <span class="keyword">if</span>(b<0</span>||T(h,l,t,n))
         b=0</span>;
   
      <span class="comment">// Calculate the color 'p' with diffuse and specular component </span>
      f p=pow(l%r*(b><span class="numbers">0</span>),<span class="numbers">99</span>);
    
      <span class="keyword">if</span>(m&<span class="numbers">1</span>){   <span class="comment">//m == 1</span>
         h=h*<span class="numbers">.2</span>; <span class="comment">//No sphere was hit and the ray was going downward: Generate a floor color</span>
         <span class="keyword">return</span>((i)(ceil(h.x)+ceil(h.y))&<span class="numbers">1</span>?v(<span class="numbers">3</span>,<span class="numbers">1</span>,<span class="numbers">1</span>):v(<span class="numbers">3</span>,<span class="numbers">3</span>,<span class="numbers">3</span>))*(b*<span class="numbers">.2</span>+<span class="numbers">.1</span>);
      }
   
      <span class="comment">//m == 2 A sphere was hit. Cast an ray bouncing from the sphere surface.</span>
      <span class="keyword">return</span> v(p,p,p)+S(h,r)*<span class="numbers">.5</span>; <span class="comment">//Attenuate color by 50% since it is bouncing (* .5)</span>
  }
</pre>
</td></tr></table>
  <div style="clear:both;"></div>
</p>


<br>
<h2>Tracer</h2>
<p>
  The Tracer is in charge of casting a Ray (Origin o ,Direction d). It return an integer that is a code
  for the intersection test with the spheres in the world (0=miss toward sky,1=miss toward floor, 2=sphere hit). If a sphere is hit, it updates the references
  t (the parametric value to compute the distance of intersection) and n (the half-vector where the ray bounce).
  </p>

<table width=100%>
  <tr>
    <td valign=top>
  <pre class="long" style="width:330px; float:left; margin-right:3ch;">
    
    #include &lt;stdlib.h&gt;   // card &gt; aek.ppm
    #include &lt;stdio.h&gt;
    #include &lt;math.h&gt;
    typedef int i;typedef float f;struct v{
    f x,y,z;v operator+(v r){return v(x+r.x
    ,y+r.y,z+r.z);}v operator*(f r){return
    v(x*r,y*r,z*r);}f operator%(v r){return
    x*r.x+y*r.y+z*r.z;}v(){}v operator^(v r
    ){return v(y*r.z-z*r.y,z*r.x-x*r.z,x*r.
    y-y*r.x);}v(f a,f b,f c){x=a;y=b;z=c;}v
    operator!(){return*this*(1/sqrt(*this%*
    this));}};i G[]={247570,280596,280600,
    249748,18578,18577,231184,16,16};f R(){
    return(f)rand()/RAND_MAX;}<span style="color:blue;">i T(v o,v d,f
    &amp;t,v&amp;n){t=1e9;i m=0;f p=-o.z/d.z;if(.01
    &lt;p)t=p,n=v(0,0,1),m=1;for(i k=19;k--;)
    for(i j=9;j--;)if(G[j]&amp;1&lt;&lt;k){v p=o+v(-k
    ,0,-j-4);f b=p%d,c=p%p-1,q=b*b-c;if(q&gt;0
    ){f s=-b-sqrt(q);if(s&lt;t&amp;&amp;s&gt;.01)t=s,n=!(
    p+d*t),m=2;}}return m;}</span>v S(v o,v d){f t
    ;v n;i m=T(o,d,t,n);if(!m)return v(.7,
    .6,1)*pow(1-d.z,4);v h=o+d*t,l=!(v(9+R(
    ),9+R(),16)+h*-1),r=d+n*(n%d*-2);f b=l%
    n;if(b&lt;0||T(h,l,t,n))b=0;f p=pow(l%r*(b
    &gt;0),99);if(m&amp;1){h=h*.2;return((i)(ceil(
    h.x)+ceil(h.y))&amp;1?v(3,1,1):v(3,3,3))*(b
    *.2+.1);}return v(p,p,p)+S(h,r)*.5;}i
    main(){printf("P6 512 512 255 ");v g=!v
    (-6,-16,0),a=!(v(0,0,1)^g)*.002,b=!(g^a
    )*.002,c=(a+b)*-256+g;for(i y=512;y--;)
    for(i x=512;x--;){v p(13,13,13);for(i r
    =64;r--;){v t=a*(R()-.5)*99+b*(R()-.5)*
    99;p=S(v(17,16,8)+t,!(t*-1+(a*(R()+x)+b
    *(y+R())+c)*16))*3.5+p;}printf("%c%c%c"
    ,(i)p.x,(i)p.y,(i)p.z);}}

  </pre></td><td>

    <pre class="long" style="margin:0px;">

   <span class="comment">//The intersection test for line [o,v].</span>
   <span class="comment">// Return 2 if a hit was found (and also return distance t and bouncing ray n).</span>
   <span class="comment">// Return 0 if no hit was found but ray goes upward</span>
   <span class="comment">// Return 1 if no hit was found but ray goes downward</span>
   i T(v o,v d,f& t,v& n){ 
     t=<span class="numbers">1e9</span>;
     i m=<span class="numbers">0</span>;
     f p=-o.z/d.z;
      <span class="keyword">if</span>(<span class="numbers">.01</span>&lt;p)›
       t=p,n=v(<span class="numbers">0</span>,<span class="numbers">0</span>,<span class="numbers">1</span>),m=<span class="numbers">1</span>;

     <span class="comment">//The world is encoded in G, with 9 lines and 19 columns</span>
     <span class="keyword">for</span>(i k=<span class="numbers">19</span>;k--;)  <span class="comment">//For each columns of objects</span>
     <span class="keyword">for</span>(i j=<span class="numbers">9</span>;j--;)   <span class="comment">//For each line on that columns</span>
      
     <span class="keyword">if</span>(G[j]&1&lt;&lt;k){ <span class="comment">//For this line j, is there a sphere at column i ?</span>
        
        <span class="comment">// There is a sphere but does the ray hits it ?</span>
        v p=o+v(-k,<span class="numbers">0</span>,-j-<span class="numbers">4</span>);
        f b=p%d,c=p%p-<span class="numbers">1</span>,q=b*b-c;
     
        <span class="comment">//Does the ray hit the sphere ?</span>
        <span class="keyword">if</span>(q>0</span>){
           <span class="comment">//It does, compute the distance camera-sphere</span>
           f s=-b-sqrt(q);
             
           if(s&lt;t && s><span class="numbers">.01</span>)
             <span class="comment">// So far this is the minimum distance, save it. And also</span>
             <span class="comment">// compute the bouncing ray vector into 'n'  </span>
             t=s,
             n=!(p+d*t),
             m=<span class="numbers">2</span>;
         }
     }
     <span class="keyword">return</span> m;
  }

</pre>
</td></tr></table>
    <div style="clear:both;"></div>
</p>


<br>
<h2>The Leet Number</h2>
<p>
  Many readers have tried to shorten the code further with more or less success. The original author stopped with the current version for 
  a very interesting reason:<br/>
  <pre class="long">  
  $ wc card.cpp
  35      95    1337 card.cpp
   </pre>
   
   <p>
    <br/>
    The total size of the code is 1337 bytes: <a href="http://en.wikipedia.org/wiki/Leet">The Leet number</a>. Beat that !
</p>

<h2>Script kiddie</h2>
<p>
  And now that the business card is fully understood, we can generate our own :<br/>
  <br/>
  </p><pre class="long" style="width:330px; float:left; margin-right:3ch;">
    
   #include &lt;stdlib.h>   // card > aek.ppm
   #include &lt;stdio.h>
   #include &lt;math.h>
   typedef int i;typedef float f;struct v{
   f x,y,z;v operator+(v r){return v(x+r.x
   ,y+r.y,z+r.z);}v operator*(f r){ return
   v(x*r,y*r,z*r);}f operator%(v r){return
   x*r.x+y*r.y+z*r.z;}v(){}v operator^(v r
   ){return v(y*r.z-z*r.y,z*r.x-x*r.z,x*r.
   y-y*r.x);}v(f a,f b,f c){x=a;y=b;z=c;}v
   operator!(){return*this*(1/sqrt(*this%*
   this));}};i G[]={133022, 133266,133266,
   133022, 254096, 131216, 131984, 131072,
   258048,};f R(){return(f)rand()/RAND_MAX
   ;}i T(v o,v d,f&t,v&n){t=1e9;i m=0;f p=
   -o.z/d.z; if(.01&lt;p)t=p, n=v(0,0,1),m=1;
   for(i k=19;k--;)for(i j=9;j--;)if(G[j]&
   1&lt;&lt;k){v p=o+v(-k,0,-j-4);f b=p%d,c=p%p-
   1,q=b*b-c;if(q>0){f s=-b-sqrt(q);if(s&lt;t
   &&s>.01)t=s,n=!(p+d*t),m=2;}}return m;}
   v S(v o,v d){f t;v n;i m=T(o,d,t,n);if(
   !m)return v(.7,.6,1)*pow(1-d.z,4);v h=o
   +d*t,l=!(v(9+R(),9+R(),16)+h*-1),r=d+n*
   (n%d*-2);f b=l%n;if(b&lt;0||T(h,l,t,n))b=0
   ;f p=pow(l%r*(b>0),99);if(m&1){h=h*.2;
   return((i)(ceil(h.x)+ceil(h.y))&1?v(3,1
   ,1):v(3,3,3))*(b*.2+.1);}return v(p,p,p
   )+S(h,r)*.5;}i main(){printf("P6 512  "
   "512 255 ");v g=!v(-6,-16,0),a=!(v(0,0,
   1)^g)*.002,b=!(g^a)*.002,c=(a+b)*-256+g
   ;for(i y=512;y--;)for(i x=512;x--;){v p
   (9,9,9);for(i r=64;r--;){v t=a*(R()-.5)
   *99+b*(R()-.5)*99;p=S(v(17,16,8)+t,!(t*
   -1+(a*(R()+x)+b*(y+R())+c)*16))*3.5+p;}
   printf("%c%c%c",(i)p.x,(i)p.y,(i)p.z);}}
  </pre>

  <img src="fab.png" style="margin-left:auto;margin-right:auto; display:block;width:521px; height:521px;"/>
    <div style="clear:both;"></div>
</p>



<br>
<h2>Recommended readings</h2>
<p>
  Since I have spent as lot of time reading about raytracing, here are a few really good resources:<br/>
  <ul>
     <li><a href="http://www.scratchapixel.com/">scratchapixel.com</a> : Great raytracer lessons written by professionals that have worked on Toy Story, Avatar, Lord of the Rings, Harry Potter, Pirates of the Caribbean and many other movies.</li>
     <li><A href="http://www.amazon.com/Introduction-Tracing-Kaufmann-Computer-Graphics/dp/0122861604/ref=sr_1_1?ie=UTF8&qid=1379818206&sr=8-1&keywords=introduction+to+raytracing">An Introduction to Ray Tracing</a> : An old book but a Classic.</li>
     <li><a href="http://www.amazon.com/Physically-Based-Rendering-Second-Edition/dp/0123750792/ref=sr_1_fkmr0_1?ie=UTF8&qid=1379818262&sr=8-1-fkmr0&keywords=physically+based+raytracer">Physically Based Rendering</a> : Heavy on maths but really good and well explained.</li>
  </ul>
</p>


    
<!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

