.po 8
.TH IPERL 1 Intercal/Perl
.ad
.nh
.SH NAME
iperl \- perl with intercal functions
.SH SYNOPSIS
\fBiperl\fP [options] filename args
.SH DESCRIPTION
\fIIperl\fP is an extension of \fIperl\fP
which retains all its original functionality,
but adds the ability to use \fIIntercal\fP operators.

The new operators are in the form of functions
and so are called using the \fBdo\fP or \fB&\fP syntax.
.SH Unary Operators
There are three unary operators,
each of which is available in 16\-bit and 32\-bit form.
The operators are
\fBand16\fP, \fBor16\fP, \fBxor16\fP, \fBand32\fP, \fBor32\fP, and \fBxor32\fP.

These operators perform their respective logical operations
on all pairs of adjacent bits,
the result from the first and last bits going into the first bit of the result.
The effect is that of rotating the operand one place to the right
and ANDing, ORing, or XORing with its initial value.
.br
.tl '''[Quoted from Woods and Lyon]'
.SH Binary Operators
There are two binary operators, mingle and select.

The \fImingle\fP operator takes two 16\-bit values
and produces a 32\-bit result by alternating the bits of the operands

The \fIselect\fP operator takes from the first operand
whichever bits correspond to 1's in the second operand,
and packs these bits at the right in the result.
.br
.tl '''[Quoted from Woods and Lyon]'
.SH EXAMPLES
See the file \fBop.ical\fP for examples.
.SH SEE ALSO
Woods, Donald R. and Lyon, James M.,
\fIThe Intercal Programming Language Reference Manual\fP, 1973.

Wall, Larry, and Schwartz, Randall,
\fIProgramming Perl\fP, 1990.

Any competent phrenologist, if you're thinking of using this!
.SH AUTHOR
It wasn't me, honest!
