
<script type="text/javascript">
  var disqus_identifier = "neverGiveUp";
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Java, LWJGL, OpenGL, OpenGL Binding, Timer, tick, LWJGL sprite animation"/>
		<meta name="Description" content="Prototyp Proof of concept using Java OpenGL Binding LWJGL"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>MyKaruga</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       September 19th, 2008</div>
   <h1>Ikaruga in Java</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="thumb.png" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         

				<table>
					<tr><td with="42px">
							<a href="demo-2008-09-13/nevergiveup.jnlp">
								<img src="../images/jws.gif" border="0" />
							</a>
						</td>
						<td style="padding-left:10px;"> 
							<a href="demo-2008-09-13/nevergiveup.jnlp"> Try it !</a>
						</td>
					</tr>
					<tr>
						<td with="42px">
							<a href="html/index.html">
								<img src="../images/code.gif" border="0" />
							</a>
						</td>
						<td style="padding-left:10px;">  
							<a href="src.zip">Download</a> the source code.</a>
						</td> 	
					</tr>
					
					<br/>
				</table>
				<div style="clear:both;"></div>
			</p>
			<br/>
			<h3>History
			</h3>
			
			<p id="paperbox">
				I've always been a huge fan of Ikaruga. Recently I was wondering if I would be able to code such an engine. This WIP is my (probably never ending) attempt for an answer.<br/>
				<br/>
				For distribution reasons, I used Java with LWJGL binding for the openGL part. I'm currently porting it to C++. Should be available soon.
			</p>
			<br/>
			<h3>Control
			</h3>
			
			<p id="paperbox">
				This game is better played with the Mouse
					<ul>
						<li> Move = Move (this is brillant) </li>
						<li> Mouse button 1: Fire</li>
						<li> Mouse button 2: Flip polarity</li>
						<li> Mouse button 3: Trigger Smart Plasma</li>
						<li> For people playing on a mac, with one button, use Z,X and C keyboard button. </li>
					</ul>
						
			</p>
			
			<br/>
			<h3>Screenshots
			</h3>
			<a href="screenShot/moreStuffDone.JPG" style="float : left; margin : 5px;">
				<div class="img-wrapper">
					<div>
						<img style="box-shadow: rgb(119, 119, 119) 3px 3px 3px;" src="screenShot/MmoreStuffDone.jpg"/>
					</div>
				</div>
			</a>
			<a href="screenShot/fixedBug.JPG" style="float : left; margin : 5px;">
				<div class="img-wrapper">
					<div>
						<img style="box-shadow: rgb(119, 119, 119) 3px 3px 3px;" src="screenShot/MfixedBug.jpg"/>
					</div>
				</div>
			</a>
			<a href="screenShot/firstPlasma.jpg" style="float : left; margin : 5px;">
				<div class="img-wrapper">
					<div>
						<img style="box-shadow: rgb(119, 119, 119) 3px 3px 3px;" src="screenShot/MfirstPlasma.jpg"/>
					</div>
				</div>
			</a>
			<div style="clear:both;"></div>
		</p>

<!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

