<script type="text/javascript">
  var disqus_identifier = "fillrate_issues";
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="fillrate, iPhone, iphone4, iphone 3GS, iPad"/>
		<meta name="Description" content="Fillrate comparaison on iPHone4, iPhone 3GS and iPad"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>Fillrate issue</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       Dec 11, 2010</div>
   <h1>Infinity Blade Fillrate</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="bladeInfinity.jpg" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         


        <style type="text/css">
table.sample {
	border-width: 1px;
	border-spacing: ;
	border-style: solid;
	border-color: gray;
	border-collapse: collapse;
	background-color: rgb(255, 255, 240);
}
table.sample th {
	border-width: thin;
	padding: 1px;
	border-style: inset;
	border-color: gray;
	background-color: white;
	-moz-border-radius: ;
}
table.sample td {
	border-width: thin;
	padding: 1px;
	border-style: inset;
	border-color: gray;
	background-color: white;
	-moz-border-radius: ;
}
</style>


I bought <a href="http://itunes.apple.com/ca/app/infinity-blade/id387428400?mt=8">"Infinity Blade"</a> yesterday. The game is a lot of fun and will satisfy both people looking for instant fun and people wishing for a long game while collecting powerful items. At $5.99 it is a bargain, a must have not only for the gameplay but also for its graphical breakthrough, just like <a href="http://itunes.apple.com/ca/app/rage-hd/id400707675?mt=8">Rage HD</a>.<br/>
<br/>
The game programmer in me really wanted to understand the engine and I was especially interested to see the game being released as a universal binary running on iPhone 3GS, iPhone4 and iPad. Those three devices have different capabilities but down the line it is often about managing the fillrate. 
<div style="clear:both;"></div>
</p>

			<h3>Differences</h3>
<p id="paperbox">
	If you don't own the game, here is an animated gif so you can see by yourself:<br/><br/>
	<img src="../fd_proxy/fillrate_issues/comparaison.gif" style="display:block;margin-right:auto;margin-left:auto;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
<br/><br/>
	The resolution difference really shows from iPhone 3GS to iPhone 4, not so much between iPhone 4 and iPad:<br/><br/>
	<table class="sample" style="width:600px; margin-left:auto; margin-right:auto; text-align: center;">
		<tr><th><b>Device</b></th><th><b>Resolution</b></th></tr>
		<tr><td>iPhone 3GS</td><td>480x320</td></tr>
		<tr><td>iPhone 4</td><td>960x640</td></tr>
		<tr><td>iPad</td><td>1024x768</td></tr>
	</table>	
	<br/>
It seems that for all iOS devices the game is rendering all static environment with a single (gorgeous) texture where all lightings effects (shadows, ambient occlusion, specular, diffuse) are prebaked ; possibly using a mega-texture technique. The difference is really in the way the enemies and player are rendered: On iPhone 3GS and iPhone4 we can see bumpmapping and probably specular mapping but no such things on iPad. I may be wrong but it also seems the player's model doesn't get dynamic lighting at all (enemies still do). Overall, the bigger screen gets the less eye candies and I think it is very representative of the difficulty to have a game running well on all major iOS platforms.<br/>
	<br/>
	In terms of pixels to draw and ratio:<br/>
	<br/>
		<table class="sample" style="margin-left:auto; margin-right:auto; text-align: center;">
		<tr><th width="10%" style="padding:10 10 10 10;">Machine</th><th>Number of pixels on screen</th><th>Num_pixels ratio vs previous line</th></tr>
		<tr><td style="padding:10 10 10 10;">iPhone&nbsp;3GS</td><td>153,600</td><td>1</td></tr>
		<tr><td style="padding:10 10 10 10;"> iPhone 4 </td><td>614,400</td><td >4</td></tr>
		<tr><td style="padding:10 10 10 10;"> iPad </td><td>786,432</td><td >1.28</td></tr>
	</table>	
	<br/>
	An iPhone 4 must draw 4 times more pixels than a 3GS. And an iPad must draw 1.28 times more pixels than an iPhone 4. This is all summarized in the following drawing:
<br/><br/>
<img src="../fd_proxy/fillrate_issues/diffsScreens.jpg" style="display:block;margin-left:auto;margin-right:auto;"/>
<br/>
<br/>

<br/>
<br/>
</p>		
<h3>Problem ?</h3>
<p id="paperbox">
	The fillrate is the number of pixels the GPU can generate per second. On iOS it is mostly determined by the velocity of the GPU, the speed of the RAM bus and of course the shaders you execute. The problem while developing a game on iOS is that the GPU raw power/screensize ratio varies a lot from a device to an other: As an example: an iPhone4 and a iPad use the same A2 ship and have the same raw fillrate....but the iPad must draw 28% more pixels.<br/><br/>
<img style="display: block;   margin-left: auto;   margin-right: auto;" src="../fd_proxy/fillrate_issues/chart.jpg"/>

<br/> Most of the time it means the iPad version will miss eye candies compared to an iPhone4. This is the case in "Infinity Blade" where it seems they had to remove bumpmapping, specular mapping and even lighting on the player (the game still looks amazing though). I had the same issue while working on SHMUP engine, fog was sacrified to remain at 60fps.<br/>
</p>

<h3>Feedback</h3>
<p id="paperbox">
	As usual, if you disagree or know better do not hesitate to email me. I see those entries as an opportunity to exchange and learn more. Happy learning, happy coding guys...
</p>


<!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>


