<script type="text/javascript">
  var disqus_identifier = "Prince_of_persia_Code_Review" ;
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Prince Of Persia, 6502, Apple II, Code review,RWT18"/>
		<meta name="Description" content="Prince Of Persia Code Review"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>Prince Of Persia Code Review  Part 3 (POP Bootloader explained)</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       June 14th, 2013</div>
   <h1>Prince Of Persia Code Review: Part 3 (POP Bootloader explained)</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="prince_of_persia.png" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         
<style type="text/css">
.shadowed-book{
  box-shadow: rgb(119, 119, 119) 3px 3px 3px;
  
 
  
  margin-right: 12px;
}

</style>

    Now that we have all the knowledge necessary, we can read the source and 
    understand where each files are located in the incredible mess that is the Apple II
    RAM layout.<br/>
<br/>
    You can also find an heavily commented version of the source code <a href="https://github.com/fabiensanglard/Prince-of-Persia-Apple-II/blob/master/01%20POP%20Source/Source/BOOT.S">on GitHub</a>.
<br/>
<br/>
<a href="index.html">Part I : Introduction</a><br/>
<a href="pop_boot.php">Part II : Bootloader</a><br/>
<a href="pop_boot2.php">Part III : Code explained</a><br/>
<br/>
    Here is a drawing of the infamous RAM that will be updated as we read on :
      <img style="display:block;margin-left:auto;margin-right:auto;width:620px;height:357px;" src="../fd_proxy/prince_of_persia/apple_IIe_RAM_layout.png" /><br/>
     
<div style="clear:both;"></div>
</p>



<br/>
<h3>BOOT.S</h3>
<p id="paperbox">
  <a href="https://github.com/fabiensanglard/Prince-of-Persia-Apple-II/blob/master/01%20POP%20Source/Source/BOOT.S"><code>BOOT.S</code></a> start by outputting <code>$01</code> to the instruction stream (<a href="https://github.com/fabiensanglard/Prince-of-Persia-Apple-II/blob/master/01%20POP%20Source/Source/BOOT.S#L21">line:21</a>). This will trigger the Apple firmware to automatically
  load one sector from track:0 to the RAM at <code>$800</code> and branch there :<br/>
  <br/>
 <img style="display:block;margin-left:auto;margin-right:auto;width:616px;height:348px;" src="../fd_proxy/prince_of_persia/apple_IIe_RAM_layout2.png"/><br/>
 <br/>
 After setting up a few soft-switches, <code>BOOT.S</code> uses RWTS16 to load a bunch of sectors to RAM using skewing table table (<a href="https://github.com/fabiensanglard/Prince-of-Persia-Apple-II/blob/master/01%20POP%20Source/Source/BOOT.S#L79">line:79</a>). It turns out those sectors contains the rest of <code>BOOT.S</code> and RWTS18 routines :<br/>
 <br/>
      <img style="display:block;margin-left:auto;margin-right:auto;width:620px;height:345px;" src="../fd_proxy/prince_of_persia/apple_IIe_RAM_layout3.png"/><br/>
      <br/>
 After moving RWTS18 routines to an other bank at <code>$D000</code> (so it can be used easily), it uses RWTS18 to load the entire track 1 to 
<code>$E000</code> (<a href="https://github.com/fabiensanglard/Prince-of-Persia-Apple-II/blob/master/01%20POP%20Source/Source/BOOT.S#L136">line:136</a>) and jump to a mysterious <code>$ee00</code>.


      <img style="display:block;margin-left:auto;margin-right:auto;width:616px;height:349px;" src="../fd_proxy/prince_of_persia/apple_IIe_RAM_layout4.png"/><br/>
</p>


<br/>
<h3>HIRES.S</h3>
<p id="paperbox">
 We have no idea what was on track 1 and what is supposed to be at <code>$ee00</code>.<br/>
 <br/>
 But we can use grep to find out:<br/>
 <pre class="long">

    fabiensanglard$ find . -name "*.S" -exec grep -H "org = \$ee00" {} \;

    ./01 POP Source/Source/HIRES.S:org = $ee00
    ./01 POP Source/Source/MOVER.S:org = $ee00

 </pre> 
 <p>
  After a bit of exploration, it turns out we are interested in <code>HIRES.S</code>.<br/>
  <br/>

 <img style="display:block;margin-left:auto;margin-right:auto;width:617px;height:349px;" src="../fd_proxy/prince_of_persia/apple_IIe_RAM_layout3.5.png"/><br/>
 <br/>
 <a href="https://github.com/fabiensanglard/Prince-of-Persia-Apple-II/blob/master/01%20POP%20Source/Source/HIRES.S"><code>HIRES.S</code></a> features a jump table at the beginning...that takes us to an other mysterious location: <code>$f880</code> (<a href="https://github.com/fabiensanglard/Prince-of-Persia-Apple-II/blob/master/01%20POP%20Source/Source/HIRES.S#L13">line:13</a>).
</p>


<br/>
<h3>MASTER.S</h3>
<p id="paperbox">
   Again, we have no idea what is supposed to be at <code>$f880</code>.<br/>
 <br/>
 But we can use grep to find out:<br/>
 <pre class="long">

    fabiensanglard$ find . -name "*.S" -exec grep -H "org = \$f880" {} \;

    ./01 POP Source/Source/MASTER.S:org = $f880
    ./04 Support/MakeDisk/S/MASTER.S:org = $f880
    ./04 Support/MakeDisk/S/MASTER525.S:org = $f880

 </pre> 
<p>
   So at <code>$f880</code> is the content of <code>MASTER.S</code>. We can edit the memory map:<br/>
   <br/>
   <img style="display:block;margin-left:auto;margin-right:auto;width:614px;height:348px;" src="../fd_proxy/prince_of_persia/apple_IIe_RAM_layout5.png"/><br/>
   <br/>
<br/>
    The content of <a href="https://github.com/fabiensanglard/Prince-of-Persia-Apple-II/blob/master/01%20POP%20Source/Source/MASTER.S"><code>MASTER.S</code></a> is as follow :
    <pre  class="long">

 
      jmp FIRSTBOOT
      jmp LOADLEVEL
      jmp RELOAD
      jmp LoadStage2
      jmp RELOAD

      jmp ATTRACTMODE
      jmp CUTPRINCESS
      jmp SAVEGAME
      jmp LOADGAME
      jmp DOSTARTGAME

      jmp EPILOG
      jmp LOADALTSET

    </pre>
    <p>
       
      At this point the game engine has been loaded in RAM and it is about to load the legendary DOUBLE-HIGH intro screen : <br/>
      <br/>
      <style>
        img.pixel, canvas.pixel {
    image-rendering: pixelated;
    image-rendering: -moz-crisp-edges;
    image-rendering: crisp-edges;
      </style>
      <img class="pixel" style="display:block;margin-left:auto;margin-right:auto;width:560px;height:384px;" 
      src="../fd_proxy/prince_of_persia/pop_splash.png"/><br/>
      
</p>

<br/>
<h3>Next</h3>
<p id="paperbox">
    That is it for now. I am unsure people are really interested in more POP Code Review. Let me know.
<p>
			
	<!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

