<script type="text/javascript">
  var disqus_identifier = "shmup_source_code";
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="iPhone 3D engine, openGL ES 1.1, openGL ES 2.0, bumpMapping, shadowMapping, tutorial, specularMapping, Source Code"/>
		<meta name="Description" content="Iphone 3D engine"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>Shmup 3D engine source code</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       June 30th, 2011</div>
   <h1>Source Code Release</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="source_code.png" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         
	
	I have decided to release the full source code of <a href="http://itunes.apple.com/us/app/shmup/id337663605?mt=8">SHMUP</a> a shoot'em up 3D engine specially designed for mobile platform and released on iOS in 2010.<br/>
	<br/>The game and engine are fairly inspired of Ikaruga, the legendary shmup from the 1999 DreamCast. Anything you saw in Ikaruga, this engine can do it too.<br/>
</p>
<div style="clear:both;"></div>

<h3>Source Code</h3>
<p>
	The license is GPL which mean you have to release the source code of what you produce with it. Note that the <code>data</code> folder is provided so you can play with it but you are not free to redistribute it and I remain the owner of the content (except for the song from Future Crew that was licensed). 
	<br/>
	
	<br/>
	A few noticable features:<br/>
	<ul>
		<li>Coded in C with two rendering path: OpenGL ES 1.0 and OpenGL ES 2.0 (<a href="../dEngine/index.php">dEngine</a> renderer).</li>
		<li><a href="../polygon_codec/index.html">Polygon Codec</a>: Visibilty set is precalculated for maximun bandwidth efficiency.</li>
		<li>Ability to <a href="../shmup_generate_videos/index.html">record replay and generate its own videos</a>.</li>
		<li>Compile on iOS and Windows. A port to MacOS X, Linux or Android should be easy.</li>
		<li>Support MD5 skeletal animation for any entity in the game.</li>
	</ul>
	<br/>
	<table align="center" style="width: 80% ;" border="0">
		<tr align="center" style="font-weight: bold; text-decoration: underline;" >
			<td style="padding-bottom: 20px;">Source code (GPL)</td>
			<td style="padding-bottom: 20px;">Video</td>
		</tr>
		<tr  align="center">
			<td><a href="https://github.com/fabiensanglard/Shmup"><img src="proj.png"/></a></td>
		
			<td r>
				<video width="320" height="480" preload="none" poster="../fd_proxy/polygon_codec/Untitled_low.jpg" controls>
  <source src="../fd_proxy/polygon_codec/Untitled_low.mov" type="video/mp4">
  Your browser does not support the video tag.
</video>

			</td>
		</tr>
		
	
	</table>
	<br/>
</p>

<h3>License</h3>
			<p id="paperbox">
			The source code is being released under GPL license. Note that the <code>data</code> folder is provided so you can play with it but you are not free to redistribute it and I remain the owner of the content (except for the song from Future Crew that was licensed). 
			</p>
			
<h3>Android port</h3>
			<p id="paperbox">
				Since the core of the engine is pure C it should be easy to port to Android. The Native Development Kit should allow the engine to be compiled as a library and you just have to write a few wrappers to take the user input, play the music and sync with the screen. If anyone is willing to do it I am ok with publishing it and sharing the revenu 50/50 (just let me know in advance you are working on it to avoid overlap).			
			</p>

<h3>3D world but 2D control</h3>
<p id="paperbox">	
	The game is a bit special because it is all 3D but you only control your ship in 2D within the screen space. I was not so trivial to accomplish at first but I wrote a first version in <a href="../neverGiveUp/index.php">Java a few years ago</a>: What I did was to draw the background with perspective projection then clear the depth buffer, switch to orthogonal projection and draw the entities/bullets. It was working ok but there was no way to have continious transition between cinematic and game since the entities were not really part of the 3D world.<br/>
	<br/>
	This version actually recalculate each entity matrix for each frame starting from their 2D screen coordinates. This way even though the camera moves in the 3D world, the entities look "glued" to the screen...and you can switch from cinematic to game at will.
</p>			
			
<h3>With more time...</h3>
			<p id="paperbox">
				There are a few things that I wish I had time to do. The reason it wasn't done is because I was burned out.<br/>
				<ul>
					<li>The OpenGL ES 2.0 is incomplete, fog and sprite rendering are missing.</li>
					<li>The Polygon Codec preprocessing should have been an independent tool. Ideally I would have wrote a plug-in for Blender to generate the camera path instead of a text file.</li>
					<li>The video generator should have been an independent tool. </li>
					<li>The Polygon Codec preprocessing is not multi-threaded...but it would have required a LOT of RAM to work anyway</li>
					<li>The collision detection system is 0(n&sup2;) complexity. Even though entities are grouped by type in their own list (enemies,enemies bullet,players,players bullets) a sweep and prune algorithm would have been better.</li>
					<li>The network synchronization system is awful.</li>
					<li>The caching system could have been more generic. C++ templates would have been godly there.</li>
					<li>Too bad I did not get to collaborate with a passionate artist in order to make the  game look better. I think the graphics don't really do justice to the engine capabilities.</li>
				</ul>
				
			</p>

<!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

