<script type="text/javascript">
  var disqus_identifier = "git_code_review";
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Git Source Code Review"/>
		<meta name="Description" content="Git Source Code Review"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
	
 	
		
		<title>Git Source Code Review</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       March 30th, 2014</div>
   <h1>Git Source Code Review: Genesis</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="git_blue_print.png" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         
        <!-- Add fancyBox -->
  <link rel="stylesheet" href="../fancybox/source/jquery.fancybox.css?v=2.1.5" type="text/css" media="screen" />
  <script type="text/javascript" src="../fancybox/source/jquery.fancybox.pack.js?v=2.1.5"></script>

    <style>

 .comment{color: rgb(66,135,65);}
 .keyword{color: rgb(182,16,162);}
 .literal{color: rgb(218,37,36);}

 .include{color: rgb(117,85,119);}

 .numbers{color: rgb(96,0,205);}

</style>
To dive into a big codebase is often a daunting task that have discouraged many (I received many emails from game developers about Dooms and Quakes).<br/>
<br/>
The advantage of Git project is that it was self-hosted from a very early stage: I was able to start with reading super-tiny-8-translation-units project from 9 years ago and then travel in time toward more complexity !<br/>
<br/>
<a href="index.php">Part 1: Overview</a><br/>
<a href="history.php">Part 2: Genesis</a></br>
<a href="architecture.php">Part 3: Architecture</a></br>
<a href="diff.php">Part 4: Algorithms for DIFF</a></br>
<br/>
    
<br/>
    <div style="clear:both;"></div>
</p>




<h2>The beginning</h2>
<p>
  Linus Torvalds gave an interesting talk at Google Talks 2007 :<br/>
  <iframe style="margin-left:auto;margin-right:auto; display:block; margin-top:20px; margin-bottom: 20px;" width="420" height="315" src="https://www.youtube.com/embed/4XpnKHJAok8" frameborder="0" allowfullscreen></iframe>
  A lot can be learned from it but one particular aspect is that Git reached self-hosting capability within two weeks of development (at 12m18s). That <a href="https://github.com/git/git/tree/e83c5163316f89bfbde7d9ab23ca2e25604af290">first commit</a> can still be checked out: its SHA1 hash is <code class="git">e83c5163316f89bfbde7d9ab23ca2e25604af290</code>.<br/>
  <br/>
  <pre>


    git checkout e83c5163316f89bfbde7d9ab23ca2e25604af290

  </pre>
  <p>
  Eight translation units and one header !
  <pre>
 
    Fabiens-MacBook-Air:git fabiensanglard$ ls -l
    total 3048
    -rw-r--r--  1 fabiensanglard  staff      957 17 Mar 23:23 Makefile
    -rw-r--r--  1 fabiensanglard  staff     8392 17 Mar 23:23 README
    -rw-r--r--  1 fabiensanglard  staff     2484 17 Mar 23:23 cache.h
    -rw-r--r--  1 fabiensanglard  staff      503 17 Mar 23:23 cat-file.c
    -rw-r--r--  1 fabiensanglard  staff     4103 17 Mar 23:23 commit-tree.c
    -rw-r--r--  1 fabiensanglard  staff     1198 17 Mar 23:23 init-db.c
    -rw-r--r--  1 fabiensanglard  staff     5681 17 Mar 23:23 read-cache.c
    -rw-r--r--  1 fabiensanglard  staff      986 17 Mar 23:23 read-tree.c
    -rw-r--r--  1 fabiensanglard  staff     2034 17 Mar 23:23 show-diff.c
    -rw-r--r--  1 fabiensanglard  staff     5395 17 Mar 23:23 update-cache.c
    -rw-r--r--  1 fabiensanglard  staff     1441 17 Mar 23:23 write-tree.c


  </pre>
  <p>
    <br/> 
    
    This early version generated seven executables <code>update-cache</code> <code>show-diff</code> <code>init-db</code> <code>write-tree</code> <code>read-tree</code> <code>commit-tree</code> <code>cat-file</code> which
    were enough to generate snapshots.<div style="clear:both;"></div>
    <p>
    <img src="git_early_days.png" style="float:left;margin-top: 0px;display:inline; margin-right:15px;"/>Later during development shell-scripts using those tiny executables were added (i.e: <a href="https://github.com/git/git/blob/master/contrib/examples/git-checkout.sh">contrib/examples/git-checkout.sh</a>). At this stage, Git had
    two distinct parts: Low-level C implemented Plumbing and High-level shell script based Porcelain (see left drawing).<br/>
    <div style="clear:both;"></div>
    <p>As the project evolved, more shell scripts commands were added and some commands ended up being converted to "built-in" using C. Here is the example of <code>git-commit</code> which started <a href="https://github.com/git/git/blob/96e67c86f817b4fbd492b12f57dae4bd821571ba/builtin/commit.c#L5">here</a> in 2005 as <code>git-commit.sh</code>  and was ported to builtin C in commit <code class="git">f5bbc3225c4b073a7ff3218164a0c820299bc9c6</code> <a href="https://github.com/git/git/commit/f5bbc3225c4b073a7ff3218164a0c820299bc9c6#diff-119048f6cdad8132b8675a11d0897c08">here</a> three years later in 2008. <br/>
    <br/>
    Eventually a "dispatch" executable <code>git</code> able to run C or shell script was added on top of everything :<br/>
    <br/>
    <img src="git-layers.png" style="margin-top: 20px;display:block; margin-left:auto;margin-right:auto;"/>
</p>

<h2>All the commands</h2>
<p>
  The old rule C = Plumbing and shell script = Porcelain is not more. A vast majority of the commands 
  have been converted to C. Here are the 102 git commands, with the C built-in in blue and shell script in black :<br/>
<br/>

  <style type="text/css">

table tr td table tr td.cmsList {
   border: 0px; 
}


  </style>

  <table style="vertical-align:top;  border-collapse: collapse ; background-color: #fff;" >
    <tr>
      <td colspan="4" style="text-align: center;border: 1px solid #000">Porcelain</td>
      <td colspan="4" style="text-align: center;border: 1px solid #000">Plumbing</td>
    </tr>
    <tr>
      <td style="text-align: center;border: 1px solid #000">Main (36)</td>
      <td style="text-align: center;border: 1px solid #000">Ancillary (30)</td>
      <td style="text-align: center;border: 1px solid #000">Interrogation (16)</td>
      <td style="text-align: center;border: 1px solid #000">Interaction (10)</td>

       <td style="text-align: center;border: 1px solid #000">Manip (17)</td>
      <td style="text-align: center;border: 1px solid #000">Interrogation (18)</td>
      <td style="text-align: center;border: 1px solid #000">Synching (12)</td>
      <td style="text-align: center;border: 1px solid #000">Internal (15)</td>
    </tr>

    <td style="vertical-align: top;border: 1px solid #000">
  <table class="cmsList"> 
    <tr><td><span style="color:blue;">git-add</span></td></tr>
    <tr><td>git-am</td></tr>
    <tr><td><span style="color:blue;">git-archive</span></td></tr>
    <tr><td><span style="color:blue;">git-bisect</span></td></tr>
    <tr><td><span style="color:blue;">git-branch</span></td></tr>
    <tr><td><span style="color:blue;">git-bundle</span></td></tr>
    <tr><td><span style="color:blue;">git-checkout</span></td></tr>
    <tr><td><span style="color:blue;">git-cherry-pick</span></td></tr>
    <tr><td>git-citool</td></tr>
    <tr><td><span style="color:blue;">git-clean</span></td></tr>
    <tr><td><span style="color:blue;">git-clone</span></td></tr>
    <tr><td><span style="color:blue;">git-commit</span></td></tr>
    <tr><td><span style="color:blue;">git-describe</span></td></tr>
    <tr><td><span style="color:blue;">git-diff</span></td></tr>
    <tr><td><span style="color:blue;">git-fetch</span></td></tr>
    <tr><td><span style="color:blue;">git-format-patch</span></td></tr>
    <tr><td><span style="color:blue;">git-gc</span></td></tr>
    <tr><td><span style="color:blue;">git-grep</span></td></tr>
    <tr><td>git-gui</td></tr>
    <tr><td><span style="color:blue;">git-init</span></td></tr>
    <tr><td><span style="color:blue;">git-log</span></td></tr>
    <tr><td><span style="color:blue;">git-merge</span></td></tr>
    <tr><td><span style="color:blue;">git-mv</span></td></tr>
    <tr><td><span style="color:blue;">git-notes</span></td></tr>
    <tr><td>git-pull</td></tr>
    <tr><td><span style="color:blue;">git-push</span></td></tr>
    <tr><td>git-rebase</td></tr>
    <tr><td><span style="color:blue;">git-reset</span></td></tr>
    <tr><td><span style="color:blue;">git-revert</span></td></tr>
    <tr><td><span style="color:blue;">git-rm</td></tr>
    <tr><td><span style="color:blue;">git-shortlog</td></tr>
    <tr><td><span style="color:blue;">git-show</td></span></tr>
    <tr><td>git-stash</td></tr>
    <tr><td><span style="color:blue;">git-status</span></td></tr>
    <tr><td>git-submodule</td></tr>
    <tr><td><span style="color:blue;">git-tag</span></td></tr>
    <tr><td>gitk</td></tr>
  </table>
</td>

  <td  style="vertical-align: top;border: 1px solid #000">
<table border="0"> 
    <tr><td><span style="color:blue;">git-config</td></tr>
    <tr><td><span style="color:blue;">git-fast-export</span></td></tr>
    <tr><td>git-fast-import</td></tr>
    <tr><td>git-filter-branch</td></tr>
    <tr><td>git-lost-found</td></tr>
    <tr><td>git-mergetool</td></tr>
    <tr><td><span style="color:blue;">git-pack-refs</td></tr>
    <tr><td><span style="color:blue;">git-prune</td></tr>
    <tr><td><span style="color:blue;">git-reflog</td></span></tr>
    <tr><td>git-relink</td></tr>
    <tr><td><span style="color:blue;">git-remote</td></tr>
    <tr><td><span style="color:blue;">git-repack</td></tr>
    <tr><td><span style="color:blue;">git-replace</td></span></tr>
    <tr><td>git-repo-config</td></tr>
     </table>
 </td>

<td  style="vertical-align: top;border: 1px solid #000">
<table border="0"> 
    <tr><td><span style="color:blue;">git-annotate</td></tr>
    <tr><td><span style="color:blue;">git-blame</td></tr>
    <tr><td><span style="color:blue;">git-cherry</td></tr>
    <tr><td><span style="color:blue;">git-count-objects</span></td></tr>
    <tr><td>git-difftool</td></tr>
    <tr><td><span style="color:blue;">git-fsck</td></tr>
    <tr><td><span style="color:blue;">git-get-tar-commit-id</td></tr>
    <tr><td><span style="color:blue;">git-help</td></span></tr>
    <tr><td>git-instaweb</td></tr>
    <tr><td><span style="color:blue;">git-merge-tree</span></td></tr>
    <tr><td>git-rerere</td></tr>
    <tr><td><span style="color:blue;">git-rev-parse</td></tr>
    <tr><td><span style="color:blue;">git-show-branch</td></tr>
    <tr><td><span style="color:blue;">git-verify-tag</td></tr>
    <tr><td><span style="color:blue;">git-whatchanged</span></td></tr>    
    <tr><td>gitweb</td></tr>
    </table>
</td>   
  

<td  style="vertical-align: top;border: 1px solid #000">   
  <table border="0"> 
    <tr><td>git-archimport</td></tr>
    <tr><td>git-cvsexportcommit</td></tr>
    <tr><td>git-cvsimport</td></tr>
    <tr><td>git-cvsserver</td></tr>
    <tr><td>git-imap-send</td></tr>
    <tr><td>git-p4</td></tr>
    <tr><td>git-quiltimport</td></tr>
    <tr><td>git-request-pull</td></tr>
    <tr><td>git-send-email</td></tr>
    <tr><td>git-svn</td></tr>
  </table>

</td>


<td  style="vertical-align: top;border: 1px solid #000">
 <table border="0"> 
    <tr><td><span style="color:blue;">git-apply</td></tr>
    <tr><td><span style="color:blue;">git-checkout-index</td></tr>
    <tr><td><span style="color:blue;">git-commit-tree</td></tr>
    <tr><td><span style="color:blue;">git-hash-object</td></tr>
    <tr><td><span style="color:blue;">git-index-pack</td></tr>
    <tr><td><span style="color:blue;">git-merge-file</td></tr>
    <tr><td><span style="color:blue;">git-merge-index</td></tr>
    <tr><td><span style="color:blue;">git-mktag</td></tr>
    <tr><td><span style="color:blue;">git-mktree</td></tr>
    <tr><td><span style="color:blue;">git-pack-objects</td></tr>
    <tr><td><span style="color:blue;">git-prune-packed</td></tr>
    <tr><td><span style="color:blue;">git-read-tree</span></td></tr>
    <tr><td>git-symbolic-ref</td></tr>
    <tr><td><span style="color:blue;">git-unpack-objects</td></tr>
    <tr><td><span style="color:blue;">git-update-index</td></tr>
    <tr><td><span style="color:blue;">git-update-ref</td></tr>
    <tr><td><span style="color:blue;">git-write-tree</span></td></tr>
</table>    
</td>

<td style="vertical-align: top;border: 1px solid #000">
 <table border="0"> 
    <tr><td><span style="color:blue;">git-cat-file</td></tr>
    <tr><td><span style="color:blue;">git-diff-files</td></tr>
    <tr><td><span style="color:blue;">git-diff-index</td></tr>
    <tr><td><span style="color:blue;">git-diff-tree</td></tr>
    <tr><td><span style="color:blue;">git-for-each-ref</td></tr>
    <tr><td><span style="color:blue;">git-ls-files</td></tr>
    <tr><td><span style="color:blue;">git-ls-remote</td></tr>
    <tr><td><span style="color:blue;">git-ls-tree</td></tr>
    <tr><td><span style="color:blue;">git-merge-base</td></tr>
    <tr><td><span style="color:blue;">git-name-rev</td></tr>
    <tr><td><span style="color:blue;">git-pack-redundant</td></tr>
    <tr><td><span style="color:blue;">git-rev-list</span></td></tr>
    <tr><td>git-show-index</td></tr>
    <tr><td><span style="color:blue;">git-show-ref</span></td></tr>
    <tr><td>git-tar-tree</td></tr>
    <tr><td><span style="color:blue;">git-unpack-file</td></tr>
    <tr><td><span style="color:blue;">git-var</td></tr>
    <tr><td><span style="color:blue;">git-verify-pack</span></td></tr>
</table>    
</td>

<td style="vertical-align: top;border: 1px solid #000">
 <table border="0"> 
    <tr><td>git-daemon</td></tr>
    <tr><td><span style="color:blue;">git-fetch-pack</span></td></tr>
    <tr><td>git-http-backend</td></tr>
    <tr><td><span style="color:blue;">git-send-pack</td></tr>
    <tr><td><span style="color:blue;">git-update-server-info</span></td></tr>
    <tr><td>git-http-fetch</td></tr>
    <tr><td>git-http-push</td></tr>
    <tr><td>git-parse-remote</td></tr>
    <tr><td><span style="color:blue;">git-receive-pack</span></td></tr>
    <tr><td>git-shell</td></tr>
    <tr><td><span style="color:blue;">git-upload-archive</span></td></tr>
    <tr><td>git-upload-pack</td></tr>
</table>    
</td>


<td style="vertical-align: top;border: 1px solid #000">
 <table border="0"> 
    <tr><td><span style="color:blue;">git-check-attr</td></tr>
    <tr><td><span style="color:blue;">git-check-ref-format</td></tr>
    <tr><td><span style="color:blue;">git-column</td></tr>
    <tr><td><span style="color:blue;">git-credential</span></td></tr>
    <tr><td>git-credential-cache</td></tr>
    <tr><td>git-credential-store</td></tr>
    <tr><td><span style="color:blue;">git-fmt-merge-msg</td></tr>
    <tr><td><span style="color:blue;">git-mailinfo</td></tr>
    <tr><td><span style="color:blue;">git-mailsplit</span></td></tr>
    <tr><td>git-merge-one-file</td></tr>
    <tr><td><span style="color:blue;">git-patch-id</span></td></tr>
    <tr><td>git-peek-remote</td></tr>
    <tr><td>git-sh-i18n</td></tr>
    <tr><td>git-sh-setup</td></tr>
    <tr><td>git-stripspace</td></tr>
</table>

</td>
</tr>
</table>
  <div style="clear:both;"></div>
</p>

<h2>Next Part</h2>
<p>
    Next: <a href="architecture.php">Architecture</a><br/>
</p>

  <!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

