<script type="text/javascript">
  var disqus_identifier = "git_code_review";
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Git Source Code Review"/>
		<meta name="Description" content="Git Source Code Review"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
	
 	
		
		<title>Git Source Code Review</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       March 30th, 2014</div>
   <h1>Git Source Code Review: Overview</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="git_blue_print.png" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         
        <!-- Add fancyBox -->
  <link rel="stylesheet" href="../fancybox/source/jquery.fancybox.css?v=2.1.5" type="text/css" media="screen" />
  <script type="text/javascript" src="../fancybox/source/jquery.fancybox.pack.js?v=2.1.5"></script>

    <style>

 .comment{color: rgb(66,135,65);}
 .keyword{color: rgb(182,16,162);}
 .literal{color: rgb(218,37,36);}

 .include{color: rgb(117,85,119);}

 .numbers{color: rgb(96,0,205);}

</style>

Since its release in December 2005, <a href="http://en.wikipedia.org/wiki/Git_(software)">git</a> has taken over the software industry. In combination with <a href="https://github.com/">GitHub</a> it is now a powerful tool to publish and share code: From big teams (<a href="https://github.com/torvalds/linux">linux kernel</a>, <a href="https://github.com/id-Software">id Software</a>, <a href="https://www.unrealengine.com/blog/welcome-to-unreal-engine-4">Epic Unreal</a>) to single individual (<a href="https://github.com/jmechner/Prince-of-Persia-Apple-II">Prince of Persia</a>, <a href="https://github.com/fabiensanglard/Another-World-Bytecode-Interpreter">Another world</a>, <a href="https://github.com/fabiensanglard/xrick/">Rick Dangerous</a>), many have adopted it as their main SCM.<Br/>
<Br/>
I wanted to get a better understanding of the "stupid content tracker" and see how it was built so I spent a few weeks in my spare time reading the source code. I found it tiny, tidy, well-documented and overall pleasant to read.<br/>
<br/>
 As usual I have compiled my notes into an article, maybe it will encourage some of us to read more source code and become better engineers.<br/>
<br/>
<a href="index.php">Part 1: Overview</a><br/>
<a href="history.php">Part 2: Genesis</a></br>
<a href="architecture.php">Part 3: Architecture</a></br>
<a href="diff.php">Part 4: Algorithms for DIFF</a></br>
<br/>
    
    <div style="clear:both;"></div>
</p>






<h2>First contact</h2>
<p>
  Getting the source code is easy :
  <pre class="long">


    git clone https://github.com/git/git

  </pre>
  <p>
    <br/>
    Compiling on Linux or MacOS X works "out of the box" as long as you only need English. If you want to build on Windows: Don't.<br/>
    
  <pre class="long">


    cd git
    echo "NO_GETTEXT = 1;" > config.mak
    make

  </pre>
    <p>
      <b><u>Trivia :</u></b> <code>NO_GETTEXT</code> indicates that no string translation should be performed. 
      Git source code wraps all its character strings in a <code>_N(msgid)</code> marker 
      so translation can be optionally downloaded before compilation.<br/>
      <br/>
      <u>What language is used ?</u><br/>
      <br/>
      In its infancy Git was programmed entirely in C (the very first Git commit was performed with just 5 tiny executables: More about this in the <a href="history.php">genesis</a> part). Today, the codebase is a mix of C (for performance critical operations) and portable shell script with an interesting architecture allowing usage of any programming language.<br/>
      <br/>
      <u>How big is it ?</u><br/>
      <br/>
      I ran <a href="http://cloc.sourceforge.net/">cloc</a> to get an idea of the volume of code :
      <pre>


    fabiensanglard$ cloc *.c *.h *.sh
     317 text files.
     317 unique files.                                          
       0 files ignored.

    http://cloc.sourceforge.net v 1.60  T=1.29 s (245.5 files/s, 93178.5 lines/s)
    -------------------------------------------------------------------------------
    Language                     files          blank        comment           code
    -------------------------------------------------------------------------------
    C                              187          12037          11507          78511
    Bourne Shell                    29            866            918           7586
    C/C++ Header                   101           1314           1978           5604
    -------------------------------------------------------------------------------
    SUM:                           317          14217          14403          91701
    -------------------------------------------------------------------------------


      </pre>
    <p>
    At 91,701 CLOC, the volume of code is roughly equivalent to Quake engine which I was able to read within a month. Per today standards it is a small project:  Linux kernel 3.10 release had 15,803,499 lines of code !
</p>








<h2>Browsing the source code</h2>
<p>
  The Linux way to browse and write code is not via traditional IDE like Visual Studio, XCode or Eclipse. Most Linux developers use either <a href="http://en.wikipedia.org/wiki/Vim_(text_editor)">Vim</a>, <a href="http://en.wikipedia.org/wiki/Emacs">Emacs</a> or <a href="http://en.wikipedia.org/wiki/MicroEMACS">MicroEmacs</a>.
  I ended up learning Vim because:
  <ul>
    <li>I wanted to invest time in something that would be available everywhere.</li>
    <li>I wanted to invest time in something that would be usable during SSH sessions.</li>
    <li>I liked the old-school text only look and feel of Vim.</li>
  </ul> 
  <p>
  <br/>

    <img src="vi_raw.png" style="float:left;margin-right: 20px;margin-bottom: 35px; margin-top: 0px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>

But coming from an Eclipse/XCode/Visual Studio world, the first contact with Vim was discouraging to say the least:<br/>

    <ul style="overflow: auto;">
        <li>There is no syntax color highlights, code is visually hard to read (not even to mention the syntax or semantic).</li>
        <li>There is no file explorer on the left side.</li>
        <li>There is no way to go directly to a method or variable definition (Command-Click in XCode, Command-Click on Eclipse/Visual Studio).</li>
        <li>Pressing the arrow keys does not move the cursor but instead produce garbage characters <b>@#&**~`</b> !</li>
        <li>Compiler errors are not reported in advance.</li>
        <li>There is no convenient search box.</li>
    </ul>
    <p>
      In one sentence: I had to learn everything again :/ ! 
    <div style="clear:both;"></div>
<p>
  <img src="vi_plugins.png" style="float:right;margin-left: 20px;box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
    But it was fun to learn something new and after a few hours everything felt very fast and natural. Also, many plugins enable the commodities of a mainstream IDE :
    <ul style="overflow: auto;">
        <li>Syntax color highlights is a built-in features of Vim: <code>:syntax on</code></li>
        <li>Vim can jump directly to a definition with <code>ctags</code>.</li>
        <li><code>NerdTree</code> plugin allows to browse the files in the project.</li>
        <li><code>You Complete Me</code> plugin allows to see compiler errors in advance and even provided semantic autocompletion</li>
    </ul>    
    
    <div style="clear:both;"></div>

<Br/>
<p>
  The end result was a tool more powerful than I ever used before :<br/>
      <ul style="overflow: auto;">
        <li>Lightweight editor that consume very little RAM/CPU.</li>
        <li>Never block or crash.</li>
        <li>Fast as lighting since hands never leave the "asdf"/"jkl;" position.</li>
        <li>Most mainstream IDE features available.</li>
        <li>Can jump to function definition regardless of the language (C or Shell Script).</li>
      </ul>
      <p>
  <br/>
<img src="vim_plugin_nerdTree.png" style="display:block; margin-left:auto; margin-right:auto; box-shadow: rgb(119, 119, 119) 3px 3px 3px;"/>
    <div style="clear:both;"></div>
    

<p>  
  <br/>
    <u><b>Trivia :</b></u> In the 90s the <a href="http://en.wikipedia.org/wiki/Editor_war">editor War</a> between Vim and Emacs users was a hot topic. I hope members of the <a href="https://googledrive.com/host/0B6LMD0u8OhYYZEotN2QyR1hwR1k/">Church of Emacs</a> won't be offended.<br/>
  </p>

<h2>Documentation</h2>
<p>
  It is easier to find something when you know what you are looking for. Before reading Git I gathered as much documentation as possible.
    Usually open source projects are poor on this side but Git is an exception:
    Not only a few good articles and books have been published about it:
    <ul>
      <li><a href="http://aosabook.org/en/git.html">The Architecture of Open Source Applications (Volume 2): Git<a/></li>
      <li><a href="https://github.com/pluralsight/git-internals-pdf/releases">Git Internals</a></li>
      <li><a href="http://git-scm.com/book/en/Git-Internals">Pro Git </a></li>
      <li><a href="http://pcottle.github.io/learnGitBranching/">LearnGitBranching</a></li>
    </ul>
    <p>
      The developers have also done an outstanding job with the <a href="https://github.com/git/git/tree/master/Documentation">Git Documentation directory</a> which contains wealth of explanations and man pages that are well-written and actually useful:
      <ul>
        <li>Rare luxury they even feature drawings <a href="https://www.kernel.org/pub/software/scm/git/docs/git-rebase.html">git-rebase(1)</a>.</li>
        <li><code>.git</code> directory layout <A href="https://www.kernel.org/pub/software/scm/git/docs/gitrepository-layout.html">gitrepository-layout(5)</a>.</li>
        <li>Principles of Plumbing and Porcelain <a href="https://www.kernel.org/pub/software/scm/git/docs/#_high_level_commands_porcelain">git(1)</a>.</li>
        <li>Additional <a href="https://github.com/git/git/blob/master/Documentation/git-tools.txt">tools</a>.</li>
        <li>Diff API <a href="https://github.com/git/git/blob/master/Documentation/technical/api-diff.txt">api-diff.txt</a>.</li>
        <li>Tutorial for the "core" git commands: <a href="https://www.kernel.org/pub/software/scm/git/docs/gitcore-tutorial.html">gitcore-tutorial(7)</a>.</li>
        <li>The <a href="https://www.kernel.org/pub/software/scm/git/docs/user-manual.html">User manual</a> is also really good and does a good job of explaining <a href="https://www.kernel.org/pub/software/scm/git/docs/user-manual.html#git-concepts">concepts</a> and everything down to the not so well down<a href="https://www.kernel.org/pub/software/scm/git/docs/user-manual.html#pack-files">pack files</a> that allow efficient data storage.</li>
      </ul>
      <p>
        Finally the official website (<a href="http://git-scm.com/">git-scm.com</a>) is a good hub of additional resources.<br/>
  <br/>
      <u><b>Trivia :</b></u> Everything still <a href="https://www.youtube.com/watch?v=UfjRcGDBvMQ">ain't all sunshine and rainbows</a>. The infamous "Forward-port local commits to the updated upstream head" from <a href="https://www.kernel.org/pub/software/scm/git/docs/git-rebase.html">git-rebase(1)</a> is still there !
</p>







<h2>Next Part</h2>
<p>
   Next : <a href="history.php">Genesis</a>
</p>













  <!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

