<script type="text/javascript">
  var disqus_identifier = "cellphoneModem";
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Android, ARM toolchain, iPhone, Hayes command set,RIL daemon MITM, AT Commands"/>
		<meta name="Description" content="Exploring Hayes command set in cellphones based on Android and iPhone OS"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>Tracing the baseband</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       May, 11th 2010</div>
   <h1>Tracing the baseband: Part 2</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="androIphone.jpg" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         

	After succesfully injecting command in the baseband on iOS, I tried the same approach on Android but
	placing hooks and operating within the application was unfortunately not possible: The loader (<code>ld</code>) does not support library preloading via LD_PRELOAD. I had to grow an unix beard and deal with threads/pseudo-terminals.<br/>
<div style="clear:both;"></div>
<h3>Android ARM Toolchain
			</h3>
			<p id="paperbox">
During normal operations the Radio Layer Interface deamon (RILd) from Android communicates with the modem via a pseudo-terminal file. RILd opens <code>/dev/smd0</code> ( the slave end of a pseudo-terminal) and uses it as I/O to issue commands and receive responses:<br/>
<br/>
<img src="../fd_proxy/cellphoneModem/android_normal.png" />
<br/>
<br/>
The trick is to rename <code>/dev/smd0</code> to <code>/dev/smd0Real</code> and then create a process that will connect to <code>/dev/smd0Real</code>  and create a proxy <code>/dev/smd0</code>. Two thread in the process then connect the ends of the two channels.<br/>
<br/>
<img src="../fd_proxy/cellphoneModem/android_mitm.png"/>
<br/>
<u>Note:</u> I found out about this technique in a <a href="http://mulliner.org/security/sms/feed/injecting_sms_mulliner_miller.pdf">great paper</a> by Collin Mulliner &  Charlie Miller ... but they did not provide any source code. So I kept on hacking using what I could get out of their paper.<br/>
<br/>
			


<u>Note:</u> Creating the pseudo terminal using <code>openpty</code>  was out of scope because not available in my toolchain (CodeSourcery). Instead the program opens <code>/dev/ptmx</code>, grab the name of the pseudo-terminal slave end via <code>ptsname</code> and then create a symbolic link from <code>/dev/smd0</code> to <code>/dev/pts/X</code>  (try to mv throw an error about cross-device :/) .
</p>
<h3>Android ARM Toolchain
			</h3>
			<p id="paperbox">
Here is the source code or the TITM (Terminal In The Middle): <a href="main.c">main.c</a><br/>
<br/>
I used a solid IBM T43 running Linux Ubuntu with <a href="http://www.codesourcery.com/sgpp/lite/arm/portal/subscription?@template=lite">CodeSourcery's IA32 for Linux</a>.<br/>
<br/>
<u>Compile :</u>
<pre class="long">

	cd :~/CodeSourcery/Sourcery_G++_Lite/bin
	./arm-none-linux-gnueabi-gcc -lutil -pthread -static -o ~/mitm ~/main.c


</pre>
<br/>
<p>
<u>Note</u> The program is statically linked, getting Android libc's implementation bionic to work was a real pain and I gave up. Downside is 744Kb executable for 168 lines of code :/ !<br/>
<br/>
<br/>
Upload to Android and run:<br/>
</p>
<pre class="long">


	fabiensanglard$ adb push mitm /data
	fabiensanglard$ adb shell

	// Note: At this point we jump in Android as root

	# cd /dev
	# mv smd0 smd0Real
	# # cd /data
	# ./mitm

	Opened /dev/smd0Real
	Pseudo-terminal slave name is '/dev/pts/1'
	Softlinking '/dev/pts/1' to '/dev/smd0'
	
	Hello, I'm Thread: 0.
	Hello, I'm Thread: 1.
 

</pre>
<p>
At this point the hook is done but <code>rild</code> process is still using the "real" fd. We need to restart it: Just kill it and initd will respawn it automatically.<br/>
<br/>
</p>
<pre class="long">
	
	
	fabiensanglard$ adb shell
	
	// Note: At this point we jump in Android as root

	# ps
	.
	root     1     0     280   168   c00b77a0 0000c78c S /init	
	system   29    1     808   264   c0182688 afe0c45c S /system/bin/servicemanager
	app_2    173   33    98448 13204 ffffffff afe0d3e4 S com.android.calendar
	app_14   206   33    98672 12644 ffffffff afe0d3e4 S com.google.android.apps.maps
	app_35   227   33    93704 11892 ffffffff afe0d3e4 S com.android.alarmclock
	radio    32    1     7988  1132  ffffffff afe0cacc S /system/bin/rild
	.

	.
	# kill -9 32


</pre>
<br/>
<p>
<u>Tips:</u> To have strace helped tremendously to debug. Many thanks to <a href="http://benno.id.au/blog/2007/11/18/android-runtime-strace">Ben Leslie</a> (<a href="strace">mirror</a>) for compiling <code>strace</code> it on ARM. In order to trace <code>rild</code> you can attach strace to PID=1 (init) and intruct strace to follow forking:<br/>
<br/>
</p>
<pre class="long">

	# strace -f -ff -o /data/strace.rild.log -p 1

</pre>
</p>
<h3>Results
			</h3>
			<p id="paperbox">
First thing to notice is that the baseband does not response OK but 0 to acknowledge a command, here is the initialization sequence tested on an HTC Magic:
<pre class="long">


	[Android send] :AT
	[Android recv] :0
	[Android send] :ATZE0S0=0Q0V0X3&C1&D1
	[Android recv] :0
	[Android send] :AT+CMEE=1	# Require error to be displayed in numeric format (1)
	[Android recv] :0
	[Android send] :AT+CRC=1
	[Android recv] :0
	[Android send] :AT+CR=1		# Enabled extended format of incoming call indication
	[Android recv] :0
	[Android send] :AT+CREG=1	# Network Registration
	[Android recv] :0
	[Android send] :AT+FCLASS=0
	[Android recv] :0
	[Android send] :AT+CMGF=0	# Set Text message format to PDU (0)
	[Android recv] :0
	[Android send] :AT+CSCS="HEX" # Set the TE (Terminal Equipment) character set
	[Android recv] :0
	[Android send] :AT+CGREG=1	# Is GPRS supported ?
	[Android recv] :0
	[Android send] :AT+CUSD=1	# Is 3G supported ?
	[Android recv] :0
	[Android send] :AT+CIMI		# What is the SIM Serial number ?
	[Android recv] :302720306663426 	# 302=Canada, 720 = Rogers, rest is serial


</pre>
<br/>
<br/>
Receiving a text message (PDU encoded) and then replying to it.
<pre class="long">


	[Android recv] :+CMT: ,45
	07915141991321F301000981F0CFEFFFFF000042C8721E640E8B59A03B3A4C0785E56550FE5D07D5E120FA1BF4A3D6CB20598D8E0635C379900
	C16838160369DACE6A2DD40E13608756C5257B114

	[Android send] :AT
	[Android recv] :0
	[Android send] :AT+CMGS=43
	[Android recv] :> 
	[Android send] :07915141991321F301000981F0CFEFFFFF000048453C9CFD96A7DD6716515E0EB7D3EE3328EC268390E1F13AED3E8342A11
	0885A2F8364353A1AD40CE74132580C0682DD74B29A8B760385DB20D4B1495DC552
	[Android recv] :



</pre>
<br/>
<br/>
Incoming call:
<pre class="long">


	[Android recv] :+CRING: VOICE			# Hey 'smart', someone is calling you.

	[Android send] :AT+CLCC				# Sure, send me the phone number of this person
	[Android recv] :+CLIP: "+1416839XXXX",145,,,""	# Here it is +11416839XXXX

	[Android send] :AT+CMUT=0			# Unmute the microphone
	[Android recv] :0
	[Android send] :ATA				# Pickup the call
	[Android recv] :0
	[Android send] :ATH				# Hang up 
	[Android recv] :0


</pre>
<br/>
<br/>
Scanning the Operator networks around (Go Canada !!):<br/>
<pre class="long">


	[Android send] :AT
	[Android recv] :0
	[Android send] :AT+COPS=?
	[Android recv] :[WCDMA] Current RRC Status = 0
	[Android recv] :+CREG: 1,"EA60","6225"
	[Android recv] :+CREG: 1,"EA60","491B"
	[Android recv] :+COPS: (2,"Rogers Wireless","ROGERS","302720",2),
	(1,"Rogers Wireless","ROGERS","302720",0),(1,"","","302880",2)
	,
	,
	(0,1,2,3,4),
	(0,1,2)
	0



</pre>

	</p>

<h3>Learn more
			</h3><br/>
			<p id="paperbox">
As usual I will recommend some really really great books that helped me a lot:<br/>
<br/>
<br/>
<table >

<tr align="center"><td ><img style="box-shadow: rgb(119, 119, 119) 3px 3px 3px;" src="Linkers&#32;and&#32;Loaders&#32;(The&#32;Morgan&#32;Kaufmann&#32;Series&#32;in&#32;Software&#32;Engineering&#32;and&#32;Programming).jpg"></td><td><img style="box-shadow: rgb(119, 119, 119) 3px 3px 3px;" src="Mac&#32;OS&#32;X&#32;Internals&#32;A&#32;Systems&#32;Approach.jpg"></td> <td><img style="box-shadow: rgb(119, 119, 119) 3px 3px 3px;"  src="unixAdvProgramming.jpg"></td></tr>
<tr align="center"><td><a href="http://www.amazon.com/Linkers-Kaufmann-Software-Engineering-Programming/dp/1558604960">Linkers and Loaders</a></td><td><a href="http://www.amazon.com/Mac-OS-Internals-Systems-Approach/dp/0321278542/ref=sr_1_1?ie=UTF8&s=books&qid=1274812559&sr=1-1">Mac OS X Internals: A Systems Approach</a></td><td><a href="./=&quot;http:/www.amazon.com/Programming-Environment-Addison-Wesley-Professional-Computing/dp/0201563177&quot;">Advanced Unix Programming</a></td></tr>
</table>
<br/>

<br/>
<br/>
<a href="index.php">Back to first page</a>
	</p>


<!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>



