<script type="text/javascript">
  var disqus_identifier = "quake3" ;
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="Quake 3 Source Code Review, id tech3, Quake Live Source Code Review"/>
		<meta name="Description" content="Quake 3 Source Code Review, Quake Live Source Code Review"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>Quake 3 Source Code Review: Artificial Intelligence</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       June 30, 2012</div>
   <h1>Quake 3 Source Code Review: Artificial Intelligence (Part 5 of 5) <a href="index.php">>></h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="quake3_icon.jpg" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         
The modding community wrote bot system for each previous idTech engines. Two of them were quite famous at the time:<br/>
<ul>
  <li>Quake1 had <a href="http://botepidemic.no-origin.net/gladiator/obots/obots.html">Omicron</a>.</li>
  <li>Quake2 had Gladiator.</li>
</ul>
<p>
But for idTech3 the bot system was fundamental so it was to be developed in-house and be available out of the box. But things did not happened exactly as expected during
development:<br/>
<br/>
<div style="clear:both;"></div>
<p>
 <u>Source</u>: Page 275 of "Masters of Doom":</br>
	   <pre class="long">
	   
	   
    To make matters worse, a fundamental ingredient of the game - the bots - was missing. Bots 
    were characters controlled by the computer. A good bot would blend in with the action and flesh 
    out the scene like a robotic extra, as well as interact with the player. For Quake III, a deathmatch
    only game, bots were essential for single-player action. They were implicitly complex because they 
    had to behave like human beings.
    
    Carmack had decided, for the First time, to delegate the job of creating these bots to another 
    programmer in the company. But he failed to follow up. Once again, Carmack incorrectly assumed 
    that everyone was as self-motivated and adept as he was. He was wrong.
    
    When Graeme struggled to rein in the work, it was discovered that the bots were completely ineffective. 
    They din't behave at all like human beings. They behaved, basically, like bots. The staff began to panic.
    By March 1999, they had reason to be scared.
   	   
	   </pre>
	   </br>

</p>

 
<h3>Architecture</h3>
<p id="paperbox">
 In the end the bots were farmed out to Jean-Paul van Waveren (a.k.a  Mr.Elusive) which is funny because he was also the author of "Omicron" and "Gladiator". 
 This probably explains why this part of the server code is in its own project: <code>bot.lib</code>:<br/>
 <br/>
<img style="margin-left: auto; margin-right: auto; display: block; width: 833px ; height: 594px; " src="../lazy_load/grey.gif" data-original="/fd_proxy/quake3/q3_bot.png">
<br/>
I could write about it but the programmer Jean-Paul van Waveren  wrote a 
<a href="../fd_proxy/quake3/The-Quake-III-Arena-Bot.pdf">
103 pages paper thesis</a> that explains everything. Moreover Alex J. Champandard wrote a <a href="http://aigamedev.com/open/article/quake3-engine/">code review on the bot system</a>
which locate the source code of each module mentioned in the thesis paper:<br/>
<br/>
Those two documents combined are all you will need to understand Quake3 I.A .
</p>

 
 
 
 <!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

