<script type="text/javascript">
  var disqus_identifier = "c";
</script>
<!DOCTYPE html>
<html>
	<head>	
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="Author" content="Fabien Sanglard">
		
		<meta name="Keywords" content="C programming language"/>
		<meta name="Description" content="How to learn C programming language"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	

		
		

 
 	
		
		<title>To become a good C programmer</title>
		
	</head>
	<body>
		<div id="main">
           
					
			<link rel='stylesheet' href='../css/neo_style.css' type='text/css'  />



    <h1 id="site-name">
        <a  href="../index.html" >Fabien Sanglard's Website</a>
    </h1>

<script>
   function setEmailTitle()
	{
 		var folders = window.location.href.split("/"); 

		var currentFolder = folders[folders.length-2];

		var emailLink = document.getElementById("mail");

		emailLink.href = "mailto:fabiensanglard.net@gmail.com?subject="+currentFolder;

	}
	
	window.onload = setEmailTitle;
</script>
<style type='text/css'>
		/**
		 * Bulletproof syntax:
		 * http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax
		 * Font files generated by Font Squirrel:
		 * http://www.fontsquirrel.com
		 * License: Open Font License. See http://evenchick.com/wp-content/themes/blaskan/OFL.txt.
		 */
		@font-face {
			font-family: 'LeagueGothic';
			src: url('../font/league_gothic/league_gothic-webfont.eot'); /* IE9 Compat Modes */
			src: url('../font/league_gothic/league_gothic-webfont.eot?iefix') format('eot'), /* IE6-IE8 */
			     url('../font/league_gothic/league_gothic-webfont.woff') format('woff'), /* Modern Browsers */
			     url('../font/league_gothic/league_gothic-webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
			     url('../font/league_gothic/league_gothic-webfont.svg') format('svg'); /* Legacy iOS */
		}
		
		@font-face {
			font-family: 'DejaVu Sans';
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf'); /* IE9 Compat Modes */
			src: url('../font/dejavu-sans/DejaVuSansMono.ttf')  format('truetype') /* Safari, Android, iOS */
			     
		}

		
</style>

<header id="header" role="banner"><nav id="nav" role="navigation"><div class="menu">
	<ul id="menu-primary-navigation-1" >
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-91">
           <a href="../index.html" >Home</a>
         </li>
         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-95">
           <a href="../about/index.html">About</a>
         </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-96">
           <a href="../faq/index.html">FAQ</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-92">
            <a id="mail" href="mailto:fabiensanglard.net@gmail.com?subject=Tunnel" title="Send me an email.">Email</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-93">
            <a href="../rss.xml" title="Suscribe to RSS Feed.">Rss</a>
         </li>
         <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-94">
            <a href="http://twitter.com/fabynou" title="Follow me on Twitter.">Twitter</a>
         </li>
     </ul></div></nav></header>
<!-- / #header -->
<section id="content" role="main">



		
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Feed" href="../rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Fabien Sanglard &raquo; Comments Feed" href="../rss.xml" />
<div id="date">
       February 2nd, 2011</div>
   <h1>To become a good C programmer</h1>
   <p id="paperbox">
	   	
          <a  href="index.php">
          <img src="c2.jpeg" style="margin-left: 2ch;float:right; border:1px black solid;width:35%;">   
          </a> 
         

Every once in a while I receive an email from a fellow programmer asking me what language I used for <a href="../shmupLite/index.html">one</a> of my <a href="../fluide/index.html">games</a> and how I learned it. Here is an entry that list the best things to read about C.<br/>
<br/>If you know of other gems, please email me or add a comment at the bottom of the page.
<div style="clear:both;"></div>
</p>

<h3>The answer (you can skip this)</h3>

<p id="paperbox">
As I mentioned it in a previous <a href="../dEngine/index.html">entry</a>, all the commercial 3D engines I wrote so far are 95% C89 (aka "Standard C", aka "ANSI C").<br/>
I picked C89 instead of C99 because some compilers still don't support fully C99…and to be able to compile on iOs, Windows and Xbox 360 was a mandatory from day one.<br/>
<br/>
Depending on the compiling platform, the 5% remaining are Objective-C (iOS) or C++ (Windows, Mac OS X) to bind the engine to the native inputs/output. Unexpectedly the C vs C++ proved quite <a href="http://www.reddit.com/r/gamedev/comments/ctiqm/iphone_3d_engine_experience_from_2009_especially/">controversial</a> on reddit. The two real reasons were:
<ul>
<li>I didn't know C++ well enough at the time I started writing the engines. The platform was quite limited (iPhone 2G) and I knew I would need to totally master my tools in order to achieve 60 frames per second.</li>
<li>Since I first read id Software source code, it was a dream to complete a commercial game using C.</li>
</ul>
<p>
Were those "good" choices? I think in the end the only valid questions are "Did you ship it?" and "Was it fast?". Considering the incredible frame rate achieved (some people mentioned experimenting motion sickness while playing <a href="../shmupLite/index.html">Shmup</a>) I think I made the right calls.
</p>
</p>

<h3>Bad C readings (stop skipping)</h3>

<p id="paperbox">
I'm going to start with the things I didn't take too seriously: Internet tutorials, blogs and almost anything brought by Google (yes, it includes this article). I usually considered those sources unreliable and potentially harmful.<br/>

<br/> Like a lot of people in the industry I used to Google way too often. Overtime I found the illusion of speed and the inaccuracy of the answers to be counter-productive.<br/>
<br/>
No website is as good as a good book. And no good book is as good as a disassembly output.
</p>

<h3>Excellent C readings</h3>

<p id="paperbox">
<img style="float:left; margin:0px 10px 0px 0px ;" src="k&amp;r.png"/>
<a href="http://www.amazon.com/Programming-Language-2nd-Brian-Kernighan/dp/0131103628/ref=sr_1_1?ie=UTF8&qid=1296604231&sr=8-1">"C Programming Language"</a> (aka: K&R)</a><br/> <br/>The classic and first book you should read about C.<br/>
<br/>It will be easy to pick up as it is a 272 pages, 386 grams book. Short and full of well explained code samples it was written by the fathers of the language Kernighan and Ritchie themselves. It is all you need to know about C…for the first few weeks. It is fun to read, keeps things short and will get you going in no time. You will probably skip the Annex A (about obscure things like promotions, decaying, conversions and other useless things) and Annex B about the C Library…and I think it's ok for the beginning. This book makes C appears very small and simple so it is very encouraging to learn.<br/>
<br/>
<p>
If you keep on practicing and learning you will soon hit some strange situations. Like for example:

<pre class="long">

    unsigned int   ui_one       =  1 ;
    signed   int   i_one        =  1 ;
    signed   short s_minus_one  = -1 ;
	
    if( s_minus_one > ui_one)
		printf("-1 > 1 \n");
	
    if( s_minus_one < i_one) 
		printf("-1 < 1 \n");

    #./run
    #
    # -1 > 1 
    # -1 < 1 

</pre>
<p>

In the previous code sample, due to "integral promotion" -1 was once evaluated to be greater than 1 and then smaller than 1. C has plenty of case like this when the language cannot longer "do stuff" for you.<br/>
<br/>
There are also plenty of subtleties:<br/>
<pre class="long">


    extern void foo(void);
    void (*f)();
	
    f = &foo;   // Valid 
    f = foo;    // Valid too ! (syntactic sugar)
	
    f();        // Calls f
    (*f)();     // Calls f too ! (syntactic sugar)



</pre>
<br/>
<p>
Or the array/pointer/decaying special cases...<br/>
</p>
<pre class="long">
	
	int array[] = {0,1,2,3,4} ;
	int* pointer = array;
	
	if (sizeof array == sizeof pointer)
		printf("This will never be printed !!");
	
	if (sizeof(int*) == sizeof &array[0])
		printf("This will be printed !!\n");
	
	if (&array[2] - &array[0] == 8)
		printf("This will never be printed either, result is 2 not 8!!");


</pre>
<br/>
<p>
When you hit the point where you understand that you actually know very little about C (and that the Annex A is way too slim), it will be time to pickup the second book.<br/>
<br/>
<img style="float:left; margin:0px 10px 0px 0px ;" src="ecp.png" /><a href="http://www.amazon.com/Expert-Programming-Peter-van-Linden/dp/0131774298/ref=sr_1_1?s=books&ie=UTF8&qid=1296604297&sr=1-1">Expert C Programming</a><br/>
<br/>This book is fantastic because it will bring your attention to what happens under the hood in a very entertaining way.<br/>Through numerous bug anecdotes and trivia (mostly NASA based) the reader will be introduced again to integral promotion, subscripting, decaying and many other C marvels. This book is so captivating that you will probably read the 353 pages within a night and be dissapointed it was so short.<br/><br/><br/>
<br/>
Now willing to do deep and become a good C programmer, you should acquire the last book you will ever need:
<br/><br/>
<img style="float:left; margin:0px 10px 0px 0px ;" src="carm.png" /><a href="http://www.amazon.com/Reference-Manual-Samuel-P-Harbison/dp/013089592X/ref=sr_1_1?s=books&ie=UTF8&qid=1296604377&sr=1-1">C: A Reference Manual</a><br/>
<br/> This is the ultimate C/C89/C99 book. The true cold boring truth that you will deal with from now on. You can put K&R and ECP back on the shelves and keep this one besides the screen monitor. Anything you want to know is there.<br/>
<br/>
<br/><br/><br/><br/><br/>
</p>
</p>






<h3>The C Standard library</h3>

<p id="paperbox">
<b><u>February 6th 2013 :</u></b> Two years have passed since I wrote this article. The three books mentioned remain the best in my opinion ... 
but what about the C Standard Library ?<br/>
<br/>
 <a href="http://www.amazon.com/Standard-C-Library-P-J-Plauger/dp/0131315099">
<img style="float:left; margin:0px 20px 0px 0px ; box-shadow: rgb(119, 119, 119) 3px 3px 3px;" src="c_standard_library.png"/></a>
 The best book to master the C Library is with no doubt "<a href="http://www.amazon.com/Standard-C-Library-P-J-Plauger/dp/0131315099">The Standard C Library</a>" by P.J. Plauger : 
Not only it comes with an implementation of the <u>entire library</u>, it also discuss design decisions and provides historical perspectives 
(ever wondered why C performed all floating operations in <code>double</code> ? Or how <code>errno</code> came to existence ? This book has the answers.<br/>
<br/>
It covers in details the 15 modules of C89:  <code>assert.h</code>,
<code>ctype.h</code>,
<code>errno.h</code>,
<code>float.h</code>,
<code>limits.h</code>,
<code>locale.h</code>,
<code>setjmp.h</code>,
<code>signal.h</code>,
<code>stdarg.h</code>,
<code>stddef.h</code>,
<code>time.h</code>,
and discuss at length the "big four": 
<code>stdio.h</code>,
<code>stdlib.h</code>,
<code>string.h</code>, and 
<code>math.h</code>.
<br/>
<br/>

The only two big things missings are the coverage of C99 integral types (<code>intypes.h</code> and <code>stdint.h</code>) which
are paramount in order to write portablecode and C11's  <code>threads.h</code> which is equaly important considering the emergence of multi-core CPUs. 
For now I haven't found anything better but I welcome reader's suggestions.

<div style="clear:both;"</div>
	<br/>
</p>

<br/>
<h3>Additional readings</h3>

<p id="paperbox">

<img style="float:left; margin:0px 10px 0px 0px ;" src="Idlogo.jpeg" />
<a href="ftp://ftp.idsoftware.com/idstuff/">id Software codebase</a><br/>
<br/>
Of course reading books is not enough. To read great C code will help tremendously. My favourite is id Software's 3D engines codebase: 
Doom, Quake, Quake 2, Quake 3, Wolfenstein 3D iPhone and Doom iPhone. While I read them I wrote memos for myself which I later turned 
into articles (<a href="../doomIphone/doomClassicRenderer.php">Doom</a>, <a href="../quakeSource/index.php">Quake</a>,<a href="../wolf3d/index.php">Wolfenstein 3D iPhone</a> and <a href="../doomIphone/index.php">Doom iPhone</a>).
<br/><br/><br/><br/>

<img style="float:left; margin:0px 10px 0px 0px ;" src="smds-small.png" />
<a href="http://www.amazon.com/Sh-t-My-Dad-Says/dp/0061992704/ref=sr_1_1?ie=UTF8&qid=1296658724&sr=8-1">Sh*t My Dad Says</a><br/>
<br/>
Try to maintain an healthy life and read some fun stuff for a change ;) !
<div style="clear:both;"></div>
</p>

<!-- <h2>Comments</h2>
<p> -->


     <!-- <div id="disqus_thread"></div> -->
    <!-- <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'fabiensanglardswebsite'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || 
                document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
    <!--<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->
<!--     




</p> -->

 <h2 style="padding: 0px; margin: 0px;">&nbsp;</h2>
<div style="text-align:center ;">@</div>

		</div>
</div>

	<script src="../lazy_load/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 	

  	<script src="../lazy_load/jquery.lazyload.min.js?v=3" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		      $(function() {
		          $("img").lazyload({
		              effect : "fadeIn"
		          });
		      });
    </script>	
	</body>

</html>

