---

name: "Archive Link"
run-name: "Archiving ${{ inputs.url }}"

on:
  workflow_dispatch:
    inputs:
      url:
        required: true
        type: string
        description: |
          The url to archive.

          By default, only the file specified will be archived.

jobs:
  archive-file:
    name: Archive File
    runs-on: ubuntu-latest
    concurrency:
      group: write
      cancel-in-progress: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.AUTO_DOWNLOAD_ARCHIVE }}
          ref: ${{ github.ref }}

      - name: Install Dependencies
        run: sudo apt-get install pandoc

      - name: Determine Target
        id: target
        env: { URL: '${{ inputs.url }}' }
        run: |
          grep --invert "^#" << EOF | tee -a "${GITHUB_OUTPUT}"

          # Get the directory to save the file into
          directory=$(
            dirname "$(
              echo "${URL}" |
                sed -E 's/^https?:\/\/web.archive.org\/web\/[0-9]+\/(https?:\/\/)?/https:\/\//' |
                sed -E 's/^https?:\/\///'
            )"
          )

          # Get the name of the file being saved  
          file=$(
            basename "${URL}"
          )

          # Get the url of the file (with any sanitisation)
          url=$(
            echo "${URL}"
          )

          EOF

      - name: Create Target Directory
        run: mkdir -p "${DIR}"
        env:
          DIR: ${{ steps.target.outputs.directory }}

      - name: Download File
        working-directory: ${{ steps.target.outputs.directory }}
        run: wget -O "${FILE}" "${URL}"
        env:
          URL: ${{ steps.target.outputs.url }}
          FILE: ${{ steps.target.outputs.file }}

      - name: Extract Tarball
        working-directory: ${{ steps.target.outputs.directory }}
        if: ${{ endsWith(steps.target.outputs.file, '.tar.gz') }}
        run: tar -xvf "${FILE}"
        env:
          FILE: ${{ steps.target.outputs.file }}

      - name: Render HTML to Markdown
        working-directory: ${{ steps.target.outputs.directory }}
        if: ${{ endsWith(steps.target.outputs.file, '.html') }}
        run: iconv -t utf-8 "${FILE}" | pandoc --from html --to markdown -o "$(echo "${FILE}" | sed 's/html$/md/')"
        env:
          FILE: ${{ steps.target.outputs.file }}

      - name: Extract Zipfile
        working-directory: ${{ steps.target.outputs.directory }}
        if: ${{ endsWith(steps.target.outputs.file, '.zip') }}
        run: unzip "${FILE}"
        env:
          FILE: ${{ steps.target.outputs.file }}

      - name: Verify Changed files
        id: changes
        uses: tj-actions/verify-changed-files@v17

      #- name: Setup GPG Keys
      #  uses: crazy-max/ghaction-import-gpg@v5
      #  with:
      #    gpg_private_key: ${{ secrets.AUTO_COMMIT_GPG_PRIVATE_KEY_ARCHIVE }}
      #    passphrase: ${{ secrets.AUTO_COMMIT_GPG_PASSPHRASE_ARCHIVE }}
      #    git_user_signingkey: true
      #    git_commit_gpgsign: true

      - name: Push Changes
        if: steps.changes.outputs.files_changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: .
          skip_dirty_check: true
          commit_author: norwd <106889957+norwd@users.noreply.github.com>
          commit_user_name: norwd
          commit_user_email: 106889957+norwd@users.noreply.github.com
          #commit_options: -s -S
          commit_message: |
            Archive ${{ steps.target.outputs.file }}

            Original source: ${{ inputs.url }}
            File(s): ${{ steps.changes.outputs.changed_files }}

            *NOTE:** This is an automatic commit. See the archive workflow.
