---

name: "Refresh Archive"
run-name: "Refresh Archive"

on:
  workflow_dispatch:

  schedule:
    - cron: '0 0 1 * *'

  push:
    branches: main
    paths:
      - .github/workflows/refresh.yml

env:
  GH_TOKEN: ${{ secrets.AUTO_DOWNLOAD_ARCHIVE }}

jobs:
  refresh-archive:
    strategy:
      matrix: # this is hard coded for now, as not all websites are straightforward to archive, in the future this might be in file in the repo itself
        link:
          - "bellard.org/tcc/"
          - "bellard.org/quickjs/"
          - "bellard.org/otcc/"
          - "bellard.org/bpg/"
          - "bellard.org/fbcc/"
          - "www.simple-cc.org/"
          - "tom7.org/papers/"
          - "tom7.org/chess/"
          - "tom7.org/talks/"
          - "spec.commonmark.org/current/spec.json"
          - "spec.commonmark.org/current/changes.html"
          - "spec.commonmark.org/current/index.html"
          - "sigbovik.org/2024/" # TODO: update this to be current year automatically?

    name: Refresh Archive
    runs-on: ubuntu-latest
    steps:
      - name: "Triger Archive Workflow"
        run: gh workflow run --repo "${REPO}" archive.yml -f url="${LINK}"
        env:
          REPO: '${{ github.repository }}'
          LINK: '${{ matrix.link }}'
