---

name: "Refresh Archive"
run-name: "Refresh Archive"

concurrency:
  group: refresh-archive
  cancel-in-progress: true

on:
  workflow_dispatch:

  schedule:
    - cron: '0 0 1 * *'

  push:
    branches: main
    paths:
      - .github/workflows/refresh.yml

env:
  GH_TOKEN: ${{ secrets.AUTO_DOWNLOAD_ARCHIVE }}

jobs:
  refresh-archive:
    name: "Refresh Archive"
    uses: ./.github/workflows/archive.yml
    with:
      url: '${{ matrix.url }}'
    secrets: inherit
    strategy:
      fail-fast: false
      matrix: # this is hard coded for now, as not all websites are straightforward to archive, in the future this might be in file in the repo itself
        url:
          - "bellard.org/"
          - "seamountknifeworks.com/"
          - "sigbovik.org/"
          - "spec.commonmark.org/"
          - "tom7.org/"
          - "www.simple-cc.org/"
          - "www.literateprogramming.com/"
          - "developercertificate.org/"
          - "myplace.frontier.com/~mr.wizard/GLGC/"
          - "www.gnuterrypratchett.com/"
          - "brainmade.org/"
          - "ftp.openbsd.org/pub/OpenBSD/songs/"
          - "www.openbsd.org/images/"
          - "semver.org/"

          # The Jargon "File" is massive and won't complete in a single run, so this breaks it down more granularly
          - "www.catb.org/jargon/oldversions/"
          - "www.catb.org/jargon/html/0/"
          - "www.catb.org/jargon/html/1/"
          - "www.catb.org/jargon/html/2/"
          - "www.catb.org/jargon/html/3/"
          - "www.catb.org/jargon/html/4/"
          - "www.catb.org/jargon/html/5/"
          - "www.catb.org/jargon/html/6/"
          - "www.catb.org/jargon/html/7/"
          - "www.catb.org/jargon/html/8/"
          - "www.catb.org/jargon/html/9/"
          - "www.catb.org/jargon/html/4/"
          - "www.catb.org/jargon/html/A/"
          - "www.catb.org/jargon/html/B/"
          - "www.catb.org/jargon/html/C/"
          - "www.catb.org/jargon/html/D/"
          - "www.catb.org/jargon/html/E/"
          - "www.catb.org/jargon/html/F/"
          - "www.catb.org/jargon/html/G/"
          - "www.catb.org/jargon/html/H/"
          - "www.catb.org/jargon/html/I/"
          - "www.catb.org/jargon/html/J/"
          - "www.catb.org/jargon/html/K/"
          - "www.catb.org/jargon/html/L/"
          - "www.catb.org/jargon/html/M/"
          - "www.catb.org/jargon/html/N/"
          - "www.catb.org/jargon/html/O/"
          - "www.catb.org/jargon/html/P/"
          - "www.catb.org/jargon/html/Q/"
          - "www.catb.org/jargon/html/R/"
          - "www.catb.org/jargon/html/S/"
          - "www.catb.org/jargon/html/T/"
          - "www.catb.org/jargon/html/U/"
          - "www.catb.org/jargon/html/V/"
          - "www.catb.org/jargon/html/W/"
          - "www.catb.org/jargon/html/X/"
          - "www.catb.org/jargon/html/Y/"
          - "www.catb.org/jargon/html/Z/"
