---

name: "Refresh Archive"
run-name: "Refresh Archive"

on:
  workflow_dispatch:

  schedule:
    - cron: '0 0 1 * *'

  push:
    branches: main
    paths:
      - .github/workflows/refresh.yml

env:
  GH_TOKEN: ${{ secrets.AUTO_DOWNLOAD_ARCHIVE }}

jobs:
  refresh-archive:
    name: "Refresh Archive"
    uses: ./.github/workflows/archive.yml
    with:
      url: '${{ matrix.url }}'
    secrets: inherit
    strategy:
      fail-fast: false
      matrix: # this is hard coded for now, as not all websites are straightforward to archive, in the future this might be in file in the repo itself
        url:
          - "bellard.org/"
          - "seamountknifeworks.com/"
          - "sigbovik.org/"
          - "spec.commonmark.org/"
          - "tom7.org/"
          - "www.simple-cc.org/"
          - "www.literateprogramming.com/"
          - "developercertificate.org/"
          - "www.spyderco.com/pdfs/SpydercoSteelChart.pdf"
          - "www.catb.org/jargon"
          - "scienceofsharp.files.wordpress.com/"
          - "sange.fi/esoteric/brainfuck/" # TODO: these sange.fi dirs might be equivalent?
          - "esoteric.sange.fi/brainfuck/" # TODO: these sange.fi dirs might be equivalent?
          - "myplace.frontier.com/~mr.wizard/GLGC/"
          - "knifesteelnerds.com/wp-content/uploads/"
