---

name: "Refresh Archive"
run-name: "Refresh Archive"

on:
  workflow_dispatch:

  schedule:
    - cron: '0 0 1 * *'

  push:
    branches: main
    paths:
      - .github/workflows/refresh.yml

env:
  GH_TOKEN: ${{ secrets.AUTO_DOWNLOAD_ARCHIVE }}

jobs:
  refresh-pull-requests:
    name: "Refresh Pull Requests"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.AUTO_DOWNLOAD_ARCHIVE }}

      - name: "Create Pull Requests"
        run: gh api "${API_PATH}" --paginate --jq "${JQ_QUERY}" | grep -E "${REF_REGX}" | awk '{ print $0; system("sleep 60"); }' | xargs -IBRANCH gh pr create --fill-first --head BRANCH
        env:
          API_PATH: '/repos/${{ github.repository }}/branches'
          JQ_QUERY: '.[].name'
          REF_REGX: '^archive/[0-9]+-[0-9]+-[0-9]+$'

  refresh-archive:
    name: "Refresh Archive"
    runs-on: ubuntu-latest
    strategy:
      matrix: # this is hard coded for now, as not all websites are straightforward to archive, in the future this might be in file in the repo itself
        link:

          # sigbovik.org gets (roughly) yearly updates, so this just refreshes the current year
          - "sigbovik.org/2024/" # TODO: update this to be current year automatically?

          # bellard.org has a large tree so to be nice to the server this only refreshes specific disrectories
          - "bellard.org/tcc/"
          - "bellard.org/quickjs/"
          - "bellard.org/otcc/"
          - "bellard.org/bpg/"
          - "bellard.org/fbcc/"

          # tom7.org has a large tree so to be nice to the server this only refreshes specific disrectories
          - "tom7.org/papers/"
          - "tom7.org/chess/"
          - "tom7.org/talks/"

          # spec.commonmark.org/current doesn't redirect in wget the same way it does in the browser so this needs revisiting
          #- "spec.commonmark.org/current/spec.json"
          #- "spec.commonmark.org/current/changes.html"
          #- "spec.commonmark.org/current/index.html"

          # full site mirrors
          - "fabiensanglard.net/"
          - "www.simple-cc.org/"
          - "www.literateprogramming.com/"
          - "developercertificate.org/"

    steps:
      - name: "Triger Archive Workflow"
        run: gh workflow run --repo "${REPO}" archive.yml -f url="${LINK}"
        env:
          REPO: '${{ github.repository }}'
          LINK: '${{ matrix.link }}'
