---

name: "Refresh Archive"
run-name: "Refresh Archive"

concurrency:
  group: refresh-archive
  cancel-in-progress: true

on:
  workflow_dispatch:

  schedule:
    - cron: '0 0 1 * *'

  push:
    branches: main
    paths:
      - .github/workflows/refresh.yml

env:
  GH_TOKEN: ${{ secrets.AUTO_DOWNLOAD_ARCHIVE }}

jobs:
  refresh-archive:
    name: "Refresh Archive"
    uses: ./.github/workflows/archive.yml
    with:
      url: '${{ matrix.url }}'
    secrets: inherit
    strategy:
      fail-fast: false
      matrix: # this is hard coded for now, as not all websites are straightforward to archive, in the future this might be in file in the repo itself
        url:
          - "bellard.org/"
          - "seamountknifeworks.com/"
          - "sigbovik.org/"
          - "spec.commonmark.org/"
          - "tom7.org/"
          - "www.simple-cc.org/"
          - "www.literateprogramming.com/"
          - "developercertificate.org/"
          - "myplace.frontier.com/~mr.wizard/GLGC/"
          - "www.gnuterrypratchett.com/"
          - "brainmade.org/"
          - "ftp.openbsd.org/pub/OpenBSD/songs/"
          - "www.openbsd.org/images/"
          - "semver.org/"
          - "steloj.de/esperanto/"
