---

name: "Refresh Archive"
run-name: "Refresh Archive"

on:
  workflow_dispatch:

  schedule:
    - cron: '0 0 1 * *'

  push:
    branches: main
    paths:
      - .github/workflows/refresh.yml

env:
  GH_TOKEN: ${{ secrets.AUTO_DOWNLOAD_ARCHIVE }}

jobs:
  refresh-archive:
    name: "Refresh Archive"
    uses: ./.github/workflows/archive.yml
    with: ${{ matrix }}
    secrets: inherit
    strategy:
      fail-fast: false
      matrix: # this is hard coded for now, as not all websites are straightforward to archive, in the future this might be in file in the repo itself
        url:

          # sigbovik.org gets (roughly) yearly updates, so this just refreshes the current year
          - "sigbovik.org/2024/" # TODO: update this to be current year automatically?

          # bellard.org has a large tree so to be nice to the server this only refreshes specific disrectories
          - "bellard.org/tcc/"
          - "bellard.org/quickjs/"
          - "bellard.org/otcc/"
          - "bellard.org/bpg/"
          - "bellard.org/fbcc/"

          # tom7.org has a large tree so to be nice to the server this only refreshes specific disrectories
          - "tom7.org/papers/"
          - "tom7.org/chess/"
          - "tom7.org/talks/"

          # spec.commonmark.org/current doesn't redirect in wget the same way it does in the browser so this needs revisiting
          #- "spec.commonmark.org/current/spec.json"
          #- "spec.commonmark.org/current/changes.html"
          #- "spec.commonmark.org/current/index.html"

          # full site mirrors
          # - "fabiensanglard.net/" # this site is huge it may be better to do a bunch of subdirs individually
          - "www.simple-cc.org/"
          - "www.literateprogramming.com/"
          - "developercertificate.org/"
